opencontainers/runc

libcontainer/integration/exec_test.go
It can happen if newContainer is failed. Now test shows real error from
newContainer instead of trace.
=> Fix panic in seccomp test on error

spec_linux.go
Fixes: #16
Set up memory.swappiness in cgroup config so write is not attempted
unless specifically set.  Fixes running runc on kernels which still have
the cgroup hierarchy write limitation.
=> Initialize memory.swappiness cgroup to -1

main.go
This allows "./runc .." instead of adding it to $PATH location
=> Allow runc to be executed as a relative path

libcontainer/factory_linux.go
A directory with a hyphen currently generates an `InvalidId` error because
of the regex in libcontainer.  I don't believe there is any reason a
hyphen should be disallowed.
=> Allow hyphen in "id" (based on `cwd` pathname)

main.go
1. Remove mention of nsinit (removed from the repo)
2. Make basic usage text a bit more informative; fix typo
3. Fix typo in panic() message (that should never be seen) :)
=> Update usage content and fix typos

main.go, run.go
A couple minor changes to error handling in startup:
1. Don't dump full help/usage text when the only problem is `runc` wasn't started under
root privileges
2. Check for rootfs and make error clear to user when it doesn't exist
3. Change fatal to logrus.Fatal to get nicer output with simple error
message
=> Make startup errors a bit friendlier

libcontainer/factory_linux.go, main.go
=> Fix absolute path getting for runc binary

README.md
Adding some extra information to the README file (docker create was introduced in 1.3)
=> Adding minimum version required for docker create

main.go, main_unix.go
Removes the dependency of nsenter on Windows.
=> Windows: Remove nsenter dependency

Makefile
This allows for just needing to run `make install` and it will install even if you hadn't build the project.
=> Added all dependency to install in Makefile

spec_linux.go
If I provide a path starting with `/` I expect that to be honored;
otherwise I have to explicitly `(cd /; /path/to/runc)`.
=> linux: Don't prepend process' cwd if rootfs path is already absolute

libcontainer/user/user.go, libcontainer/user/user_test.go
I wasn't originally ping'd on docker/libcontainer#603, so here's a PR to fix the API. If we want nice testability, we should always provide an `io.Reader`.  It also makes it much nicer if we ever want to make generators for `/etc/group` and `/etc/passwd` formatted data that we get from other sources (like generating it from an Active Directory user list or smth similar).
Fixes: d4ece29c0bd38d680af6a2544a5ce705c3daeb24
=> libcontainer: user: fix GetAdditionalGroups* API

checkpoint.go, events.go, main.go, main_unsupported.go, restore.go, run.go, signals.go, spec.go, tty.go, utils.go
Should compile now without errors but changes needed to be added for each system so it actually works.
main_unsupported.go is a new file with all the unsupported commands
Fixes #9
Signed-off-by: Marianna <mtesselh@gmail.com>
=> Enable build on unsupported platforms

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/systemd/apply_systemd.go
In some older kernels setting swappiness fails. This happens even
when nobody tries to configure swappiness from docker UI because
we would still get some default value from host config.
With this we treat -1 value as default value and skip the enforcement
of swappiness.
Signed-off-by: Raghavendra K T <raghavendra.kt@linux.vnet.ibm.com>
=> Treat -1 as default value for memory swappiness

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/specs/bundle.md, Godeps/_workspace/src/github.com/opencontainers/specs/config.md, Godeps/_workspace/src/github.com/opencontainers/specs/spec_linux.go, libcontainer/configs/config.go, libcontainer/integration/exec_test.go, libcontainer/standard_init_linux.go, spec.go
Supports setting /proc/sys keys for a container.
=> Adds Sysctl support

libcontainer/integration/template_test.go
For older kernels, upon running make localtest, it fails to setting the swapiness value due to which the tests are failing
Kernel used for identifying this issue: 3.13 ( based on Ubuntu 14.04 LTS)
This change is made in template file for cgroups to have memory swappiness as -1.
post that tests were passed by not setting the value for the test containers
=> Fixing memory swappiness as -1 in template file for older kernels

README.md
Fix bug in Readme.md,change GOPATH to GOPATH/src
to avoid missunderstanding of how to build.
Signed-off-by: zenlin <linzhinan@huawei.com>
=> Fix bug in Readme.md,change GOPATH to GOPATH/src

libcontainer/seccomp/bpf.go, libcontainer/seccomp/context.go, libcontainer/seccomp/filter.go, libcontainer/seccomp/seccomp_unix.go, libcontainer/seccomp/seccomp_unsupported.go
Factors out seccomp on the Windows platform where not applicable.
=> Windows: Factor out seccomp

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/specs/config-linux.md, Godeps/_workspace/src/github.com/opencontainers/specs/config.md, Godeps/_workspace/src/github.com/opencontainers/specs/spec_linux.go, spec.go
Pull in opencontainers/specs#63 to get clearer field names and fix the
swapped assignment when parsing JSON specs.
I've split this pull request into two commits, so the Godeps bump is
independent of the local change.  I think that will make it easier to
review the change.  It may cause trouble for folks bisecting bugs
though (because the Godeps-bump commit won't compile without the
local-change commit), so feel free to squash the two commits together
if that's a concern.
=> Fix IDMapping host / container field confusion

libcontainer/cgroups/fs/memory.go
Fixes: #57
Normally all cgroup subsystems are optional except device cgroup,
but memory cgroup optional was broken by:
https://github.com/docker/libcontainer/pull/637
This patch fixes this.
=> Fix error when memory cgroup not mounted

libcontainer/rootfs_linux.go
Fixes: https://github.com/docker/docker/issues/14543
Fixes: https://github.com/docker/docker/pull/14610
Before this, we got mount info in container:
```
sysfs /sys sysfs ro,seclabel,nosuid,nodev,noexec,relatime 0 0
/sys/fs/cgroup tmpfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,relatime,cpuset 0 0
```
It has no mount source, so in `parseInfoFile` in Docker code,
we'll get:
```
Error found less than 3 fields post '-' in "84 83 0:41 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime - tmpfs  rw,seclabel"
```
After this fix, we have mount info corrected:
```
sysfs /sys sysfs ro,seclabel,nosuid,nodev,noexec,relatime 0 0
tmpfs /sys/fs/cgroup tmpfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,relatime,cpuset 0 0
``` …
=> Correct tmpfs mount for cgroup

README.md, spec.go
(I made a mistake and causing the old PR to be closed, so I have to open a new PR)
Without this patch, I won't be able to start containers with runc, because it tries to write to the cgroup's swappiness and fails.
=> Add memory swappiness support

README.md, libcontainer/rootfs_linux.go, spec.go
Otherwise we have no way to know our resource limit in the runtime.
=> Add cgroup mount in the recommended config

libcontainer/cgroups/utils.go, libcontainer/integration/exec_test.go, libcontainer/rootfs_linux.go
Because of this there was problems with mounting cgroups in children containers. It tried to mount whole path, which exists on host, but not in container.
ping @mrunalp @hqhq @avagin
=> Cgroups mount fix

libcontainer/integration/exec_test.go, libcontainer/rootfs_linux.go
Now it is exactly like on host.
=> Remount /sys/fs/cgroup as readonly always

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/utils.go
This is needed because for nested containers cgroups. Without this patch
they creating unnecessary intermediate cgroup like:
```
/sys/fs/cgroup/memory/system.slice/docker-9409d9f0b68fb9e9d7d532d5b3f35e7c7f9cca1312af392ae3b28436f1f2998f.scope/system.slice/docker-9409d9f0b68fb9e9d7d532d5b3f35e7c7f9cca1312af392ae3b28436f1f2998f.scope/docker/908ebcc9c13584a14322ec070bd971e0de62f126c0cd95c079acdb99990ad3a3
```
It is because in /proc/self/cgroup we see paths from host, and they don't
exist in container.
ping @rjnagal @vmarmol @vishh @mrunalp
=> Substract source mount from cgroup dir

libcontainer/integration/exec_test.go, libcontainer/rootfs_linux.go
This reverts commit 18de1a273e00fd87205e174e2bfe3c36837a6d37.
It caused failures in docker test suite.
=> Revert "Remount /sys/fs/cgroup as readonly always"

libcontainer/cgroups/fs/apply_raw.go
Sometimes subsystem can be mounted to path like "subsystem1,subsystem2",
so we need to handle this.
I need this to remount /sys/fs/cgroup as ro. Before it tried to create new cgroups `cpu` and `cpuacct` even if `cpu,cpuacct` was already there.
=> Fix subsystem path with abs parent

libcontainer/container_linux.go, libcontainer/rootfs_linux.go
Actually cgroup mounts are bind-mounts, so they should be
handled by the same way.
Cc: @boucher
Reported-by: Ross Boucher <rboucher@gmail.com>
Signed-off-by: Andrey Vagin <avagin@openvz.org>
=> ct: give criu informations about cgroup mounts

libcontainer/stacktrace/capture.go
The stack trace call goes into a infinite loop with GCCGO 5.1 branch. This is required for Docker integrations tests to run well.
Signed-off-by: Srini Brahmaroutu <srbrahma@us.ibm.com>
=> avoid infinite loop with GCCGO

MAINTAINERS_GUIDE.md
This makes some changes to the maintainer's guide and roles within the
project.  It removed the concept of a BDFL and carries over the chief
maintainer role into the project.  BDFL sucks and we can do better and
these changed help to make many more things specific around adding new
maintainers and removing them as well.
=> Update maintainers guide

spec.go
... unless there's any good reason to leave `lo` down inside private namespaces by default?
Without this, unnecessary privileges and capabilities would need to be given to the container so it can bring the interface up itself.
=> bring the loopback interface up inside containers

libcontainer/integration/utils_test.go
When the copyBusybox() fails, the error message should be
propagated to the caller of newRootfs().
=> test: propagate the error to the caller

libcontainer/integration/exec_test.go, libcontainer/rootfs_linux.go
Now I tried this with docker, all is okay after fix of abs cgroup-parent.
Now it looks like on host.
=> Remount /sys/fs/cgroup as RO if MS_RDONLY was passed

signals.go
Without this we have a memory leak in the signal handling code. @dqminh has this as part of #105 but I think we could get this in before we get that PR in.
=> signal: Fix leak

spec.go
Only add the localhost interface information to the config if the NEWNET
flag is passed on the namespaces.
This fixes an issue running the container in the host's network namespace.
=> Only add network info if NEWNET is set

README.md
Now that the generated spec (and the example above in the README) use
uid/gid and don't have the hardcoded `daemon` entry, the statement about
changing `daemon` to `root` no longer applies.  Also added a comment
about using the `runc spec` command to generate `config.json`.
=> Update README.md to correct comment about spec and user

Makefile
This commit allows to send `go test` arguments to current makefile
`test` and `localtest` targets.
A usage example would be `make test TESTFLAGS="-run=SomeTestFunction"`
to easily run a single test function.
Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>
=> Add test arguments to Makefile targets

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/rootfs_linux.go
Please review; I find it moderately serious as missing error from MkdirAll() can lead to some other errors at a later stage, possibly hard to track down to the cause.
=> Simplify and fix os.MkdirAll() usage

libcontainer/integration/exec_test.go, script/test_Dockerfile, script/tmpmount
Also unskip test that was screwed by it.
We don't need dind anymore, because docker mounting cgroups in container
itself.
=> Remove dind

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/dbus.go, Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/dbus_test.go, Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods.go, Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods_test.go, Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/properties.go, Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/set.go, Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/set_test.go, Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/subscription.go, Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/subscription_set.go, Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/subscription_set_test.go, Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/subscription_test.go, Godeps/_workspace/src/github.com/coreos/go-systemd/util/util.go, libcontainer/cgroups/systemd/apply_systemd.go
- update github.com/coreos/go-systemd/dbus to v3
- adapt code to go-systemd/dbus v3
noticed the v2 is about 1 year old so thought to upgrade it to v3 
Signed-off-by: Antonio Murdaca <runcom@linux.com>
=> Update go systemd dbus v3

libcontainer/factory_linux.go
This is more secure and simpler than using os.Args[0].
=> Use /proc/self/exe as default for InitPath

libcontainer/compat_1.5_linux.go, libcontainer/container_linux.go, libcontainer/setgroups_linux.go
This fixes an issue with Go 1.5, introduced by:
https://github.com/golang/go/commit/f5c60ff2da4851f9056120a423ce6b48624fb97e
=> Go1.5 compatibility fix

libcontainer/container.go, libcontainer/container_linux.go, libcontainer/restored_process.go
This adds a `Signal()` method to the container interface so that the
initial process can be signaled after a Load or operation.  It also
implements signaling the init process from a nonChildProcess.
This implements the Signal API in the libcontainer so that #124 can be implemented.  
=> Add signal API to Container interface

spec.go
It's "pid" in opencontainers/specs
=> Rename process namespace to pid

README.md
#180 changed `spec.go` but not the example configuration in the README file. To use "pid" rather than "process" in the namespaces.
Signed-off-by: William Temple <wtemple@redhat.com>
=> Change example JSON to refer to "pid" namespace rather than "process."

restore.go, run.go, spec.go
Without this, multiple runc containers can accidentally share the same cgroup(s) (and change each other's limits), when runc is invoked from the same directory (i.e.: same `cwd` on multiple runc invocations).
After these changes, each runc container will run on its own cgroup(s). Before, the only workaround was to invoke runc from an unique (temporary?) cwd for each container (ugh).
Common cgroup configuration (and hierarchical limits) can be set by having multiple runc containers share the same cgroup parent, which is the cgroup of the process executing runc.
The behavior will be the same as before when an explicit `--id` option is not passed to `runc`: the container id will be inferred from `cwd`.
Related: #3 
Signed-off-by: Fabio Kung <fabio.kung@gmail.com>
=> container id is the cgroup name

libcontainer/process_linux.go
Simplify the code introduced by the commit d1f0d5705deb:
Return actual ProcessState on Wait error
Cc: Alexander Morozov <lk4d4@docker.com>
=> Simplify the return on process wait

libcontainer/factory_linux_test.go
@LK4D4 @mrunalp 
While running make localtest /tmp is filled with /tmp/libcontainer<ID>
Function TestFactoryNewTmpfs is created using
factory, err := New(root, Cgroupfs, TmpfsRoot), since tmpfs is mounted on /tmp/libcontainer<ID>, unless we unmount the tmpfs, /tmp/libcontainer<ID> directory is not removed
Added the umount call, so that it unmount the file system and cleans up the /tmp/libcontainer<ID> correctly
=> make localtest fills up /tmp with /tmp/libcontainer

libcontainer/netlink/netlink_linux_armppc64.go, libcontainer/netlink/netlink_linux_notarm.go
Again. It looks like a build tag was somehow dropped between
the PR here: https://github.com/docker/libcontainer/pull/625
and the move to runc.
Signed-off-by: Christy Perez <clnperez@linux.vnet.ibm.com>
=> Fixing netlink build error on ppc64le with gccgo

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/memory.go, libcontainer/process_linux.go
Some of the cleanup jobs in the deferrer depend on an 'err' variable that would be assigned later on. 
But this is a bit fragile because it's quite usual to use
```go
if err := func(); err != nil {
return err
}
```
to handle errors in go.
In such cases a new local 'err' variable will be created and the outer 'err' that the deferrer depends on won't be assigned so this will prevent the cleanup jobs from executing.
Signed-off-by: Shijiang Wei <mountkin@gmail.com>
=> Ensure the cleanup jobs in the deferrer are executed on error

libcontainer/rootfs_linux.go
Adding the securityfs mount point during start of the container for apparmor profiles to be loaded at run time
~Rajasec
=> Adding securityfs mount

tty.go
When we use ```cat | runc``` or ```runc /dev/stdin < config.json```,
it will fail and output ```FATA[0000] Container start failed: inappropriate ioctl for device```.
It is hard for the users to find out the reason from the message:
the config.json enables the terminal but the user redirect the stdin
to an non-terminal file.
After this patch, the output will be
```FATA[0000] Container start failed: Failed to set the terminal from the stdin: inappropriate ioctl for device```
So the user can disable the terminal in the config.json.
See the #202
Cc: W. Trevor King <wking@tremily.us> (@wking)
=> richer information error message for terminal

libcontainer/container_linux.go
Lots of people ask where they can find this log file, even more people don't know the file exists, so this should help people debug why checkpoint/restore fails more easily.
Signed-off-by: Ross Boucher <rboucher@gmail.com>
=> Add the criu log file path to the failure message.

README.md, main.go, start.go
When any non-global-flag parameter appears on the command line make sure
there's a "command" even in the 'start' (run) case to ensure its not
ambiguous as to what the arg is. For example, w/o this fix its not
clear if
```
runc foo
```
means 'foo' is the name of a config file or an unknown command.  Or worse,
you can't name a config file the same as ANY command, even future (yet to
be created) commands.
We should fix this now before we ship 1.0 and are forced to support this
ambiguous case for a long time.
=> Add a 'start' command

libcontainer/seccomp/config.go, spec.go
Now that the Seccomp backend work is merged, wire it into the spec so it can be used from the runc command line. The spec has a section for Seccomp configuration that is largely identical to what's in the libcontainer config, minus constants be exchanged for strings corresponding to variables names in libseccomp's header. Converting from an opencontainer spec to a libcontainer config is otherwise very simple.
=> Connect Seccomp configuration in Spec to backend

restore.go
When the container is destroyed or  not running, I tried to do the runc restore, restore failed which is expected because neither it was checkpointed.
But after restore failure, it failed to clean up the directory /run/oci/runc which has been created from restore.go file
This prevents to run the runc next time, because runc reported saying Container ID already exists.
So I've added the code to handle this situation to clean up the /run/oci/ directory when user tried to run runc  restore on destroyed container.
I've ensure that this will not affect the checkpointed container by adding condition to work ( clean up) only on destroyed containers.
=> Restore container cleanup

start.go
Signed-off-by: Shishir Mahajan <shishir.mahajan@redhat.com>
=> Systemd integration with runc, for on-demand socket activation

main.go
Add a `--debug-log` flag for specifying a path to write the debug logs
to for runc.
Fixes #167 
=> Add --log flag

libcontainer/label/label.go, libcontainer/label/label_selinux.go, libcontainer/label/label_selinux_test.go, libcontainer/rootfs_linux.go
- Check if Selinux is enabled before relabeling. This is a bug.
- Make exclusion detection constant time. Kinda buggy too, imo.
- Do not depend on a magic string to create a new Selinux context.
/cc @lk4d4
Signed-off-by: David Calavera <david.calavera@gmail.com>
=> Make label.Relabel safer.

libcontainer/integration/exec_test.go
I got:
```
exec_test.go:823: Mode expected to contain 'ro,nosuid,nodev,noexec': tmpfs on /sys/fs/cgroup type tmpfs (ro,seclabel,nosuid,nodev,noexec,relatime,mode=755
```
=> Fix cgroup mount tests

restore.go
With the runc, I've started the container by setting the terminal as false for checkpointing. In second terminal gave the command runc checkpoint --leave-running, 
Checkpoint happened successfully and at the same time container running in first terminal is not stopped which is expected behavior.
In the second terminal I typed runc restore, this also started the container.
with single ID runc, two instances of runc were running.
Upon killing  ./runc restore, it failed to remove the cgroup paths.
So I've added the check in restore, if the container with specific ID is already running, give an message saying " Container with ID already running".
=> Restorefixforrunningcontainer

libcontainer/cgroups/utils.go
Bug was introduced in #250
According to: http://man7.org/linux/man-pages/man5/proc.5.html
36 35 98:0 /mnt1 /mnt2 rw,noatime master:1 - ext3 /dev/root rw,errors=continue
(1)(2)(3)   (4)   (5)      (6)      (7)   (8) (9)   (10)         (11)
...
(7)  optional fields: zero or more fields of the form
"tag[:value]".
The 7th field is optional. We should skip it when parsing mount info.
=> Fix bug in find cgroup mount point dir

Makefile, README.md, libcontainer/seccomp/seccomp_linux.go, libcontainer/seccomp/seccomp_unsupported.go
Add a seccomp build tag and also support in the Makefile to add or
remove build tags.
=> Add seccomp build tag

libcontainer/cgroups/cgroups_test.go, libcontainer/cgroups/utils.go, libcontainer/container_linux.go, libcontainer/rootfs_linux.go
Here are two reasons:
* If we use systemd, we need to ask it to create cgroups
* If a container is restored with another ID, we need to
change paths to cgroups.
Cc: @boucher 
Signed-off-by: Andrey Vagin <avagin@openvz.org>
=> c/r: create cgroups to restore a container

libcontainer/integration/seccomp_test.go
@crosbymichael @mrunalp @LK4D4 
With the latest runc, I've compiled by eliminating seccomp build tag in Makefile.
When I ran make localtest, following errors occured.
--- FAIL: TestSeccompDenyGetcwd (0.37s)
seccomp_test.go:54: [8] System error: seccomp: config provided but seccomp not supported
=== RUN TestSeccompPermitWriteConditional
time="2015-09-12T14:32:13+05:30" level=warning msg="exit status 1"
--- FAIL: TestSeccompPermitWriteConditional (0.41s)
seccomp_test.go:128: [8] System error: seccomp: config provided but seccomp not supported
=== RUN TestSeccompDenyWriteConditional
Added the seccomp tag in seccomp_test.go to compile only if seccomp build tag is enabled in Makefile
=> make localtest failure on removing seccomp flag in Makefile

checkpoint.go
@crosbymichael @mrunalp 
I've done the checkpoint of my container, In another terminal ( by mistake) I have done the checkpoint again. It failed as expected. But the problem is, I could not restore my container back.
First terminal ( with terminal as false)
./runc checkpoint
Second terminal
./runc checkpoint ( this failed the checkpoint as it is already checkpointed)
Post that I could not restore my container back.
I have added condition if the container is already checkpointed, have the message to user saying Container already checkpointed, 
This will prevent checkpoint on checkpointed container.
=> Fixing checkpoint issue

start.go
The patch mainly removes the wrong "for writing".
The config files are readonly when `runc start`.
=> update the command usage for `runc start`

libcontainer/configs/mount.go, libcontainer/rootfs_linux.go, spec.go
Fixes issue #263 
Right now if one passes a mount propagation flag in spec file, it
does not take effect. For example, try following in spec json file.
{
"type": "bind",
"source": "/root/mnt-source",
"destination": "/root/mnt-dest",
"options": "rbind,shared"
}
One would expect that /root/mnt-dest will be shared inside the container
but that's not the case.
#findmnt -o TARGET,PROPAGATION
`-/root/mnt-dest                      private
Reason being that propagation flags can't be passed in along with other
regular flags. They need to be passed in a separate call to mount syscall.
That too, one propagation flag at a time. (from mount man page).
Hence, store propagation flags separately in a slice and apply these
in that order after the mount call wherever appropriate. This allows
user to …
=> libcontainer: Allow passing mount propagation flags

script/test_Dockerfile
debian testing doesn't contain criu `1.6-2` anymore, `1.7-2` is available
this fixes CI failures and `make test` locally
Signed-off-by: Antonio Murdaca <runcom@linux.com>
=> script: test_Dockerfile: update criu version

tty.go
When we are using user namespaces we need to make sure that when we do
not have a TTY we change the ownership of the pipe()'s used for the
process to the root user within the container so that when you call
open() on any of the /proc/self/fd/*'s you do not get an EPERM.
=> Fix STDIO ownership for non-tty processes

libcontainer/init_linux.go, libcontainer/integration/exec_test.go
Fix the permissions of the container's main processes STDIO when the
process is not run as the root user.  This changes the permissions right
before switching to the specified user so that it's STDIO matches it's
UID and GID.
Add a test for checking that the STDIO of the process is owned by the
specified user.
=> Fix STDIO permissions when container user not root

libcontainer/rootfs_linux.go
We need to update the mount's destination after we resolve symlinks so
that it properly creates and mounts the correct location.
This fixes a regression from the mount propagation merge. 
=> Change mount dest after resolving symlinks

libcontainer/configs/config.go, libcontainer/seccomp/seccomp_linux.go
This commit allows additional architectures to be added to Seccomp filters
created by containers. This allows containers to make syscalls using these
architectures. For example, in a container on an AMD64 system, only AMD64
syscalls would be usable unless x86 was added to the filter using this patch,
which would allow both 32-bit and 64-bit syscalls to be used.
This only adds support to the Libcontainer config - going to need an additional PR to the spec to get the field included there.
=> Libcontainer: Add support for multiple architectures in Seccomp

README.md
* version in the config example is advanced to 0.1.0 as the current spec version
* rootfsPropagation in config.json is removed
(The same one is already in runtime.json)
* rlimit time is changed from magic number to name(string)
* add pids cgroup
* add cgroup path
After this change applied, the example config in this README.md
is consistent with the result of `runc spec`.
=> README.md: Update the config example

libcontainer/configs/mount.go, libcontainer/rootfs_linux.go
Do not have methods and actions that require syscalls in the configs
package because it breaks cross compile.
=> Move mount methods out of configs pkg

libcontainer/configs/config.go, libcontainer/container_linux.go, libcontainer/process_linux.go, spec.go
The spec.go commit will be taken out once merged upstream.
=> Add prestart/poststop hooks to runc

libcontainer/process_linux.go
Signed-off-by: keloyang <yangshukui@huawei.com>
=> no need to use p.cmd.Process.Pid in function, use p.pid() instead.

libcontainer/rootfs_linux.go
This is causing docker to crash when --selinux-enforcing mode is set.
=> /proc and /sys do not support labeling

libcontainer/rootfs_linux.go
Do not remount a bind mount to enable flags if the current filesystem
mount already sufficiently provides the requested flags. MS_REC is not a
flag represented in statfs_t, so is cleaned from the comparison
operation.
=> Only remount if requested flags differ from current

libcontainer/rootfs_linux.go
We should open /dev/null with os.O_RDWR, otherwise it won't be
possible written to it
Signed-off-by: Chun Chen <ramichen@tencent.com>
Found this bug when I tried to set docker containers' stdout/stderr to null if launching with --log-drive=none. 
See the following simple program. It won't work without `os.O_RDWR`.
```
func main() {
if err := reOpenDevNull(); err != nil {
fmt.Println("Error reOpenDevNull ", err, "\n")
}
fmt.Println(syscall.Exec("/bin/echo", []string{"echo"}, os.Environ()))
}
func reOpenDevNull() error {
file, err := os.Open("/dev/null")
//	file, err := os.OpenFile("/dev/null", os.O_RDWR, 0) // should open it with os.O_RDWR
return fmt.Errorf("Failed to open /dev/null - %s", err)
}
defer file.Close()
for fd := 1; fd < 3; fd++ {
if err := …
```
=> Fix reOpenDevNull

libcontainer/configs/config.go, libcontainer/integration/exec_test.go, libcontainer/rootfs_linux.go, spec.go
=> Create container_private, container_slave and container_shared modes for rootfsPropagation

libcontainer/user/user.go, libcontainer/user/user_test.go
/etc/groups is not needed when specifying numeric group ids. This
change allows containers without /etc/groups to specify numeric
supplemental groups.
Signed-off-by: Sami Wagiaalla <swagiaal@redhat.com>
=> Allow numeric groups for containers without /etc/group

libcontainer/cgroups/fs/name.go, libcontainer/cgroups/systemd/apply_systemd.go
This fixes https://github.com/docker/docker/issues/16775
docker exec doesn't set the name cgroup for systemd correctly. This PR introduces a name cgroup that is used only in GetPaths so docker exec gets all the paths that are passed down to EnterPid.
=> Systemd name

Godeps/Godeps.json, Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mount.go, Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mountinfo.go, Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mountinfo_freebsd.go, Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mountinfo_linux.go, Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mountinfo_linux_test.go, Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mountinfo_unsupported.go, Godeps/_workspace/src/github.com/docker/docker/pkg/mount/sharedsubtree_linux_test.go, Godeps/_workspace/src/github.com/docker/docker/pkg/term/term_windows.go, Godeps/_workspace/src/github.com/docker/docker/pkg/units/size.go, libcontainer/rootfs_linux.go
Docker pkgs were updated while golinting the whole docker code base.
Now when trying to bump libcontainer/runc in docker, it fails compiling with the following error:
```
vendor/src/github.com/opencontainers/runc/libcontainer/rootfs_linux.go:424: undefined: mount.MountInfo
```
This is because, for instance, the mount pkg was updated here https://github.com/docker/docker/commit/0f5c9d301b9b1cca66b3ea0f9dec3b5317d3686d#diff-49294d05afa48e2f7c0d2f02c6f7614c and now that type is only `mount.Info`.
This patch bump docker pkgs commit and adapt code to it.
get -u github.com/opencontainers/runc fails as well while building
this is necessary to update libcontainer/runc in docker
ping @LK4D4 @crosbymichael @mrunalp 
Signed-off-by: Antonio Murdaca <amurdaca@redhat.com>
=> bump docker pkgs

libcontainer/nsenter/nsexec.c
This is required on ARM64 builds that use the clone syscall. Check [1].
[1] http://lxr.free-electrons.com/source/arch/arm64/kernel/process.c#L264
Signed-off-by: Bogdan Purcareata <bogdan.purcareata@freescale.com>
=> nsexec: Align clone child stack ptr to 16

libcontainer/integration/execin_test.go, libcontainer/process_linux.go
This rather naively fixes an error observed where a processes stdio
streams are not written to when there is an error upon starting up the
process, such as when the executable doesn't exist within the
container's rootfs.
Before the "fix", when an error occurred on start, `terminate` is called
immediately, which calls `cmd.Process.Kill()`, then calling `Wait()` on
the process. In some cases when this `Kill` is called the stdio stream
have not yet been written to, causing non-deterministic output. The
error itself is properly preserved but users attached to the process
will not see this error.
With the fix it is just calling `Wait()` when an error occurs rather
than trying to `Kill()` the process first. This seems to preserve stdio.
=> Fix for race from error on process start

libcontainer/label/label_selinux.go
Only valid options to --security-opt for label should be
disable, user, role, type, level.
Return error on invalid entry
=> Validate label options

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/cgroups/utils.go
Closes #331
Closes #329
@ibuildthecloud I carried and slightly changed code. Now you can just review and not spend time on my comments in your branch.
=> Get PIDs from cgroups recursively

libcontainer/cgroups/utils.go, libcontainer/integration/exec_test.go
=> Reorder checks in Walk to avoid panics

main.go
Add a flag which allows the user to switch logging formats when execing `runc`.
Invoking `runc --logfmt json` will cause runc to emit lines of json which can be easily hoovered/parsed/collected/filtered by log handling tools.
The default value (or, invoking `runc --logfmt text` explicitly) continues to use the textual format (with tty autodetection, etc) that logrus used previously.
=> Add ability to use json structured logging format.

libcontainer/cgroups/fs/cpuset.go
It can avoid unnecessary task migrataion, see this scenario:
- container init task is on cpu 1, and we assigned it to cpu 1,
but parent cgroup's cpuset.cpus=2
- we created the cgroup dir and inherited cpuset.cpus from parent as 2
- write container init task's pid to cgroup.procs
- [it's possibile the container init task migrated to cpu 2 here]
- set cpuset.cpus as assigned to cpu 1
- [the container init task has to be migrated back to cpu 1]
So we should set cpuset.cpus and cpuset.mems before writing pids
to cgroup.procs to aviod such problem.
=> Set cpuset.cpus and cpuset.mems before join the cgroup

libcontainer/rootfs_linux.go
Minor fix, the former setupDev=true means not setup dev,
which is contrary to intuition, just correct it.
=> Correct intuition for setupDev

libcontainer/utils/utils.go
Minor typo in the comment. Changed from existed  cleanly to exited cleanly
=> Fixing typo in the comment for exit

libcontainer/SPEC.md
The spec uses symlinks to "/proc/1/..." but the implementation uses
"/proc/self/...": see setupDevSymlinks (libcontainer/rootfs_linux.go).
The implementation is more correct, so I'm changing the spec to match
the implementation.
=> libcontainer/SPEC.md: fix /dev/stdio symlinks

libcontainer/cgroups/fs/freezer_test.go, libcontainer/cgroups/fs/hugetlb_test.go, libcontainer/cgroups/fs/name.go, libcontainer/cgroups/fs/net_cls.go, libcontainer/cgroups/fs/net_cls_test.go, libcontainer/cgroups/fs/net_prio.go, libcontainer/cgroups/fs/net_prio_test.go
This is the sixth of a bunch of small PRs to move to that goal - this fixes a bunch of build tags under libcontainer\cgroups\fs which were missing the Linux build tag. This allows a clean build and test on Windows (even though it's not actually imported).
=> Fixes build tags on cgroups\fs\*.go

libcontainer/configs/cgroup_unix.go, libcontainer/configs/cgroup_windows.go
This is the fourth of a bunch of small PRs to move to that goal - refactoring of libcontainer\configs\cgroup.go as it's a Unix specific construct. More work can be done here ultimately to completely factor this out on Windows, but let's take a baby step first.
=> Windows: Refactor configs/cgroup.go

spec.go
A return statement without arguments returns the current values of the results. This is known as a "naked" return.
Naked return statements should be used only in short function. They can harm readability in longer functions and be liable to misunderstand.
Signed-off-by: yangshukui <yangshukui@huawei.com>
=> Remove naked return

libcontainer/cgroups/fs/memory.go
We have a rule that for optional cgroups, don't fail if some
of them are not mounted, but we want it fail hard when a
user specifies an option and we are unable to fulfill the
request.
Memory cgroup should also follow this rule.
=> Unify behavior for memory cgroup

libcontainer/configs/config_unix_test.go, libcontainer/configs/config_windows_test.go, libcontainer/container.go, libcontainer/container_linux.go, libcontainer/container_windows.go, libcontainer/factory_linux_test.go
This is the first of a bunch of small PRs to move to that goal - refactoring of the state structure into platform agnostic (common) pieces, and platform specific pieces.
=> Windows: Refactor state struct

libcontainer/criu_opts_unix.go, libcontainer/criu_opts_windows.go
This is the third of a bunch of small PRs to move to that goal - refactoring of criu_opts as it's a Unix specific construct. More work can be done here ultimately to completely factor this out on Windows, but let's take a baby step first.
=> Windows: Factor down criu_opts

libcontainer/container.go, libcontainer/container_linux.go, libcontainer/container_windows.go
This is the second of a bunch of small PRs to move to that goal - refactoring of the container interface into platform agnostic (common) methods, and platform specific methods.
=> Windows: Refactor Container interface

libcontainer/container_linux.go, libcontainer/process_linux.go
When starting and quering for pids a container can start and exit before
this is set.  So set the opts after the process is started and while
libcontainer still has the container's process blocking on the pipe.
=> Fix race setting process opts

libcontainer/configs/config.go, libcontainer/container_linux.go, spec.go
Integrate poststart hooks from the OCI spec.
=> Add poststart hooks

exec.go
We make sure that the args are present. All other items are optional and default to sensible values.
=> Validate process configuration for runc exec

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/blkio.go, libcontainer/cgroups/fs/blkio_test.go, libcontainer/cgroups/fs/cpu.go, libcontainer/cgroups/fs/cpu_test.go, libcontainer/cgroups/fs/cpuacct.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/fs/cpuset_test.go, libcontainer/cgroups/fs/devices.go, libcontainer/cgroups/fs/devices_test.go, libcontainer/cgroups/fs/freezer.go, libcontainer/cgroups/fs/freezer_test.go, libcontainer/cgroups/fs/hugetlb.go, libcontainer/cgroups/fs/hugetlb_test.go, libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/cgroups/fs/name.go, libcontainer/cgroups/fs/net_cls.go, libcontainer/cgroups/fs/net_cls_test.go, libcontainer/cgroups/fs/net_prio.go, libcontainer/cgroups/fs/net_prio_test.go, libcontainer/cgroups/fs/perf_event.go, libcontainer/cgroups/fs/util_test.go
Some cleanups to make cgroup code more easier to be understood:
- Rename parent and data
- Refactor cgroupData
- Add some comments about cgroup
=> Some cgroup cleanups

Makefile
```
jessie at debian in ~/runc on i-have-this-thing-for-static-binaries
$ make static
CGO_ENABLED=1 go build -tags "seccomp cgo static_build" -ldflags "-w -extldflags -static" -o runc .
jessie at debian in ~/runc on i-have-this-thing-for-static-binaries
$ ldd runc 
not a dynamic executable
```
=> static binary \o/

libcontainer/rootfs_linux.go
Enables launching userns containers by catching EPERM errors for writing
to devices cgroups, and for mknod invocations.
This reflected the changes suggested by @mrunalp and @crosbymichael in https://github.com/opencontainers/specs/pull/228 
Signed-off-by: Abin Shahab <ashahab@altiscale.com>
=> Bind mount device nodes on EPERM

libcontainer/apparmor/apparmor_disabled.go
When apparmor is disabled during runc compilation and runtime config had the appamor profile configured, added the error condition during container start to handle this case
=> Adding error conditions when apparmor disabled

events.go
Fixing minor typo in runc events usage statement
=> Fixing minor typo in usage

README.md
=> README.md: clarify OCI JSON files

libcontainer/xattr/xattr_test.go
1)xattr Test case were not ran due to smaller case in function name
2) xattr-test file was not created in openFile
With this PR
Modified to upper case to pick up xattr test step
Added O_CREAT to create the file during localtest
=> Fixing xattr test step issue

libcontainer/network_linux.go
This patch fixes the following go vet warnings (even if `LinkAttrs` is an embedded field):
```
libcontainer/network_linux.go:96: github.com/vishvananda/netlink.Device
composite literal uses unkeyed fields
libcontainer/network_linux.go:114: github.com/vishvananda/netlink.Device
composite literal uses unkeyed fields
```
=> libcontainer: network_linux.go: fix go vet

libcontainer/configs/cgroup_unsupported.go
=> libcontainer: configs: create cgroup_unsupported.go in order to build on darwin as well

libcontainer/console_freebsd.go, libcontainer/console_linux.go, libcontainer/console_windows.go, libcontainer/error.go, libcontainer/process.go
This exports the NewConsole func and NewConsoleFromPath for external users to use.
=> Export console New func

libcontainer/container_linux.go, libcontainer/message_linux.go, libcontainer/nsenter/nsenter_test.go, libcontainer/nsenter/nsexec.c, libcontainer/process_linux.go
replace passing of pid and console path via environment variable with passing them with netlink message via an established pipe.
This is the first step in the process to unify the setup process between init and setns. We can use the netlink message to pass more structured data into the nsexec bootstrap process to eventually setup custom namespaces, setgroup, uid/gid map etc.
=> nsexec: replace usage of environment variable with netlink message

README.md
Fixes: #429
We missed the former one and haven't got a new one, remove
it from README to avoid confusing.
=> Remove the timeframe for v1 spec

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/blkio.go, libcontainer/cgroups/fs/blkio_test.go, libcontainer/cgroups/fs/cpu.go, libcontainer/cgroups/fs/cpu_test.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/fs/cpuset_test.go, libcontainer/cgroups/fs/devices.go, libcontainer/cgroups/fs/devices_test.go, libcontainer/cgroups/fs/freezer.go, libcontainer/cgroups/fs/freezer_test.go, libcontainer/cgroups/fs/hugetlb.go, libcontainer/cgroups/fs/hugetlb_test.go, libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/cgroups/fs/net_cls.go, libcontainer/cgroups/fs/net_cls_test.go, libcontainer/cgroups/fs/net_prio.go, libcontainer/cgroups/fs/net_prio_test.go, libcontainer/cgroups/fs/util_test.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/configs/cgroup_unix.go, libcontainer/container_linux.go, libcontainer/integration/exec_test.go, libcontainer/integration/template_test.go, spec.go
This allows us to distinguish cases where a container
needs to just join the paths or also additionally
set cgroups settings. This will help in implementing
cgroupsPath support in the spec.
=> Move the cgroups setting into a Resources struct

libcontainer/message_linux.go
Caclulate NLA_HDRLEN as gccgo workaround
syscall.NLA_HDRLEN is not in gccgo (as of 5.3), so in the meantime
use the #defines taken from linux/netlink.h.
See https://github.com/golang/go/issues/13629
Signed-off-by: Christy Perez <christy@linux.vnet.ibm.com>
=> Add NLA_HDRLEN workaround for gccgo

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/blkio.go, libcontainer/cgroups/fs/cpu.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/fs/devices.go, libcontainer/cgroups/fs/freezer.go, libcontainer/cgroups/fs/hugetlb.go, libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/net_cls.go, libcontainer/cgroups/fs/net_prio.go, libcontainer/cgroups/fs/pids.go, libcontainer/cgroups/fs/pids_test.go, libcontainer/cgroups/stats.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/configs/cgroup_unix.go, libcontainer/factory_linux.go, libcontainer/generic_error.go, libcontainer/init_linux.go, libcontainer/integration/exec_test.go, libcontainer/process_linux.go, libcontainer/standard_init_linux.go, spec.go
Add support for the pids cgroup controller, a recent feature that is
(see: [will be][1]) available in Linux 4.3.
Closes #382
[1]: https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=bbe179f88d39274630823a0dc07d2714fd19a103 "note the comment about the pids controller"
=> cgroups: add pids controller support

checkpoint.go, libcontainer/container.go, libcontainer/container_linux.go, libcontainer/container_linux_test.go, libcontainer/factory_linux.go, libcontainer/integration/checkpoint_test.go, libcontainer/state_linux.go, libcontainer/state_linux_test.go, restore.go, start.go
One of the most complex parts of the container are the various states that it has.  Pause, running, stopped, destroyed, checkpointed, resumed, etc.  Transitioning to these various states are also complex.  Right now we use various methods to figure out what state the container is in and not really where it was.  There is a good pattern to follow when you have to deal with states and transitions.
For each of the container states there is a separate type.  Right now most of the logic is around how to destroy the container and depending on the state what to remove on disk.  By moving all the destroy logic to the state types and letting them handle what other states they are able to transition to this it reduces the complexity when figuring out the transitions even if it is a little more code …
=> Implement Container States

libcontainer/rootfs_linux.go
Fixes: #400
It would be useful to use fuse to isolate proc info.
=> Add white list for bind mount check

libcontainer/label/label_selinux_test.go
Upon enabling selinux in Makefile, make localtest fails with following error
--- FAIL: TestRelabel (0.00s)
label_selinux_test.go:97: Relabel shared failed: %v no such file or directory
This PR handles to creation/removal of the required directory by the Relabel test step
=> make localtest failure with selinux enabled

libcontainer/selinux/selinux_test.go
Currently selinux test programs runs even with seccomp and apparmor enabled. Added the selinux compile flag to test programs
testSetfilecon function is in lower case, not executed during localtest.
Modified to uppercase ( starting letter)
Post that file creation was problem
--- FAIL: TestSetfilecon (0.00s)
selinux_test.go:19: Setfilecon failed
selinux_test.go:20: no such file or directory
Added the O_CREAT flags for the file creation
=> Adding selinux label

libcontainer/cgroups/cgroups.go, libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/systemd/apply_nosystemd.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/cgroups/utils.go, libcontainer/container_linux.go, libcontainer/container_linux_test.go, libcontainer/init_linux.go
=> Revert to non-recursive GetPids, add recursive GetAllPids

libcontainer/rootfs_linux.go, libcontainer/system/linux.go
Therefore check for that.  This is a step to being able to run docker/runc containers inside a user namespaced container.
No change in behavior when running in the initial user namespace.
Signed-off-by: Serge Hallyn <serge.hallyn@ubuntu.com>
=> Handle running nested in a user namespace

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/cpuset.go
Properly sanitise the --cgroup-parent path, to avoid potential issues
(as it starts creating directories and writing to files as root). In
addition, fix an infinite recursion due to incomplete base cases.
/cc @security-team @diogomonica
=> cgroups: fs: fix cgroup.Parent path sanitisation

exec.go, restore.go, start.go, tty.go
This flag allows systems that are running runc to allocate tty's that
they console and provide to the container.
=> Add --console to specify path to use from runc

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/blkio.go, libcontainer/cgroups/fs/cpu.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/fs/devices.go, libcontainer/cgroups/fs/freezer.go, libcontainer/cgroups/fs/hugetlb.go, libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/net_cls.go, libcontainer/cgroups/fs/net_prio.go, libcontainer/cgroups/fs/pids.go, libcontainer/cgroups/fs/pids_test.go, libcontainer/cgroups/stats.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/configs/cgroup_unix.go, libcontainer/factory_linux.go, libcontainer/generic_error.go, libcontainer/init_linux.go, libcontainer/integration/exec_test.go, libcontainer/process_linux.go, libcontainer/standard_init_linux.go, spec.go
This is a fixed up version of the now-reverted #58. The main issue with that code was that **some of** the memory cgroup's limits weren't being set at all if you were using systemd. Unfortunately, I seem to be unable to test the systemd portion (and the systemd test cases for memory don't actually test that the limits cause a process to fail).
All other cgroups were unaffected by this bug (as their limits were set using `.Set()`, and were joined either explicitly or using systemd), regardless of whether they were unsupported, partial supported or fully supported by systemd.
Some testing has revealed that the old setup didn't work either (because `getSubsystemPath` doesn't appear to work as expected).
/cc @mrunalp @hqhq @vishh @crosbymichael @dqminh
=> cgroup: add PIDs cgroup controller support

libcontainer/configs/device_defaults.go
These are the real host devices, container should not generally
have or need them.
Signed-off-by: Serge Hallyn <serge.hallyn@ubuntu.com>
=> Do not allow access to /dev/tty{0,1}

libcontainer/cgroups/utils.go
This PR solves an issue where the cgroup mount can't be found because another, non-cgroup, mount doesn't pass the validation. For example:
```
Error found less than 3 fields post '-' in "24 21 0:6 / /home/ec2-user/web/dev ro,relatime - devtmpfs  rw,size=500712k,nr_inodes=125178,mode=755"
```
The validation remains intact for cgroup mounts.
=> Only validate post-hyphen field length on cgroup mounts

libcontainer/container_linux.go, libcontainer/notify_linux.go, libcontainer/notify_linux_test.go
It may be desirable to receive memory pressure levels notifications
before the container depletes all memory. This may be useful for
handling cases where the system thrashes when reaching the container's
memory limits.
Instead of adding another notification registration function, handle
both OOM and pressure level notifications as if OOM is the highest
pressure level.
Signed-off-by: Ido Yariv <ido@wizery.com>
=> libcontainer: Add support for memcg pressure notifications

libcontainer/README.md
=> Update README of libcontainer

libcontainer/init_linux.go, libcontainer/integration/checkpoint_test.go, libcontainer/integration/exec_test.go, libcontainer/integration/execin_test.go, libcontainer/integration/seccomp_test.go, libcontainer/integration/utils_test.go, spec.go, start.go
=> Make cwd required

libcontainer/configs/cgroup_unix.go
Fixes: https://github.com/docker/docker/issues/19329
=> Embed Resources for backward compatibility

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/configs/cgroup_unix.go
This is for supporting joining cgroups by container id in docker.
See https://github.com/docker/docker/pull/19244
=> Add support for just joining in apply using cgroup paths

libcontainer/configs/cgroup_unix.go
Set `-1` doesn't mean disable swap, disable swap means you
can't use swap memory, set `-1` really means you can use
unlimited swap memory.
=> Fix comment of swap limit

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/cgroups/systemd/apply_systemd.go
Modify the memory cgroup code such that kmem is not managed by Set(), in
order to allow updating of memory constraints for containers by Docker.
This also removes the need to make memory a special case cgroup.
This is split from #470:
>  The other issue is fixed by #495:
> * Updating a container doesn't work for the memory cgroup, causing `docker update` tests to fail. This was caused by my commit `f36ed4b174bb7e8951db6b61e2202a45a7251e30`.
/cc @crosbymichael @mrunalp @dqminh @LK4D4
=> cgroups: set memory cgroups in Set

libcontainer/init_linux.go
For existing consumers of libconatiner to not require cwd inside the
libcontainer code.  This can be done at the runc level and is already
evaluated there.
=> Only set cwd when not empty

main.go
This PR prints specs versions when `runc --version` is used.
Sample:
```
marcos@XPS:~$ ./runc --version
runc version 0.3
spec version 0.2.0
```
Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>
=> Add spec version to runC version cli

libcontainer/README.md
=> Revert "update date in README"

libcontainer/container_linux.go, libcontainer/error.go, libcontainer/factory_linux.go, libcontainer/state_linux.go, libcontainer/state_linux_test.go
There were issues where a process could die before pausing completed
leaving the container in an inconsistent state and unable to be
destoryed.  This makes sure that if the container is paused and the
process is dead it will unfreeze the cgroup before removing them.
Closes #484 
Closes #470
=> Fix various state bugs for pause and destroy

libcontainer/cgroups/systemd/apply_systemd.go
Rather than using '/' to denote hierarchy in slice names, systemd uses
'-' in an odd way. This results in runC incorrectly assuming that
certain kernel features are missing (and using inconsistent paths for
the cgroups not supported by systemd), because the "subsystem path" used
is not the one that systemd has created. Fix all of this by properly
expanding slice names.
/cc @LK4D4 @mrunalp @dqminh @crosbymichael @hqhq
=> cgroup: systemd: properly expand systemd slice names

libcontainer/container_linux.go, libcontainer/factory_linux.go, libcontainer/factory_linux_test.go, libcontainer/generic_error.go, libcontainer/init_linux.go, libcontainer/process_linux.go, libcontainer/utils/utils.go
Marshall the raw objects for the sync pipes so that no new line chars
are left behind in the pipe causing errors.
=> Do not use stream encoders for pipe communication

libcontainer/cgroups/systemd/apply_systemd.go
Add some further (not critical, since Docker does this already)
validation to systemd slice names, to make sure users don't get cryptic
errors.
This is inspired from docker/docker#19774.
/cc @mrunalp @hqhq @LK4D4
=> cgroup: systemd: further systemd slice validation

libcontainer/container.go, libcontainer/container_linux.go, libcontainer/factory_linux.go, list.go, main.go
Adds a runc list command.  Show minimal information about the container and their current status. 
=> adds list command

delete.go, libcontainer/state_linux.go, main.go, start.go
By adding detach to runc the container process is the only thing running
on the system is the containers process.
This allows better usage of memeory and no runc process being long
lived.  With this addition you also need a delete command because the
detached container will not be able to remove state and the left over
cgroups directories.
=> Add detach to runc

main.go
This happened from a bad rebase, sorry.
=> Remove double exec from command list

spec.go
=> Remove version check in runc

libcontainer/container.go, libcontainer/container_linux.go, libcontainer/factory_linux.go, list.go, utils.go
We don't need a CreatedTime method on the container because it's not
part of the interface and can be received via the state.  We also do not
need to call it CreateTime because the type of this field is time.Time
so we know its time.
=> Update list command and created methods

libcontainer/nsenter/nsexec.c
Under CentOS/RHEL 6, the `linux/netlink.h` header is missing definition for `sa_family_t`. That definition is provided by including `bits/sockaddr.h`.
Under the applied patch, `runc` builds cleanly under the CentOS 6 kernel (`2.6.32-573.12.1.el6.x86_64`) and the CentOS 7 kernel (`3.10.0-327.4.5.el7.x86_64`).
With this patch `runc` works on a stock CentOS/RHEL 6 system (subject to proper `config.json` and `runtime.json` configuration).
=> Add a compatibility header for CentOS/RHEL 6

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/cgroups/fs/stats_util_test.go, libcontainer/cgroups/stats.go
The value is populated with the content of `limit_in_bytes`.
=> Add limit value to memory stats

libcontainer/cgroups/utils.go, libcontainer/cgroups/utils_test.go
GetMounts is very cpu-expensive. I'll change other funcs in this package
to reuse code from GetCgroupMounts later.
=> Remove usage of GetMounts from GetCgroupMounts

libcontainer/keys/keyctl.go, libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go
Create a new session key for every container to avoid sharing the key
structure of the process that created the container and the container
inherits from.
Fixes #453
Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>
=> Create a new session key for every container

exec.go, restore.go, start.go, tty.go, utils.go
This change adds loading a process.json for exec via a flag so that you can exec processes using both methods.  
It also adds detach and the pid-file to exec so that runc can exit after it spawns the processes.
=> Load process.json for exec and add detach

README.md, exec.go, kill.go, main.go, main_unsupported.go, restore.go, start.go, utils.go
Closes #532
This requires the container id to always be passed to all runc commands
as arg one on the cli.  This was the result of the last OCI meeting and
how operations work with the spec.
=> Require container id as arg1

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/configs/cgroup_unix.go, libcontainer/integration/template_test.go, libcontainer/rootfs_linux.go, libcontainer/utils/utils.go, spec.go
Fixes #396
Closes #397 
Closes #399 
---
Since #397 and #399 haven't been touched in a month, I've made this PR.
This hopefully includes all decisions following the discussions in the aforementioned PRs.
However, since #466 was merged, we may need a better name than CgroupsPath now that we have a "Paths" member, but I couldn't come up with a better name. Open to suggestions.
=> Replace Cgroup Parent and Name fields by CgroupsPath

restore.go
@crosbymichael 
Though there is no direct terminal associated with for C/R, added the closure for pipes during failure of container restore
Please let me know your comments.
=> Adding tty closure for restore operation

libcontainer/rootfs_linux.go
Also adds /proc/net/dev to the valid mount destination white list
Signed-off-by: Chun Chen <ramichen@tencent.com>
=> It's /proc/stat, not /proc/stats

libcontainer/factory_linux.go, libcontainer/generic_error.go, libcontainer/process_linux.go
It's never used and not needed. Our pipe is created with
syscall.SOCK_CLOEXEC, so pipe will be closed once container
process executed successfully, parent process will read EOF
and continue. If container process got error before executed,
we'll write procError to sync with parent.
=> Remove procStart

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/apply_raw_test.go, libcontainer/utils/utils.go
Fix m.Path legacy code to actually work. This means
we'll be able to finally vendor to Docker. It'd be nice
to merge this ASAP so we can finally merge a bunch
of stuff in Docker.
Fixes #551
/cc @crosbymichael @LK4D4
=> libcontainer: cgroups: fs: fix innerPath

restore.go, utils.go
`newSignalHandler` needs to be called before the process is started, otherwise if
the process exits quickly the SIGCHLD can be recieved (and ignored) before [the signal
handler is set up](https://github.com/opencontainers/runc/blob/master/signals.go#L24). When this happens [the syscall.Wait4](https://github.com/opencontainers/runc/blob/master/signals.go#L59) never runs, the process becomes a zombie, and the exit code isn't returned to the user.
Signed-off-by: Julian Friedman <julz.friedman@uk.ibm.com>
=> Register signal handlers earlier to avoid zombies

libcontainer/rootfs_linux.go
Host is having /dev/core linked to /proc/kcore
To be consistent with host, changing the link name from /dev/kcore to /dev/core
=> Change softlink name to /dev/core

libcontainer/configs/config.go, libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go, libcontainer/system/linux.go, spec.go
Support NoNewPrivileges for additional security in containers.
=> Add support for NoNewPrivileges

utils.go
This occurs when the container was requested to be started in detached
mode and without a tty.
=> Prevent a panic when container fails to start

restore.go, utils.go
Started container in detached mode, since the executable was not in right path, it could not start the container
Since the container started in detached mode, return value of setupIO function was nil.
The container failed to start of incorrect executable path, it tried to close the tty. Derefenced the nil pointer and thrown the below panic condition
Added the nil check before tty closure as part of fix
Below is the panic trace
WARN[0000] os: process already finished
[signal 0xb code=0x1 addr=0x0 pc=0x410e5d]
main.(*tty).Close(0x0, 0x0, 0x0)
/home/raj/go/pkg/src/github.com/opencontainers/runc/tty.go:82 +0x12d
main.runProcess(0x7ff6aac62c18, 0xc20809a0c0, 0xc2080366f0, 0xc2080a11a0, 0x0, 0x0, …
=> panic during start of failed detached container

libcontainer/cgroups/fs/apply_raw.go
It's handled in `destroy()`, no need to do this in
`Apply()`. I found this because systemd cgroup didn't
do this removal and it works well.
=> Remove unneeded cgroups path removal

libcontainer/cgroups/fs/devices.go
When in a non-initial user namespace you cannot update the devices
cgroup whitelist (or blacklist).  The kernel won't allow it.  So
detect that case and don't try.
This is a step to being able to run docker/runc containers inside a user
namespaced container.
Signed-off-by: Serge Hallyn <serge.hallyn@ubuntu.com>
=> Do not set devices cgroup entries if in a user namespace

checkpoint.go, delete.go, events.go, exec.go, kill.go, list.go, main.go, pause.go, restore.go, spec.go, start.go
=> updating usage for runc, and all runc commands that now use <container id> as the first argument

spec.go, spec_test.go
When CgroupsPath code was introduced with #497 it was mistakenly made
to act as the equivalent of docker CgroupsParent. This ensure that it
is taken as the final cgroup path.
A couple of unit tests have been added to prevent future regression.
--- 
This basically fix a mistake I made within #497. I somehow only realized this now while trying to use v0.0.8 with docker.
=> Fix CgroupsPath interpretation

utils.go
Removing the host devices tty0 and tty1 from allowed devices.
=> Removing tty0 tty1 from allowed devices

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/name.go
If you don't move the process out of the named cgroup for systemd then
systemd will try to delete all the cgroups that the process is currently
in.
=> Move the process outside of the systemd cgroup

start.go
Even in the detach usecase we need to make sure that the contianer is
destroyed if there is an error starting the container or anywhere in
that workflow.
=> Make sure container is destroyed on error

libcontainer/generic_error.go, libcontainer/init_linux.go, libcontainer/process_linux.go, libcontainer/rootfs_linux.go, libcontainer/standard_init_linux.go
Today mounts in pre-start hooks get overriden by the default mounts.
Moving the pre-start hooks to after the container mounts and before
the pivot/move root gives better flexiblity in the hooks.
=> Move pre-start hooks after container mounts

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/configs/cgroup_unix.go, libcontainer/integration/template_test.go, spec.go
This prior fix was lost in other refactorings of the codebase.
Fixes: #543 
Fixes: #575
=> Handle memory swappiness default properly

libcontainer/configs/validate/config.go
/proc/sys isn't completely namespaced and only some properties are allowed
per linux namespace.
The list has been compiled from namespaces(7)
=> Add validation for sysctl

libcontainer/container_linux.go, libcontainer/init_linux.go, libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go
Create a unique session key name for every container. Use the pattern
_ses.<postfix> with postfix being maximum 12 characters of the container's
Id.
This patch does not prevent containers from joining each other's session
keyring.
Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>
=> Create unique session key name for every container

.gitignore, Makefile
Currently we need to clone github.com/opencontainers/runc to
GOPATH so we can make it, it's not friendly for developers.
We can resolve it by vendoring itself as a symlink in GOPATH.
=> Make runc buildable everywhere

libcontainer/rootfs_linux.go
os.Remove function is called at the last in the pivotRoot function. There are sys calls being called and upon failure it will return earlier. In that case removal of pivotRoot may not gets called. So added os.Remove during defer
=> Removing pivot directory in defer

libcontainer/rootfs_linux.go
This allows the mount syscall to validate the addiontal types where we
do not have to perform extra validation and is up to the consumer to
verify the functionality of the type of device they are trying to
mount.
Fixes #572
=> Allow extra mount types

restore.go, tty.go, utils.go
Add a waitgroup to wait for the io.Copy of stdout/err to finish before
existing runc.  The problem happens more in exec because it is really
fast and the pipe has data buffered but not yet read after the process
has already exited.
=> Wait for pipes to write all data before exit

libcontainer/factory_linux.go, libcontainer/integration/execin_test.go, libcontainer/integration/init_test.go, start.go, utils.go
Exec erros from the exec() syscall in the container's init should be
treated as if the container ran but couldn't execute the process for the
user instead of returning a libcontainer error as if it was an issue in
the library.
Before specifying different commands like `/etc`, `asldfkjasdlfj`, or
`/alsdjfkasdlfj` would always return 1 on the command line with a
libcontainer specific error message.  Now they return the correct
message and exit status defined for unix processes.
Example:
```bash
root@deathstar:/containers/redis# runc start test
exec: "/asdlfkjasldkfj": file does not exist
root@deathstar:/containers/redis# echo $?
127
root@deathstar:/containers/redis# runc start test
exec: "asdlfkjasldkfj": executable file not found in $PATH
root@deathstar:/containers/redis# echo $?
127 …
```
=> Return proper exit code for exec errors

exec.go, libcontainer/configs/config.go, list.go, spec.go
This adds the bundle path to runc list via labels added to the libcontainer config.  This allows any type of information to be added to the container and its state.
Fixes #548  
Closes #559
=> Add bundle to runc list

Dockerfile, Makefile
This creates a runC binary using a Docker container. This means you are no longer dependent on having Golang installed on the host. The base image is the existing runctestimage. If this does not already exist it will be built as part of the build.
Usage: `make dbuild`
Result: A runC binary in the root directory. 
Signed-off-by: Ben Hall <ben@benhall.me.uk>
=> Build runC binary via a Docker container

libcontainer/process_linux.go
Sometimes when the process finishes, runc fails with error like:
error: [10] System error: invalid character 'a' looking for beginning of value
This is because part of encoded string was read and abandoned when decoding a smaller type.
This fix will avoid part of the stream be read and abandomed by using a single instance of Decoder
for the stream.
Signed-off-by: Hushan Jia <hushan.jia@gmail.com>
=> Use single decoder instance for one stream

libcontainer/stacktrace/capture_test.go
The path in the stacktrace might not be:
"github.com/opencontainers/runc/libcontainer/stacktrace"
For example, for me its:
"_/go/src/github.com/opencontainers/runc/libcontainer/stacktrace"
so I changed the check to make sure the tail end of the path matches instead
of the entire thing
=> Fix to allow for build in different path

libcontainer/configs/namespaces_unix.go, libcontainer/container_linux.go, libcontainer/init_linux.go, libcontainer/integration/exec_test.go, libcontainer/integration/execin_test.go, libcontainer/integration/utils_test.go, libcontainer/message_linux.go, libcontainer/nsenter/nsenter_test.go, libcontainer/nsenter/nsexec.c, libcontainer/process_linux.go, libcontainer/standard_init_linux.go, spec.go
This is a rebase of https://github.com/opencontainers/runc/pull/105.
It move the `setns` calls within the init C code. This allows for namespaces that only affect future children (e.g. `NEWPID`) to correctly apply to created containers.
=> Move setns within nsexec

spec.go, utils.go
This updates the current list to what we have now in docker and also
makes these always added so that these are masked out.  Privileged
containers can always unmount these if they want to read from kcore or
something like that.
=> Update masked and ro paths

spec.go
It is what we hard coded in runC, now we do it in config,
also removed the legacy function.
=> Set sysfs readonly in config

main.go, state.go
=> adds the spec required state command

libcontainer/container_linux.go
currentState() always adds all possible namespaces to the state,
regardless of whether they are supported.
If orderNamespacePaths detects an unsupported namespace, an error is
returned that results in initialization failure.
Fix this by only adding paths of supported namespaces to the state.
=> Fix handling of unsupported namespaces

libcontainer/nsenter/nsexec.c
Build failed on centos6:
```sh
#make
...
In file included from Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c:6:
/usr/include/linux/netlink.h:35: error: expected specifier-qualifier-list before 'sa_family_t'
```
PR fix the error.
Signed-off-by: Ye Yin <eyniy@qq.com>
=> Fix build error on centos6

libcontainer/container.go
As per the state implementation currently checkpoint is not an state transition. Upon checkpoint we are cleaning up the state.json  & respective directory too. Eliminated the string corresponding to checkpoint.
=> Eliminating checkpoint state in container

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/specs/README.md, Godeps/_workspace/src/github.com/opencontainers/specs/config-linux.md, Godeps/_workspace/src/github.com/opencontainers/specs/config.go, Godeps/_workspace/src/github.com/opencontainers/specs/config.md, Godeps/_workspace/src/github.com/opencontainers/specs/config_linux.go, Godeps/_workspace/src/github.com/opencontainers/specs/runtime.md, Godeps/_workspace/src/github.com/opencontainers/specs/style.md, Godeps/_workspace/src/github.com/opencontainers/specs/version.go, exec.go, libcontainer/configs/config.go, libcontainer/container_linux.go, libcontainer/init_linux.go, libcontainer/process.go, libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go, spec.go, utils.go
This updates the specs dependency to master.
It also refactors the use of process specific settings after moving caps, no new privs, selinux and apparmor labeling fields to the process.  It does this in a reverse compatible way to existing libcontainer users.
=> Update specs dep and runc functionality

libcontainer/system/unsupported.go
Add a stub for non-Linux that always returns false
=> Stub RunningInUserNS for non-Linux

libcontainer/init_linux.go, libcontainer/nsenter/nsexec.c, libcontainer/process_linux.go, libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go
The re-work of namespace entering lost the setuid/setgid that was part
of the Go-routine based process exec in the prior code. A side issue was
found with setting oom_score_adj before execve() in a userns that is
also solved here.
=> Properly setuid/setgid after entering userns

libcontainer/cgroups/systemd/apply_systemd.go
We are now setting all cgroup entries in fs way, no need to
use dbus for memory, cpu shares etc.
=> Cleanup systemd apply

Makefile, tests/sniffTest
just so that we're not merging code into master w/o any tests at all.
I expect this to be removed once we have a real testing infrastructure.
=> Add the most basic sniff tests of runc

libcontainer/configs/config.go, libcontainer/factory_linux_test.go
This is needed to make 'runc delete' correctly run the post-stop hooks.
Signed-off-by: Ed King <eking@pivotal.io>
Signed-off-by: Julian Friedman <julz.friedman@uk.ibm.com>
=> Serialize CommandHooks to state so that PostStop hooks execute during 'runc delete'

spec.go
When there is failure in loadpsec function, return nil instead of spec
=> Handling error condition in loadspec

utils.go
Currently pid-file over riding the previous container pid-file and moreover there is chance of over riding the host files using create. added the fix to create the file only if not exists
=> Create pid file when not exist

events.go, exec.go, main.go, main_unsupported.go, restore.go, spec.go, start.go, utils.go
The error handling on the runc cli is currenly pretty messy because
messages to the user are split between regular stderr format and logrus
message format.  This changes all the error reporting to the cli to only
output on stderr and exit(1) for consumers of the api.
By default logrus logs to /dev/null so that it is not seen by the user.
If the user wants extra and/or structured loggging/errors from runc they
can use the `--log` flag to provide a path to the file where they want
this information.  This allows a consistent behavior on the cli but
extra power and information when debugging with logs.
This also includes a change to enable the same logging information
inside the container's init by adding an init cli command that can share
the existing flags for all other runc commands. …
=> Improve error handling in runc

libcontainer/factory_linux.go, libcontainer/integration/execin_test.go, libcontainer/integration/init_test.go, start.go, utils.go
This reverts commit 6bb653a6e881594eebd9532f6ed95339d3856ac6.
I made this original commit to help runc handle exit status from containers.  However, it was not the right place to do this.  With the current code there is no way to synchronously know that the container failed to start because of the exec error, especially with `runc start -d`.
=> Revert "Return proper exit code for exec errors"

libcontainer/nsenter/nsexec.c
Clears supplementary groups that have effect on the
mount permissions before joining the user specified
groups happens.
cc @mlaventure @estesp 
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
=> Clear groups after entering userns

Makefile, main.go
=> Add gitcommit to runc builds

libcontainer/cgroups/fs/pids.go, libcontainer/cgroups/fs/pids_test.go, libcontainer/cgroups/stats.go
In order to allow nice usage statistics (in terms of percentages and
other such data), add the value of pids.max to the PidsStats struct
returned from the pids cgroup controller.
=> libcontainer: cgroups: add pids.max to PidsStats

libcontainer/container_linux.go, libcontainer/criu_opts_unix.go, libcontainer/criurpc/criurpc.pb.go, libcontainer/criurpc/criurpc.proto
Docker uses Prestart hooks to call a libnetwork hook to configure container's network namespace. When we are restoring a container, we need to call the libnetwork hook too.
I had an idea to add Prerestore hooks, but then I decided that it isn't actually required.
Cc: @boucher
=> Call Prestart hooks before restoring processes

exec.go, spec.go, utils.go
Handling the validation of spec in exec and start of container.
Added the args check in validation check to avoid index out of bounds during container exec.
=> Adding spec validation for exec and start

libcontainer/generic_error.go, main.go, start.go, utils.go
This ensures that anything written to the logs are synced as they
happen.
This also changes the error message of the libcontainer error.  The
original idea was to have this extra information in the message but it
makes it hard to parse and if the caller needed this information they
can just get it from the error type.
=> Ensure logs are flushed

libcontainer/cgroups/systemd/apply_systemd.go
This is required because we manage some of the cgroups ourselves.
This recommendation came from talking with systemd devs about
some of the issues that we see when using the systemd cgroups driver.
=> Set Delegate to true for cgroups transient units

Makefile
So we won't see the link message every time we make
runc. Also it use force remove when make clean, so
we don't see annoying error when do extra make clean.
=> Don't link runc every time

exec.go, libcontainer/init_linux.go, libcontainer/system/linux.go, restore.go, signals.go, start.go, utils.go
We need to make sure the container is destroyed before closing the stdio
for the container.  This becomes a big issues when running in the host's
pid namespace because the other processes could have inherited the stdio
of the initial process.  The call to close will just block as they still
have the io open.
Calling destroy before closing io, especially in the host pid namespace
will cause all additional processes to be killed in the container's
cgroup.  This will allow the io to be closed successfuly.
This change makes sure the order for destroy and close is correct as
well as ensuring that if any errors encoutered during start or exec will
be handled by terminating the process and destroying the container.  We
cannot use defers here because we need to enforce the correct ordering
on …
=> Destroy container along with processes before stdio

start.go
Shrink it to one line so it looks consistent in help message.
Without this PR, it looks like:
```
COMMANDS:
checkpoint   checkpoint a running container
delete       delete any resources held by the container often used with detached containers
events       display container events such as OOM notifications, cpu, memory, IO and network stats
exec         execute new process inside the container
init         init is used to initialize the containers namespaces and launch the users process.
This command should not be called outside of runc.
kill         kill sends the specified signal (default: SIGTERM) to the container's init process
```
=> Fix help info of init command

libcontainer/factory_linux.go
Fixes #635
Also removed _ ,as _ is part of \w
=> Fixing valid-id in regex

libcontainer/user/lookup.go
Export errors as variables when no matching entries are found in passwd or group file.
=> Export user and group lookup errors as variables.

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/cgroups/stats.go, libcontainer/configs/cgroup_unix.go, spec.go
This is a carry of #376, as well as adding statistics to `kmem.tcp`. This cgroup knob does not have the same requirement as `kmem` (it must be set before any processes enter the cgroup), so we can treat it like any other memory knob.
=> libcontainer: cgroups: add support for kmem.tcp limits

libcontainer/cgroups/fs/pids.go, libcontainer/cgroups/fs/pids_test.go, libcontainer/cgroups/stats.go
Make sure we don't error out collecting statistics for cases where
pids.max == "max". In that case, we can use a limit of 0 which means
"unlimited".
Sorry, I forgot about this case in #640. This should fix it.
/cc @hqhq @mrunalp
=> libcontainer: cgroups: deal with unlimited case for pids.max

libcontainer/process_linux.go
=> Set oom_score_adj before we send the config to avoid race

spec.go
Fixed the typo in error for device access.
=> fixing typo in device access error

main.go, man/runc.8.md, restore.go, spec.go, spec_test.go, utils.go
This adds a flag to enable systemd cgroups in runc.
=> Add support for enabling systemd cgroups 

spec.go
systemd expects cgroupsPath to be of form "slice:prefix:name".
So dont call cleanPath on it anymore.
Signed-off-by: Anusha Ragunathan <anusha@docker.com>
=> Dont cleanPath for systemd cgroup paths.

start.go
Move this to be one of the first things that is done in the main if we
are executing the init as it is causing some inconsistencies with capset on ARM systems.  
Fixes #684
=> Move lockthread to package level

libcontainer/seccomp/seccomp_linux.go
Logging in packages is bad, mkay.
=> Remove log from seccomp package

libcontainer/init_linux.go, libcontainer/integration/exec_test.go, libcontainer/integration/execin_test.go, libcontainer/process_linux.go, libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go, libcontainer/system/linux.go
Fixes #680
This changes setupRlimit to use the Prlimit syscall (rather than
Setrlimit) and moves the call to the parent process. This is necessary
because Setrlimit would affect the libcontainer consumer if called in
the parent, and would fail if called from the child if the
child process is in a user namespace and the requested rlimit is higher
than that in the parent.
Signed-off-by: Julian Friedman <julz.friedman@uk.ibm.com>
=> Set rlimits using prlimit in parent

libcontainer/cgroups/utils.go
Based on Golang document, %s is for "the uninterpreted bytes of the
string or slice", so %v is more appropriate.
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>
=> Use %v for map structure format

libcontainer/rootfs_linux.go
Do label mqueue when mounting it with label failed/not supported.
Signed-off-by: Thomas Tanaka <thomas.tanaka@oracle.com>
=> Only perform mount labelling when necessary

libcontainer/user/user.go, libcontainer/user/user_test.go
Most shadow-related tools don't treat numeric ids as potential
usernames, so change our behaviour to match that. Previously, using an
explicit specification like 111:222 could result in the UID and GID not
being 111 and 222 respectively (which is confusing).
Fixes #695
=> libcontainer: user: always treat numeric ids numerically

libcontainer/specconv/spec_linux.go, restore.go, start.go, utils.go
This adds a `--no-pivot` cli flag to runc so that a container's rootfs
can be located ontop of ramdisk/tmpfs and not fail because you cannot
pivot root.
This should be a cli flag and not part of the spec because this is a
detail of the host/runtime environment and not an attribute of a
container.
=> Add --no-pivot option for containers on ramdisk

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go
Currently, if we start a container with:
`docker run -ti --name foo --memory 300M --memory-swap 500M busybox sh`
Then we want to update it with:
`docker update --memory 600M --memory-swap 800M foo`
It'll get error because we can't set memory to 600M with
the 500M limit of swap memory.
=> Fix problem when update memory and swap memory

libcontainer/configs/validate/validator.go, libcontainer/configs/validate/validator_test.go
This PR renames the `config.go` file to `validator.go` (the interface name) and add unit tests covering the flows that check if the config is valid or not.
=> Add unit tests for validate.Validator

Makefile
golang.org/x/tools/cmd/vet has been removed as it is available in go cmd directly
=> Fix the build by removing go get for vet

libcontainer/configs/config.go
Fixes #733
This reports the stdout/err for a hook if it returns a non-zero exit
status.
=> Report hook output on error

libcontainer/label/label.go, libcontainer/label/label_selinux.go, libcontainer/selinux/selinux_test.go
One of our volume plugins needs to get the label of the target mount point
so that it can set the content inside of the volume to match.
We need label.GetFileLabel() to make this work.
=> Add label.GetFileLabel interface

libcontainer/configs/validate/validator.go
Without this, we fail with an error when the rootfs property has a trailing slash
```
/runc/containers/fedora/ is not an absolute path or is a symlink
```
=> Fix for runc failing when rootfs has a trailing slash

libcontainer/rootfs_linux.go, libcontainer/rootfs_linux_test.go
setupDev was introduced in #96, but broken since #536 because spec 0.3.0 introduced default devices.
Fix #80 again
Fix docker/docker#21808
This is carry of #732, so Closes #732 
ping @mrunalp @cpuguy83 @crosbymichael
=> Fix setupDev logic in rootfs_linux.go

exec.go, libcontainer/configs/config.go, libcontainer/container_linux.go, libcontainer/integration/exec_test.go, libcontainer/process_linux.go, libcontainer/state_linux.go, libcontainer/utils/utils.go, libcontainer/utils/utils_test.go, list.go, state.go
* Adds `BundlePath` field in `HookState`
* Renames JSON field for `HookState.Version` to `ociVersion`
* Promotes private `searchLabels` function to `libcontainer/utils`
Signed-off-by: George Lestaris <glestaris@pivotal.io>
Signed-off-by: Ed King <eking@pivotal.io>
/cc @teddyking @cloudfoundry/cf-garden
=> HookState adhears to OCI

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go
When swap memory is unsupported, Docker will set
cgroup.Resources.MemorySwap as -1.
Fixes: https://github.com/docker/docker/pull/21937
=> Fix problem when swap memory unsupported

Makefile
Since runC requires root in order to run, it makes more sense to put it
in /usr/sbin (which is traditionally for root-only utilities). This also
fixes the section number mismatch (man8 is usually for administrative
utilities in /usr/sbin).
Closes #693
=> Makefile: install to /usr/local/sbin

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/cpu_test.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/cgroups/stats.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/cgroups/utils.go, libcontainer/configs/config.go, libcontainer/configs/config_unix.go, libcontainer/configs/device_defaults.go, libcontainer/container.go, libcontainer/container_linux.go, libcontainer/container_linux_test.go, libcontainer/criu_opts_unix.go, libcontainer/error.go, libcontainer/integration/init_test.go, libcontainer/keys/keyctl.go, libcontainer/label/label_selinux.go, libcontainer/label/label_selinux_test.go, libcontainer/message_linux.go, libcontainer/rootfs_linux.go, libcontainer/seccomp/seccomp_unsupported.go, libcontainer/selinux/selinux.go, libcontainer/stacktrace/capture.go, libcontainer/system/linux.go, utils.go
No substantial code change.
Note that some style errors reported by `golint` are not fixed due to possible compatibility issues.
Signed-off-by: Akihiro Suda <suda.kyoto@gmail.com>
=> Fix trivial style errors reported by `go vet` and `golint`

script/test_Dockerfile
This is a WIP to fix the issues discussed over in https://github.com/opencontainers/runc/pull/749#issuecomment-209571860.
I'm seeing CRIU issues locally, but I don't know if that's related to this change or my local setup (so hopefully Jenkins can help shed more light on that).
=> Switch from mixed jessie/testing to jessie+backports for libseccomp

libcontainer/specconv/spec_linux.go
Currently validator code( validate/config.go) in runc implemented to throw error  if user is not specified in namespaces part of config ( even though have UID/gid mapping). But in spec userns is added by default part of config.
with this PR, it will throw an error as per existing validation logic.
"User namespace mappings specified, but USER namespace isn't enabled in the config"
@dqminh 
This was added part of #105, please confirm whether this was desired behavior.
=> handling error for userns

libcontainer/SPEC.md
Eliminated redundant word in SPEC
=> Typo in SPEC.md

libcontainer/container_linux.go, libcontainer/generic_error.go, libcontainer/process_linux.go, libcontainer/rootfs_linux.go
This is the inital port of the libcontainer.Error to added a cause to
all the existing error messages.  Going forward, when an error can be
wrapped because it is not being checked at the higher levels for
something like `os.IsNotExist` we can add more information to the error
message like cause and stack file/line information.  This will help
higher level tools to know what cause a container start or operation to
fail.
=> Add cause to error messages

libcontainer/rootfs_linux.go
We use bind mount to achieve this as other file system remounts are disallowed
in a user namespace.
=> Allow mounting cgroups as read-only when user namespace is configured

libcontainer/nsenter/nsexec.c
Remove a wrongly added include which was added in commit 3c2e77ee (Add a
compatibility header for CentOS/RHEL 6, 2016-01-29) apparently to
fix this compile error on centos 6:
> In file included from
> Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c:20:
> /usr/include/linux/netlink.h:35: error: expected specifier-qualifier-list before 'sa_family_t'
The glibc bits/sockaddr.h says that this header should never be included
directly[1]. Instead, sys/socket.h should be used.
The problem was correctly fixed later, in commit 394fb55 (Fix build
error on centos6, 2016-03-02) so the incorrect bits/sockaddr.h can
safely be removed.
This is needed to build musl libc.
Fixes #761
[1]: https://github.molgen.mpg.de/git-mirror/glibc/blob/20003c49884422da7ffbc459cdeee768a6f …
=> nsexec: fix build against musl libc

libcontainer/container_linux.go
As per current implementation running  container can be paused. Updated the comment to remove pausing state
=> Update the comment for container pause

exec.go
During exec of container, panic thrown for index out of range
exec failed: panic from initialization: runtime error: index out of range, /home/raj/go/pkg/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:255 (0x4b763f)
/usr/local/go/src/runtime/asm_amd64.s:401 (0x43b525)
/usr/local/go/src/runtime/panic.go:387 (0x428ee8)
/usr/local/go/src/runtime/panic.go:12 (0x42807e)
/home/raj/go/pkg/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/setns_init_linux.go:52 (0x4b44e8)
/home/raj/go/pkg/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:263 (0x49fd04) …
=> Fixing index out of range during exec of container

libcontainer/cgroups/utils.go, libcontainer/rootfs_linux.go, libcontainer/selinux/selinux.go
Fixes #631 (and the corresponding issue docker/docker#20851). The solutions here are:
1. Skip parsing of `mountinfo` in [FindCgroupMountpoint()](https://github.com/opencontainers/runc/blob/177f2c405cc0f4fc027f7210675350e9be2b515c/libcontainer/cgroups/utils.go#L22) and [FindCgroupMountpointAndRoot()](https://github.com/opencontainers/runc/blob/177f2c405cc0f4fc027f7210675350e9be2b515c/libcontainer/cgroups/utils.go#L49) when a given cgroup subsystem is not enabled. The check is done by testing the subsystem is included in a result of [ParseCgroupFile()](https://github.com/opencontainers/runc/blob/177f2c405cc0f4fc027f7210675350e9be2b515c/libcontainer/cgroups/utils.go#L246).
2. Break the parsing loop in [FindCgroupMountpointDir()](https://github.com/opencontainers/runc/blob/177f2c405cc0f4fc027f …
=> Eliminate redundant parsing of mountinfo

libcontainer/configs/validate/validator.go, libcontainer/specconv/spec_linux.go
Added the error check if selinux is not enabled and config.json had the process label for selinux.
=> Adding selinux check during container start

README.md
Runc install path changed to /usr/local/sbin, updated the readme file.
=> Updating README for runc path

libcontainer/specconv/spec_linux.go
This caused issues if someone omitted or set "resources": null, in the
runC config. The panic follows.
```
[signal 0xb code=0x1 addr=0x20 pc=0x545b53]
panic(0x7aed40, 0xc820014260)
/usr/lib64/go/src/runtime/panic.go:464 +0x3e6
github.com/opencontainers/runc/libcontainer/specconv.CreateLibcontainerConfig(0xc8200b0e30, 0x836480, 0x0, 0x0)
/home/cyphar/src/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/specconv/spec_linux.go:222 +0xe83
main.createContainer(0xc82007eb40, 0x7ffd8024e439, 0x4, 0xc82008e780, 0x0, 0x0, 0x0, 0x0)
/home/cyphar/src/runc/utils_linux.go:174 +0x105
main.startContainer(0xc82007eb40, 0xc82008e780, 0x0, 0x0, 0x0)
/home/cyphar/src/runc/start.go:114 +0x189 …
```
=> libcontainer: specconv: fix nil dereference in resource setup

events.go
When the container is destroyed state, there is no process associated with that. Looks like there is no process activity associated with cgroup ( cgroup.procs is empty). Do not show the event statistics for destroyed container.
=> Not showing up the events for destroyed container

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/config.go, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/version.go, libcontainer/specconv/spec_linux.go, main.go
This will merged the version bump back into master.
=> Bump to v0.1.1 for selinux mount label fix

list.go, ps.go
For programatic parsing add a json format option to the new `runc ps`
command.
=> Add json format to ps command

events.go
This adds specific types and improves the json format for the marshaled
structure so that it is inline with the output that the spec produce,
camelCase not snake_case.
This should be the last change needed for people to really depend on the
output of this command and ensure that it does not change with any
internal changes instead of just marshaling the libcontainer structure.
=> Improve stats output format for stability 

libcontainer/standard_init_linux.go
See https://github.com/docker/docker/issues/22252
Previously we would apply seccomp rules before applying
capabilities, because it requires CAP_SYS_ADMIN. This
however means that a seccomp profile needs to allow
operations such as setcap() and setuid() which you
might reasonably want to disallow.
If prctl(PR_SET_NO_NEW_PRIVS) has been applied however
setting a seccomp filter is an unprivileged operation.
Therefore if this has been set, apply the seccomp
filter as late as possible, after capabilities have
been dropped and the uid set.
Note a small number of syscalls will take place
after the filter is applied, such as `futex`,
`stat` and `execve`, so these still need to be allowed
in addition to any the program itself needs.
=> If possible, apply seccomp rules immediately before exec

libcontainer/cgroups/utils.go
`libcontainer/cgroups/utils.go` uses an incorrect path to the
documentation for cgroups.  This updates the comment to use the correct
URL.  Fixes #794.
Signed-off-by: Jim Berlage <james.berlage@gmail.com>
=> Correct outdated URL

libcontainer/label/label_selinux_test.go, libcontainer/selinux/selinux.go
Because Docker has deprecated ':' in https://github.com/docker/docker/pull/21232
Triggered by https://github.com/docker/docker/issues/22413
=> Use '=' instead of ':' separator on labels

libcontainer/apparmor/apparmor.go
When applying profiles, when the profile is not there, currently runc throws error saying
no such file or directory.
From user perspective, little confusion to identify where the error occured from libcontainer, so updated the message accordingly
=> Updating error condition in applying apparmor profile

Makefile, script/test_Dockerfile
Enable the full test suite to run on `make test`. They also all run
inside a Docker container for maximum reproducibility.
=> Use full test suite on make test

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/system/sysconfig.go, main.go, tests/integration/cgroups.bats, tests/integration/update.bats, update.go
This PR does 2 things:
- Re-allow to update `memory.kmem.limit_in_bytes` once a container is running (provided that the value was set before the any task joined the cgroup)
- Add a new `update` command, allowing an user to update some of the cgroup constraints for a given container
=> Runc update cgroup kmem limit

libcontainer/rootfs_linux.go
Reverts opencontainers/runc#796
As per @rhatdan's comment in #796:
> @mrunalp @crosbymichael This patch should be reverted.  /dev is mounted on a tmpfs with context="system_u:object_r:svirt_sandbox_file_t:s0:c1,c2".  Having this label will cause this relabel to fail with operation not supported.
> I am not sure how to get the other error to happen with /dev not being on a tmpfs. 
> Please revert this patch, or should I open another pull to remove it.
=> Revert "Need to make sure labels applied to /dev"

libcontainer/nsenter/nsexec.c
Fix the following warnings when building runc (on my Fedora 24 box, gcc 6):
```
Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c:
In function ‘nsexec’:
Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c:322:6:
warning: ‘__s’ may be used uninitialized in this function
[-Wmaybe-uninitialized]
pr_perror("Failed to open %s", ns);
Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c:273:30:
note: ‘__s’ was declared here
static struct nsenter_config process_nl_attributes(int pipenum, char
*data, int data_size)
^~~~~~~~~~~~~~~~~~~~~
```
This is weird but according to some threads around this is the only way to fix this (man pages uses the save_ptr uninitialized also...): …
=> libcontainer: nsenter: nsexec.c: fix warnings

libcontainer/system/sysconfig.go
-- 
Following the discussion [here](https://github.com/opencontainers/runc/pull/790#discussion-diff-63080859) updated the `GetLongBit()` definition to handle platform without support for `_SC_LONG_BIT` in which case we will default to 64bits
=> Fix GetLongBit() returns value when _SC_LONG_BIT is not available

script/test_Dockerfile, tests/integration/README.md, tests/integration/cgroups.bats, tests/integration/checkpoint.bats, tests/integration/debug.bats, tests/integration/delete.bats, tests/integration/events.bats, tests/integration/exec.bats, tests/integration/help.bats, tests/integration/helpers.bash, tests/integration/kill.bats, tests/integration/list.bats, tests/integration/pause.bats, tests/integration/root.bats, tests/integration/spec.bats, tests/integration/start_detached.bats, tests/integration/start_hello.bats, tests/integration/state.bats, tests/integration/update.bats, tests/integration/version.bats
On some systems, the cgroup hierarchies are grouped together
(cpu,cpuacct). In order to avoid fake failures, update the cgroup
parsing to just check whether or not the mountinfo options *contain* the
cgroup type.
/cc @hqhq
=> integration: fix cgroup parsing

spec.go
loadSpec() is not support blank path now, remove relative comments.
=> Fix outdated comment for loadSpec

libcontainer/integration/execin_test.go, libcontainer/process.go, libcontainer/process_linux.go, restore.go, tty.go, utils_linux.go
In user namespaces, we need to make sure we don't chown() the console to
unmapped users. This means we need to get both the UID and GID of the
root user in the container when changing the owner.
This is part of the cleanup I did for rootless containers, but benefits the
project as a whole so we might as well apply it now. Obviously we still
need to fix the user namespace interaction (#814).
/cc @crosbymichael
=> *: correctly chown() consoles

tests/integration/cgroups.bats, tests/integration/helpers.bash
Since kernel 4.6, we can update kernel memory without
initialization, because it's accounted by default.
=> Fix update kernel memory test

Godeps/Godeps.json, Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp.go, Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp_internal.go, script/test_Dockerfile
This update allows more distributions to build runC with seccomp out of
the box (the include path and library paths are not always the Go
defaults).  In addition, update the test's Dockerfile to have pkg-config
installed.
=> godeps: update seccomp to 60c9953736798c4a04e90d0f3da2f933d44fd4c4

main.go
When we set a wrong --log-format value, runc exit without any
message:
#
It is again "no news is good news" rule.
And it is not unified with the case when we set a wrong --log
value:
ERRO[0000] open /: is a directory
open /: is a directory
#
This patch unified action for above two error-setting.
After patch:
unknown log-format: aaa
#
=> Unify log setting's error output

libcontainer/factory_linux.go
Signed-off-by: pankit thapar <pankit@umich.edu>
=> Allow + in container ID

.pullapprove.yml
Enforce 2 LGTMs for pull requests.
=> Add PullApprove support

.pullapprove.yml
On GitHub the maintainers of runC are *not* the same as the maintainers
of runtime-spec. Fix this, and use the right team.
Fixes #847.
=> pullapprove: use the right team

tests/integration/README.md, tests/integration/cgroups.bats, tests/integration/checkpoint.bats, tests/integration/debug.bats, tests/integration/delete.bats, tests/integration/events.bats, tests/integration/exec.bats, tests/integration/help.bats, tests/integration/helpers.bash, tests/integration/kill.bats, tests/integration/list.bats, tests/integration/pause.bats, tests/integration/root.bats, tests/integration/spec.bats, tests/integration/start_detached.bats, tests/integration/start_hello.bats, tests/integration/state.bats, tests/integration/update.bats, tests/integration/version.bats
This makes it much simpler to write tests, and you don't have to worry
about some of the oddness with bats.
This is part of the cleanup I did for rootless containers, but benefits the
project as a whole so we might as well apply it now.
=> Integration framework cleanup

README.md
=> Changing OCF to OCI in README

libcontainer/cgroups/fs/memory.go
Kernel memory cannot be set in these circumstances (before kernel 4.6):
1. kernel memory is not initialized, and there are tasks in cgroup
2. kernel memory is not initialized, and use_hierarchy is enabled,
and there are sub-cgroups
While we don't need to cover case 2 because when we set kernel
memory in runC, it's either:
- in Apply phase when we create the container, and in this case,
set kernel memory would definitely be valid;
- or in update operation, and in this case, there would be tasks
in cgroup, we only need to check if kernel memory is initialized
or not.
Even if we want to check use_hierarchy, we need to check sub-cgroups
as well, but for here, we can just leave it aside.
=> Remove use_hierarchy check when set kernel memory

libcontainer/cgroups/systemd/apply_systemd.go
Fix #801 
Delegate is only available in systemd >218, applying it for older systemd will
result in an error. Therefore we should check for it when testing systemd
properties.
=> systemd cgroup: check for Delegate property

checkpoint.go, man/runc-checkpoint.8.md, man/runc-events.8.md, man/runc-exec.8.md, man/runc-list.8.md, man/runc-ps.8.md, man/runc-restore.8.md, man/runc-spec.8.md, man/runc-start.8.md, man/runc-update.8.md, man/runc.8.md, restore.go, update.go
The major change is the description of options, change
it as the latest cli help message shows, which specify
a "value" after an option if it takes value, and add
(default: xxx) if the option has a default value.
This also includes some other minor consistency fixes.
=> Update man pages to refect the latest cli change

libcontainer/seccomp/config.go
Proably needed to complete docker/docker#22922
Signed-off-by: Michael Holzheu <holzheu@linux.vnet.ibm.com>
=> seccomp: Add ppc and s390x to seccomp/config.go

libcontainer/specconv/spec_linux.go, libcontainer/utils/utils.go, list.go, state.go
=> Add annotations to list and state output

libcontainer/setns_init_linux.go
Function SetProcessLabel is checking for nil, hence removed the redundant one from the caller.
func SetProcessLabel(processLabel string) error {
if processLabel == "" {
return nil
}
=> Removing the nil check for process label

events.go
Tick function in go returns nil when the duration is lesser than or equal to 0. When we run the events command with interval --0s, runc hangs. So added the condition to throw out the error when the duration is lesser than or equal to.
=> runc events hang for zero duration

restore.go
The same option was added for the "checkpoint" command in https://github.com/opencontainers/runc/commit/3ad3d937d280f58ead3fc7814968d86c1724d6f9
For example:
./runc restore --empty-ns network CTID
In this case criu creates a network namespace, but doesn't restore it.
We are going to use this option to restore docker containers and
Docker sets a hook to restore a network namespace.
https://github.com/xemul/criu/issues/165
Cc: @boucher 
Signed-off-by: Andrew Vagin <avagin@virtuozzo.com>
=> restore: add the empty-ns option

main_unix.go
Not having an error return is deprecated
=> Add error return to action function signature

Godeps/Godeps.json, Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp_internal.go
=> godeps: bump libseccomp-golang to 32f571b70023028bd57d9288c20efbcb237f3ce0

tests/integration/spec.bats
Use the commit that we have in Godeps.json rather than relying on
runtime-spec HEAD
=> bats: Fix spec validation test

libcontainer/cgroups/fs/apply_raw.go
The presence of the "devices" subsystem is a necessary condition for a
(privileged) container.
Signed-off-by: Christian Brauner <cbrauner@suse.com>
=> fail if path to devices subsystem is missing

libcontainer/specconv/spec_linux.go
There is no judgment whether LeafWeight is nil which can cause runc panic.
this pr fix it.
e.g.
```
root@ubuntu:~# docker run -ti --blkio-weight-device "/dev/sda:200" ubuntu
docker: Error response from daemon: rpc error: code = 2 desc = "containerd: container not started".
message form daemon:
[signal 0xb code=0x1 addr=0x0 pc=0x554179]
github.com/opencontainers/runc/libcontainer/specconv.createCgroupConfig(0x7fffe03bbd1d, 0x40, 0x0, 0xc82009ea00, 0xc8200b3870, 0x0, 0x0)
/root/workspace/gocode/src/github.com/opencontainer/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/specconv/spec_linux.go:394 +0xe99
github.com/opencontainers/runc/libcontainer/specconv.CreateLibcontainerCo …
```
=> bug fix, LeafWeight nil err

create.go, libcontainer/configs/config.go, libcontainer/setns_init_linux.go, libcontainer/specconv/spec_linux.go, libcontainer/standard_init_linux.go, run.go, utils_linux.go
This adds an `--no-new-keyring` flag to run and create so that a new
session keyring is not created for the container and the calling
processes keyring is inherited.
Fixes #818
=> Add option to disable new session keys

libcontainer/cgroups/fs/utils.go
Removed the unused variable, as we are returning nil for subsystems( freezer & devices) when there is no statistics.
=> Removing unused variable for cgroup subsystem

libcontainer/container.go, libcontainer/container_linux.go, libcontainer/factory_linux.go, libcontainer/init_linux.go, libcontainer/integration/init_test.go, libcontainer/integration/seccomp_test.go, libcontainer/integration/utils_test.go, libcontainer/process_linux.go, libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go, start.go, utils_linux.go
This removes the use of a signal handler and SIGCONT to signal the init
process to exec the users process.
Closes #871
=> Use fifo for create / start instead of signal handling 

tests/integration/helpers.bash
bats doesn't automatically print the entirety of $output when an error
has occurred in a test. This makes debugging much harder, so add to the
runc wrapper some more debug information to make maintainers' lives
easier.
=> tests: add debug information for failing tests

libcontainer/container_linux.go
Currently runc allows to update the resource constraints for all container states. With new create start changes, runc doesnt allow to start an container from stopped state. So we dont need to update the container resource constraints in stopped state.
With this PR change container can be updated in Created/Running/Paused state ( except stopped state).
=> Update for stopped container

libcontainer/factory_linux.go, libcontainer/standard_init_linux.go
=> Fix fifo usage with userns and not root users

restore.go
The returned variables name seems be able to removed.
Signed-off-by: xiekeyang <xiekeyang@huawei.com>
=> remove unused returned variables name

man/runc-ps.8.md, ps.go
Argument of "ps options" for ps command is a optional parameter.
Should use [] instead of <> in manual.
=> Fix ps argument manual

libcontainer/rootfs_linux.go
Comparisons with paths aren't really a good idea unless you're
guaranteed that the comparison will work will all paths that resolve to
the same lexical path as the compared path.
There's no point in changing directory here. Syscalls are resolved local
to the linkpath, not to the current directory that the process was in
when creating the hard link. Changing directories just confuses people
who are trying to debug things.
=> rootfs: clean up

delete.go, tests/integration/delete.bats
Reasons:
- I'm lazy and I don't want to type 2 different commands :). Typing `--force` actually make it explicit that I know what I'm doing
- When using an higher level tool to control runc, it's cheaper to do only 1 exec instead of 2 (kill + delete)
P.S: This also update the `Makefile` to tag the images generated via `make` with the current branch name instead of always overriding `latest`. I can move that commit in a separate PR if needed.
=> Add force to delete

libcontainer/container_linux.go, libcontainer/factory_linux.go
Fixes: https://github.com/opencontainers/runc/issues/871
=> Make state detection precise

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/system/sysconfig.go
This PR should also fix #841 
xref: https://github.com/kubernetes/kubernetes/issues/27204
#841 needs to be fixed to make it possible to update libcontainer version in kubernetes.
cc @cyphar @crosbymichael @dubstack
=> Use update time to detect if kmem limits have been set

list.go
To remove confusion over the wording of the list api.. This PR documents use of the global `--root value` option for specifying "the given root" where stats are stored and from which containers are listed via the `runc list` command. 
=> address issue #797 by adding additional documentation

libcontainer/configs/cgroup_unix.go
Previously we used the same JSON tag name for the regular and realtime
versions of the CpuRt* fields, which causes issues when you want to use
two different values for the fields.
Fixes #948
=> configs: fix json tags for CpuRt* options

libcontainer/cgroups/fs/net_cls.go, libcontainer/cgroups/fs/net_cls_test.go, libcontainer/configs/cgroup_unix.go, libcontainer/specconv/spec_linux.go
Setting classid of net_cls cgroup failed:
ERRO[0000] process_linux.go:291: setting cgroup config for ready process caused "failed to write 𐀁 to net_cls.classid: write /sys/fs/cgroup/net_cls,net_prio/user.slice/abc/net_cls.classid: invalid argument"
process_linux.go:291: setting cgroup config for ready process caused "failed to write 𐀁 to net_cls.classid: write /sys/fs/cgroup/net_cls,net_prio/user.slice/abc/net_cls.classid: invalid argument"
The classid is a *uint32, use strconv to convert to string.
Signed-off-by: Hushan Jia <hushan.jia@gmail.com>
=> fix setting net_cls classid

libcontainer/nsenter/README.md
the workflow of `nsexec()` described in `libcontainer/nsenter/README.md` is outdated, as mentioned in #945.
This PR aims to fix  it.
=> Fix libcontainer/nsenter/README.md

libcontainer/integration/exec_test.go
s/destory/destroy for error message output.
=> integration_testing: Fix a output typo

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/utils.go
I am working on introducing pod level cgroups in Kubernetes (kubernetes/kubernetes#27204). As a part I would like to use libcontainer for creating and managing cgroups in the system. I would like to just create a cgroup with no pid attached and if need be apply a pid to the cgroup later on. But currently libcontainer doesn't support cgroup creation without attaching a pid. 
This would allow us to skip attaching a pid to a cgroup during creation.
cc @mrunalp  @vishh @derekwaynecarr
=> Allow cgroup creation without attaching a pid

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/systemd/apply_systemd.go
In this scenario, we join the paths in Apply and don't have to do anything in Set. This was broken when Apply/Set were separated.
=> Fix cgroup Set when Paths are specified

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/system/sysconfig.go
Revert: #935
Fixes: #946
I can reproduce #946 on some machines, the problem is on
some machines, it could be very fast that modify time
of `memory.kmem.limit_in_bytes` could be the same as
before it's modified.
And now we'll call `SetKernelMemory` twice on container
creation which cause the second time fail.
Revert this before we find a better solution.
=> Revert "Use update time to detect if kmem limits have been set"

update.go
Back quotes are the placeholder feature described here:
https://github.com/urfave/cli#placeholder-values
Without this, cli will take `-1` as default value as:
```
--memory-swap -1             Total memory usage (memory + swap); set `-1` to enable unlimited swap
```
After this patch, it'll act correctly
```
--memory-swap value          Total memory usage (memory + swap); set '-1' to enable unlimited swap
```
=> Fix help message for memory-swap

libcontainer/configs/validate/validator_test.go
We should bypass userns test instead of show fail in platform without userns support.
=> UNITTEST: Bypass userns test on platform without userns support

libcontainer/keys/keyctl.go, libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go
This avoid the goimports tool from remove the libcontainer/keys import line due the package name is diferent from folder name
=> libcontainer: rename keyctl package to keys

tests/integration/spec.bats
git -C <path> reset --hard <spec commit> is not supported with older versions of git.  For tests/integration/spec.bats I changed from git -C to cd to the directory, run the git reset, then cd back where you were.  Very simple change, but it fixes problems with older versions of git.
=> Change git -C reset to git reset

libcontainer/README.md, libcontainer/cgroups/fs/devices.go, libcontainer/cgroups/fs/devices_test.go, libcontainer/configs/cgroup_unix.go, libcontainer/integration/template_test.go
temporary fix for #932
I am currently working on introducing a cgroup hierarchy in the node in Kubernetes. See (kubernetes/kubernetes#27204)
Allowing or denying all devices by writing 'a' to devices.allow or devices.deny is
not possible once the device cgroups has children. As a libcontainer user I should atleast have the option of skipping updates on devices cgroup.
cc @cyphar @vishh @derekwaynecarr @mrunalp 
Signed-off-by: Buddha Prakash <buddhap@google.com>
=> Skip updates on parent Devices cgroup

libcontainer/cgroups/systemd/apply_systemd.go
Fixes #931 
There was talk in the issue about using dbus to determine which cgroup contains systemd, but I'm not seeing how that is relevant.  Seems like we just want to always start at the cgroup root.
@derekwaynecarr @vishh @euank @mrunalp
=> fix init.scope in cgroup paths

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/system/sysconfig.go
I suggest that we modify the logic for setting the kmem.limit_on_bytes to be more deterministic and
remove the kmemInitialized check.
If kernel memory is enabled we limit the cgroup during cgroup creation ie. in apply(). This will enable kernel memory accounting on the cgroup ( http://lxr.free-electrons.com/source/Documentation/cgroups/memory.txt?v=3.9#L284 ). 
We limit the cgroup by writing some arbitrary limiting value(say 1) so that the kernel memory is accounted, and then we remove the limitation by writing -1. 
Once accounting is enabled we should be able to set the kernel memory limit to configuration value in the Set method.
The only scenario in which this would fail is if someone straight out calls Set() on a cgroup which was not created by libcontainer, in which case, if there …
=> Remove kmem Initialization check while setting memory configuration

tests/integration/cgroups.bats, tests/integration/update.bats
So we can pass the test in container os local or systemd
environment.
Also fixes: #967
=> Use absolute cgroup path for integration test

libcontainer/init_linux.go
Currently, if the `cwd` set in the config.json does not exist under `rootfs`, `runc create ...` only fails with the following error info: `no such file or directory`, which is not helpful enough to allow the user to diagnose the problem.
This PR changes the error info to be:
```
chdir to cwd ("/testdir") set in config.json failed: no such file or directory
```
Signed-off-by: Haiyan Meng <haiyanalady@gmail.com>
=> Fix the err info of chdir(cwd) failure

spec.go
/proc/timer_list seems to leak information about the host. Here is
an example from a busybox container running on docker+kubernetes.
<ffff8800b8cc3db0>, hrtimer_wakeup, S:01, futex_wait_queue_me, kubelet/2497
<ffff880129ac3db0>, hrtimer_wakeup, S:01, futex_wait_queue_me, kube-proxy/3478
<ffff8800b1b77db0>, hrtimer_wakeup, S:01, futex_wait_queue_me, kube-proxy/3470
<ffff8800bb6abdb0>, hrtimer_wakeup, S:01, futex_wait_queue_me, kubelet/2499
=> Adding /proc/timer_list to the masked paths list

libcontainer/cgroups/fs/cpu.go, libcontainer/cgroups/fs/cpu_test.go
This is a fix for issue #806, it applies the `cpu.rt_runtime_us` and `cpu.rt_period_us`
values (if not zero) before joining the cgroup.
This is required if runc itself is running in SCHED_RR mode, as it is not
possible to add a process in SCHED_RR mode to a cgroup which hasn't been
assigned any RT bandwidth. And RT bandwidth is not inherited, each new
cgroup starts with 0 bandwidth.
Signed-off-by: Ben Gray <ben.r.gray@gmail.com>
=> Set the cpu cgroup RT sched params before joining.

libcontainer/SPEC.md, libcontainer/configs/device_defaults.go
This device is not required by the OCI spec.
The rationale for this was linked to https://github.com/docker/docker/issues/2393
So a non functional /dev/fuse was created, and actual fuse use still is
required to add the device explicitly. However even old versions of the JVM
on Ubuntu 12.04 no longer require the fuse package, and this is all not
needed.
=> Do not create /dev/fuse by default

libcontainer/rootfs_linux.go
These are provided by lxcfs.
Signed-off-by: Serge Hallyn <serge@hallyn.com>
=> checkMountDesktionation: add swaps and uptime to /proc whitelist

libcontainer/nsenter/nsexec.c
Just to make the code much easier to read, also removing redundant code. I also added the functionality that `setns(2)` will fail if we passed the wrong path to the bootstrap process (to avoid bugs in runC's namespace sending being non-fatal).
In addition, I switch `pr_perror` to `bail`, where the process will exit with a **distinct** error code. Currently we aren't handling `syncT` properly within the bootstrap process. But this is a good stopgap.
There are also lots of other fixes that make the code more robust, easier to read and much nicer to maintain. Some of this code comes from the rootless containers PR #774.
`TODO`:
* :x: Refactor pipes within `nsenter` and with bootstrap process. (not relevant here, there's only one pipe for bootstrap and one for the inter-process stuff).
There …
=> nsenter: major cleanups

libcontainer/integration/exec_test.go, libcontainer/integration/utils_test.go
`newTestRoot` is an util function which is called in some files. So it seems had better to be located in `utils_test.go`.
Signed-off-by: xiekeyang <xiekeyang@huawei.com>
=> move util function

exec.go
This keeps the flag but makes it hidden so that existing clients do not
encounter an error if we were to have removed the flag.
Linked to #971
=> Disable the subreaper on exec

libcontainer/configs/config_unix_test.go
these 2 functions seems not be unused.
Signed-off-by: xiekeyang <xiekeyang@huawei.com>
=> remove unused code

libcontainer/container_linux.go
Set the start time similar to a brand new container.
=> Restored-from-checkpoint containers should have a start time

man/runc-create.8.md, man/runc-run.8.md, man/runc-start.8.md, man/runc.8.md, start.go
=> Adjust man pages for create start split

libcontainer/stacktrace/capture_test.go
TestCaptureTestFunc failed in localunittest:
=== RUN   TestCaptureTestFunc
--- FAIL: TestCaptureTestFunc (0.00s)
capture_test.go:26: expected package "github.com/opencontainers/runc/libcontainer/stacktrace" but received "_/root/runc/libcontainer/stacktrace"
#
Reason: the path for stacktrace is a fixed string which
only valid for container environment.
And we can switch to relative path to make both in-container
and out-of-container test works.
After patch:
=== RUN   TestCaptureTestFunc
--- PASS: TestCaptureTestFunc (0.00s)
#
=> Test: Make TestCaptureTestFunc pass in localunittest

utils_linux.go
The function `tty.Close()` is called whenever exit. So, it had better to use `defer`.
Signed-off-by: xiekeyang <xiekeyang@huawei.com>
=> let defer function

libcontainer/system/syscall_linux_386.go
The original SETUID takes a 16 bit UID.  Linux 2.4 introduced  a new
syscall, SETUID32, with support for 32 bit UIDs.  The setgid wrapper
already uses SETGID32.
Signed-off-by: Carl Henrik Lunde <chlunde@ifi.uio.no>
=> Support 32 bit UID on i386

libcontainer/container_linux.go, libcontainer/factory_linux.go
1. According to docs of Cmd.Path and Cmd.Args from package "os/exec":
Path is the path of the command to run. Args holds command line
arguments, including the command as Args[0]. We have mixed usage
of args. In InitPath(), InitArgs only take arguments, in InitArgs(),
InitArgs including the command as Args[0]. This is confusing.
2. InitArgs() already have the ability to configure a LinuxFactory
with the provided absolute path to the init binary and arguements as
InitPath() does.
3. exec.Command() will take care of serching executable path.
4. The default "/proc/self/exe" instead of os.Args[0] is passed to
InitArgs in order to allow relative path for the runC binary.
Signed-off-by: Yang Hongyang <imhy.yang@gmail.com>
=> Fix and refactor init args

list.go, state.go
When a container is in the stopped state it no longer has a pid so the list and state commands should return 0
=> Return 0 for pid if container is stopped

exec.go, man/runc-exec.8.md
This flag allows using parameters starting with a - such as:
ps --args -afx
=> Add "--" exec cli support for command arguments

man/runc-ps.8.md, ps.go
Currently, ps command can not support argument:
(But following usage is in manual)
| # ./runc ps 123 -ef
| Incorrect Usage.
|
| NAME:
|    runc ps - ps displays the processes running inside a container
|
| USAGE:
|    runc ps [command options] <container-id> [ps options]
|
| OPTIONS:
|    --format value, -f value  select one of: table or json
|
| flag provided but not defined: -ef
| #
Instead of using odd command like:
| # ./runc ps -- 123 -ef
We can make it seems little better:
| # ./runc ps 123 -- -ef
| UID        PID  PPID  C STIME TTY          TIME CMD
| root     29046 29038  0 11:18 pts/2    00:00:00 sh
| #
This patch also fixed manual which can not working in current
code.
Closes #788
=> cli: Workaround for ps's argument

exec.go
Do not allow to exec an container from stopped state, which is similar to start.
=> Not exec a container from stopped state

libcontainer/factory_linux.go
When the container not exists, user gets the error saying
open /run/runc/container1/state.json: no such file or directory
From end user perspective, if we do any operation on container we can show whether the container ID is valid one, instead of giving the state.json error.
Hence the change in this PR , upon executing runc on invalid ID, it will show as below.
"container not exist"
=> Error handling when container not exists

libcontainer/specconv/spec_linux.go, libcontainer/specconv/spec_linux_test.go
Alternative of #895 , part of #892
The intension of current behavior if to create cgroup in
parent cgroup of current process, but we did this in a
wrong way, we used devices cgroup path of current process
as the default parent path for all subsystems, this is
wrong because we don't always have the same cgroup path
for all subsystems.
For example, the cgroup path of current process is:
```
qhuang@ubuntu-25:~/tools/runc$ cat /proc/self/cgroup
11:hugetlb:/user/1000.user/64.session
10:perf_event:/user/1000.user/64.session
9:blkio:/user/1000.user/64.session
8:freezer:/user/1000.user/64.session
7:devices:/user/1000.user/64.session
6:memory:/user
5:name=systemd:/user/1000.user/64.session
4:cpuacct:/user/1000.user/64.session …
```
=> Fix default cgroup path

Makefile
Change dependency of integration to runcimage.
=> Makefile: Fix wrong dependency of "integration" target

libcontainer/specconv/spec_linux.go
`clear bool` element is unnecessary for `struct propagationFlags`, remove it for simplifying codes.
=> Tiny refactor: remove unused local variables

Makefile
If runc binary is compiled from codes with modified but not commited
files, git commits should report "COMMIT-dirty" instead of single
"COMMIT" to warn users.
=> Append string "-dirty" to version if git repo is unclean

libcontainer/nsenter/nsexec.c
=> remove redundant by in annotation(nsexec.c)

.gitignore, Makefile
So we can make all types of release binary with combination
of following flags:
seccomp
selinux
apparmor
static
All binary files are put in release/ dir, like:
[root@zlosvm1 runc]# ls -l release
total 53488
-rwxr-xr-x. 1 root root 9517965 Jun 14 18:11 runc
-rwxr-xr-x. 1 root root 9673533 Jun 14 18:10 runc.seccomp
-rwxr-xr-x. 1 root root 9705839 Jun 14 18:09 runc.seccomp.selinux
-rwxr-xr-x. 1 root root 9546175 Jun 14 18:10 runc.selinux
-rwxr-xr-x. 1 root root 8169190 Jun 14 18:10 runc.selinux.static
-rwxr-xr-x. 1 root root 8150060 Jun 14 18:11 runc.static
...
Closes #899
=> Introduce make release

libcontainer/configs/cgroup_unix.go
Fixes #999
This allows older state files to be loaded without the unmarshal error
of the string to int conversion.
=> Change netclassid json tag

libcontainer/cgroups/fs/apply_raw.go
After #1009, we don't always set `cgroup.Paths`, so
`getCgroupPath()` will return wrong cgroup path because
it'll take current process's cgroup as the parent, which
would be wrong when we try to find the cgroup path in
`runc ps`.
Fix it by using `m.GetPath()` to get the true cgroup
paths.
Also Fixes: #1034
Fixes: #1031 
Reported-by: Yang Shukui <yangshukui@huawei.com>
=> Fix runc ps issue

Makefile
currently make release may have a error in some distribution(e.g. Ubuntu 14.04.3)
/bin/sh: 1: Syntax error: "(" unexpected
make: *** [release] Error 2
this pr will fix this.
=> Fix make release error

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/config.go, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/state.go, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/version.go, libcontainer/specconv/spec_linux.go, libcontainer/specconv/spec_linux_test.go, spec.go, tests/integration/spec.bats
runc currently fails to build against the upstream version of runtime-spec/specs-go:
```
./spec.go:189: cannot use specs.Linux literal (type specs.Linux) as type *specs.Linux in field value
```
on account of https://github.com/opencontainers/runtime-spec/commit/63231576ec8460849308b78f0308506010a0f709#diff-7f24d60f0cbb9c433e165467e3d34838R25
This PR updates the dependency to current runtime-spec master, fixes the type mismatch, adds nil pointer checks, and updates spec config paths.
Fixes #1035
Signed-off-by: Adam Thomason <ad@mthomason.net>
=> Update runtime-spec to current upstream

Makefile
So we don't get `mount: permission denied` when make dbuild.
=> Add privileged to make dbuild

libcontainer/cgroups/fs/apply_raw.go
only call m.GetPaths once is ok. os move it out of the loop.
=> move m.GetPaths out of the loop

list.go
This will print out the error on stderr when loading a container but
still list everything that was sucessful.
=> Continue for list on errors

libcontainer/generic_error.go, libcontainer/process_linux.go
Error sent from child process is already genericError, if
we don't allow recrusive generic error, we won't get any
cause infomation from parent process.
Before, we got:
WARN[0000] exit status 1
ERRO[0000] operation not permitted
After, we got:
WARN[0000] exit status 1
ERRO[0000] container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"operation not permitted\""
it's not pretty but useful for detecting root causes.
=> Allow recrusive generic error

libcontainer/label/label_selinux.go
Currently if a user does a command like
docker: Error response from daemon: operation not supported.
With this fix they should see a much more informative error message.
docker run -ti -v /proc:/proc:Z fedora sh
docker: Error response from daemon: SELinux Relabeling of /proc is not allowed: operation not supported.
=> Fix error messages to give information of relabeling failed

libcontainer/cgroups/utils.go, libcontainer/cgroups/utils_test.go, libcontainer/rootfs_linux.go
This requirement comes from cadvisor so it can pick the right mounts that it needs when run in a container. It shouldn't affect internal libcontainer/runc code.
=> Add flag to allow getting all mounts for cgroups subsystems

libcontainer/container_linux.go
if a container state is `running` or `created`, the `container.Pause()`
method can set the state to pausing, and then paused.
this patch update the comment, so it can be consistent with the code.
=> update the comment for container.Pause() method on linux

libcontainer/cgroups/fs/cpu.go
cgroupData.join method using `WriteCgroupProc` to place the pid into
the proc file, it can avoid attach any pid to the cgroup if -1 is
specified as a pid.
so, replace `writeFile` with `WriteCgroupProc` like `cpuset.go`'s
ApplyDir method.
=> cgroup: using WriteCgroupProc to write the specified pid into the cgroup's cgroup.procs file

Makefile
If we modify the code of runc without a new branch of runc, the runc will be compiled with the code in the old runc-dev:** image. This pr will make the compiling use right code like make unittest and make integration.
=> Bug fix for make dbuild

libcontainer/README.md, libcontainer/integration/template_test.go, libcontainer/rootfs_linux.go, libcontainer/standard_init_linux.go, spec.go, tests/integration/mask.bats
For example, the /sys/firmware directory should be masked because it can contain some sensitive files (https://github.com/docker/docker/pull/26618):
- /sys/firmware/acpi/tables/{SLIC,MSDM}: Windows license information:
- /sys/firmware/ibft/target0/chap-secret: iSCSI CHAP secret
IMO the issue should be fixed but no need to get this PR in v1.0
~~~runtime-spec PR: https://github.com/opencontainers/runtime-spec/pull/582~~~
=> MaskPaths: support directory

checkpoint.go
Currently when we checkpoint an container in created state ( not an ideal case) the created container also got destroyed.
Since the container fails to checkpoint because of created state, it must not delete the created container without user awareness.
With this PR, container can not checkpoint in created state.
=> Container must not checkpoint in created state

tests/integration/delete.bats
this patch add two testcases for the `runc delete` with
multi-containers. see : https://github.com/opencontainers/runc/pull/1053
=> [integration] add testcases for `runc delete` command

exec.go, ps.go, tests/integration/exec.bats, tests/integration/ps.bats
https://github.com/opencontainers/runc/pull/1051 has been merged to fix ps/exec parameter error, so we can remove the redundant workaround for runc ps.
=> Remove the workaround which add a -- flag to runc ps command

libcontainer/factory_linux.go, update.go
grep -r "range map" shows 3 parts use map to
range enum types, use slice instead can get
better performance and less memory usage.
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>
=> Refactor enum map range to slice range

Godeps/Godeps.json, Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability.go, Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability_linux.go, Godeps/_workspace/src/github.com/syndtr/gocapability/capability/enum.go, Godeps/_workspace/src/github.com/syndtr/gocapability/capability/syscall_linux.go, libcontainer/capabilities_linux.go
Since Linux 4.3 ambient capabilities are available. If set these allow unprivileged child
processes to inherit capabilities, while at present there is no means to set capabilities
on non root processes, other than via filesystem capabilities which are not usually
supported in image formats.
With ambient capabilities non root processes can be given capabilities as well, and so
the main reason to use root in containers goes away, and capabilities work as expected.
The code falls back to the existing behaviour if ambient capabilities are not supported.
=> Set ambient capabilities where supported

libcontainer/factory_linux.go
Just a small typo/grammatical error I noticed when I accidentally tried to start a container I hadn't created.
=> Fix typo when container does not exist

libcontainer/rootfs_linux.go, libcontainer/rootfs_linux_test.go
In order to mount root filesystems inside the container's mount
namespace as part of the spec we need to have the ability to do a bind
mount to / as the destination.
I cannot remember why this is here specifically, I know the reasons for `/proc` and other paths and didn't know if we just added `/` just to be safe or if we had a specific reason. 
=> Remove check for binding to /

main.go
`urfave/cli` now takes upon itself to log the error returned by the
command action directly. This means that by default the `--log` option
was ignored upon error.
This commit ensure that `urfave/cli.ErrWriter` will use logrus
=> Ensure we log into logrus on command error

libcontainer/cgroups/systemd/apply_systemd.go
This patch adds support for the systemd cgroup driver to manage slices.
The ability to manage slices via the dbus api was not available until systemd v229, but some distros have back-ported it to earlier levels.  The driver verifies the ability to start a slice via a transient unit is supported prior to using the feature.
If the supplied cgroup name ends with a .slice suffix, we assume the user wanted a slice created instead of a scope.  Creation of a slice does not require a PID, so support from the cgroupfs driver for pid=-1 is carried over into systemd driver.
Finally, `ExpandSlice` is made public for use by downstream consumers.  In addition, it fixes a logic error associated with `-.slice` needing to be `/` when expanded.
Signed-off-by: derekwaynecarr <decarr@redhat.com>
=> systemd cgroup driver supports slice management

libcontainer/cgroups/fs/memory.go
Don't enable the kmem limit if it is not specified in the config.
Fixes #1083
=> Don't enable kernel mem if not set

ps.go
the `-p pidlist` flag of `ps` command selects the process whose process
ID numbers apper in `pidlist`([man ps])
This patch use `-p pidlist` to filter process which we want.
[man ps]: http://man7.org/linux/man-pages/man1/ps.1.html
=> simplify ps command

libcontainer/label/label_selinux.go, libcontainer/label/label_selinux_test.go
At some point InitLabels was changed to look for SecuritOptions
separated by a ":" rather then an "=", but DupSecOpt was never
changed to match this default.
=> DupSecOpt needs to match InitLabels

spec.go
run an arm64 image on an amd64 platform, it will failed with
````
panic: standard_init_linux.go:175: exec user process caused "exec format error" [recovered]
panic: standard_init_linux.go:175: exec user process caused "exec format error"
goroutine 1 [running, locked to thread]:
panic(0x7e7e40, 0xc820124380)
/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200c52f8)
/home/lei/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7e7e40, 0xc820124380)
/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200c4c08, 0xc8200220a0, 0xc8200c4d18)
/home/lei/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontaine …
```
=> Valide platform on loading config.json

libcontainer/specconv/spec_linux.go
When hugetlb ( either pageSize or limit) configs were missing, runc panics. Added nil check to fix.
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal 0xb code=0x1 addr=0x0 pc=0x56b09c]
panic(0x7ca4e0, 0xc8200100e0)
/home/raj/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200a72f8)
/home/raj/go/pkg/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7ca4e0, 0xc8200100e0)
/home/raj/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer/specconv.createCgroupConfig(0x7ffea64bc585, 0x2, 0x0, 0xc8200c8000, 0xc8200c4860, 0x0, 0x0) …
=> Fixing runc panic during hugetlb pages

man/runc-pause.8.md, man/runc-resume.8.md, pause.go, tests/integration/pause.bats
With this patch, `runc pasue` and `runc resume` can
pause and resume multi-containers.
=> pause and resume multi-containers

man/runc-start.8.md, start.go, tests/integration/start.bats
With this patch, `runc start` command can start multi-containers
at one command,  this patch also checks the argument of the `start`
command.
```
root@ubuntu:# runc list
ID          PID         STATUS      BUNDLE         CREATED
a           0           stopped     /mycontainer   2016-09-23T08:56:42.754026567Z
b           62979       created     /mycontainer   2016-09-23T09:01:36.421976458Z
c           62993       running     /mycontainer   2016-09-23T09:01:38.105940389Z
d           63006       created     /mycontainer   2016-09-23T09:01:39.65441942Z
e           63020       created     /mycontainer   2016-09-23T09:01:40.989995515Z
root@ubuntu:# runc start
runc: "start" requires a minimum of 1 argument
root@ubuntu:# runc start a b c d e f
cannot start a container that has run and stopped …
```
=> start multi-containers with `runc start` command

libcontainer/label/label.go, libcontainer/label/label_selinux.go, libcontainer/label/label_selinux_test.go, libcontainer/selinux/selinux.go
We need support for read/only mounts in SELinux to allow a bunch of
containers to share the same read/only image.  In order to do this
we need a new label which allows container processes to read/execute
all files but not write them.
Existing mount label is either shared write or private write.  This
label is shared read/execute.
=> Add support for r/o mount labels

libcontainer/specconv/spec_linux.go
If the file mode is missing in devices configuration ( config.json), runc panics.
panic(0x7ca4e0, 0xc8200100d0)
/home/raj/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200bf2f8)
/home/raj/go/pkg/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7ca4e0, 0xc8200100d0)
/home/raj/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer/specconv.createDevices(0xc820112000, 0xc82010c200, 0x0, 0x0)
/home/raj/go/pkg/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/specconv/spec_linux.go:552 +0x59b
github.com/opencontainers/runc/libcontainer/specconv.CreateLibcontainerConfig(0xc8200beb88, 0x855bc0, 0x0, 0x0) …
=> Fixing runc panic for missing file mode

kill.go
Before this pr 
```
root@ubuntu:~/workspace/runc-test# ./runc kill test 35
container_linux.go:290: signaling init process caused "invalid argument"
```
After this pr 
```
root@ubuntu:~/workspace/runc-test# ./runc kill test 35
unknown signal "35"
```
=> Add num check for kill command

delete.go, man/runc-delete.8.md
This patch also update the description in `delete.go` in order to
keep consistent with the manual.
=> update the man for runc delete command

checkpoint.go
Fixes: a60040c62d03 ("Container must not checkpoint in created state")
Fixes: #1076
=> checkpoint: fix gofmt

ps.go
./runc ps ps -b
exit status 1
From end user, it is slightly not possible to understand what is the real error of the command.
With this PR, it will show detailed errors instead of exit status
For example:
./runc ps ps -z
exit status 1: error: unsupported SysV option
Usage:
ps [options]
Try 'ps --help <simple|list|output|threads|misc|all>'
or 'ps --help <s|l|o|t|m|a>'
for additional help text.
For more details see ps(1).
exit status 1
=> ps error logging improvement

tests/integration/mask.bats
In certain circumstances (such as the rootless containers patchset), it
is not possible to test things using /sys/firmware. In addition, we
should be testing our own functionality rather than testing protection
against /sys attacks (for which the system might already have extra
protections).
Instead, just make some fake paths in the rootfs that we then mask.
Oddly I noticed that one of the errors changed when doing this (because
before we tested removing a file from /sys/firmware which is -EPERM). So
the old test was broken.
Fixes: 53179559a15f5 ("MaskPaths: support directory")
Fixes: #1068
=> tests: mask: use test paths rather than /sys

libcontainer/cgroups/systemd/apply_systemd.go
If a unit already exists with the specified name, ignore the error.
This allows the call to be idempotent when doing slice management on systemd 231+.
=> Ignore error when starting transient unit that already exists

Godeps/Godeps.json, Godeps/_workspace/src/github.com/mrunalp/fileutils/LICENSE, Godeps/_workspace/src/github.com/mrunalp/fileutils/README.md, Godeps/_workspace/src/github.com/mrunalp/fileutils/fileutils.go, Godeps/_workspace/src/github.com/mrunalp/fileutils/idtools.go, libcontainer/configs/mount.go, libcontainer/integration/exec_test.go, libcontainer/rootfs_linux.go, libcontainer/specconv/spec_linux.go
This replaces #707 by simply copying over a directory instead of using tar.
=> Add support for copying up directories into tmpfs when a tmpfs is mounted over them

tests/integration/create.bats
This patch add test `--pid-file` option for create command.
=> add test cases for create command

libcontainer/configs/config.go, libcontainer/rootfs_linux.go
Namely, use an undocumented feature of pivot_root(2) where
pivot_root(".", ".") is actually a feature and allows you to make the
old_root be tied to your /proc/self/cwd in a way that makes unmounting
easy. Thanks a lot to the LXC developers which came up with this idea
first.
This is the first step of many to allowing runC to work with a
completely read-only rootfs.
Fixes #1122.
=> rootfs: make pivot_root not use a temporary directory

libcontainer/configs/validate/validator.go, libcontainer/configs/validate/validator_test.go
ref docker/docker#27484
> There are two checks we can make for seeing if the user specified the host namespace.
>
> 1. The Namespaces list does not have the NEWNET struct added to it
> 2. If it does have a NEWNET struct added and the path is not an empty string then we need to
>   1. Do a readlink on the current processes network namespace os.Readlink("/proc/self/ns/net") 
>   2. Do a readlink on the Path provided in the struct and compare the current processes network namespace with the one provided in the Path. If they match then it should be considered as the host namespace.
Signed-off-by: Ce Gao <ce.gao@outlook.com>
=> docker/docker#27484-check if sysctls are used in host network mode.

create.go
This patch checks the arguments for command  `runc create`.
the `create` command requires exactly one argument
eg:
```
root@ubuntu:~# runc create -b /mycontainer/ a
root@ubuntu:~# runc list
ID          PID         STATUS      BUNDLE         CREATED
a           61637       created     /mycontainer   2016-10-20T08:21:20.169810942Z
root@ubuntu:~# runc create -b /mycontainer/ a b
runc: "create" requires exactly one argument
root@ubuntu:~# runc create -b /mycontainer/
runc: "create" requires exactly one argument
```
=> check the arguments for `runc create`

libcontainer/configs/namespaces_unix.go, libcontainer/container_linux.go, libcontainer/nsenter/namespace.h, libcontainer/nsenter/nsenter_test.go, libcontainer/nsenter/nsexec.c
Depending on your SELinux setup, the order in which you join namespaces
can be important. In general, user namespaces should *always* be joined
and unshared first because then the other namespaces are correctly
pinned and you have the right priviliges within them. This also is very
useful for rootless containers, as well as older kernels that had
essentially broken unshare(2) and clone(2) implementations.
This also includes huge refactorings in how we spawn processes for
complicated reasons that I don't want to get into because it will make
me spiral into a cloud of rage. The reasoning is in the giant comment in
clone_parent. Have fun.
In addition, because we now create multiple children with CLONE_PARENT,
we cannot wait for them to SIGCHLD us in the case of a death. Thus, we
have to …
=> nsenter: guarantee correct user namespace ordering

Dockerfile, tests/integration/create.bats, tests/integration/exec.bats, tests/integration/start_detached.bats
At https://github.com/opencontainers/runc/pull/1132#pullrequestreview-5017081, It is necessary to make sure that pid-file contains the right information.
This patch employ `jq` and `runc state` command to achieve it.
Signed-off-by: Wang Long long.wanglong@huawei.com
=> Check pid file

libcontainer/configs/validate/validator.go, libcontainer/configs/validate/validator_test.go
When changing this validation, the code actually allowing the validation
to pass was removed. This meant that any net.* sysctl would always fail
to validate.
Fixes: bc84f83344fd ("fix docker/docker#27484")
Reported-by: Justin Cormack <justin.cormack@docker.com>
Fixes #1138
/cc @justincormack Does this fix the issue you mentioned?
=> validator: unbreak sysctl net.* validation

libcontainer/rootfs_linux.go
This reverts part of the commit eb0a144b5e383
That commit introduced two issues.
- We need to make parent mount of rootfs private before bind mounting
rootfs. Otherwise bind mounting root can propagate in other mount
namespaces. (If parent mount is shared).
- It broke test TestRootfsPropagationSharedMount() on Fedora.
On fedora /tmp is a mount point with "shared" propagation. I think
you should be able to reproduce it on other distributions as well
as long as you mount tmpfs on /tmp and make it "shared" propagation.
Reason for failure is that pivot_root() fails. And it fails because
kernel does following check.
IS_MNT_SHARED(new_mnt->mnt_parent)
Say /tmp/foo is new rootfs, we have bind mounted rootfs, so new_mnt
is /tmp/foo, and new_mnt->mnt_parent is /tmp which is "shared" on
fedora and …
=> Make parent mount private before bind mounting rootfs

libcontainer/specconv/spec_linux.go, libcontainer/specconv/spec_linux_test.go
When spec file contains duplicated namespaces, e.g.
```
specs: specs.Spec{
Linux: &specs.Linux{
Namespaces: []specs.Namespace{
{
Type: "pid",
},
{
Type: "pid",
Path: "/proc/1/ns/pid",
},
},
},
}
```
runc should report malformed spec instead of using latest one by
default, because this spec could be quite confusing.
=> Detect and forbid duplicated namespace in spec

libcontainer/nsenter/nsexec.c
config.cloneflag is not mandatory, when using `runc exec`,
config.cloneflag can be empty, and even then it won't be
`-1` but `0`.
So this validation is totally wrong and unneeded.
=> Remove unnecessary cloneflag validation

README.md
Just fix a nit in installation guide.
The current doc put `libseccomp` instructions after installation scripts, this is easy to be ignored and leads to issues like #1032
Signed-off-by: Harry Zhang <harryz@hyper.sh>
=> Clarify libseccomp installation in guide

libcontainer/console_freebsd.go, libcontainer/console_linux.go, libcontainer/console_solaris.go, libcontainer/console_windows.go, libcontainer/container.go, libcontainer/integration/exec_test.go, libcontainer/rootfs_linux.go, tests/integration/start.bats
I use the same tool (https://github.com/client9/misspell)
as Daniel used a few days ago, don't why he missed these
typos at that time.
Signed-off-by: Qiang Huang h.huangqiang@huawei.com
=> Fix all typos found by misspell

libcontainer/nsenter/nsexec.c
This fixes up some incorrect comments.
=> nsenter: fix up comments

libcontainer/factory_linux.go
Print the error message to stderr if we are unable to return it back via
the pipe to the parent process.  Also, don't panic here as it is most
likely a system or user error and not a programmer error.
Fixes #1103
Signed-off-by: Michael Crosby crosbymichael@gmail.com
=> Remove panic from init

Makefile, README.md, libcontainer/capabilities_ambient.go, libcontainer/capabilities_linux.go, libcontainer/capabilities_noambient.go
This moves the ambient capability support behind an `ambient` build tag
so that it is only compiled upon request.
ping @justincormack 
=> Move ambient capabilties behind build tag

libcontainer/console_linux.go, libcontainer/integration/execin_test.go
The default terminal setting for a new pty on Linux (unix98) has +ONLCR,
resulting in '\n' writes by a container process to be converted to
'\r\n' reads by the managing process. This is quite unexpected, and
causes multiple issues with things like bats testing. To fix it, make
the terminal sane after opening it by setting -ONLCR.
This patch might need to be rewritten after the console rewrite patchset
is merged.
Fixes #1145.
Signed-off-by: Aleksa Sarai asarai@suse.de
=> libcontainer: io: stop screwing with \n in console output

tests/integration/exec.bats
This patch add test `--cwd`, `--env`, `--user` option for exec command.
Signed-off-by: Wang Long long.wanglong@huawei.com
=> add test cases for exec command

man/runc-update.8.md, tests/integration/update.bats, update.go
Currently runc already supports setting realtime runtime and period
before container processes start, this commit will add update support
for realtime scheduler resources.
PS: I searched github issues and PRs and didn't find why `runc` didn't support updating real time scheduler resources, as I can see, setting the rt_period_us and rt_runtime_us when container is booting already works, so `updating` should be a reasonable enhancement.
Let me know if I miss something. :smile:
=> Allow update rt_period_us and rt_runtime_us

contrib/completions/bash/runc
Add bash completions for flags "--cpu-rt-period" and "--cpu-rt-runtime"
for `update` command.
This is follow up of https://github.com/opencontainers/runc/pull/1173, sorry for forgetting the bash completions, now it's here.
=> Add bash completions for new flags of `update`

libcontainer/nsenter/nsexec.c
=> More fix to nsexec.c's comments

contrib/completions/bash/runc, delete.go, kill.go, libcontainer/container.go, libcontainer/container_linux.go, libcontainer/init_linux.go, libcontainer/process_linux.go, libcontainer/state_linux.go, man/runc-kill.8.md
This allows a user to send a signal to all the processes in the
container within a single atomic action to avoid new processes being
forked off before the signal can be sent.
This is basically taking functionality that we already use being
`delete` and exposing it ok the `kill` command by adding a flag.
=> Add --all flag to kill

create.go, exec.go, run.go, tests/integration/create.bats, tests/integration/exec.bats, tests/integration/start_detached.bats, utils.go
When we use `--pid-file` option of the `runc exec`  command with an relative path. it will generate file in the bundle's directory.
This patch fix that. `runc exec --pid-file pid.txt` will generate file relative to the directory which we type the `runc exec` command.
Signed-off-by: Wang Long long.wanglong@huawei.com
=> fix the pid-file option for runc exec/run/create command

libcontainer/nsenter/nsexec.c
Small update to error message when open calls fails on path
=> Fixing error message in nsexec

libcontainer/cgroups/fs/cpuset.go
This PR fix issue in this scenario:
```
in terminal 1:
~# cd /sys/fs/cgroup/cpuset
~# mkdir test
~# cd test
~# cat cpuset.cpus
0-3
~# echo 1 > cpuset.cpu_exclusive (make sure you don't have other cgroups under root)
in terminal 2:
~# echo $$ > /sys/fs/cgroup/cpuset/test/tasks
// set resources.cpu.cpus="0-2" in config.json
~# runc run test1
back to terminal 1:
~# cd test1
~# cat cpuset.cpus
0-2
~# echo 1 > cpuset.cpu_exclusive
in terminal 3:
~# echo $$ > /sys/fs/cgroup/test/tasks
// set resources.cpu.cpus="3" in config.json
~# runc run test2
container_linux.go:247: starting container process caused "process_linux.go:258:
applying cgroup configuration for process caused \"failed to write 0-3\\n to
cpuset.cpus: write /sys/fs/cgroup/cpuset/test2/cpuset.cpus: invalid argument\""
``` …
=> Fix cpuset issue with cpuset.cpu_exclusive

libcontainer/selinux/selinux.go
Both suffered from different race conditions.
SelinuxEnabled assigned selinuxEnabledChecked before selinuxEnabled.
Thus racing callers could see the wrong selinuxEnabled.
getSelinuxMountPoint assigned selinuxfs to "" before it know the right
value. Thus racing could see "" improperly.
The gate selinuxfs, enabled, and mclist all on the same lock
=> Fix thread safety of SelinuxEnabled and getSelinuxMountPoint

libcontainer/configs/validate/validator.go
When checking if the provided networking namespace is the host
one or not, we should first check if it's a symbolic link or not
as in some cases we can use persistent networking namespace under
e.g. /var/run/netns/.
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> validate: Check that the given namespace path is a symlink

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/config.go, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/state.go, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/version.go, checkpoint.go, libcontainer/specconv/spec_linux.go, libcontainer/specconv/spec_linux_test.go, spec.go, update.go
* Bump underlying runtime-spec to version 1.0.0-rc3
* Fix related changed struct names in config.go
=> Bump runtime-spec to v1.0.0-rc3

libcontainer/configs/config.go, libcontainer/configs/config_test.go, libcontainer/container_linux.go, libcontainer/integration/exec_test.go, libcontainer/integration/utils_test.go, libcontainer/process_linux.go, libcontainer/state_linux.go
<del>* modify json name of `ociVersion` to `version`
<del>* Add missing `Status` and `Annotations` field
Edit:
`HookState` struct should follow definition of `State` in runtime-spec:
* Remove redundant `Rootfs` field as rootfs can be retrived from
`bundlePath/config.json`
=> Sync HookState struct with OCI spec

libcontainer/devices/devices_unix.go
Fix a race where a device is first seen while walking /dev but has disappeared by the time we stat it. This is seen in environments where lots of privileged containers are launched/deleted rapidly with devicemapper as storage driver as lots of device mapper devices are created/deleted.
=> Don't add device to list if it doesn't exist anymore

checkpoint.go, create.go, delete.go, events.go, exec.go, kill.go, list.go, pause.go, ps.go, restore.go, run.go, spec.go, start.go, state.go, update.go, utils.go
Add a general args number validator for all client commands.
Signed-off-by: Zhang Wei zhangwei555@huawei.com
=> Check args numbers before application start

libcontainer/rootfs_linux.go, libcontainer/standard_init_linux.go
fix #1223 
A remount of a mount point must include all the current flags or
these will be cleared:
```
The mountflags and data arguments should match the values used in the
original mount() call, except for those parameters that are being
deliberately changed.
```
The current code does not do this; the bug manifests in the specified
flags for `/dev` being lost on remount read only at present. As we
need to specify flags, split the code path for this from remounting
paths which are not mount points, as these can only inherit the
existing flags of the path, and these cannot be changed.
In the bind case, remove extra flags from the bind remount. A bind
mount can only be remounted read only, no other flags can be set,
all other flags are inherited from the parent. From the man page:
```
Since …
```
=> Split the code for remounting mount points and mounting paths.

tests/integration/cgroups.bats, tests/integration/helpers.bash, tests/integration/update.bats
Add missing integration test for https://github.com/opencontainers/runc/pull/1173 with "requires" support, because our test machine doesn't have a kernel supporting RT Cgroup yet.
/cc @cyphar
=> Add integration for update rt period and runtime

.travis.yml
This sets up a working Travis CI configuration, that runs all of our
integration and unit tests (and also checks a simple raw-build on the
Travis server).
Closes #1241 (this is a carry).
=> travis: add travis-ci

libcontainer/integration/exec_test.go, libcontainer/integration/execin_test.go
Previously, we would get failures with go-vet with test files.
```
% go vet ./...
libcontainer/integration/exec_test.go:42: github.com/opencontainers/runc/libcontainer/configs.IDMap composite literal uses unkeyed fields
libcontainer/integration/exec_test.go:43: github.com/opencontainers/runc/libcontainer/configs.IDMap composite literal uses unkeyed fields
libcontainer/integration/exec_test.go:184: github.com/opencontainers/runc/libcontainer/configs.IDMap composite literal uses unkeyed fields
libcontainer/integration/exec_test.go:185: github.com/opencontainers/runc/libcontainer/configs.IDMap composite literal uses unkeyed fields
libcontainer/integration/exec_test.go:1568: github.com/opencontainers/runc/libcontainer/configs.IDMap composite literal uses unkeyed fields …
```
=> *: fix go-vet failures

libcontainer/cgroups/fs/apply_raw.go
In the cases that we got failure on a subsystem's Apply,
we'll get some subsystems' cgroup directories leftover.
On Docker's point of view, start a container failed, use
`docker rm` to remove the container, but some cgroup files
are leftover.
Sometimes we don't want to clean everyting up when something
went wrong, because we need these inter situation
information to debug what's going on, but cgroup directories
are not useful information we want to keep.
=> Fix leftover cgroup directory issue

Makefile
I think generated manpages should also need cleanup
=> Makefile: add manpage cleanup

libcontainer/configs/namespaces_syscall_unsupported.go
runc/libcontainer/configs/namespaces_syscall_unsupported.go
Line 7: error: unreachable code (vet)
Line 14: error: unreachable code (vet)
=> Fix go_vet errors

Makefile
Signed-off-by: Fengtu Wang <wangfengtu@huawei.com>
=> remove `-i` option to avoid failure of jenkins in non-interactive mode.

libcontainer/container_linux.go
In user namespaces devices are bind-mounted from the host, so
we need to add them as external mounts for CRIU.
Reported-by: @boucher
=> checkpoint: handle config.Devices and config.MaskPaths

exec.go
Fixes #1264
Set minimal required args to 1 for `exec` command to roll back to
previous behavior, also modify help message a little bit.
=> Fix regression of exec command

libcontainer/user/user.go
Signed-off-by: Lei Jitang <leijitang@huawei.com>
Has `if groupArg != ""` before enter the `if ... else if groupArg != ""`, check `if groupArg != ""` is redundant here.
=> Cleanup: remove redundant code

libcontainer/rootfs_linux.go
On some systems, when we mount some cgroup subsystems into
a same mountpoint, the name sequence of mount options and
cgroup directory name can not be the same.
For example, the mount option is cpuacct,cpu, but
mountpoint name is /sys/fs/cgroup/cpu,cpuacct. In current
runc, we set mount destination name from combining
subsystems, which comes from mount option from
/proc/self/mountinfo, so in my case the name would be
/sys/fs/cgroup/cpuacct,cpu, which is differernt from
host, and will break some applications.
Fix it by using directory name from host mountpoint.
=> Do not create cgroup dir name from combining subsystems

libcontainer/cgroups/utils.go
=> small refactor

kill.go
commit b517076907b7c1 added a check that kill accepts two arguments.
Since the second argument is optional, change it back to accept the
shorter form "kill CONTAINER".
=> kill: make second argument optional

libcontainer/cgroups/utils.go, libcontainer/cgroups/utils_test.go
Our current cgroup parsing logic assumes cgroup v1 mounts
so we should ignore cgroup2 mounts for now
Closes #1209 
=> Ignore cgroup2 mountpoints

libcontainer/cgroups/utils.go, libcontainer/seccomp/seccomp_linux.go
The `bufio.Scanner.Scan` method returns false either by reaching the
end of the input or an error. After Scan returns false, the Err method
will return any error that occurred during scanning, except that if it
was io.EOF, Err will return nil.
We should check the error when Scan return false(out of the for loop).
refer: [https://golang.org/pkg/bufio/#Scanner.Scan](https://golang.org/pkg/bufio/#Scanner.Scan)
=> move error check out of the for loop

libcontainer/selinux/selinux.go
using golang-style assignment, not the c-style
Signed-off-by: Wang Anyu <wanganyu@outlook.com>
=> using golang-style assignment

libcontainer/utils/cmsg.c
POSIX mandates that `cmsg_len` in `struct cmsghdr` is a `socklen_t`,
which is an `unsigned int`. Musl libc as used in Alpine implements
this; Glibc ignores the spec and makes it a `size_t` ie `unsigned long`.
To avoid the `-Wformat=` warning from the `%lu` on Alpine, cast this
to an `unsigned long` always.
=> Remove a compiler warning in some environments

libcontainer/README.md
Add the import of nsenter to the example in libcontainer's README.md, as without it none of the example code works.
Signed-off-by: Steven Hartland <steven.hartland@multiplay.co.uk>
=> Add nsenter details to libcontainer README.md

utils_linux.go
We could fail and return in tty.recvtty() and miss
tty.Close(), which might cause broken console output.
=> Call defer tty.Close() earlier

libcontainer/factory_linux.go
Ensure that the pipe is always closed during the error processing of  StartInitialization.
Also:
* Fix a comment typo.
* Use newContainerInit directly as there's no need for i to be an initer.
* Move the comment about the behaviour of Init() directly above it, clarifying what happens for all defers.
Signed-off-by: Steven Hartland <steven.hartland@multiplay.co.uk>
=> Ensure pipe is always closed on error in StartInitialization

README.md, libcontainer/README.md
Add godoc links to README.md files for runc and libcontainer so its easy to access the golang documentation.
=> Add godoc links to README.md files

libcontainer/label/label_selinux.go, libcontainer/label/label_selinux_test.go
This reverts commit 491cadac9260de4886d2d4df680de065ccdffec1.
@rhatdan PTAL as per discussion in https://github.com/opencontainers/runc/pull/1109#issuecomment-275868464 and https://github.com/docker/docker/pull/30532#issuecomment-275864816
=> Revert "DupSecOpt needs to match InitLabels"

libcontainer/container_linux.go, libcontainer/factory_linux.go, libcontainer/init_linux.go, libcontainer/process_linux.go, libcontainer/setns_init_linux.go
If we pass a file descriptor to the host filesystem while joining a
container, there is a race condition where a process inside the
container can ptrace(2) the joining process and stop it from closing its
file descriptor to the stateDirFd. Then the process can access the
*host* filesystem from that file descriptor. This was fixed in part by
5d93fed3d27f ("Set init processes as non-dumpable"), but that fix is
more of a hail-mary than an actual fix for the underlying issue.
To fix this, don't open or pass the stateDirFd to the init process
unless we're creating a new container. A proper fix for this would be to
remove the need for even passing around directory file descriptors
(which are quite dangerous in the context of mount namespaces).
There is still an issue with containers that have …
=> libcontainer: init: only pass stateDirFd when creating a container

libcontainer/factory_linux.go
If a relative pathed exe is used for InitArgs init will fail to run if Cwd is not set the original path.
Prevent failure of init to run by ensuring that exe in InitArgs is an absolute path.
Signed-off-by: Steven Hartland <steven.hartland@multiplay.co.uk>
=> Resolve InitArgs to ensure init works

libcontainer/container.go
Correct container.Destroy() docs to clarify that destroy can only operate on containers in specific states.
=> Correct container.Destroy() docs

libcontainer/state_linux.go
Correct typo in docs for restoredState.
=> Correct docs typo for restoredState.

libcontainer/init_linux.go
signalAllProcesses was making the assumption that the requested signal was SIGKILL, possibly due to the signal parameter being added at a later date, and hence it was safe to wait for all processes which is not the case.
BaseContainer.Signal(s os.Signal, all bool) exposes this functionality to consumers, so an arbitrary signal could be used which is not guaranteed to make the processes exit.
Correct the documentation for signalAllProcesses around the signal delivered and update it so that the wait is only performed on SIGKILL hence making it safe to process other signals without risk of blocking forever, while still maintaining compatibility to SIGKILL callers.
Signed-off-by: Steven Hartland <steven.hartland@multiplay.co.uk>
=> Only wait for processes after delivering SIGKILL in signalAllProcesses

libcontainer/selinux/selinux.go
`label.InitLabels` takes options as a string slice in the form of:
user:system_u
role:system_r
type:container_t
level:s0:c4,c5
However, `DupSecOpt` and `DisableSecOpt` were still adding a docker
specifc `label=` in front of every option. That leads to `InitLabels`
not being able to correctly init selinux labels in this scenario for
instance:
label.InitLabels(DupSecOpt([%OPTIONS%]))
if `%OPTIONS` has options prefixed with `label=`, that's going to fail.
Fix this by removing that docker specific `label=` prefix.
=> libcontainer: selinux: fix DupSecOpt and DisableSecOpt

libcontainer/rootfs_linux.go
As the runtime-spec allows it, we want to be able to specify overlayfs
mounts with:
{
"destination": "/etc/pki",
"type": "overlay",
"source": "overlay",
"options": [
"lowerdir=/etc/pki:/home/amurdaca/go/src/github.com/opencontainers/runc/rootfs_fedora/etc/pki"
]
},
This patch takes care of allowing overlayfs mounts. Both RO and RW
should be supported.
=> libcontainer: rootfs_linux: support overlayfs

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, tests/integration/update.bats, update.go
Should set Swap to '-1' (unlimited) if memory is set to unlimited. Otherwise kernel validation fails.
these changes required to fix this issue in Docker project: https://github.com/docker/docker/pull/22578
=> Fixes set memory to unlimited

libcontainer/nsenter/nsexec.c
This helps fix compile warnings on some arm systems.
=> Use %zu for printing of size_t values

.travis.yml, Dockerfile
Travis is testing against 1.6.x and 1.7.x if the intent is test againts the last two stable version we should remove the 1.6 and add the 1.8
Also the tool being use for the validation of bash scripts (https://github.com/mvdan/sh) is only compatible with 1.7>
Also I added tip as an allowed to fail version
=> update go version at travis-ci

libcontainer/label/label_selinux.go
The error message added here provides no value as the caller already
knows all the added details. However it is covering up the underlying system error (typically `ENOTSUP`). There is no way to correctly handle this error before this change.
=> Don't override system error

create.go, run.go, utils_linux.go
This preserves the given number of file descriptors on top of the 3 stdio, that
is, fds [3..3+N) will be passed through.
Since Socket Activation (via $LISTEN_FDS) also claims fd 3 onwards the use of
this new flag is incompatible with socket activation.
Signed-off-by: Ian Campbell <ian.campbell@docker.com>
=> Add --preserve-file-descriptors=N to create

notify_socket.go, restore.go, signals.go, utils.go, utils_linux.go
The current support of systemd-notify has a race condition as the
message send to the systemd notify socket might be dropped if the sender
process is not running by the time systemd checks for the sender of the
datagram.  A proper fix of this in systemd would require changes to the
kernel to maintain the cgroup of the sender process when it is dead (but
it is not probably going to happen...)
Generally, the solution to this issue is to specify the PID in the
message itself so that systemd has not to guess the sender, but this
wouldn't work when running in a PID namespace as the container will pass
the PID known in its namespace (something like PID=1,2,3..) and systemd
running on the host is not able to map it to the runc service.
The proposed solution is to have a proxy in runc that …
=> fix systemd-notify when using a different PID namespace

libcontainer/user/user.go
The parameters passed to `GetExecUser` is not correct.
Consider the following code:
```
package main
import (
"fmt"
"io"
"os"
)
func main() {
passwd, err := os.Open("/etc/passwd1")
passwd = nil
} else {
defer passwd.Close()
}
err = GetUserPasswd(passwd)
fmt.Printf("%#v\n", err)
}
}
func GetUserPasswd(r io.Reader) error {
if r == nil {
return fmt.Errorf("nil source for passwd-formatted
data")
} else {
fmt.Printf("r = %#v\n", r)
}
return nil
}
```
If the file `/etc/passwd1` is not exist, we expect to return
`nil source for passwd-formatted data` error, and in fact, the func
`GetUserPasswd` return nil.
The same logic exists in runc code. this patch fix it.
=> user: fix the parameter error

exec.go, start.go
container can be in stopped status from created status. even if it was't been run before.
Signed-off-by: CuiHaozhi <cuihaozhi@chinacloud.com.cn>
=> Container can be in stopped status from created status.

tty.go, utils_linux.go
This is a fix for rootless containers and general io handling.  The
higher level systems must preparte the IO for the container in the
detach case and make sure it is setup correctly for the container's
process.
Replacement for #1349
Fixes detached use case for #774 
=> Don't fchown when inheriting io

libcontainer/cgroups/systemd/apply_systemd.go
Close https://github.com/docker/docker/issues/30121
=> fix cpu.cfs_quota_us changed when systemd daemon-reload using systemd.

libcontainer/devices/devices_unix.go
getDevices() has been updated to skip `/dev/.lxc` and `/dev/.lxd-mounts`, which was breaking privileged Docker containers running on runC inside of LXD managed Linux Containers.
See https://github.com/lxc/lxd/issues/2825
=> Update devices_unix.go for LXD

libcontainer/container_linux.go, libcontainer/init_linux.go
In container process's Init function, we use
fd + execFifoFilename to open exec fifo, so this
field in init config is never used.
=> Remove unused ExecFifoPath

libcontainer/network_linux.go
When failed to attach veth pair, should remove the veth device
Signed-off-by: Wentao Zhang <zhangwentao234@huawei.com>
=> fix minor issue

libcontainer/network_linux.go
This reverts commit d4091ef151f33ecc000a4c9fe91a9ca043fc683f.
d4091ef151f3 ("fix minor issue") doesn't actually make any sense, and
actually makes the code more confusing.
=> Revert "fix minor issue"

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/cpu.go, libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/configs/cgroup_unix.go, libcontainer/specconv/spec_linux.go, update.go
=> Use uint64 for resources to keep consistency with runtime-spec

libcontainer/init_linux.go, libcontainer/integration/exec_test.go
When process config doesnt specify capabilities anywhere, we should not panic because setting capabilities are optional.
Without this, process without configured caps will panic with:
```
utils_test.go:51: exec_test.go:370: unexpected error: container_linux.go:259: starting container process caused "panic from initialization: runtime error: invalid memory address or nil pointer dereference, goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0xc4200bf878, 0x704700, 0xabedd0)
\t/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func2(0xc4200bfee0)
\t/go/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:278 +0x60
panic(0x704700, 0xabedd0)
\t/usr/local/go/src/runtime/panic.go:489 +0x2cf …
```
=> fix panic regression when config doesnt have caps

.travis.yml
cc @mrunalp 
I'm also going to try this as the upstream default https://github.com/vbatts/git-validation/pull/15
Signed-off-by: Vincent Batts <vbatts@redhat.com>
=> travis: use alternate commit range

.travis.yml
Master builds [only have a `git clone …`][1] so `FETCH_HEAD` isn't defined and [git-validation crashes][2].  We don't want to be hard-coding a range here, and should update git-validation to handle these cases automatically.
Also echo `TRAVIS_*` variables during testing to make debugging git-validation easier.
[1]: https://travis-ci.org/opencontainers/runc/jobs/213508696#L243
[2]: https://travis-ci.org/opencontainers/runc/jobs/213508696#L347
=> .travis.yml: Don't require FETCH_HEAD (partial fix for failing master tests)

libcontainer/console_linux.go
Fixes opencontainers/runc/issues/1364
Signed-off-by: Christy Perez <christy@linux.vnet.ibm.com>
=> Fix console syscalls

libcontainer/container_linux.go
Instead of relying on version numbers it is possible to check if CRIU
actually supports certain features. This introduces an initial
implementation to check if CRIU and the underlying kernel actually
support dirty memory tracking for memory pre-dumping.
Upstream CRIU also supports the lazy-page migration feature check and
additional feature checks can be included in CRIU to reduce the version
number parsing. There are also certain CRIU features which depend on one
side on the CRIU version but also require certain kernel versions to
actually work. CRIU knows if it can do certain things on the kernel it
is running on and using the feature check RPC interface makes it easier
for runc to decide if the criu+kernel combination will support that
feature.
Signed-off-by: Adrian Reber …
=> checkpoint: check if system supports pre-dumping

libcontainer/container_linux.go
When C/R was implemented, it was enough to call manager.Set to apply
limits and to move a task. Now .Set() and .Apply() have to be called
separately.
Fixes: 8a740d5391a7 ("libcontainer: cgroups: don't Set in Apply")
Cc: @cyphar
=> restore: apply resource limits

Makefile
This was changed in
https://github.com/opencontainers/runc/commit/d2f49696#diff-b67911656ef5d18c4ae36cb6741b7965R7
and is causing install problems for people building runc and having it
installed in /bin and /sbin.
=> Revert back to using /sbin

libcontainer/container_linux.go
Irrespective of 'isInit' is set to true or false, set container state during start only once. 
Signed-off-by: Harshal Patil <harshal.patil@in.ibm.com>
=> Set container state only once during start

libcontainer/generic_error_test.go
add testcase with function `Error(),Code()`  in generic_error_test.go 
Signed-off-by: chchliang <chen.chuanliang@zte.com.cn>
=> add testcase in generic_error_test.go

checkpoint.go, man/runc-checkpoint.8.md, restore.go
Hi there.  Here's a very small patch to fix the word "properties" where it has been misspelled in various places.
(Resubmitted after adding Signed-off-by to certify DCO).
=> Fix misspelling of "properties" in various places

libcontainer/container_linux.go
If we try to pause a container on the system without freezer cgroups,
we can found that runc tries to open ./freezer.state. It is obviously wrong.
$ ./runc pause test
no such directory for freezer.state
$ echo FROZEN > freezer.state
$ ./runc pause test
container not running or created: paused
=> Don't try to read freezer.state from the current directory

tests/integration/spec.bats, vendor.conf
vndr doesn't support non-top-level imports, and in addition we really
should be using tagged releases far more than we currently are
(*especially* when it come to the OCI specs).
=> vendor: clean up to be better written

libcontainer/container_linux.go
There is no need to loop twice just to skip the namespaces
that we don't need to join. 
Signed-off-by: Harshal Patil <harshal.patil@in.ibm.com>
=> Optimizing looping over namespaces

tests/integration/update.bats, update.go
=> Allow updating pids limit

libcontainer/configs/namespaces_unix.go, libcontainer/container_linux.go
Namespaces slice is declared twice. Let's keep list 
namespaces at one place instead of duplicating it. Should
there be any change in future in the number of namespaces
or anything like that, we just have to change in one 
location.
Signed-off-by: Harshal Patil <harshal.patil@in.ibm.com>
=> Remove redundant declaration of namespace slice

libcontainer/factory_linux.go
Based on the discussions in Issue #1429, we should not 
be checking the length of the id string
Signed-off-by: Harshal Patil <harshal.patil@in.ibm.com>
=> Issue #1429 : Removing check for id string length

tests/integration/cgroups.bats, tests/integration/checkpoint.bats, tests/integration/delete.bats, tests/integration/events.bats, tests/integration/exec.bats, tests/integration/kill.bats, tests/integration/list.bats, tests/integration/mask.bats, tests/integration/pause.bats, tests/integration/ps.bats, tests/integration/root.bats, tests/integration/start_detached.bats, tests/integration/state.bats, tests/integration/tty.bats, tests/integration/update.bats
It is useless and potentially we can skip bugs.
=> tests: don't call wait_for_container after synchronous operations

libcontainer/configs/cgroup_linux.go, libcontainer/configs/config_linux.go, libcontainer/configs/config_linux_test.go, libcontainer/configs/namespaces_linux.go, libcontainer/configs/namespaces_unsupported.go, libcontainer/criu_opts_linux.go, libcontainer/devices/devices_linux.go, libcontainer/devices/devices_unsupported.go, main_linux.go, main_solaris.go
FreeBSD does not support cgroups or namespaces, which the code suggested, and is not supported
in runc anyway right now. So clean up the file naming to use `_linux` where appropriate.
=> Clean up unix vs linux usage

delete.go, tests/integration/delete.bats
This patch mimics the behavior of "rm -rf" so that if a container
doesn't exist and you force delete it, it won't error out.
=> Ignore error when force deleting a non-existing container

libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/utils.go, libcontainer/cgroups/utils_test.go
As described in https://github.com/opencontainers/runc/issues/1367, if a non-cpuset subsystem has been been mounted earlier in the mount table at a disjoint location to the rest of the hierarchy (e.g. `/sys/fs/cgroup/{cpuset,cpu,memory...}`) then `runc create` will fail with:
```
container_linux.go:259: starting container process caused "process_linux.go:283: applying cgroup configuration for process caused \"open /sys/fs/cpuset.cpus: no such file or directory\""
```
To replicate this behaviour, using Ubuntu 14.04 with a 4.4 kernel (linux-generic-lts-xenial package), create a mount table that looks like this:
```
cgroup /cgroup cgroup rw,relatime,cpu 0 0
none /sys/fs/cgroup tmpfs rw,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/cpu cgroup …
```
=> Handle container creation when cgroups have already been mounted in another location

libcontainer/process_linux.go
* User Case:
User could use prestart hook to add block devices to container. so the
hook should have a way to set the permissions of the devices.
Just move cgroup config operation before prestart hook will work.
Signed-off-by: Wentao Zhang <zhangwentao234@huawei.com>
=> Fix setup cgroup before prestart hook

Makefile
This is needed if you need to customise the build config for a given platform.
=> Allow specification of general Go build flags and ldflags

libcontainer/README.md
Follow commit 3d7cb4293c15 ("Move libcontainer to x/sys/unix") and also
move the examples in README.md from syscall to x/sys/unix.
=> Switch examples in README.md from syscall to x/sys/unix

libcontainer/message_linux.go
Use the NLA_ALIGNTO and NLA_HDRLEN constants from x/sys/unix instead of
syscall, as the syscall package shouldn't be used anymore (except for a
few exceptions).
This also makes the syscall_NLA_HDRLEN workaround for gccgo unnecessary.
=> Use NLA_* constants from x/sys/unix instead of syscall

libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go, libcontainer/system/linux.go
Use unix.Prctl() instead of reimplemnting it as system.Prctl().
=> Use Prctl() from x/sys/unix instead of own wrapper

.travis.yml
If someone forks runc and wants to check changes in travis, he will find
that the command 'make BUILDTAGS="${BUILDTAGS}"' fails, because
github.com/opencontainers/runc/ is used in many places to import
packages (e.g. libcontainer).
=> travis: set go_import_path to github.com/opencontainers/runc

contrib/cmd/recvtty/recvtty.go, libcontainer/console_linux.go, libcontainer/integration/execin_test.go, tty.go
And use it only in local tooling that is forwarding the pseudoterminal master.  That way runC no longer has an opinion on the `onlcr` setting for folks who are creating a terminal and detaching.  They'll use `--console-socket` and can setup the pseudoterminal however they like without runC having an opinion.  With this commit, the only cases where runC still applies SaneTerminal is when *it* is the process consuming the master descriptor.
Previous discussion in #1146 (which landed `saneTerminal` in the first place) and also [on IRC earlier today][1].  From that IRC discussion, this PR takes the “whoever gets the master descriptor can set it up as they see fit” approach.  And alternative floated by @crosbymichael was to [expose some subset of the termios structure in the config][2] which …
=> libcontainer/console_linux.go: Make SaneTerminal public

tests/integration/checkpoint.bats, tests/integration/helpers.bash
Currently we don't see these messages, but there may be useful information for understanding problems.
=> tests: redirect runc log messages to stderr

Dockerfile, tests/integration/checkpoint.bats
Story for the stack gap problem: https://github.com/xemul/criu/issues/322
This upgrades criu to a testing commit to fix our test failures. We should upgrade again when criu does a release but this commit seems to fix the tests for now.
=> Fix checkpoint/restore tests with newer kernel

libcontainer/cgroups/fs/memory.go, libcontainer/configs/cgroup_linux.go, libcontainer/specconv/example.go, spec.go, update.go, vendor.conf, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
Update memory specs to use int64 not uint64
replace #1492 #1494
fix #1422
Since https://github.com/opencontainers/runtime-spec/pull/876 the memory
specifications are now `int64`, as that better matches the visible interface where
`-1` is a valid value. Otherwise finding the correct value was difficult as it
was kernel dependent.
Also in the update of the spec, `Platform` was removed, so remove some code.
=> Update spec to master, switch to int64 for memory limits

libcontainer/specconv/spec_linux.go
Part of catching runC up with the spec, which [punts valid options to `mount(8)`][1].  Part of opencontainers/runtime-spec#771.
[1]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0-rc5/config.md#L68
=> libcontainer/specconv/spec_linux: Add support for (no)lazytime

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/cgroups/fs/stats_util_test.go, libcontainer/cgroups/stats.go
Fixes https://github.com/opencontainers/runc/issues/1376
Signed-off-by: Derek Carr <decarr@redhat.com>
=> Expose memory.use_hierarchy in MemoryStats

script/check-config.sh
Recent changes in upstream shfmt have started causing our scripts to no
longer be "correctly formatted". Fix up with `shfmt -w`.
=> *: fix shfmt

libcontainer/user/user.go
As described in [opencontainers/image-spec#492](https://github.com/opencontainers/image-spec/pull/492) by @cyphar 
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>
=> libcontainer/user: add supplementary groups only for non-numeric users

tests/integration/helpers.bash
If criu isn't installed in the host, integration tests won't be able
to go on, it should skip checkpoint/restore tests instead of interrupt.
Output before:
```
$ make localintegration
bats -t tests/integration
/usr/lib/bats/bats-exec-suite: line 20: let: count+=: syntax error:
operand expected (error token is "+=")
Makefile:103: recipe for target 'localintegration' failed
```
=> Fix integration when missing criu

libcontainer/factory_linux.go, list.go
If a container is owned by a UID that is not listed in /etc/passwd,
previously we would cast the UID to a string which contained a character
with the unicode value of the UID. This is clearly wrong, switch to
using fmt.Sprintf as intended.
In addition, notate unknown users with a leading '#' in the column. This
is necessary to ensure that a user is not under the impression that the
UID is the same as a numeric username.
It appears as though these semantics were not fully thought out when
implementing them for rootless containers. It is not necessary (and
could be potentially dangerous) to set the owner of /run/ctr/$id to be
the root inside the container (if user namespaces are being used).
Instead, just use the e{g,u}id of runc to determine the owner.
Fixes #1515 
Signed-off-by: Aleksa …
=> list: fix various problems with owner field

libcontainer/container_linux.go, libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go
Use ParseSocketControlMessage and ParseUnixRights from
golang.org/x/sys/unix instead of their syscall equivalent.
Use PR_SET_NO_NEW_PRIVS defined in golang.org/x/sys/unix instead of
manually defining it.
=> libcontainer: use additional functions and constants from x/sys/unix

libcontainer/devices/devices_linux.go, libcontainer/devices/devices_test.go
Refactor DeviceFromPath in order to get rid of package syscall and
directly use the functions from x/sys/unix. This also allows to get rid
of the conversion from the OS-independent file mode values (from the os
package) to Linux specific values and instead let's us use the raw
file mode value directly.
=> libcontainer: one more switch from syscall to x/sys/unix

README.md
The format of the capabilities section in config.json was changed in the
runtime spec 1.0.0.rc5 (pulled in through PR #1370). Update the example
in README.md correspondingly.
Also fix a small typo (though -> through).
=> README.md: adjust capabilities section in config.json example

libcontainer/nsenter/nsexec.c
There is a possibility that  the code close negative descriptor,  it don't lead to a issue, but the code is ugly.
Signed-off-by: yangshukui <yangshukui@huawei.com>
=> Remove the code that close negative descriptor

libcontainer/configs/namespaces_linux.go, libcontainer/container_linux_test.go
fix #1476
If containerA shares namespace, say ipc namespace, with containerB, then
its ipc namespace path would be the same as containerB and be stored in
`state.json`. Exec into containerA will just read the namespace paths
stored in this file and join these namespaces. So, if containerB has
already been stopped, `docker exec containerA` will fail.
To address this issue, we should always save own namespace paths no
matter if we share namespaces with other containers.
Signed-off-by: Yuanhong Peng <pengyuanhong@huawei.com>
=> Always save own namespace paths

libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/container_linux.go, libcontainer/integration/exec_test.go, libcontainer/integration/execin_test.go
Fix two classes of issues found by staticcheck (honnef.co/go/tools/cmd/staticcheck):
- Unhandled error return values
- Ineffective break statements in switch
More details can be found in the commit messages.
=> Fix issues found by staticcheck

libcontainer/user/lookup.go, libcontainer/user/lookup_unix.go, libcontainer/user/lookup_unsupported.go
-- 
This fix a compile error on systems that import the user package (e.g. `Docker` on `Windows`)
=> Move user pkg unix specific calls to unix file

libcontainer/devices/devices_linux.go
--
Before this fix, `/dev/fuse` is created as a block device, and `docker` tries to create `/dev/fd` as a `0,0` device.
=> Fix condition to detect device type in DeviceFromPath

libcontainer/user/user.go
This reverts commit 5c73abbe75d73352bf966c9c27abdd6daeeaad69, reversing
changes made to 51b501dab1889ca609db9c536ac976f0f53e7021.
-- 
ping @crosbymichael @cyphar @justincormack 
Continuing the conversation here :innocent:
=> Revert "Merge pull request #1450 from vrothberg/sgid-non-numeric"

libcontainer/init_linux.go, libcontainer/nsenter/nsexec.c, libcontainer/process_linux.go
Fixes https://github.com/opencontainers/runc/issues/1443
=> Pass back the pid of runc:[1:CHILD] so we can wait on it

libcontainer/devices/devices_linux.go
Before this change, some file type would be treated as char devices
(e.g. symlinks).
-- 
In my previous PR #1544 I had forgotten to commit a piece of code before pushing :man_facepalming:. Since I had it in a dirty vendor on my docker PR I didn't realize it was missing from here. 
This PR should fix this issue once and for all hopefully :sweat_smile: 
ping @crosbymichael @mrunalp
=> Handle non-devices correctly in DeviceFromPath

libcontainer/specconv/spec_linux.go
Linux is not always not nil.
If Linux is nil, panic will occur.
Closes #1449
This is a rebase of #1449
=> fix panic when Linux is nil

libcontainer/notify_linux.go, libcontainer/notify_linux_test.go
Fixes: #1228
It can be reproduced by applying this patch:
```diff
@@ -45,6 +46,7 @@ func registerMemoryEvent(cgDir string, evName string, arg string) (<-chan struct
go func() {
defer func() {
close(ch)
+                       <-time.After(1 * time.Second)
eventfd.Close()
evFile.Close()
}()
```
We can close channel after fds were closed.
=> Fix flaky test TestNotifyOnOOM

Makefile
Go has supported PIC builds for a while now, and given the security
benefits of using PIC binaries we should really enable them. There also
appears to be some indication that non-PIC builds have been interacting
oddly on ppc64le (the linker cannot load some shared libraries), and
using PIC builds appears to solve this problem.
=> makefile: enable -buildmode=pie

libcontainer/container_linux.go, libcontainer/container_linux_test.go
state.json should be a reflection of the container's
realtime state, including resource configurations,
so we should update state.json after updating container
resources.
=> Update state after update

.travis.yml, Makefile, script/release.sh
This script is far easier to use than the previous `make release`
target, not to mention that it also automatically signs all of the
artefacts and makes everything really easy to do for maintainers.
[I'm going to re-release all of our previous releases using this script.]
Ref: openSUSE/umoci#163
=> release: import umoci's release.sh script

libcontainer/specconv/spec_linux.go
congfig.Sysctl setting is duplicated.
when contianer is rootless and Linux is nil, runc will panic.
=> fix panic when Linux is nil for rootless case

signals.go, utils_linux.go
Both tty.resize and notifySocket.setupSocket return an error which isn't
handled in the caller. Fix this and either log or propagate the errors.
Found using https://github.com/mvdan/unparam
=> Check error return values

checkpoint.go, libcontainer/container_linux.go, libcontainer/criu_opts_linux.go, restore.go
Memory image deduplication, very useful for incremental dumps.
See: https://criu.org/Memory_images_deduplication
Signed-off-by: Nikolas Sepos <nikolas.sepos@gmail.com>
=> Add AutoDedup option to CriuOpts

libcontainer/container_linux.go, libcontainer/factory_linux.go, libcontainer/init_linux.go, libcontainer/process_linux.go, libcontainer/standard_init_linux.go
While we have significant protections in place against CVE-2016-9962, we
still were holding onto a file descriptor that referenced the host
filesystem. This meant that in certain scenarios it was still possible
for a semi-privileged container to gain access to the host filesystem
(if they had CAP_SYS_PTRACE).
Instead, open the FIFO itself using a O_PATH. This allows us to
reference the FIFO directly without providing the ability for
directory-level access. When opening the FIFO inside the init process,
open it through procfs to re-open the actual FIFO (this is currently the
only supported way to open such a file descriptor).
=> init: switch away from stateDirFd entirely

libcontainer/cgroups/systemd/apply_systemd.go
Fixes: #1557
I'm not quite sure about the root cause, looks like
systemd still want them to be uint64.
=> Fix systemd cgroup after memory type changed

libcontainer/rootfs_linux.go
The documentation here:
https://docs.docker.com/engine/security/userns-remap/#user-namespace-known-limitations
says that readonly containers can't be used with user namespaces do to some
kernel restriction. In fact, there is a special case in the kernel to be
able to do stuff like this, so let's use it.
This takes us from:
```
ubuntu@docker:~$ docker run -it --read-only ubuntu
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:125: remounting \\\"/dev\\\" as readonly caused \\\"operation not permitted\\\"\"".
```
to:
```
ubuntu@docker:~$ docker-runc --version
runc version 1.0.0-rc4+dev
commit: ae2948042b08ad3d6d13cd09f40a50ffff4fc688-dirty
spec: 1.0.0 …
```
=> fix --read-only containers under --userns-remap
