opencontainers/runc

README.md
This seems like a simple typo.
=> Change "... JSON Format;" to "... JSON Format:"

tty.go, utils.go
Signed-off-by: Zefan Li <lizefan@huawei.com>
=> Remove nsinit from comments

spec_linux.go
=> Fix function name typo

README.md
=> Add notcie about config format changes

README.md
=> Minor README tweaks to help newbies

checkpoint.go, libcontainer/container_linux.go, libcontainer/criu_opts.go, restore.go
Signed-off-by: mapk0y <mapk0y@gmail.com>
=> checkpoint/restore commands support 'file-locks' option.

Makefile, README.md, main.go, restore.go, run.go, spec.go, spec_linux.go, utils.go
For a full list of the changes see the commits and read the descriptions.
=> Update config based on spec changes

Makefile
=> Prefer Godep dependencies in the GOPATH

README.md
=> README changes for the newer spec format.

spec.go
Don't know why we missed that.
=> Add memory limit set

libcontainer/cgroups/systemd/apply_systemd.go
=> Add oom-kill-disable support for systemd

libcontainer/utils/utils.go, libcontainer/utils/utils_unix.go
Factors out CloseExecFrom which is only called on the Linux path.
=> Windows: Factor out CloseExecFrom

restore.go
Signed-off-by: Jin-Hwan Jeong <jhjeong.kr@gmail.com>
=> typo: SICHLD -> SIGCHLD

libcontainer/netlink/netlink_linux_armppc64.go, libcontainer/netlink/netlink_linux_notarm.go
Signed-off-by: Srini Brahmaroutu <srbrahma@us.ibm.com>
=> the data type should be int8 for ppc64le

utils.go
Signed-off-by: Jin-Hwan Jeong <jhjeong.kr@gmail.com>
=> typo: exists -> exits

signals.go, tty.go
Signed-off-by: Jin-Hwan Jeong <jhjeong.kr@gmail.com>
=> Fixed two typos

libcontainer/cgroups/utils.go
Before name=systemd cgroup was mounted inside container to
/sys/fs/cgroup/name=systemd, which is wrong, it should be
/sys/fs/cgroup/systemd
=> Fix handling name= cgroups

libcontainer/rootfs_linux.go
This allows software be not aware about existence of merged cgroups.
ping @mrunalp
=> Create symlinks for merged cgroups

libcontainer/init_linux.go
Signed-off-by: Jin-Hwan Jeong <jhjeong.kr@gmail.com>
=> typo: tempory -> temporary

run.go
Signed-off-by: Shishir Mahajan shishir.mahajan@redhat.com
=> systemd integration with container runtime for supporting sd_notify protocol

libcontainer/cgroups/utils.go
=> Fix files not closed in mountinfo parsing function

libcontainer/integration/checkpoint_test.go
Signed-off-by: Andrew Vagin <avagin@openvz.org>
=> tests: dump/restore a container with cgroups

libcontainer/container_linux.go
Signed-off-by: Hui Kang <hkang.sunysb@gmail.com>
=> Add debug message when unable to execute criu

restore.go
There was previously a memory issue in the signal handler that showed up
when using restore.  This has been fixed, therefore, restore can use the
signal handler.
=> Use signal handler for restore

libcontainer/rootfs_linux.go
=> Don't make modifications to /dev when it is bind mounted

checkpoint.go, libcontainer/container_linux.go, spec.go
=> Fix minor stylistic issues

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/apply_raw_test.go
I had pretty convenient input data to miss this bug.
ping @mrunalp @crosbymichael @ibuildthecloud
=> Fix cgroup parent searching

README.md, main.go
=> Minor update to usage/help text

kill.go
=> Add the default signal (SIGTERM) for runc kill

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/specs/.travis.yml, Godeps/_workspace/src/github.com/opencontainers/specs/README.md, Godeps/_workspace/src/github.com/opencontainers/specs/config-linux.md, Godeps/_workspace/src/github.com/opencontainers/specs/implementations.md, Godeps/_workspace/src/github.com/opencontainers/specs/spec_linux.go, spec.go
Update spec devices from strings to structs.
cc @LK4D4
=> Update device specs

spec.go
=> Integrate security settings

exec.go, main.go
Starts a new process inside an existing container.
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
=> Add exec command

libcontainer/container_linux.go, libcontainer/criu_opts.go
Signed-off-by: Hui Kang <hkang.sunysb@gmail.com>
=> Add hooks for passing explicit veth pairs for forwarding to CRIU

start.go
Signed-off-by: Shishir Mahajan <shishir.mahajan@redhat.com>
=> Error should be checked after loadSpec

README.md, spec.go
Adding rlimit constraints to spec with hard and soft values
=> Adding rlimit in spec

README.md
Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>
=> Update README config file devices

restore.go
=> Remove hard-coded default for tcp connections

README.md
Signed-off-by: Mark Sta Ana <booyaabooyaabooyaa@gmail.com>
=> Add caveat will only build on Linux as per #9

start.go
Signed-off-by: Shishir Mahajan <shishir.mahajan@redhat.com>
=> cleanup: outdated comment

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/utils.go
- Refactor find mount point functions
- Rename FindCgroupMountpointAndSource to FindCgroupMountpointAndRoot
=> Some cgroups cleanup

README.md
Add more build tags in readme for building runc.
=> Add all support build tags for runc features

libcontainer/rootfs_linux.go
=> Always remount for bind mount

main.go
=> Minor comments fix

README.md
=> Add testing docs in README

main.go
=> update the command usage of `runc`

spec.go
=> close config file after loaded

script/test_Dockerfile
Fix https://github.com/opencontainers/runc/issues/287
ping @LK4D4 @crosbymichael @mrunalp 
Signed-off-by: Antonio Murdaca <runcom@linux.com>
=> script: test_Dockerfile: install criu from source

libcontainer/init_linux.go
Whenever dev/null is used as one of the main processes STDIO, do not try
to change the permissions on it via fchown because we should not do it
in the first place and also this will fail if the container is supposed
to be readonly.
=> Ignore changing /dev/null permissions if used in STDIO

libcontainer/nsenter/nsexec.c
When executing an additional process in a container, all namespaces are
entered but the user namespace. As a result, the process may be
executed as the host's root user. This has both functionality and
security implications.
Fix this by adding the missing user namespace to the array of
namespaces. Since joining a user namespace in which the caller is
already a member yields an error, skip namespaces we're already in.
Last, remove a needless and buggy AT_SYMLINK_NOFOLLOW in the code.
Signed-off-by: Ido Yariv <ido@wizery.com>
=> Enter existing user namespace if present

libcontainer/console_linux.go, libcontainer/rootfs_linux.go
Signed-off-by: Antonio Murdaca <runcom@linux.com>
=> Cleanup unused func arguments

spec.go
=> simple refactor for the options of `runc spec`

libcontainer/cgroups/fs/hugetlb_test.go
=> Run tests for all HugetlbSizes

libcontainer/cgroups/systemd/apply_systemd.go
=> Systemd: Join perf_event cgroup

libcontainer/configs/config_unix.go
change `uid` to `gid` in func `HostGID`
=> change uid to gid in func HostGID

libcontainer/cgroups/systemd/apply_systemd.go
Seems it's missed in the first place.
=> Add memory reservation support for systemd

libcontainer/seccomp/config.go
=> change named to names

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/specs/.travis.yml, Godeps/_workspace/src/github.com/opencontainers/specs/README.md, Godeps/_workspace/src/github.com/opencontainers/specs/bundle.md, Godeps/_workspace/src/github.com/opencontainers/specs/code-of-conduct.md, Godeps/_workspace/src/github.com/opencontainers/specs/config-linux.md, Godeps/_workspace/src/github.com/opencontainers/specs/config.go, Godeps/_workspace/src/github.com/opencontainers/specs/config.md, Godeps/_workspace/src/github.com/opencontainers/specs/config_linux.go, Godeps/_workspace/src/github.com/opencontainers/specs/principles.md, Godeps/_workspace/src/github.com/opencontainers/specs/runtime-config-linux.md, Godeps/_workspace/src/github.com/opencontainers/specs/runtime-config.md, Godeps/_workspace/src/github.com/opencontainers/specs/runtime-linux.md, Godeps/_workspace/src/github.com/opencontainers/specs/runtime.md, Godeps/_workspace/src/github.com/opencontainers/specs/runtime_config.go, Godeps/_workspace/src/github.com/opencontainers/specs/runtime_config_linux.go, Godeps/_workspace/src/github.com/opencontainers/specs/version.go, spec.go
Bump up specs and hook up additional gids support
=> Add additional groups support

checkpoint.go, libcontainer/container_linux.go, libcontainer/criu_opts.go, libcontainer/criurpc/criurpc.pb.go, libcontainer/criurpc/criurpc.proto, restore.go
Signed-off-by: Hui Kang <hkang.sunysb@gmail.com>
=> Add option to support criu manage cgroups mode for dump and restore

libcontainer/seccomp/config.go, spec.go
Add the conversion of architectures for seccomp config 
Signed-off-by: yangshukui <yangshukui@huawei.com>
=> Add the conversion of architectures for seccomp config

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/blkio.go, libcontainer/cgroups/fs/cpu.go, libcontainer/cgroups/fs/cpuacct.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/fs/devices.go, libcontainer/cgroups/fs/freezer.go, libcontainer/cgroups/fs/hugetlb.go, libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/name.go, libcontainer/cgroups/fs/net_cls.go, libcontainer/cgroups/fs/net_prio.go, libcontainer/cgroups/fs/perf_event.go, libcontainer/cgroups/systemd/apply_systemd.go
=> Add name to cgroup subsystem and set order

utils.go
Remove a wee bit of unused code.  (Noticed this in passing while researching https://github.com/opencontainers/runc/issues/349 .)
=> Remove fatalf function; unused.

libcontainer/container_linux.go
While testing different versions of criu it helps to know which
criu binary with which options is currently used. Therefore additional
debug output to display these information is added.
Signed-off-by: Adrian Reber <adrian@lisas.de>
=> Add criu related debug output

libcontainer/cgroups/fs/utils.go, libcontainer/factory_linux.go
=> Add more context around some error cases

libcontainer/label/label.go, libcontainer/label/label_selinux.go
=> Docker needs to know whether the user requested a relabel

README.md
Fix the command and elaborate the instruction.
=> README.md: fix description for runc with systemd

libcontainer/configs/config.go, libcontainer/seccomp/config.go, libcontainer/seccomp/seccomp_linux.go
This updates and replaces the previous PR.
Closes #347
=> Add seccomp trace support

libcontainer/rootfs_linux.go
=> Fix comment to be consistent with the code

libcontainer/configs/namespaces_unsupported.go
=> libcontainer: configs: extend unsupported os

main.go
=> Bump version constant to 0.0.5 in preparation for a new release

libcontainer/error.go
=> fix minor typo

libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/configs/cgroup_unix.go, libcontainer/integration/exec_test.go, libcontainer/integration/utils_test.go
Pick up #119
Fixes: docker/docker#16681
=> systemd: support cgroup parent with specified slice

libcontainer/process.go, restore.go, start.go, tty.go, utils.go
=> Move STDIO initialization to libcontainer.Process

libcontainer/process.go, libcontainer/process_linux.go
Otherwise Docker doesn't compile on Windows.
/cc @crosbymichael
Signed-off-by: David Calavera <david.calavera@gmail.com>
=> Move linux only Process.InitializeIO behind the linux build flag.

main.go
update release version from 0.0.5 to 0.0.6
=> update version for release 0.0.6

libcontainer/SPEC.md
Signed-off-by: Kai Qiang WU(Kennan) <wkq5325@gmail.com>
=> Fix typo word in SPEC.md

script/test_Dockerfile
=> update go version to 1.5.3 in dockerfile and cleanup

libcontainer/selinux/selinux.go, libcontainer/selinux/selinux_test.go
Adding `setenforce` implementation and updated tests.
=> selinux: add SelinuxSetEnforceMode implementation

spec.go
=> Check that cwd is absolute

libcontainer/seccomp/fixtures/proc_self_status, libcontainer/seccomp/seccomp_linux.go, libcontainer/seccomp/seccomp_linux_test.go, libcontainer/seccomp/seccomp_unsupported.go
This is much like apparmor.IsEnabled() function and a nice helper.
Signed-off-by: Jessica Frazelle <acidburn@docker.com>
=> add seccomp.IsEnabled() function

libcontainer/container_linux.go
=> Remove some hard coded strings

libcontainer/README.md
update date in README from 2014 to 2015
=> update date in README

libcontainer/README.md
Updating README file with user namespace.
=> Adding user namespace in README

libcontainer/container.go, libcontainer/container_linux_test.go, libcontainer/factory_linux.go, libcontainer/state_linux.go, libcontainer/state_linux_test.go
Add a "createdState" in its place since I think that better describes
what its used for.
=> Remove the nullState

libcontainer/process_linux.go
=> Fix the comment about sendConfig

Godeps/Godeps.json, Godeps/_workspace/src/github.com/codegangsta/cli/.travis.yml, Godeps/_workspace/src/github.com/codegangsta/cli/README.md, Godeps/_workspace/src/github.com/codegangsta/cli/app.go, Godeps/_workspace/src/github.com/codegangsta/cli/autocomplete/bash_autocomplete, Godeps/_workspace/src/github.com/codegangsta/cli/cli.go, Godeps/_workspace/src/github.com/codegangsta/cli/command.go, Godeps/_workspace/src/github.com/codegangsta/cli/context.go, Godeps/_workspace/src/github.com/codegangsta/cli/flag.go, Godeps/_workspace/src/github.com/codegangsta/cli/help.go, exec.go
=> update exec to pass args and --tty on run

libcontainer/error.go, libcontainer/process.go
Added error strings when there is no process operations.
=> Added error string for process operations

pause.go
corrected minor usage instruction in resume command
=> Fixing usage in resume command

libcontainer/SPEC.md
Fixing capabilities name in SPEC.md
=> Fixing capabilities name in SPEC.md

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/go-systemd/activation/files.go, Godeps/_workspace/src/github.com/coreos/go-systemd/activation/listeners.go, Godeps/_workspace/src/github.com/coreos/go-systemd/activation/packetconns.go, start.go, utils.go
=> *: use coreos/go-systemd/activation for socket activation

exec.go, start.go, utils.go
and it'll really help my start/create PR when I need to rebase  :-)
=> Create some util funcs that are common between start and exec

libcontainer/SPEC.md
Updating pids subsystem in SPEC.
=> Adding pids subsystem in SPEC.md

utils.go
=> Close tty on error before handler

libcontainer/integration/exec_test.go
Because we are implemented in Go, the number of pids present in a
container is not very well-defined (other than it not being /much/
bigger than the limit you'd want to set). As a result, we need to make
the tests a bit less flaky in this regard.
/cc @LK4D4 @crosbymichael @vmarmol @mrunalp @dqminh
=> libcontainer: integration: fix flaky pids limit tests

signals.go
=> Check if tty is nil in handler

libcontainer/cgroups/utils.go, libcontainer/cgroups/utils_test.go
- symbol can appear in any path
ping @mlaventure
=> Look for " - " instead of just - as separator

list.go
Addresses issue #547.  Adds a json option to the list command.
Closes #547
=> adding --format json to list command

libcontainer/selinux/selinux.go
Added the error check for Getfilecon if it returns an error.
=> Added error check in Getfilecon

libcontainer/rootfs_linux.go
Because we more than likely control dev and populate devices and files
inside of it we need to make sure that we fulfil the user's request to
make it ro only after it has been populated.  This removes the need to
expose something like ReadonlyPaths in the config but still have the
same outcome but more seemless for the user.
=> Remount /dev as ro after it is populated

spec.go
cc @crosbymichael 
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
=> Fix setting OomScoreAdj from OCI spec

libcontainer/README.md
Updated swappiness value in README file
=> Updating swapiness value in README

libcontainer/cgroups/stats.go, libcontainer/cgroups/utils_test.go
Added the linux compile flag for unit test
Fixed some minor typos.
=> Adding linux label to test file

libcontainer/nsenter/nsexec.c
=> Remove duplicated included head file

.gitignore, man/README.md, man/md2man-all.sh, man/runc-checkpoint.8.md, man/runc-delete.8.md, man/runc-events.8.md, man/runc-exec.8.md, man/runc-kill.8.md, man/runc-list.8.md, man/runc-pause.8.md, man/runc-restore.8.md, man/runc-resume.8.md, man/runc-spec.8.md, man/runc-start.8.md, man/runc-state.8.md, man/runc.8.md
=> Add man pages

libcontainer/nsenter/nsexec.c
This is a copy of
https://github.com/avagin/runc/commit/d31e97fa28345375b3f76bff64d12cdb07e03ba0
to address https://github.com/opencontainers/runc/issues/613
Signed-off-by: Andrew Fernandes <andrew@fernandes.org>
=> nsexec: don't use CLONE_PARENT and CLONE_NEWPID together

list.go
Changing from logrus to fatal to show the errors to user while listing containers
=> Changing from logrus to fatal in list

libcontainer/container_linux.go
=> Fix encoding gid mappings

utils.go
For things that depend or watch for this pid file to know when the
container is started we need to create this file atomically.
=> Create pid-file atomically

utils.go
@crosbymichael @LK4D4 I think it might be better to add a sync on this file as well.
=> Sync on the pid file to ensure the write is persisted

libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/container_linux.go, libcontainer/integration/exec_test.go, libcontainer/label/label_selinux_test.go, main_unsupported.go, tty.go, utils.go
Signed-off-by: Jessica Frazelle <acidburn@docker.com>
=> remove deadcode

man/runc-spec.8.md, man/runc-start.8.md, spec.go, start.go
=> adds detail to runc start and spec help text

libcontainer/cgroups/fs/apply_raw.go
=> Add more information in the error messages when writing to a file

libcontainer/cgroups/fs/memory_test.go
=> Fix the kmem TCP test

libcontainer/factory_linux.go, libcontainer/process_linux.go
@crosbymichael @mlaventure 
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
=> Show proper error from init process panic

libcontainer/README.md
Just a few alterations to make the example compile.
=> Fix libcontainer README.md example config

libcontainer/nsenter/nsexec.c
=> Refactor nsexec.c and add some comments

libcontainer/nsenter/nsenter_test.go
Fixes #692
Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>
=> Fix hanging tests when run without root

delete.go
If runc was SIGKILL'd or something happened and the container was not
able to start and runc died as well then we could get into the state
where `$root/<containerid>` exists but `$root/<containerid>/state.json`
does not.  This will not allow libcontainer to load the container to
call the delete function as it has no data on the container other than
its id.  We should just remove it in runc so that that system matches
what runc sees for the container.
=> Remove container root dir from an aborted start

libcontainer/configs/validate/config.go
=> Return a more meaningful error when namespaces are disabled

libcontainer/specconv/spec_linux.go
=> Fixup incorrect package name in a comment

libcontainer/README.md
Adding signal interaction with container in README
=> Updating README with container signal interaction

libcontainer/selinux/selinux.go
=> Synchronize writes to mcs map

libcontainer/selinux/selinux.go
=> Fix broken build due to missing import

libcontainer/configs/config_test.go
This PR only adds unit tests to config.Hooks.
=> Add unit tests for configs.Hooks

libcontainer/utils/utils_test.go
This PR doesn't add any new behaviour, but adds unit tests.
cc: @cloudfoundry/cf-garden
=> Add unit tests for the utils package

README.md
=> README.md: simplify Docker image example

README.md
Signed-off-by: Jonathan Boulle <jonathanboulle@gmail.com>
=> Fix OCI reference in README

man/runc-start.8.md
Added the start options for subreaper and pivot.
=> updating man page for start option

list.go, man/runc-list.8.md
=> Add -q to list to print only container IDs

man/runc-spec.8.md, spec.go
=> Add infomation about ocitools in runc spec

libcontainer/configs/validate/validator_test.go
Changing to /proc/kcore instead of kcores
=> Updating kcore in validator test

Makefile
=> Add target man in Makefile

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/config.go, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/version.go, libcontainer/specconv/spec_linux.go
=> Bump up spec and add support for mount label

main.go, ps.go
=> Add ps command

tests/integration/events.bats
=> Fix integration test for events

tests/integration/spec.bats
=> Change specs to runtime-spec in integration test

libcontainer/rootfs_linux.go
=> Need to make sure labels applied to /dev

main.go, man/runc.8.md
=> Change OCF to OCI in help string and man page.

man/runc-update.8.md, update.go
=> Add man page and fix typo for update command

man/runc-update.8.md, tests/integration/update.bats, update.go
Adding kernel mem tcp limits for update command
rajasec79@gmail.com
=> Adding kernel mem tcp for update command

man/runc.8.md
Update man page for runc commands
=> Updating runc man page

libcontainer/nsenter/README.md
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>
=> Update nsenter README

libcontainer/container_linux.go
=> Add comments for error cases in status functions

script/check-config.sh
It copied from docker and removed unnecessary configs.
Closes: https://github.com/opencontainers/runc/issues/819
=> Add check_config.sh for runc

libcontainer/SPEC.md
Updated wait description in SPEC.md
=> Updated description in SPEC

libcontainer/container.go
Signed-off-by: Bhanu Valasa <valasabk@yahoo.com>
=> libcontainer: Fix Running Comment

libcontainer/nsenter/README.md, man/runc-spec.8.md, spec.go
infomation -> information
transfered -> transferred
=> Fix some spelling typo in manual

Makefile, contrib/completions/bash/runc
I have taken the docker command completions code and reworked it for runc
support.
=> Add bash completion support

checkpoint.go, libcontainer/container_linux.go
For example:
./runc checkpoint --empty-ns network CTID
In this case criu creates a network namespace, but doesn't restore it.
We are going to use this option to restore docker containers and
Docker sets a hook to restore a network namespace.
https://github.com/xemul/criu/issues/165
Cc: @boucher
=> checkpoint: add the empty-ns option

libcontainer/README.md
=> README: Destroy container before fatal

tests/integration/update.bats, update.go
Support update memory with:
runc update --memory 50M container-id
=> Improve update memory

contrib/completions/bash/runc
Adding the bash completion step for update command
=> bash completion step for update command

libcontainer/README.md
Updating README to include set interface for updating resource constraints
=> Updating README with set interface

ps.go
The code is called in both cases so remove the duplicate one.
Signed-off-by: Hushan Jia <hushan.jia@gmail.com>
=> cleanup ps.go

README.md, main.go, spec.go, tests/integration/README.md
README to include the latest changes for running the container
=> Updating README for starting the container

README.md
=> readme: Mention the go 1.6 requirement in the README for building runc

README.md
=> Update readme for create start

list.go, man/runc-list.8.md
=> Use cli default value for list format

libcontainer/cgroups/utils.go, libcontainer/cgroups/utils_test.go
Prior to this change, a cgroup with a `:` character in its path was not parsed correctly.
See https://github.com/kubernetes/kubernetes/issues/26903 for discussion of an issue where this actually caused a problem.
Happy to add more test cases if desired. 
cc @philips
=> cgroups: Fix issue if cgroup path contains :

tests/integration/start_detached.bats, tests/integration/start_hello.bats
This is a very important testcase, as certain permission issues can
arise if we don't test this automatically.
=> tests: add tests with {u,g}id != 0

Makefile
=> Use git branch name as tag when building images

libcontainer/factory_linux.go, utils_linux.go
Added a helper func to set CriuPath for LinuxFactory.
Signed-off-by: Yang Hongyang <imhy.yang@gmail.com>
=> libcontainer: Add a helper func to set CriuPath

libcontainer/specconv/spec_linux_test.go
Just a typo that I found when browsing the code.
=> Fixed typo in build constraint.

list.go, man/runc-list.8.md
Follow up https://github.com/opencontainers/runc/pull/939
=> Add runc list man change

libcontainer/system/sysconfig.go
=> Cleanup GetLongBit

libcontainer/rootfs_linux.go
Signed-off-by: Haiyan Meng <haiyanalady@gmail.com>
=> Fix the err info of mount failure

libcontainer/configs/config.go
It's possible that `cmd.Process` is still nil when we reach timeout.
Start creates `Process` field synchronously, and there is no way to such
race.
Encountered in https://jenkins.dockerproject.org/job/runc-PRs/2004/console
=> libcontainer/configs: make hooks run safer

libcontainer/nsenter/nsexec.c
Without this build is broken on Fedora
@cyphar @LK4D4 @crosbymichael PTAL
=> Fix format specifier for size_t

libcontainer/cgroups/fs/apply_raw.go
=> Fix race condition when using cgroups.Paths

libcontainer/container.go, libcontainer/container_linux.go
Updated the libcontainer interface comments as per error code
=> Updated the libcontainer interface comments

README.md
Signed-off-by: Jonathan Boulle <jonathanboulle@gmail.com>
=> Fix runtime-spec repository reference in README

libcontainer/specconv/spec_linux.go
=> Fix null point reference panic

contrib/completions/bash/runc
Adding bash completion for create and run commands.
Updated the start command (there is no sub options/arguments associated with start command)
=> Adding bash completion for create and run

events.go
Removing fatal error from events in stopped state
=> Removing fatal error from events in stopped state

Dockerfile
=> Update golang to 1.7.1

tests/integration/update.bats
=> Fix update cpuset on single processor box

tests/integration/help.bats
=> remove duplicate test command on integration

list.go, state.go, tests/integration/list.bats
=> Use same state object for state and list

delete.go
This patch enhance the `runc delete` command as following
1) when `runc delete` without one container-id
```
runc: "delete" requires a minimum of 1 argument
```
2) we can delete more containers at one command
for example:
```
ID          PID         STATUS      BUNDLE         CREATED
a           8490        created     /mycontainer   2016-09-18T03:49:32.259760434Z
b           8520        running     /mycontainer   2016-09-18T03:49:36.999299944Z
c           8535        created     /mycontainer   2016-09-18T03:49:40.975277538Z
d           8549        created     /mycontainer   2016-09-18T03:49:42.675282602Z
e           8562        running     /mycontainer   2016-09-18T03:49:44.175400931Z
cannot delete container b that is not stopped: running
container cc is not exist
ID          PID …
```
=> enhance runc delete command

libcontainer/error_test.go
=> [unittest] add extra ErrorCode in TestErrorCode testcase

libcontainer/README.md
Updated the README file for container start.
=> Updating libcontainer README for container run

libcontainer/user/user_test.go, libcontainer/utils/utils.go
=> Fix TestGetAdditionalGroups on i686

tests/integration/ps.bats
=> Add integration test for ps command

ps.go
This reverts commit 067ce21f7aaf9b2fc4a8af890e00eb0966b22ef1.
=> Revert "simplify ps command"

delete.go
=> Delete: exit with non zero if one of the containers encountered an error

libcontainer/process_linux.go
=> just fix a typo

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/configs/cgroup_unix.go, libcontainer/console_linux.go, libcontainer/console_windows.go, libcontainer/container.go, libcontainer/process_linux.go, libcontainer/rootfs_linux.go, libcontainer/standard_init_linux.go, utils.go
pipe the source through https://github.com/client9/misspell. typos be gone!
=> fix typos with misspell

Dockerfile
=> remove /tmp/bats from dev_runc

libcontainer/specconv/spec_linux.go
=> tiny fix, add a null check for specs.Resources.Pids.Limit

libcontainer/state_linux.go, utils_linux.go
Some tiny refactor, no function change.
=> Some refactor and cleanup

tests/integration/list.bats
This patch add test `-q` option for list command.
=> add test cases for list command

delete.go, pause.go, start.go
Signed-off-by: allencloud <allen.sun@daocloud.io>
=> fix nits in stderr log

contrib/completions/bash/runc
Updating bash completion for ps command.
=> Updating bash completion for ps command

man/runc-delete.8.md
Changed the status of container from destroyed to stopped in man page.
Signed-off-by: rajasec rajasec79@gmail.com
=> man page update for delete command

libcontainer/utils/utils_test.go
small correction in util error messages
Signed-off-by: rajasec rajasec79@gmail.com
=> Correction in util error messages

man/runc-update.8.md, update.go
Usage correction in update resource json file format. 
Signed-off-by: rajasec rajasec79@gmail.com
=> Small correction in update resource file usage

libcontainer/configs/validate/validator.go, utils_linux.go
Signed-off-by: Qiang Huang h.huangqiang@huawei.com
=> Unify rootfs validation

libcontainer/README.md
Updated README file to add the container state & status API interaction
Signed-off-by: rajasec rajasec79@gmail.com
=> Updating container state and status API in README

libcontainer/process_linux.go
fix typo.
@hqhq PTAL
Signed-off-by: HaoZhang <crazykev@zju.edu.cn>
=> fix error message

tests/integration/help.bats
Adding update command in help-bats.
=> Adding update command in help-bats

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/go-systemd/activation/listeners.go, Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/dbus.go, Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods.go, Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/properties.go, Godeps/_workspace/src/github.com/coreos/go-systemd/util/util.go, Godeps/_workspace/src/github.com/coreos/go-systemd/util/util_cgo.go, Godeps/_workspace/src/github.com/coreos/go-systemd/util/util_stub.go, Godeps/_workspace/src/github.com/coreos/pkg/LICENSE, Godeps/_workspace/src/github.com/coreos/pkg/NOTICE, Godeps/_workspace/src/github.com/coreos/pkg/dlopen/dlopen.go, Godeps/_workspace/src/github.com/coreos/pkg/dlopen/dlopen_example.go
This improves the reliability of the dbus connection.
=> godeps: update go-systemd to v14

libcontainer/console.go
=> tiny refactor

Makefile
=> delete unused variable

CONTRIBUTING.md, README.md
=> *: add information about security mailing list

Dockerfile
Signed-off-by: Michal Rostecki <michal@kinvolk.io>
=> Clean apt archives and source directories in Dockerfile

man/runc-spec.8.md, spec.go
=> rename ocitools to oci-runtime-tool

README.md
Add badge for Go Report Card and move the badges down to allow more room for future badges.
Signed-off-by: Xianglin Gao <xlgao@zju.edu.cn>
=> Add badge for Go Report Card

delete.go, restore.go, utils_linux.go
=> Fix error shadow and error check warnings

spec.go
=> Remove unused code and unnecessary conversion

exec.go, ps.go, tty.go, update.go, utils.go
=> Simplify error handling on function return

libcontainer/cgroups/cgroups.go
=> cgroups: update the comments

libcontainer/error.go
=> Fix the outdated comment for Error interface

Dockerfile
=> Bump golang to 1.7.4

events.go, libcontainer/selinux/selinux.go, rlimit_linux.go
Signed-off-by: yupeng <yu.peng36@zte.com.cn>
=> fix typos by the result of golint checking 

kill.go, utils.go
=> kill: requires max 2 arguments

libcontainer/rootfs_linux.go
=> Small cleanup

libcontainer/rootfs_linux.go, libcontainer/specconv/spec_linux.go
=> support create device with type p and u

ps.go
command ps: value of the option --format should be one of table or json.(default: table)
Signed-off-by: CuiHaozhi <cuihaozhi@chinacloud.com.cn>
=> ps: --format value check

libcontainer/container_linux.go, libcontainer/factory_linux.go
=> Fix state when _LIBCONTAINER in environment

man/runc-ps.8.md
small cleanup for `runc ps` man pages.
Signed-off-by: CuiHaozhi <cuihaozhi@chinacloud.com.cn>
=> small cleanup for `runc ps` man pages

libcontainer/cgroups/fs/memory.go
Fixes: #1347
Fixes: #1083
The root cause of #1083 is because we're joining an
existed cgroup whose kmem accouting is not initialized,
and it has child cgroup or tasks in it.
Fix it by checking if the cgroup is first time created,
and we should enable kmem accouting if the cgroup is
craeted by libcontainer with or without kmem limit
configed. Otherwise we'll get issue like #1347
=> Fix kmem accouting when use with cgroupsPath

libcontainer/cgroups/systemd/apply_systemd.go
=> Remove unused function in systemd cgroup

contrib/cmd/recvtty/recvtty.go, libcontainer/console.go, libcontainer/console_linux.go, libcontainer/container_linux.go, libcontainer/factory_linux.go, libcontainer/init_linux.go, libcontainer/integration/execin_test.go, libcontainer/process.go, libcontainer/process_linux.go, libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go, libcontainer/sync.go, libcontainer/utils/utils_unix.go, restore.go, tty.go, utils_linux.go
=> Add separate console socket

libcontainer/factory.go
could load a stopped container without error.
Signed-off-by: CuiHaozhi <cuihz@wise2c.com>
=> could load a stopped container.

README.md
=> Update examples on README to allow rootless execution

man/runc-update.8.md
update man pages for `runc update`
supplement to [pr1423](https://github.com/opencontainers/runc/pull/1423)
Signed-off-by: CuiHaozhi <cuihz@wise2c.com>
=> update man page for `runc  update`

libcontainer/rootfs_linux.go
=> Fix comments about when to pivot_root

libcontainer/state_linux_test.go
Signed-off-by: chchliang <chen.chuanliang@zte.com.cn>
=> add createdState and runningState status testcase

exec.go, libcontainer/specconv/example.go, libcontainer/specconv/spec_linux.go, spec.go, tests/integration/update.bats, update.go, utils_linux.go, vendor.conf, vendor/github.com/opencontainers/runtime-spec/README.md, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
This provides updates to runc for the spec changes with *Process and
OOMScoreAdj
=> Update spec to 239c4e44f2a612ed85f6db9c66247aa33f4

libcontainer/keys/keyctl.go
Use KeyctlJoinSessionKeyring, KeyctlString and KeyctlSetperm from
golang.org/x/sys/unix instead of manually reimplementing them.
=> Use keyctl wrappers from x/sys/unix

Makefile
The "go build -i" invocation may slightly help with incremental
recompilation, but it will cause builds to fail if $GOROOT is not
writeable by the current user. While this does appear to work sometimes,
it's a concern for external build systems where "-i" causes build errors
for no real gain.
Given the size of the runc project, --install is not really giving us
much anyway.
=> makefile: drop usage of --install

libcontainer/specconv/spec_linux.go
=> Fixes #1585 config.Namespaces is empty when accessed

libcontainer/specconv/example.go, spec.go
Signed-off-by: Xiaobing Jiang <s7v7nislands@gmail.com>
=> Delete unused function

libcontainer/container_linux.go, libcontainer/init_linux.go, libcontainer/keys/keyctl.go
Generated using github.com/mdempsky/unconvert
=> libcontainer: remove unnecessary type conversions

libcontainer/specconv/spec_linux.go
=> support unbindable,runbindable for rootfs propagation

Makefile, libcontainer/nsenter/nsexec.c, script/validate-c
Options for `indent` are taken from https://github.com/opencontainers/runc/pull/950#discussion_r71268646
@cyphar PTAL?
=> make: validate C format

README.md
Trying this again... so very hard...
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>
=> adding go get instruction to readme

Makefile
This just makes it nicer to do "make release" if you have to do builds
for more than one release.
=> makefile: make "release" PHONY

README.md
Clarifying a bit the explanation why fine-grained control is benefitial.
=> Minor wording enhancement in readme

libcontainer/rootfs_linux.go
move variable close to where is used
Signed-off-by: Bin Chen <nk@devicu.com>
=> libcontainer/rootfs_linux: minor cleanup

libcontainer/cgroups/fs/apply_raw.go
Include a rootless argument for isIgnorableError to avoid people
accidentally using isIgnorableError when they shouldn't (we don't ignore
any errors when running as root as that really isn't safe).
=> cgroup: clean up isIgnorableError for skippable EROFS

libcontainer/rootfs_linux.go
This reverts commit 1b27db67f13bccaaa325f8372069e15575988eb9.
Fixes #1866 
=> Revert "libcontainer/rootfs_linux: minor cleanup"

man/runc.8.md
=> Add --rootless option to man page

contrib/completions/bash/runc, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/fs/stats_util_test.go, libcontainer/cgroups/utils.go, libcontainer/container_linux_test.go, libcontainer/intelrdt/intelrdt.go, libcontainer/nsenter/nsexec.c, libcontainer/process_linux.go, libcontainer/stacktrace/capture_test.go, signals.go, tests/integration/events.bats, tests/integration/helpers.bash, tests/integration/update.bats, tty.go
=> doc: fix typo

libcontainer/nsenter/README.md
Corrected the content with up to date information.
=> Update outdated nsenter README content

libcontainer/init_linux.go
This is a regression from 06f789cf26774dd64cb2a9cc0b3c6a6ff832733b
when the user namespace was configured without a privileged helper.
To allow a single mapping in an user namespace, it is necessary to set
/proc/self/setgroups to "deny".
For a simple reproducer, the user namespace can be created with
"unshare -r".
=> rootless: fix running with /proc/self/setgroups set to deny

README.md
=> readme: add nokmem build tag

checkpoint.go, delete.go, kill.go, libcontainer/cgroups/fs/cpu.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/container_linux.go, libcontainer/init_linux.go, libcontainer/integration/exec_test.go, libcontainer/keys/keyctl.go, libcontainer/rootfs_linux.go, libcontainer/standard_init_linux.go, libcontainer/sync.go, notify_socket.go, pause.go, signals.go, spec.go
Applied various fixes as recommended by golint (mostly redundant `if`)
Signed-off-by: Dominik Süß <dominik@suess.wtf>
=> Various cleanups to address linter issues

tty.go
ec0d23a92ffe ("tty: close epollConsole on errors") fixed a significant
issue, but the cleanup was not ideal (especially if the function is
changed in future to add additional error conditions to those currently
present). Using the defer-named-error trick avoids this issue and makes
the code more readable.
Fixes #1895
=> tty: clean up epollConsole closing

libcontainer/cgroups/utils.go, libcontainer/intelrdt/intelrdt.go, man/runc-pause.8.md, man/runc-resume.8.md, pause.go
Fix some typos:
1. "Dont" to "Don't".
2. "identiy" to "identify".
=> Fix some typos

README.md
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
=> README: link to /org/security/

vendor.conf, vendor/github.com/seccomp/libseccomp-golang/seccomp.go, vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go, vendor/github.com/sirupsen/logrus/go.mod
Diff here: https://github.com/seccomp/libseccomp-golang/compare/1b506fc7c24e...v0.9.1
Fixes https://nvd.nist.gov/vuln/detail/CVE-2017-18367
=> Update dependency libseccomp-golang

Dockerfile
Seems to fix #2068 
cc @adrianreber
=> Bump CRIU to 3.12

libcontainer/devices/devices.go
Closes: #2093
Signed-off-by: Erik Sipsma <sipsma@amazon.com>
=> Skip searching /dev/.udev for device nodes.

libcontainer/cgroups/fs/io_v2.go
=> io_v2.go: remove blkio v1 code

README.md, SECURITY.md
Fixes https://github.com/opencontainers/runc/issues/2220
=> Fix path for security report line

libcontainer/cgroups/systemd/unified_hierarchy.go
Fix #2164 
Exchanged deprecated systemd resources with the appropriate for cgroupv2
Signed-off-by: Boris Popovschi <zyqsempai@mail.ru>
=> Exchange deprecated systemd resources with the appropriate for cgroupv2

libcontainer/cgroups/fs2/io.go, libcontainer/cgroups/utils.go
Fix #2211 
Properly convert blkioWeight to io.weight
Signed-off-by: Boris Popovschi <zyqsempai@mail.ru>
=> Convert blkioWeight to io.weight properly

libcontainer/container_linux.go, libcontainer/state_linux.go
Hey, I'm not sure if this kind of optimization is welcome but during my investigations I came across some unreachable code paths. I took the liberty to remove them. WDYT?
=> Remove unreachable code paths

libcontainer/sync.go
Type comparatin not work correct, it need to be outside of the error check.
=> fix readSync

libcontainer/cgroups/systemd/unified_hierarchy.go, libcontainer/cgroups/utils.go
This is a set of small cleanups and fixes for cgroup v2 unified hierarchy + systemd. Please see individual commits for descriptions.
@AkihiroSuda PTAL
=> cgroup v2 cleanups

libcontainer/cgroups/fs2/fs2.go, libcontainer/cgroups/fs2/hugetlb.go
Added support for new introduced HugeTlb controller https://www.spinics.net/lists/cgroups/msg24003.html
Signed-off-by: Boris Popovschi <zyqsempai@mail.ru>
=> Added HugeTlb controller for cgroupv2

README.md
=> README.md: update Go version to build

libcontainer/cgroups/utils.go
=> libcontainer: remove unneeded import

Makefile
No functional change, just readability/maintainability improvements.
=> Makefile nits

libcontainer/cgroups/fs2/devices.go
In this case we just do not install any eBPF rules
checking the devices.
=> cgroupv2: allow to set EnableAllDevices=true

libcontainer/specconv/spec_linux.go
A strange behavior when we use runc directly(with file system cgroup v2).
With `busybox` rootfs, and the `config.json` is like this:
```
{
"ociVersion": "1.0.2",
"process": {
"terminal": false,
...
"args": [
"sleep", "100000"
],
...
},
...
"linux": {
...
"resources": {
},
...
}
```
For this `config.json`, there is nothing in `resources` section.
when we run `runc run -d test`. It works fine.
But if we remove the `resources` section, when we run `runc run -d test`:
```
root@bogon runctest]# runc run -d test
WARN[0000] exit status 1                                
ERRO[0000] container_linux.go:349: starting container process caused "process_linux.go:439: container init caused \"rootfs_linux.go:114: reopening /dev/null inside container caused \\\"Failed to open /dev/null - open /dev/null: …
```
=> cgroupv2: use default allowed devices when linux resources is null

libcontainer/system/linux.go
Made similar changes in containerd, so thought I'd do the same here.
FWIW; perhaps we could use a sync.once on `CurrentProcessUIDMap` and `CurrentProcessGIDMap` which do the actual reading and parsing, but I wasn't sure if there would be situations where we needed to retry those if they failed (open to suggestions there)
=> libcontainer: RunningInUserNS() use sync.Once

go.mod, go.sum, libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go, vendor/modules.txt
full diff: https://github.com/opencontainers/selinux/v1.4.0...v1.5.1
=> vendor: opencontainers/selinux v1.5.1, update deprecated uses

go.mod, go.sum, libcontainer/configs/config.go, libcontainer/integration/seccomp_test.go, libcontainer/seccomp/seccomp_linux.go, libcontainer/specconv/spec_linux.go, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/version.go, vendor/modules.txt
=> libcontainer: honor seccomp errnoRet

README.md
https://master.bestpractices.coreinfrastructure.org/projects/588
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add CII Badge to README

Dockerfile
... in case we have more than one CPU, that is.
=> Dockerfile: speed up criu build

libcontainer/cgroups/systemd/v1.go
This is a regression from commit 1d4ccc8e0 (PR #2343). We only need to enable
kernel memory accounting once, from the `(*legacyManager).Apply()`,
and there is no need to do it in `(*legacyManager).Set()`.
While at it, rename the method to better reflect what it's doing.
This saves us 1 call to mountinfo parser.
=> cgroupv1/systemd.Set: don't enable kernel memory acct

libcontainer/cgroups/fs/cpuacct.go, libcontainer/cgroups/fs/cpuacct_test.go
Signed-off-by: Katarzyna Kujawa <katarzyna.kujawa@intel.com>
=> Fix #2440 omit cpuacct.usage_all when not available

libcontainer/container_linux.go
=> Write state.json atomically

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go
Signed-off-by: Katarzyna Kujawa <katarzyna.kujawa@intel.com>
=> Fix #2469 omit memory.numa_stat when not available

libcontainer/configs/device.go, libcontainer/configs/device_unix.go, libcontainer/configs/device_windows.go
=> Allow libcontainer/configs to be imported on Windows

ps.go
Signed-off-by: Xiaoyu Zhang mateuszhang@tencent.com
=> fix small typo

libcontainer/rootfs_linux.go
Signed-off-by: Xiaodong Liu <liuxiaodong@loongson.cn>
=> remove redundant parameter of chroot function

utils_linux.go
Signed-off-by: Jeff Zvier <zvier20@gmail.com>
=> cleancode: clean code for utils_linux.go

checkpoint.go, libcontainer/criu_opts_linux.go
Signed-off-by: liuxiaodong <liuxiaodong@loongson.cn>
=> use criu cgroup mode const from go-criu

libcontainer/container_linux.go
This is a followup to #2525 to address a couple of very minor nits.
@adrianreber PTAL
=> external pidns c/r code nits

libcontainer/configs/config.go, libcontainer/rootfs_linux.go, libcontainer/specconv/spec_linux.go, tests/integration/umask.bats
Add support for umask and vendor in new runtime-spec
Signed-off-by: Ashley Cui <acui@redhat.com>
=> Add support for umask

tests/integration/dev.bats
Fixes #2249 
Signed-off-by: Eduardo Vega <edvegavalerio@gmail.com>
=> Add integration tests for cgroup devices

contrib/cmd/recvtty/recvtty.go, libcontainer/apparmor/apparmor.go, libcontainer/cgroups/ebpf/devicefilter/devicefilter.go, libcontainer/cgroups/systemd/common.go, libcontainer/configs/namespaces_linux.go, libcontainer/container_linux.go, libcontainer/integration/exec_test.go, libcontainer/setns_init_linux.go, libcontainer/specconv/spec_linux.go, libcontainer/standard_init_linux.go, libcontainer/system/proc.go, libcontainer/user/lookup_windows.go, libcontainer/utils/utils_test.go, main.go, notify_socket.go, utils_linux.go
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
=> use string-concatenation instead of sprintf for simple cases

libcontainer/specconv/spec_linux.go
=> libcontainer: remove the unused variable from spec

libcontainer/configs/config_linux_test.go
loadConfig() is the unused function now.
=> libcontainer: remove loadConfig which is the unused function

go.mod, go.sum, libcontainer/factory_linux_test.go, libcontainer/intelrdt/intelrdt.go, libcontainer/rootfs_linux.go, vendor/github.com/moby/sys/mountinfo/doc.go, vendor/github.com/moby/sys/mountinfo/mounted_unix.go, vendor/github.com/moby/sys/mountinfo/mountinfo.go, vendor/github.com/moby/sys/mountinfo/mountinfo_bsd.go, vendor/github.com/moby/sys/mountinfo/mountinfo_filters.go, vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go, vendor/github.com/moby/sys/mountinfo/mountinfo_unsupported.go, vendor/github.com/moby/sys/mountinfo/mountinfo_windows.go, vendor/modules.txt
It contains some breaking changes, so fix the code.
=> vendor: bump mountinfo v0.3.1

contrib/completions/bash/runc
This commit supports below capabilities.
* CAP_BPF
* CAP_CHECKPOINT_RESTORE
* CAP_PERFMON
=> Update bash completion to support new capabilities

libcontainer/cgroups/fs2/devices.go, libcontainer/cgroups/fscommon/fscommon_test.go, libcontainer/cgroups/systemd/common.go
Fix some typos about libcontainer :)
https://github.com/opencontainers/runc/blob/master/CONTRIBUTING.md#pull-requests-are-always-welcome
=> Fix some typos about libcontainer

libcontainer/cgroups/fs/blkio.go, libcontainer/cgroups/fs/blkio_test.go
Updates blkio GetStats, as proposed in [2365](https://github.com/opencontainers/runc/issues/2365)
Signed-off-by: Piotr Wagner <piotr.wagner@intel.com>
=> Update blkio GetStats

libcontainer/integration/execin_test.go
This helps to debug https://github.com/opencontainers/runc/issues/2425
=> libct/int/execin_tty: help debug a flake

libcontainer/configs/validate/validator.go, libcontainer/configs/validate/validator_test.go
In case nsfs mount (such as /run/docker/netns/xxxx) is provided as
the netns path, the current way of determining whether path is of
host netns or not is not working.
The proper way to check is to do stat(2) and compare dev_t and
inode fields, which is what this commit does.
A test case is added and I have checked that it fails before and passes
after the fix.
While at it, optimize repeated check in case more than one net.*
sysctl is given and there is no error.
Fixes #2693
=> libct/configs/validate.sysctl: fix host netns check

events.go
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
=> events: simplify some conversion functions

libcontainer/apparmor/apparmor_linux.go
Fix #2801 (https://github.com/docker/for-linux/issues/1199)
Tested on Arch Linux with the following configuration
```console
[root@archlinux ~]# pacman -Q runc containerd docker linux
runc 1.0.0rc93-1
containerd 1.4.3-1
docker 1:20.10.3-1
linux 5.10.14.arch1-1
[root@archlinux ~]# cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-linux root=UUID=bd8aaf58-8735-4fd5-a0c1-804a998f8d57 rw net.ifnames=0 rootflags=compress-force=zstd apparmor=1 lsm=capability,lockdown,yama,bpf,apparmor
[root@archlinux ~]# cat /etc/docker/daemon.json
{
"runtimes": {
"runc-tmp": {
"path": "/tmp/runc"
}
}
}
[root@archlinux ~]# docker run -it --rm alpine
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: …
```
=> apparmor: try attr/apparmor/exec before attr/exec

libcontainer/factory_linux.go
Signed-off-by: Iceber Gu <wei.cai-nat@daocloud.io>
=> libcontainer: fix LinuxFactory comments

tests/integration/README.md
Signed-off-by: Iceber Gu <wei.cai-nat@daocloud.io>
=> fix integration tests README.md

libcontainer/README.md
Signed-off-by: Liang Zhou <zhoul110@chinatelecom.cn>
=> fix a typo

vendor/github.com/cilium/ebpf/link/cgroup.go, vendor/github.com/cilium/ebpf/link/iter.go, vendor/github.com/cilium/ebpf/link/kprobe.go, vendor/github.com/cilium/ebpf/link/link.go, vendor/github.com/cilium/ebpf/link/netns.go, vendor/github.com/cilium/ebpf/link/perf_event.go, vendor/github.com/cilium/ebpf/link/raw_tracepoint.go, vendor/github.com/cilium/ebpf/link/tracepoint.go
The current master branch does not build, running a `make vendor` fixes
this inconsistency.
=> Fix vendored dependencies

script/release.sh
This is an alternative to #2930. 
https://golang.org/cmd/go/#hdr-Build_and_test_caching says:
> If you have made changes to the C libraries on your system, you will
> need to clean the cache explicitly or else use the -a build flag
> (see 'go help build') to force rebuilding of packages that depend
> on the updated C libraries.
This means that:
1. We need to either `go clean -cache` or `go build -a` when building
the release binary. Adding `-a` seems less intrusive / more focused.
2. The check for existing `libseccomp.a` (added by commit d748280aa)
is no longer needed.
=> script/release.sh: add -a to force rebuild

MAINTAINERS
Signed-off-by: Michael Crosby <michael@thepasture.io>
=> update crosbymichael email

libcontainer/rootfs_linux.go
Signed-off-by: Kailun Qin <kailun.qin@intel.com>
=> libct/rootfs: consolidate utils imports

.cirrus.yml
Since commit 9f656dbb11c42 these conditions are not needed.
=> ci/cirrus: remove unused code

Dockerfile
For one thing, this should help PR #2862 (see https://github.com/opencontainers/runc/pull/2682/commits/a0e755efd86b5e474e4874c6c25ceb16bf4af30e#r684182923)
=> Dockerfile: switch to bullseye

libcontainer/factory_linux.go
if function returns error before WriteJSON defer, error will not be
printed out, so move this defer as early as possible and use logrus to
print out error if returns before it.
Signed-off-by: xiadanni <xiadanni1@huawei.com>
=> optimize log: move WriteJSON defer as early as possible

.github/workflows/validate.yml, contrib/cmd/seccompagent/seccompagent.go, contrib/cmd/seccompagent/unsupported.go
Update the linters, fix a minor issue found. See individual commits for details.
=> ci/gha: update golangci-lint to 1.42.1

go.mod, go.sum, libcontainer/cgroups/systemd/cpuset.go, vendor/github.com/bits-and-blooms/bitset/bitset.go, vendor/modules.txt
Cut down third party dependency.
=> libct/cg: replace bitset with std math/big library

libcontainer/init_linux.go, libcontainer/system/linux.go
It is now available from golang.org/x/sys/unix
(https://go-review.googlesource.com/c/sys/+/332029)
=> libcontainer/system: rm Prlimit

Vagrantfile.fedora
=> Vagrantfile.fedora: upgrade Fedora to 36

tests/integration/seccomp.bats
=> tests: enable seccomp default action tests on arm

.cirrus.yml
A partial backport of #3614 to 1.1 branch to fix CI. See the original PR for details.
=> [1.1] fix centos 7 CI

tests/integration/dev.bats, tests/integration/update.bats
Amends commit 98fe566c527479195ce3c ("runc: do not set inheritable capabilities").
=> tests/int: do not set inheritable capabilities

libcontainer/init_linux.go
ref #3612 the old comment is outdated
=> Fix comment of signalAllProcesses for process wait due to sigkill

libcontainer/README.md
Signed-off-by: yaozhenxiu <946666800@qq.com>
fix libcontainer example
=> fix libcontainer example

tests/integration/capabilities.bats
Signed-off-by: Alex Jia <ajia@redhat.com>
=> tests: add tests for capabilities

tests/integration/mounts.bats
This fixes a few issues with the recently added test case, including #3792. Please see individual commits for details.
Fixes:  #3792
=> Fix mount test

docs/spec-conformance.md, go.mod, go.sum, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/version.go, vendor/modules.txt
https://github.com/opencontainers/runtime-spec/releases/tag/v1.1.0-rc.3
=> go.mod: runtime-spec v1.1.0-rc.3

libcontainer/nsenter/nsexec.c
While testing this with old kernel versions and kernels that don't support idmap mounts for some of the filesystems used by a container, I realized we can throw a more clear errors.
Let's make it clear which syscall we are using, when it is not supported and when if the fs doesn't support idmap mounts, which path it is.
=> libct/nsenter: Show better errors for idmap mounts

docs/spec-conformance.md
Signed-off-by: Zheao Li <me@manjusaka.me>
=> Update feature status in docs

docs/spec-conformance.md, libcontainer/configs/config.go, libcontainer/configs/config_linux.go, libcontainer/init_linux.go, libcontainer/setns_init_linux.go, libcontainer/specconv/spec_linux.go, libcontainer/standard_init_linux.go, libcontainer/system/linux.go, tests/integration/personality.bats
=> carry #3126: linux: Support setting execution domain via linux personality

libcontainer/configs/validate/validator.go, libcontainer/configs/validate/validator_test.go
https://man7.org/linux/man-pages/man2/sched_setattr.2.html
=> fix scheduler validate

Makefile
Follow up of https://github.com/opencontainers/runc/pull/4174#issuecomment-1968738161
=> fix runc-dmz bin path error in Makefile

docs/systemd.md
=> Fix link to gvariant documentation in systemd docs.

tests/integration/helpers.bash, tests/integration/run.bats, tests/integration/selinux.bats
=> Misc tests/int cleanups

libcontainer/process.go, libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go, script/check-config.sh
Tiny nits needed after merging #4482 and #4448. Easy to review.
=> Post overlay addition and dmz removal nits

tests/integration/hooks_so.bats, tests/integration/tty.bats
Fix some shell code in tests/integration which always bothered me.
No functional change, a mere cleanup.
=> Misc nits to tests/integration

libcontainer/container_linux.go
_This is a backport of #4599 to release-1.2._
----
The previous logic caused runc to hang if CloseExecFrom returned an error, as the defer waiting on logsDone never finished as the parent process was never started (and it controls the closing of logsDone via it's logsPipe).
This moves the defer to after we have started the parent, with means all the logic related to managing the logsPipe should also be running.
(cherry picked from commit 7b26da9ee3abf274ac90b7bedcbf11c3df43127a)
=> [1.2] libcontainer: Prevent startup hang when CloseExecFrom errors

docs/spec-conformance.md
Update runtime-spec version from `v1.2.0` to `v1.2.1`.
=> doc: update spec-conformance.md

libcontainer/integration/exec_test.go, libcontainer/integration/execin_test.go, libcontainer/integration/utils_test.go, tests/integration/selinux.bats
Addressing some assorted minor issues in the code here and there.
- libct/int: add/use needUserNS helper
- tests/int/selinux: fix skip message
=> Misc CI nits

libcontainer/init_linux.go
There is no behavior change, it is just more readable to use -1 to mean don't touch this.
Please note that if the GID is not mapped in the userns, by using -1 for that no error is returned. We just avoid dealing with it completely, as we want here.
=> libct: Use chown(uid, -1) to not change the gid

libcontainer/init_linux.go, tests/integration/exec.bats, tests/integration/run.bats
Backport of #4693 to release-1.3.
----
Because we have to set a default HOME env for the current container user, so we should set it after we are in the jail of the container, or else we'll use host's /etc/passwd to get a wrong HOME value.
Fixes #4688.
=> [1.3] libct: we should set envs after we are in the jail of the container

CHANGELOG.md
This ports the 1.2.x changes to the changelog in main
=> CHANGELOG: Port 1.2.x changes

CHANGELOG.md
=> CHANGELOG: forward-port entries from 1.3.0

libcontainer/configs/validate/validator.go, libcontainer/configs/validate/validator_test.go
These sysctls are all per-userns (termed `ucounts` in the kernel code) are settable with CAP_SYS_RESOURCE in the user namespace.
(cherry picked from commit 70d88bc449535c0b87174034ecf013d405cf39fa)
=> [1.4] libcontainer/validator: allow setting user.* sysctls inside userns

libcontainer/process_linux.go
Hello maintainers,
This is my first ever PR to the project; I would like to understand the internals of containers.
Your feedback is much appreciated.
ba0b5e26 introduced a request function that handles two tasks:
- the exchanges with the request and response channels
- the closing of the request channel.
From 1.21, the closing of the request channel may be done with [`context.AfterFunc()`](https://pkg.go.dev/context#AfterFunc). Moreover, `context.AfterFunc()` is guaranteed to run once.
Suggested-by: @cyphar
=> libcontainer: switch `goCreateMountSources()` to `ctx.AfterFunc`

CHANGELOG.md
=> CHANGELOG: add v1.3.2 entry
