opencontainers/runc

.travis.yml
It looks like we missed this in 5930d5b42728 ("Remove shfmt"), which was
causing CI to break (since it looks like the repo has moved or something
like that). Since we're no longer using shfmt, drop it completely from
the repo.
=> travis: drop shfmt install

signals.go
Fixes a race that occurred very frequently in testing where the tty of
the container may be closed by the time that runc gets to sending
SIGWINCH. This failure mode is not fatal, but it would cause test
failures due to expected outputs not matching. On further review it
appears that the original addition of these checks in 4c5bf649d01e
("Check error return values") was actually not necessary, so partially
revert that change.
The particular failure mode this resolves would manifest as error logs
of the form:
time="2017-08-24T07:59:50Z" level=error msg="bad file descriptor"
Fixes: 4c5bf649d01e ("Check error return values")
Fixes #1571
=> signal: ignore tty.resize errors

events.go, libcontainer/SPEC.md, libcontainer/configs/config.go, libcontainer/configs/intelrdt.go, libcontainer/configs/validate/validator.go, libcontainer/container_linux.go, libcontainer/container_linux_test.go, libcontainer/factory_linux.go, libcontainer/factory_linux_test.go, libcontainer/intelrdt/intelrdt.go, libcontainer/intelrdt/intelrdt_test.go, libcontainer/intelrdt/stats.go, libcontainer/intelrdt/util_test.go, libcontainer/process_linux.go, libcontainer/specconv/spec_linux.go, libcontainer/state_linux.go, libcontainer/stats_linux.go, utils_linux.go
**v5 commits:**
4d2756c116315cd30b7ded82dfbb4bca78ceb627 libcontainer: add test cases for Intel RDT/CAT
692f6e1e27b2e4d38e1c9e0b463f7d1bfe3f7492 libcontainer: add support for Intel RDT/CAT in runc
af3b0d9dce34fb0e91c58d823d0ad48268b0f988 libcontainer/SPEC.md: add documentation for Intel RDT/CAT
**Changes in v5:**
Reworked code according to @crosbymichael and @hqhq's comments:
1. https://github.com/opencontainers/runc/pull/1279#issuecomment-319085278
2. https://github.com/opencontainers/runc/pull/1279#issuecomment-320008325
3. https://github.com/opencontainers/runc/pull/1279#issuecomment-319917615
- Obsoleted the design of "refactor resource manager interface": removed generic resourceManagers, isolated IntelRdt functions without touching cgroups code, removed the static map with static …
=> libcontainer: add support for Intel RDT/CAT in runc

libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go
This further reduces the number of syscalls that a user needs to enable
in their seccomp profile.
This mirrors the standard_init_linux.go seccomp code, which only applies
seccomp early if NoNewPrivileges is enabled. Otherwise it's done
immediately before execve to reduce the amount of syscalls necessary for
users to enable in their seccomp profiles.
=> init: delay seccomp application as late as possible

libcontainer/configs/validate/validator.go, libcontainer/container_linux_test.go, libcontainer/factory_linux.go, libcontainer/intelrdt/intelrdt.go, libcontainer/intelrdt/intelrdt_test.go, utils_linux.go
This is the follow-up PR of #1279 to fix remaining issues:
Use init() to avoid race condition in IsIntelRdtEnabled().
Add also rename some variables and functions.
=> libcontainer: intelrdt: use init() to avoid race condition

Dockerfile, Makefile, libcontainer/configs/validate/rootless.go, libcontainer/configs/validate/rootless_test.go, libcontainer/container_linux.go, libcontainer/factory_linux.go, libcontainer/init_linux.go, libcontainer/message_linux.go, libcontainer/nsenter/nsexec.c, main.go, man/runc.8.md, tests/integration/exec.bats, tests/integration/helpers.bash, tests/integration/spec.bats, tests/integration/start_detached.bats, tests/integration/start_hello.bats, tests/integration/tty.bats, tests/rootless.sh, utils_linux.go
Take advantage of the newuidmap/newgidmap tools to allow multiple users/groups to be mapped into the new user namespace in the rootless case.
This is what I've tried here (only the relevant bits showed for config.json):
```json
"args": [
"cat", "/proc/self/uid_map"
],
...
"uidMappings": [
{
"hostID": 1000,
"containerID": 0,
"size": 1
},
{
"hostID": 110000,
"containerID": 1,
"size": 255
}
],
"gidMappings": [
{
"hostID": 1000,
"containerID": 0,
"size": 1
}
],
```
```bash
$ whoami
gscrivano
$ grep ^gscrivano /etc/subuid
gscrivano:110000:65536
$ runc run foo
0       1000          1
1     110000        255
```
=> Support multiple users/groups mapped for the rootless case

Makefile
This fix adds `netgo` to tags for static build so that the following warning could be addressed:
```
/tmp/go-link-355596637/000000.o: In function `_cgo_b0c710f30cfd_C2func_getaddrinfo':
/tmp/go-build/net/_obj/cgo-gcc-prolog:46: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```
The above warning appears when building `make static` with go 1.9.
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
=> Use `netgo` for static build

libcontainer/cgroups/systemd/apply_nosystemd.go, libcontainer/cgroups/systemd/apply_systemd.go
This fix tries to address the warnings caused by static build with go 1.9. As systemd needs dlopen/dlclose, the following warnings will be generated for static build in go 1.9:
```
root@f4b077232050:/go/src/github.com/opencontainers/runc# make static
CGO_ENABLED=1 go build  -tags "seccomp cgo static_build" -ldflags "-w -extldflags -static -X main.gitCommit="1c81e2a794c6e26a4c650142ae8893c47f619764" -X main.version=1.0.0-rc4+dev " -o runc .
/tmp/go-link-113476657/000007.o: In function `_cgo_a5acef59ed3f_Cfunc_dlopen':
/tmp/go-build/github.com/opencontainers/runc/vendor/github.com/coreos/pkg/dlopen/_obj/cgo-gcc-prolog:76: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```
This fix disables systemd …
=> Disable systemd in static build

libcontainer/process_linux.go
This applies cgroups earlier for container creation before the init
process starts running and forking off any additional processes.
=> Apply cgroups earlier

libcontainer/specconv/spec_linux.go
The code in prepareRoot (https://github.com/opencontainers/runc/blob/e385f67a0e45fa1d8ef8154e2aea5128ea1d331b/libcontainer/rootfs_linux.go#L599-L605)
attempts to default the rootfs mount to `rslave`. However, since the spec
conversion has already defaulted it to `rprivate`, that code doesn't
actually ever do anything.
This changes the spec conversion code to accept "" and treat it as 0.
Implicitly, this makes rootfs propagation default to `rslave`, which is
a part of fixing the moby bug https://github.com/moby/moby/issues/34672
Alternate implementatoins include changing this defaulting to be
`rslave` and removing the defaulting code in prepareRoot, or skipping
the mapping entirely for "", but I think this change is the cleanest of
those options.
cc @cyphar, this is somewhat similar to …
=> libcontainer: default mount propagation correctly

libcontainer/container_linux.go, libcontainer/init_linux.go, libcontainer/process.go, tests/integration/tty.bats, utils_linux.go
Signed-off-by: Petar Petrov <pppepito86@gmail.com>
This commit hopefully resolves issue #1269, setting the initial console size for TTYs based on the ConsoleSize properties in the process spec.
Two thoughts about this PR that would be good to get feedback on: Firstly, the height and width are passed through as separate primitives and turned into a `term.WinSize` right before use. We weren't sure of the pros and cons of this approach vs the `term` package all the way up the stack, or the runtime-spec `Box` or even whether we should define another process config struct.
Secondly, the bats test would ideally read the master fd from the `$CONSOLE_SOCKET` and read output directly from a `runc exec` invocation calling `stty -a` but there seems to be no convention for doing this and working …
=> Set initial console size based on process spec

libcontainer/rootfs_linux.go, libcontainer/standard_init_linux.go
The benefit for doing this within runc is that it works well with
userns.
Actually, runc already does the same thing for mount points.
discussed in https://github.com/containerd/containerd/pull/1585 (cc @crosbymichael @estesp )
If this change is fine, I'll open a PR to runtime-spec correspondingly.
=> libcontainer: create Cwd when it does not exist

libcontainer/factory_linux.go, libcontainer/intelrdt/intelrdt.go, update.go
Add runc update command support for Intel RDT/CAT.
for example:
runc update --l3-cache-schema "L3:0=f;1=f" container-id
For more information about Intel Resource Director Technology (RDT)
and Cache Allocation Technology (CAT), please refer to #1279 
=> libcontainer: intelrdt: add update command support

libcontainer/cgroups/fs/freezer.go
This commit ensures we write the expected freezer cgroup state after
every state check, in case the state check does not give the expected
result. This can happen when a new task is created and prevents the
whole cgroup to be FROZEN, leaving the state into FREEZING instead.
This patch prevents the case of an infinite loop to happen.
Fixes https://github.com/opencontainers/runc/issues/1609
=> libcontainer: cgroups: Write freezer state after every state check

libcontainer/rootfs_linux.go
Using MS_PRIVATE meant that there was a race between the mount(2) and
the umount2(2) calls where runc inadvertently has a live reference to a
mountpoint that existed on the host (which the host cannot kill
implicitly through an unmount and peer sharing).
In particular, this means that if we have a devicemapper mountpoint and
the host is trying to delete the underlying device, the delete will fail
because it is "in use" during the race. While the race is _very_ small
(and libdm actually retries to avoid these sorts of cases) this appears
to manifest in various cases.
=> rootfs: switch ms_private remount of oldroot to ms_slave

.travis.yml, libcontainer/integration/seccomp_test.go, vendor.conf, vendor/github.com/seccomp/libseccomp-golang/README, vendor/github.com/seccomp/libseccomp-golang/seccomp.go, vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
A bug in Seccomp filter handling was recently identified in Moby related to handling of syscall arguments in Seccomp filters (https://github.com/moby/moby/issues/32714). The bug was in the `libseccomp-golang` bindings, and has been fixed there. This PR updates the bindings to include this fix, and provides integration tests to catch regressions in this behavior.
The minimum supported version of `libseccomp` is bumped from v2.1.0 to v2.2.0 by associated changes to the bindings. Support for v2.1.0 was never very good (some features had to be gated off because of a library bug), though it is still the version provided by a few major distributions. If this change is contentious, I can see about backing out the changes that require v2.2.0.
=> Update libseccomp-golang dependency for filter generation bugfix

libcontainer/container_linux.go, libcontainer/factory_linux.go
This allows runc to be used as a target for docker's reexec module that depends on a correct argv0 to select which process entrypoint to invoke. Without this patch, when runc re-execs argv0 is set to "/proc/self/exe" and the reexec module doesn't know what to do with it.
=> Propagate the correct argv0 when re-execing

exec.go, man/runc-exec.8.md, tests/integration/exec.bats
Closes #1307 
This is a carry of #1307
=> add additional-gids to runc exec

libcontainer/specconv/spec_linux.go
Due to the semantics of chroot(2) when it comes to mount namespaces, it
is not generally safe to use MS_PRIVATE as a mount propgation when using
chroot(2). The reason for this is that this effectively results in a set
of mount references being held by the chroot'd namespace which the
namespace cannot free. pivot_root(2) does not have this issue because
the @old_root can be unmounted by the process.
Ultimately, --no-pivot is not really necessary anymore as a commonly
used option since f8e6b5af5e12 ("rootfs: make pivot_root not use a
temporary directory") resolved the read-only issue. But if someone
really needs to use it, MS_PRIVATE is never a good idea.
Fixes #1602 
=> specconv: emit an error when using MS_PRIVATE with --no-pivot

libcontainer/intelrdt/intelrdt.go
This fixes a GetStats() issue introduced in #1590:
If Intel RDT is enabled by hardware and kernel, but intelRdt is not
specified in original config, GetStats() will return error unexpectedly
because we haven't called Apply() to create intelrdt group or attach
tasks for this container. As a result, runc events command will have no
output.
=> libcontainer: intelrdt: fix a GetStats() issue

libcontainer/integration/seccomp_test.go, libcontainer/seccomp/seccomp_linux.go
Multiple conditions were previously allowed to be placed upon the same syscall argument. My earlier patch #1424 fixed an issue in the Libseccomp bindings with conditional syscall matching, but this broke multiple conditions being placed upon the same argument. This patch restores the old behavior for rules which would be broken by the prior change.
Note that the prior behavior here is still not correct behavior - the conditions for these rules will still be logical-OR instead of logical-AND as they should be. I looked into generating rules that would act correctly, but that proved to be unreasonably complex in some cases.
I haven't added a warning for the badly-behaved profiles, though I am open to doing so.
=> Fix breaking change in Seccomp profile behavior

libcontainer/container_linux.go
Closes #1295
This is a carry of #1295 to run on the new tests again.
=> libcontainer: handler errors from terminate 

libcontainer/init_linux.go, tests/integration/tty.bats
Previously we weren't testing that detached io works properly -- which
will be quite important in the case for rootless containers.
=> tests: add various !terminal tests

libcontainer/specconv/spec_linux_test.go
The aim of this is to improve the current `specconv` testsuite so that edge cases are spotted early and future refactorings are easier.
This is a work in progress, opened the PR early so that I can take benefit of CI and comments.
Signed-off-by: Lorenzo Fontana <lo@linux.com>
=> WIP: Better testsuite for specconv

tests/integration/update.bats
Since the defined config.json contains kmem settings, the test will try
writing to memory.kmem.* and fail. Therefore, it needs to require
cgroups_kmem.
Signed-off-by: Thomas Hipp <thipp@suse.de>
=> tests: add missing cgroups_kmem requirement

libcontainer/specconv/spec_linux_test.go
Signed-off-by: Lorenzo Fontana <lo@linux.com>
=> Specconv: Test create command hooks and seccomp setup

libcontainer/integration/utils_test.go
When running runc tests with temp directory with size 500M, copying
busybox without preserving hardlinks causes the folder to inflate to
roughly 330M. Copying busybox twice in certain tests causes the /tmp
directory to overfill. Using `-a` preserves links which busybox uses to
implement its choice of binary to run.
Signed-off-by: Tom Godkin <tgodkin@pivotal.io>
=> Avoid disk usage explosion when copying busybox

libcontainer/specconv/example.go
Port over https://github.com/moby/moby/pull/35399
=> specconv.Example(): add /proc/scsi to masked paths

Dockerfile
Currently, unit test can't be done on arm64 platform
due to multi-arch issue.
Fix points:
golang:1.8.0 doesn't support arm64.
We use golang:1.8 to replace it.
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>
=> enable unit test on arm64 platform

.travis.yml
`tip` should point to 1.10 already ? (or soon-ish)
/cc @cyphar @crosbymichael @dqminh
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
=> Add build 1.9 to travis

libcontainer/cgroups/systemd/apply_systemd.go
xref https://bugzilla.redhat.com/show_bug.cgi?id=1509467#c6
@derekwaynecarr @jupierce @mrunalp
=> systemd: adjust CPUQuotaPerSecUSec to compensate for systemd internal handling

libcontainer/container_linux_test.go
TestGetContainerStateAfterUpdate creates its state.json file on the current
directory which turns out to be the host runc directory. Thus whenever
the test completes it leaves the state.json file behind thus
a) poluting the local git repository
b) changing the host file system violating the principle of doing
everything in an isolated container environment
This change would create a new temporary (in-container) directory and use it as
linuxContainer.root
Signed-off-by: Tom Godkin <tgodkin@pivotal.io>
=> Ensure container tests do not write on the host

checkpoint.go
Except created containers, stopped containers should also not be supported to be checkpointed
=> stopped container can't be checkpoint

libcontainer/specconv/spec_linux.go
=> specconv: avoid skipping gidmappings applied when uidmappings is empty

.travis.yml, README.md, libcontainer/apparmor/apparmor.go
libapparmor is integrated in libcontainer using cgo but is only used to
call a single function: aa_change_onexec. It turns out this function is
simple enough (writing a string to a file in /proc/<n>/attr/...) to be
re-implemented locally in libcontainer in plain Go.
This allows to drop the dependency on libapparmor and the corresponding
cgo integration.
Fixes #1674
=> RFC: libcontainer: remove dependency on libapparmor

libcontainer/init_linux.go, libcontainer/system/linux.go
When a subreaper is enabled, it might expect to reap a process and
retrieve its exit code. That's the reason why this patch is giving
the possibility to define the usage of a subreaper as a consumer of
libcontainer. Relying on this information, libcontainer will not
wait for signalled processes in case a subreaper has been set.
Fixes #1677
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
=> libcontainer: Do not wait for signalled processes if subreaper is set

libcontainer/cgroups/systemd/apply_systemd.go
- T0: runc triggers a systemd unit creation asynchronously from [here](https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/systemd/apply_systemd.go#L298)
- T1: runc then moves ahead and starts creating cgroup paths(.scope directories), [here](https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/systemd/apply_systemd.go#L348). Kernel creates .scope directory and cgroup.procs file(along with other default files) in the directory automatically, in an atomic manner.
- T3: systemd execution thread which was invoked at time `T0`, is still in the process of unit creation. systemd also trying to create cgroup paths and deletes the `.scope` directory which is created at time `T1` by runc from [here](https://github.com/systemd/systemd/blob/v219/src/shared/cgrou …
=> Fix race against systemd

tests/integration/spec.bats
Fixes #1680 (partially). This is suggested as a temporary fix to runc so that CI can go green and development can continue.
We will detail a potential problem we've found with opencontainers json schema validation in a email to the mailing list.
Signed-off-by: Will Martin <wmartin@pivotal.io>
=> Pin version of gojsonschema in tests

libcontainer/container_linux.go, libcontainer/process_linux.go, libcontainer/state_linux.go
Annotations weren't passed to hooks. This patch fixes that by passing
annotations to stdin for hooks.
Fix https://github.com/opencontainers/runc/issues/1686
/cc @mrunalp @FlorianOtel
=> libcontainer: expose annotations in hooks

libcontainer/container_linux.go
When starting a container with `runc start` or `runc run`, the stub
process (runc[2:INIT]) opens a fifo for writing. Its parent runc process
will open the same fifo for reading. In this way, they synchronize.
If the stub process exits at the wrong time, the parent runc process
will block forever.
This can happen when racing 2 runc operations against each other: `runc
run/start`, and `runc delete`. It could also happen for other reasons,
e.g. the kernel's OOM killer may select the stub process.
This commit resolves this race by racing the opening of the exec fifo
from the runc parent process against the stub process exiting. If the
stub process exits before we open the fifo, we return an error.
Another solution is to wait on the stub process. However, it seems it
would require more …
=> Avoid race when opening exec fifo

kill.go
... that prevent sending signals not mentioned in signal map.
Currently these are SIGRTMIN..SIGRTMAX.
Signed-off-by: Valentin Kulesh <valentin.kulesh@virtuozzo.com>
=> kill.go: Remove unnecessary checks

libcontainer/state_linux_test.go
The helper DRYs up the transition tests and makes it easy to get complete coverage for invalid transitions.
I'm also using `t.Run()` for subtests.  `Run()` is [new in Go 1.7][1], but runc dropped support for 1.6 back in e773f96b (#1335).
[1]: https://blog.golang.org/subtests
=> libcontainer/state_linux_test: Add a testTransitions helper

libcontainer/rootfs_linux.go, libcontainer/standard_init_linux.go
We shouldn't skip the rootfs code when NEWNS is not specified because it will place the process in the host's `/`, instead, perform a simple `chroot` so that the process is still placed inside the specified rootfs. 
=> chroot when no mount namespaces is provided

man/md2man-all.sh
If 'go-md2man' is not installed,
an error can occur when running md2man-all.sh like below:
```
$ ./man/md2man-all.sh -q
./man/md2man-all.sh: line 21: go-md2man: command not found
```
So fix it.
=> Warning message if 'go-md2man' is not yet installed

man/runc-create.8.md, man/runc-run.8.md
The commit 244c9fc ("*: console rewrite")
removed the --console option and the commit 7df64f8
("runc: implement --console-socket") create new option
--console-socket. However, the old --console option
still exists so fix it.
In addtion, add missing --preserve-fds option to
create and run manpages.
=> man: Fix manpages related to console

libcontainer/capabilities_linux.go, libcontainer/container_linux.go
gocapability has supported 0 as “the current PID” since syndtr/gocapability#2.  libcontainer was ported to that approach in 444cc298 (docker/libcontainer#358), but the change was clobbered by 22df5551 which landed via 5b73860e (docker/libcontainer#388).  This pull-request restores the changes from 444cc298.
=> libcontainer/capabilities_linux: Drop os.Getpid() call

libcontainer/cgroups/systemd/apply_systemd.go
As of now systemd slice expansion would result in strings with a suffix  "/" but we want "/" to be prefixed in kubernetes so that cAdvisor can read stats.
The only call to ExpandSlice function in runc seems to be happening from 
https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/systemd/apply_systemd.go#L449
which uses filepath.Join, so shouldn't cause a behavioural change.
xref: https://github.com/kubernetes/kubernetes/issues/59993
/cc @derekwaynecarr @sjenning 
Signed-off-by: ravisantoshgudimetla <ravisantoshgudimetla@gmail.com>
=> fix systemd slice expansion so that it could be consumed by cAdvisor

vendor.conf, vendor/github.com/containerd/console/tc_linux.go
This fixes a bug in the console package for big-endian architectures.
When creating a new pty the returned path to the new pty slave was
wrong for the second und all subsequent ptys.
In runc the exec subcommand failed with an runtime error such as
`container_linux.go:265: starting container process caused "open
/dev/pts/4294967296: no such file or directory"`.
The number is shifted by 32.
Signed-off-by: Peter Morjan <peter.morjan@de.ibm.com>
=> Update console dependency to fix runc exec on BE

libcontainer/specconv/example.go
When I open runC project with my vs code, the IDE automatically reports this error:
```
comment on exported function ToRootless should be the form of `ToRootless`...
```
Try to fix this lint error.
Signed-off-by: Allen Sun <allensun.shl@alibaba-inc.com>
=> fix lint error in specconv

libcontainer/specconv/spec_linux.go
The setupUserNamespace is always called even if the usernamespace is not set. This results having wrong uid/gid set on devices.
This fix add a test to check if usernamespace is set befor calling
setupUserNamespace.
Fixes #1742
Signed-off-by: Julien Lavesque <julien.lavesque@gmail.com>
=> libcontainer: setupUserNamespace is always called

Makefile
The "shell" rule in the Makefile uses docker to run a bash session,
however it was depending on the "all" rule which assumes non-docker local
development. This commit fixes it by making it depend on the "runcimage" rule.
=> Fix make shell

libcontainer/user/lookup.go, libcontainer/user/lookup_unix.go, libcontainer/user/lookup_windows.go, libcontainer/user/user.go
This rearranges a bit of the user and group lookup, such that only a
basic subset is exposed.
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
=> libcontainer/user: platform dependent calls

libcontainer/cgroups/fs/apply_raw.go
Currently Manager accepts nil cgroups when calling Apply, but it will panic then trying to call Destroy with the same config.
=> cgroups/fs: fix NPE on Destroy than no cgroups are set

libcontainer/cgroups/systemd/apply_systemd.go
This PR adds one second timeout for waiting on channel for `StartTransientUnit` completion signal.
This channel was introduced to avoid a rare race between systemd and runc where systemd could delete pids cgroup created by runc. https://github.com/opencontainers/runc/pull/1683
If for some reason signal is not received like the case [here](https://bugzilla.redhat.com/show_bug.cgi?id=1548358#c22), runc will hang forever. Adding a timeout will help recover in such a case.
In the timeout handling, we have two options either return Error or continue. Since originally purpose of introducing channel was to avoid the race mentioned above, one second time duration should be enough in ensuring the same and to continue seems a better option of the two.
/cc @derekwaynecarr @sjenning
=> Add timeout while waiting for StartTransinetUnit completion signal

libcontainer/rootfs_linux.go, libcontainer/standard_init_linux.go
Currently if a confined container process tries to list these directories
AVC's are generated because they are labeled with external labels.  Adding
the mountlabel will remove these AVC's.
=> Label the masked tmpfs with the mount label

Dockerfile, Makefile
CRIU needs to load a few modules to checkpoint/resume containers.
https://github.com/opencontainers/runc/issues/1745
=> tests: allow to load kernel modules from a test container

main.go
According to the XDG specification[1], in order to avoid the possibility of
our container states being auto-pruned every 6 hours we need to set the
sticky bit. Rather than handling all of the users of --root, we just
create the directory and set the sticky bit during detection, as it's
not expensive.
[1]: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
Fixes #1694
=> rootless: set sticky bit if using XDG_RUNTIME_DIR

libcontainer/container_linux.go
There is no reason to set the container state to "running" as a
temporary value when exec'ing a process on a container in "created"
state. The problem doing this is that consumers of the libcontainer
library might use it by keeping pointers in memory. In this case,
the container state will indicate that the container is running, which
is wrong, and this will end up with a failure on the next action
because the check for the container state transition will complain.
Fixes #1767
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
=> libcontainer: Don't set container state to running when exec'ing

libcontainer/cgroups/systemd/apply_systemd.go
The channel was introduced in #1683 to work around a race condition. However, the check for error in StartTransientUnit ignores the error for an already existing unit, and in that case there will be no notification from DBus (so waiting on the channel will make it hang.)
Later PR #1754 added a timeout, which worked around the issue, but we can fix this correctly by only waiting on the channel when there is no error. Fix the code to do so.
The timeout handling was kept, since there might be other cases where this situation occurs (the [bug entry at Red Hat's bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1548358) mentions calling this code from inside a container, it's unclear whether an existing container was in use or not, so not sure whether this would have fixed that bug as …
=> Fix systemd.Apply() to check for DBus error before waiting on a channel.

libcontainer/nsenter/nsexec.c
```
$ make BUILDTAGS="seccomp selinux"
go build -buildmode=pie  -ldflags "-X main.gitCommit="0e16bd9b53eb3c57ea6fe59fc6d9385c2edb9fd9" -X main.version=1.0.0-rc5+dev " -tags "seccomp selinux" -o runc .
nsexec.c: In function ‘join_namespaces’:
nsexec.c:508:3: warning: ‘strncpy’ specified bound 4096 equals destination size [-Wstringop-truncation]
strncpy(ns->path, path, PATH_MAX);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> nsexec.c: fix GCC 8 warning

libcontainer/specconv/spec_linux.go, notify_socket.go, tests/integration/mounts.bats
From the “Creating a bind mount” section of [`mount(2)`][1]:
> If mountflags includes MS_BIND (available since Linux 2.4), then perform a bind mount…
>
> The filesystemtype and data arguments are ignored.
This pull request adds support for configurations that leave the [OPTIONAL `type`][2] unset for bind mounts.  There's a related spec-example change in flight with opencontainers/runtime-spec#954, although my personal preference would be a more explicit spec for the whole mount structure (opencontainers/runtime-spec#771).
[1]: http://man7.org/linux/man-pages/man2/mount.2.html
[2]: https://github.com/opencontainers/runtime-spec/blame/v1.0.1/config.md#L102
=> libcontainer/specconv/spec_linux: Support empty 'type' for bind mounts

libcontainer/specconv/spec_linux.go, libcontainer/specconv/spec_linux_test.go
This function is useful for converting from the OCI spec format to the one used by runC/libcontainer.
Signed-off-by: dlorenc <lorenc.d@gmail.com>
=> Make the setupSeccomp function public.

libcontainer/nsenter/nsexec.c
nsenter: move namespace creation after userns creation
Technically, this change should not be necessary, as the kernel
documentation claims that if you call clone(flags|CLONE_NEWUSER), the
new user namespace will be the owner of all other namespaces created in
@ flags. Unfortunately this isn't always the case, due to various
additional semantics and kernel bugs.
One particular instance is SELinux, which acts very strangely towards
the IPC namespace and mqueue. If you unshare the IPC namespace *before*
you map a user in the user namespace, the IPC namespace's internal
kern-mount for mqueue will be labelled incorrectly and the container
won't be able to access it. The only way of solving this is to unshare
IPC *after* the user has been mapped and we have changed to that user.
I've also …
=> nsenter: improve namespace creation and SELinux IPC handling

libcontainer/init_linux.go, libcontainer/standard_init_linux.go
=> Wrap error messages during init

checkpoint.go, libcontainer/container_linux.go, libcontainer/system/linux.go, libcontainer/system/linux_test.go, libcontainer/system/unsupported.go, libcontainer/user/lookup_unix.go, libcontainer/user/user.go, main.go, ps.go, restore.go, utils.go, utils_linux.go
Running rootless containers in userns is useful for mounting
filesystems (e.g. overlay) with mapped euid 0, but without actual root
privilege.
Usage: (Note that `unshare --mount` requires `--map-root-user`)
```console
user$ mkdir lower upper work rootfs
user$ curl http://dl-cdn.alpinelinux.org/alpine/v3.7/releases/x86_64/alpine-minirootfs-3.7.0-x86_64.tar.gz | tar Cxz ./lower || ( true; echo "mknod errors were ignored" )
user$ unshare --mount --map-root-user
mappedroot# runc spec --rootless
mappedroot# sed -i 's/"readonly": true/"readonly": false/g' config.json
mappedroot# mount -t overlay -o lowerdir=./lower,upperdir=./upper,workdir=./work overlayfs ./rootfs
mappedroot# runc run foo
```
Note: unprivileged overlay is only supported in Ubuntu and a few distros …
=> main: support rootless mode in userns

exec.go, libcontainer/container_linux.go, libcontainer/integration/checkpoint_test.go, libcontainer/integration/exec_test.go, libcontainer/integration/execin_test.go, libcontainer/integration/seccomp_test.go, libcontainer/integration/utils_test.go, libcontainer/process.go, utils_linux.go
There is a race in runc exec when the init process stops just before
the check for the container status. It is then wrongly assumed that
we are trying to start an init process instead of an exec process.
=> Fix race in runc exec

libcontainer/configs/validate/rootless.go
When running in a new unserNS as root, don't require a mapping to be
present in the configuration file.  We are already skipping the test
for a new userns to be present.
=> runc: not require uid/gid mappings if euid()==0

libcontainer/system/linux.go, libcontainer/user/user.go
This fixes the following compilation error on 32bit ARM:
```
$ GOARCH=arm GOARCH=6 go build ./libcontainer/system/
libcontainer/system/linux.go:119:89: constant 4294967295 overflows int
```
Signed-off-by: Tibor Vass <tibor@docker.com>
Related to #1688
Fixes #1818
=> libcontainer: fix compilation on GOARCH=arm GOARM=6 (32 bits)

libcontainer/configs/validate/validator.go
These sysctls are namespaced by CLONE_NEWUTS, and we need to use
"kernel.domainname" if we want users to be able to set an NIS domainname
on Linux. However we disallow "kernel.hostname" because it would
conflict with the "hostname" field and cause confusion (but we include a
helpful message to make it clearer to the user).
=> libcontainer: improve "kernel.{domainname,hostname}" sysctl handling

docs/terminals.md
As discussed with @cyphar , a first attempt to document how to use terminals with runc. See discussion [here](https://github.com/opencontainers/runc/issues/1721) particularly [this comment](https://github.com/opencontainers/runc/issues/1721#issuecomment-366493547)
I am sure there are some errors here, so happy to take updates.
=> Add docs for terminals

.gitignore, .travis.yml, Dockerfile, Makefile
So as to avoid issues like https://github.com/opencontainers/runc/pull/1819
cc @tiborvass @andrewhsu
=> travis: test cross compilation

libcontainer/devices/devices.go
It turns out that MIPS uses uint32 in the device number returned by
stat(2), so explicitly wrap everything to make the compiler happy. I
really wish that Go had C-like numeric type promotion.
Fixes #1823
=> libcontainer: devices: fix mips builds

Makefile
This should fix the following (very legitimate) warnings on static build:
> /tmp/go-link-818454663/000019.o: In function `mygetgrouplist':
> /usr/lib/go-1.10/src/os/user/getgrouplist_unix.go:15: warning: Using
> 'getgrouplist' in statically linked applications requires at runtime the
> shared libraries from the glibc version used for linking
>
> /tmp/go-link-818454663/000018.o: In function `mygetgrgid_r':
> /usr/lib/go-1.10/src/os/user/cgo_lookup_unix.go:38: warning: Using
> 'getgrgid_r' in statically linked applications requires at runtime the
> shared libraries from the glibc version used for linking
>
> ...
as well as segfaults in the resulting binary.
For more details, check https://github.com/golang/go/issues/23265
=> Add osusergo flag to static build

tests/integration/checkpoint.bats
Upstream renamed the feature check for lazy migration support from
'lazy_pages' to 'uffd'. The lazy migration test case was therefore
not running at all. This enables the lazy migration test case in runc
again.
The test will, however, not run in travis as the kernel is too old.
But it works again locally.
Signed-off-by: Adrian Reber <areber@redhat.com>
=> criu tests: rename criu feature check

checkpoint.go
RunC doesn't manage network devices and their configurations,
so it is impossible to describe external dependencies to restore them
back.
This means that all users have to set --empty-ns network, so let's do
this by default.
Signed-off-by: Andrei Vagin <avagin@openvz.org>
=> cr: don't dump network devices and their configuration

Makefile, tests/integration/README.md
Currently, To pass argument "TESTFLAGS" for Makefile to execute "make test" is meaningless because TESTFLAGS is used in both localunittest and localintegration. So, this commit modifies Makefile to handle test targets for "unittest" and "integration" correctly.
=> Fix the problem TESTFLAGS is not to be used in Makefile correctly

libcontainer/container_linux.go
This will help runc's init to not spawn many threads on large systems when
launched with max procs by the caller.
=> Pass GOMAXPROCS to init processes

Dockerfile
For criu v3.10, a patch is needed for `@test "checkpoint --lazy-pages and restore"`.
Starting with v3.11, the patch will no longer be needed.
See https://github.com/opencontainers/runc/issues/1863#issuecomment-412074413
The issue had not been caught in Travis because the kernel is too old and the test
had not been executed in Travis.
=> Dockerfile: update criu to v3.10 + checkpoint-restore/criu@27034e7c

restore.go
since runc don't manage net device and their configuration, checkpoint
also don't dump net namespace by default, so set 'nsmask = unix.CLONE_NEWNET'
by default in restore. Or if user do not pass 'empty-ns network', criu will
cost extra time in restore.
=> cr: don't restore net namespace by default

README.md
This commit adds an explanation of TESTPATH for `make test`.
=> Add an explanation for TESTPATH

Makefile, README.md
Currently, `make test` cannot be executed in a proxy environment. This commit resolves it.
=> Add docker proxy settings for make test in a proxy environment

libcontainer/container_linux.go, tests/integration/checkpoint.bats
With the initial CRIU patches merged to support checkpointing and restoring a container into a external defined network namespace, these are the necessary runc changes to honour an external network namespace (something like ```"path": "/run/netns/test"```).
Details about the existing problem are described at https://github.com/opencontainers/runc/issues/1786
There are still two CRIU patches under review to complete CRIU's RPC interface which is used by runc.
Once all the necessary patches are merged and a new CRIU release is available with these patches the CRIU version in runc's travis test can be updated and from that point on the newly added test case in ```checkpoint.bats``` should be automatically activated. Currently it detects the missing CRIU functionality and is skipped. (@avagin …
=> Add support to checkpoint and restore into external network namespaces

libcontainer/rootfs_linux.go
MOVE_MOUNT will fail under certain situations.
You are not allowed to MS_MOVE if the parent directory is shared.
```
man mount
...
The move operation
Move a mounted tree to another place (atomically).  The call is:
mount --move olddir newdir
This  will cause the contents which previously appeared under olddir to
now be accessible under newdir.  The physical location of the files  is
not changed.  Note that olddir has to be a mountpoint.
Note  also that moving a mount residing under a shared mount is invalid
and unsupported.  Use findmnt -o TARGET,PROPAGATION to see the  current
propagation flags.
```
=> When doing a copyup, /tmp can not be a shared mount point

libcontainer/network_linux.go, libcontainer/utils/utils.go, libcontainer/utils/utils_test.go
Networking is setup by plugins for users of runc so it makes sense
to get rid of the veth strategy.
=> Remove unused veth setup code

libcontainer/rootfs_linux.go
Signed-off-by: JunLi <lijun.git@gmail.com>
=> libcontainer: add /proc/loadavg to the white list of bind mount

libcontainer/rootfs_linux.go, libcontainer/rootfs_linux_test.go
it is now allowed to bind mount /proc when the PID namespace is shared
with the host.
=> linux: drop check for /proc as invalid dest

libcontainer/factory_linux.go
Signed-off-by: Lifubang <lifubang@acmcoder.com>
There is a big bug which can delete files not belonging to the container when use runc delete --force.
Command history is:
/opt/runc/runcroot is ruc's root dir.
```
root@dockerdemo:/opt/runc# ls -lh
total 16K
drwxr-xr-x 2 root root 4.0K Aug 31 11:19 dbback
drwx------ 2 root root 4.0K Aug 31 10:49 runcroot
-rw-r--r-- 1 root root    5 Aug 31 11:19 test
-rw-r--r-- 1 root root    6 Aug 31 11:19 test1
```
While **dbback dir** have very important db backup files.
run two container:
```
root@dockerdemo:/opt/runctest/redis# runc --root /opt/runc/runcroot run -d redis
root@dockerdemo:/opt/runctest/redis# 6:C 31 Aug 03:24:24.741 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
root@dockerdemo:/opt/runctest/redis# runc --root /opt/runc/runcroot run -d …
```
=> fix delete other file bug when container id is ..

libcontainer/utils/utils_test.go
add more test case for `libcontainer/utils.CleanPath`.
=> test: add more test case for CleanPath

tty.go
make sure epollConsole is closed before returning an error.  It solves
a hang when using these commands with a container that uses a
terminal:
runc run foo &
ssh root@localhost runc exec foo echo hello
=> tty: close epollConsole on errors

libcontainer/keys/keyctl.go, libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go
While all modern kernels (and I do mean _all_ of them -- this syscall
was added in 2.6.10 before git had begun development!) have support for
this syscall, LXC has a default seccomp profile that returns ENOSYS for
this syscall. For most syscalls this would be a deal-breaker, and our
use of session keyrings is security-based there are a few mitigating
factors that make this change not-completely-insane:
* We already have a flag that disables the use of session keyrings
(for older kernels that had system-wide keyring limits and so
on). So disabling it is not a new idea.
* While the primary justification of using session keys *is*
security-based, it's more of a security-by-obscurity protection.
The main defense keyrings have is VFS credentials -- which is
something that users already have …
=> keyring: handle ENOSYS with keyctl(KEYCTL_JOIN_SESSION_KEYRING)

libcontainer/specconv/spec_linux.go
Fix https://github.com/opencontainers/runc/issues/1890
Just moved the check for `spec.Linux.IntelRdt` into the `if spec.Linux != nil` block.
=> Fix issue #1890: config.json with no linux config should not crash

.travis.yml
fixes travis ci build break..
"go get -u github.com/golang.org/lint/golint"
fails with 
```expects import "golang.org/x/lint/golint"```
commit switches to use "golang.org/x/lint/golint" as requested at https://github.com/golang/lint 
=> fix build break

checkpoint.go, libcontainer/cgroups/fs/apply_raw.go, libcontainer/configs/config.go, libcontainer/configs/validate/rootless.go, libcontainer/configs/validate/rootless_test.go, libcontainer/configs/validate/validator.go, libcontainer/container_linux.go, libcontainer/factory_linux.go, libcontainer/init_linux.go, libcontainer/message_linux.go, libcontainer/nsenter/nsexec.c, libcontainer/process_linux.go, libcontainer/specconv/example.go, libcontainer/specconv/spec_linux.go, libcontainer/specconv/spec_linux_test.go, main.go, pause.go, ps.go, restore.go, rootless_linux.go, spec.go, utils_linux.go
This PR decomposes  `libcontainer/configs.Config.Rootless bool` into `RootlessEUID bool` and
`RootlessCgroups bool`, so as to make "runc-in-userns" to be more compatible with "rootful" runc.
`RootlessEUID` denotes that runc is being executed as a non-root user (euid != 0) in
the current user namespace. `RootlessEUID` is almost identical to the former `Rootless`
except cgroups stuff.
`RootlessCgroups` denotes that runc is unlikely to have the full access to cgroups.
`RootlessCgroups` is set to false if runc is executed as the root (euid == 0) in the initial namespace.
Otherwise `RootlessCgroups` is set to true.
(Hint: if `RootlessEUID` is true, `RootlessCgroups` becomes true as well)
When runc is executed as the root (euid == 0) in an user namespace (e.g. by Docker-in-LXD, Podman, …
=> Disable rootless mode except RootlessCgMgr when executed as the root in userns (fix Docker-in-LXD regression)

events.go, libcontainer/SPEC.md, libcontainer/configs/config.go, libcontainer/configs/intelrdt.go, libcontainer/configs/validate/validator.go, libcontainer/container_linux_test.go, libcontainer/factory_linux.go, libcontainer/intelrdt/intelrdt.go, libcontainer/intelrdt/intelrdt_test.go, libcontainer/intelrdt/stats.go, libcontainer/specconv/spec_linux.go, update.go, utils_linux.go, vendor.conf, vendor/github.com/opencontainers/runtime-spec/README.md, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
This PR is the runc part of #1596 
The runtime-spec part: https://github.com/opencontainers/runtime-spec/pull/932
Memory Bandwidth Allocation (MBA) is a resource allocation sub-feature
of Intel Resource Director Technology (RDT) which is supported on some
Intel Xeon platforms. Intel RDT/MBA provides indirect and approximate
throttle over memory bandwidth for the software. A user controls the
resource by indicating the percentage of maximum memory bandwidth.
Hardware details of Intel RDT/MBA can be found in section 17.18 of
Intel Software Developer Manual:
https://software.intel.com/en-us/articles/intel-sdm
In Linux 4.12 kernel and newer, Intel RDT/MBA is enabled by kernel
config CONFIG_INTEL_RDT. If hardware support, CPU flags `rdt_a` and
`mba` will be set in /proc/cpuinfo.
Intel RDT …
=> libcontainer: intelrdt: add support for Intel RDT/MBA in runc

libcontainer/user/lookup_unix.go
subgid is defined per user, not group (see [`subgid(5)`](http://man7.org/linux/man-pages/man5/subgid.5.html))
This commit also adds support for specifying subuid owner with a numeric UID.
=> libcontainer: CurrentGroupSubGIDs -> CurrentUserSubGIDs

libcontainer/container_linux.go
This fixes
libcontainer/container_linux.go:1200: Error call has possible formatting directive %s
Signed-off-by: Adrian Reber <areber@redhat.com>
=> Fix travis Go: tip

README.md, libcontainer/README.md
=> clarify license information

Makefile, libcontainer/cgroups/fs/kmem.go, libcontainer/cgroups/fs/kmem_disabled.go, libcontainer/cgroups/fs/memory.go
Commit fe898e7862f94 (PR #1350) enables kernel memory accounting
for all cgroups created by libcontainer -- even if kmem limit is
not configured.
Kernel memory accounting is known to be broken in some kernels,
specifically the ones from RHEL7 (including RHEL 7.5). Those
kernels do not support kernel memory reclaim, and are prone to
oopses. Unconditionally enabling kmem acct on such kernels lead
to bugs, such as
* https://github.com/opencontainers/runc/issues/1725
* https://github.com/kubernetes/kubernetes/issues/61937
* https://github.com/moby/moby/issues/29638
This commit gives a way to compile runc without kernel memory setting
support. To do so, use something like
make BUILDTAGS="seccomp nokmem"
=> libcontainer: ability to compile without kmem

Makefile
There is no need to explicitly add `cgo` build tag, it is set by
by go tools if cgo is enabled.
Fixes: ecd64631019d0c08
=> Makefile: rm cgo tag

libcontainer/specconv/spec_linux.go
for the code logic, pointer 'spec.Process' should be judge first
to avoid panic.
=> libcontainer: fix potential panic if spec.Process is nil

rootless_linux.go
move `context.GlobalBool("systemd-cgroup") ` inside if condition `context != nil`
```
if context != nil {
.....
if context.GlobalBool("systemd-cgroup") {
return false, nil
}
}
```
=> rootless: fix potential panic in shouldUseRootlessCgroupManager

libcontainer/specconv/spec_linux_test.go
add Root in created spec, or `TestDupNamespaces` is not test dup-namespace ,but test `lack of Root`,  error message is 'Root must be specified'
if not add Root field, test will fail at 
```
if spec.Root == nil {
return nil, fmt.Errorf("Root must be specified")
}
```
=> test: fix TestDupNamespaces fail to test dup-ns error

libcontainer/cgroups/systemd/apply_systemd.go
Currently runc applies PidsLimit restriction by writing directly to
cgroup's pids.max, without notifying systemd. As a consequence, when the
later updates the context of the corresponding scope, pids.max is reset
to the value of systemd's TasksMax property.
This can be easily reproduced this way (I'm using "postfix" here just an
example, any unrelated but existing service will do):
```
111
max
```
This patch adds TasksAccounting=true and TasksMax=PidsLimit to the
properties sent to systemd.
Signed-off-by: Sergio Lopez <slp@redhat.com>
=> libcontainer: map PidsLimit to systemd's TasksMax property

libcontainer/README.md, libcontainer/SPEC.md, libcontainer/cgroups/utils.go, libcontainer/configs/namespaces_linux.go, libcontainer/configs/namespaces_syscall.go, libcontainer/configs/validate/validator.go, libcontainer/container_linux.go, libcontainer/integration/exec_test.go, libcontainer/nsenter/nsexec.c, libcontainer/process_linux.go, libcontainer/rootfs_linux.go, libcontainer/specconv/spec_linux.go
Carrying [#781](https://github.com/opencontainers/runc/pull/781). Thanks for @cyphar 's work. :smile:
Closes #1184
Fixes #1884
Cgroup namespace can be configured in `config.json` as other
namespaces. Here is an example:
```
"namespaces": [
{
"type": "pid"
},
{
"type": "network"
},
{
"type": "ipc"
},
{
"type": "uts"
},
{
"type": "mount"
},
{
"type": "cgroup"
}
],
```
Note that if you want to run a container which has shared cgroup ns with
another container, then it's strongly recommended that you set
proper `CgroupsPath` of both containers(the second container's cgroup
path must be the subdirectory of the first one). Or there might be
some unexpected results.
Signed-off-by: Yuanhong Peng pengyuanhong@huawei.com
=> Add support for cgroup namespace

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/cgroups/utils.go, libcontainer/cgroups/utils_test.go
Hi there!
We have a testing environment where we have multiple instances of garden/runc running, where each instance creates and destroys containers for its tests. Each of these testing nodes are run in isolation on the same host, so each have their own cgroup directories to minimise interference.
We have noticed that occasionally, when runc is trying to write properties to a cgroup, it chooses a neighbours cgroup by accident.
We think this is to do with the implementation of [`FindCgroupMountpointAndRoot`](https://github.com/opencontainers/runc/blob/20aff4f0488c6d4b8df4d85b4f63f1f704c11abd/libcontainer/cgroups/utils.go#L30), which finds the *first* occurrence of a subsystem in the mount table. When we run multiple instances in parallel, this is not always the right one.
We'd like to …
=> Respect container's cgroup path

man/runc-update.8.md
This adds two missing intelRdt parameters in 'runc update' manpage. These two parameters are used to update RDT cache and memory bandwidth config [1].
[1] https://github.com/opencontainers/runc/blob/master/update.go#L117-L124
cc @xiaochenshen
=> add missing intelRdt parameters in 'runc update' manpage

Dockerfile
Upgrade CRIU to 3.11 in the Dockerfile as it includes the patch which
was manually added to fix an error with read-only root containers.
Now that the patch is part of the CRIU 3.11 release this simplifies the
Dockerfile (minimal).
Signed-off-by: Adrian Reber <areber@redhat.com>
=> Bump CRIU to 3.11

libcontainer/configs/config.go, libcontainer/configs/config_test.go, libcontainer/container.go, libcontainer/container_linux.go, libcontainer/factory_linux_test.go, libcontainer/integration/exec_test.go, libcontainer/process_linux.go, libcontainer/state_linux.go
Finish off the work started in #1201 to bring hook stdin into compliance with runtime-spec.
Also:
* Drop `HookState`, since there's no need for a local alias for `specs.State`.
* ~~Add `len` guards to avoid computing the state when `.Hooks` is non-`nil` but the particular phase we're looking at is empty.~~ I had to drop these to satisfy @cyphar [here][4].
* Also set `c.initProcess` in `newInitProcess` to support `OCIState` calls from within `initProcess.start()`.  I think the cyclic references between `linuxContainer` and `initProcess` are unfortunate, but didn't want to address that here.
* I've also left the timing of the `Prestart` hooks alone, although [the spec calls for them to happen before start][1] (not as part of creation, #1710).  Once the timing gets fixed we can drop the …
=> libcontainer: Set 'status' in hook stdin

libcontainer/container_linux.go
Signed-off-by: Lifubang <lifubang@acmcoder.com>
If a container A has been stopped, and after a long time, the host start a new process B whose process id is just equal to container A's process id.
When `runc kill A 9` again, process B will be killed.
So, we need to check container's status when we want to kill it.
=> fix: may kill other process when container has been stopped

MAINTAINERS
After talking to Rohit, he mentioned that he wasn't aware he was still a
maintainer (and that his maintainership was grandfathered from his
Docker maintainership). He's moved on to other projects now, and thus
said he would happily step down as maintainer. (Since he's stepping down
voluntarily, this doesn't require a mailing-list vote.)
After discussion with Victor, he mentioned that he wanted to rescind
his maintainership a few years ago (due to a change in priorities and
what he's been working on) but wasn't sure what the right process is.
Thanks for all of your hard work, Rohit and Victor!
/cc @rjnagal  @vmarmol 
=> MAINTAINERS: remove @rjnagal and @vmarmol

libcontainer/SPEC.md, libcontainer/configs/intelrdt.go, libcontainer/intelrdt/intelrdt.go, libcontainer/intelrdt/intelrdt_test.go
This PR is the runc part of Intel RDT/MBA Software Controller support.
The runtime-spec part: https://github.com/opencontainers/runtime-spec/pull/992
MBA Software Controller feature is introduced in Linux kernel v4.18.
It is a software enhancement to mitigate some limitations in MBA which
describes in kernel documentation. It also makes the interface more user
friendly - we could specify memory bandwidth in "MBps" (Mega Bytes per
second) as well as in "percentages".
The kernel underneath would use a software feedback mechanism or a
"Software Controller" which reads the actual bandwidth using MBM
counters and adjust the memory bandwidth percentages to ensure:
"actual memory bandwidth < user specified memory bandwidth".
We could enable this feature through mount option "-o mba_MBps":
mount …
=> libcontainer: intelrdt: add support for Intel RDT/MBA Software Controller in runc

libcontainer/container_linux.go
when restore container from a checkpoint directory, we should get
pid from criu notify, since c.initProcess has not been created.
I fail to update runc version in pouch project, https://github.com/alibaba/pouch/pull/2516, I check the restore code, in `criuNotifications` function,  `currentOCIState()` can not get pid since c.initProcess has not been created.
```
case notify.GetScript() == "setup-namespaces":
if c.config.Hooks != nil {
s, err := c.currentOCIState()
return nil
}
```
I do not figure out how criu notify can get pid, I want invite @avagin and @adrianreber help to check whether the fix in pr is correct.
=> cr: get pid from criu notify when restore

libcontainer/container_linux.go
regression introduced by 87a188996e229bf382c27865584765d1a50c0211
=> kill: allow to signal paused containers

libcontainer/cgroups/fs/kmem.go, libcontainer/cgroups/fs/kmem_disabled.go
When built with nokmem we explicitly are disabling support for kmemcg,
but it is a strict specification requirement that if we cannot fulfil an
aspect of the container configuration that we error out.
Completely ignoring explicitly-requested kmemcg limits with nokmem would
undoubtably lead to problems.
Fixes #1938
Fixes: 6a2c15596845 ("libcontainer: ability to compile without kmem")
=> cgroups: nokmem: error out on explicitly-set kmemcg limits

libcontainer/container_linux_test.go
Fix a small typo "recevied" to "received" in [container_linux_test.go](https://github.com/opencontainers/runc/compare/master...JoeWrightss:patch-4?expand=1#diff-241fad5897efafe2687db97efcef0757) at line 170 and 178.
=> Fix .Fatalf() error message

libcontainer/rootfs_linux.go
When creating a new user namespace, the kernel doesn't allow to mount
a new procfs or sysfs file system if there is not already one instance
fully visible in the current mount namespace.
When using --no-pivot we were effectively inhibiting this protection
from the kernel, as /proc and /sys from the host are still present in
the container mount namespace.
A container without full access to /proc could then create a new user
namespace, and from there able to mount a fully visible /proc, bypassing
the limitations in the container.
A simple reproducer for this issue is:
unshare -mrfp sh -c "mount -t proc none /proc && echo c > /proc/sysrq-trigger"
=> rootfs: umount all procfs and sysfs with --no-pivot

libcontainer/integration/exec_test.go, libcontainer/integration/init_test.go, libcontainer/integration/utils_test.go
For some reason, libcontainer/integration has a whole bunch of incorrect
usages of libcontainer.Factory -- causing test failures with a set of
security patches that will be published soon. Fixing ths is fairly
trivial (switch to creating a new libcontainer.Factory once in each
process, rather than creating one in TestMain globally).
=> integration: fix mis-use of libcontainer.Factory

libcontainer/cgroups/utils.go
This is related to https://github.com/opencontainers/runc/issues/1884
This fix allows more leniency for setting up cgroups on exec when cgroup namespaces are not used.
The issue linked above was partly resolved by https://github.com/opencontainers/runc/pull/1916 - we can avoid the issue entirely by using cgroup namespaces. Cloud Foundry's use of runc does not yet use cgroup namespaces and we encounter the issue above frequently.
We believe that since not using cgroup namespaces is a valid configuration of a config.json, runc should be more resilient when we choose not to. This PR will attempt to write to cgroup.procs a few times when execing, only retrying on seeing EINVAL (which, unless you're using realtime processes, means the task's state in the kernel is still TASK_NEW: …
=> Resilience in adding of exec tasks to cgroups

libcontainer/intelrdt/intelrdt.go
This patch fixes a corner case when destroy a container:
If we start a container without 'intelRdt' config set, and then we run
“runc update --l3-cache-schema/--mem-bw-schema” to add 'intelRdt' config
implicitly.
Now if we enter "exit" from the container inside, we will pass through
linuxContainer.Destroy() -> state.destroy() -> intelRdtManager.Destroy().
But in IntelRdtManager.Destroy(), IntelRdtManager.Path is still null
string, it hasn’t been initialized yet. As a result, the created rdt
group directory during "runc update" will not be removed as expected.
=> libcontainer: intelrdt: fix null intelrdt path issue in Destroy()

vendor.conf, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
Bumps to latest version of the runtime-spec
=> Vendor opencontainers/runtime-spec 29686dbc

libcontainer/cgroups/systemd/apply_systemd.go
The detection for scope properties (whether scope units support `DefaultDependencies=` or `Delegate=`) has always been broken, since systemd refuses to create scopes unless at least one PID is attached to it (and this has been so since scope units were introduced in systemd v205, see systemd commit [v204-230-g6c12b52e1964](https://github.com/systemd/systemd/commit/6c12b52e19640747e96f89d85422941a23dc6b29).)
This can be seen in journal logs whenever a container is started with libpod:
```
Feb 11 15:08:07 myhost systemd[1]: libcontainer-12345-systemd-test-default-dependencies.scope: Scope has no PIDs. Refusing.
Feb 11 15:08:07 myhost systemd[1]: libcontainer-12345-systemd-test-default-dependencies.scope: Scope has no PIDs. Refusing.
```
Since this logic never worked, just assume both …
=> Remove detection for scope properties, which have always been broken

libcontainer/nsenter/cloned_binary.c
My first attempt to simplify this and make it less costly focussed on
the way constructors are called. I was under the impression that the ELF
specification mandated that arg, argv, and actually even envp need to be
passed to functions located in the .init_arry section (aka
"constructors"). Actually, the specifications is (cf. [2]:
SHT_INIT_ARRAY
This section contains an array of pointers to initialization functions,
as described in ``Initialization and Termination Functions'' in Chapter
5. Each pointer in the array is taken as a parameterless procedure with
a void return.
which means that this becomes a libc specific decision. Glibc passes
down those args, musl doesn't. So this approach can't work. However, we
can at least remove the environment parsing part based on POSIX since
[1] …
=> nsexec (CVE-2019-5736): avoid parsing environ

.travis.yml
The CRIU test for lazy migration was always skipped in Travis because
the kernel was too old. This switches Travis testing to dist: xenial
which provides a newer kernel which enables CRIU lazy migration testing.
Not sure if this is something runc cannot or does not want to do (yet).
Tests are all successful, so switching to a newer distribution in Travis seems doable.
=> switched travis to xenial

exec.go, man/runc-exec.8.md, tests/integration/exec.bats
The implementation is already there, we only need to add the CLI
option and pass it down.
=> exec: expose --preserve-fds

utils_linux.go
`--preserve-fds` may caluse `runc create` and `runc run` hang.
If preserve-fds > 3, and /dev/fd/5 is not exist, runc will hang.
Because at that time, there is a socket pair for `runc init`, 
one of it's fd is 5.
So, when we pass preserve-fds flag, we need to check whether these fds is exist.
```
root@test:/opt/ubuntu# ls /dev/fd/ -alh
dr-x------ 2 root root  0 2月  28 16:36 .
dr-xr-xr-x 9 root root  0 2月  28 16:36 ..
lrwx------ 1 root root 64 2月  28 16:36 0 -> /dev/pts/2
lrwx------ 1 root root 64 2月  28 16:36 1 -> /dev/pts/2
lrwx------ 1 root root 64 2月  28 16:36 2 -> /dev/pts/2
lr-x------ 1 root root 64 2月  28 16:36 3 -> /proc/24479/fd
root@test:/opt/ubuntu# docker-runc run -d --preserve-fds 3 test1
^C^C^C^C^C
root@test:/opt/ubuntu#
```
=> fix preserve-fds flag may cause runc hang

libcontainer/container_linux.go, libcontainer/rootfs_linux.go
runc creates all bind mount mountpoints when it starts a container, this commit also creates those mountpoints during restore. Now it is possible to restore a container using the same, but newly created rootfs just as during container start.
Additionally this PR wires the CRIU option `--ext-mount-map auto` through to make it available during container restore using `runc restore --autodetect-external-mounts`.
These changes are necessary for https://github.com/containers/libpod/issues/1618
CC: @avagin, @rst0git this are some of the necessary changes as described on the mailing list
=> Create bind mount mountpoints during restore

libcontainer/container_linux.go, libcontainer/nsenter/cloned_binary.c
For a variety of reasons, sendfile(2) can end up doing a short-copy so
we need to just loop until we hit the binary size. Since /proc/self/exe
is tautologically our own binary, there's no chance someone is going to
modify it underneath us (or changing the size).
In order to get around the memfd_create(2) requirement, 0a8e411
("nsenter: clone /proc/self/exe to avoid exposing host binary to
container") added an O_TMPFILE fallback. However, this fallback was
flawed in two ways:
* It required O_TMPFILE which is relatively new (having been added to
Linux 3.11).
* The fallback choice was made at compile-time, not runtime. This
results in several complications when it comes to running binaries
on different machines to the ones they were built on.
The easiest way to resolve these things is to …
=> nsenter: cloned_binary: "memfd" cleanups

.travis.yml, libcontainer/specconv/spec_linux.go, tests/integration/checkpoint.bats, tests/integration/exec.bats, tests/integration/helpers.bash
This allows us to test runc using libcontainer's systemd driver, by passing a `RUNC_USE_SYSTEMD=1` argument to localintegration tests.
Tested:
```
$ sudo make localintegration RUNC_USE_SYSTEMD=1
```
All tests passed to me (with exception of one writing to `blkio.weight` which for some reason is missing on my Linux kernel 5.0, will look into that...)
And confirmed that systemd was in use by looking at creation and removal of <code>libcontainer_<em>&lt;pid&gt;</em>_systemd_test_default.slice</code> test slices. Also introduced a breakage in systemd cgroup driver and confirmed that the tests failed as expected.
=> Add $RUNC_USE_SYSTEMD to run tests using systemd cgroup driver

libcontainer/nsenter/cloned_binary.c
secure_getenv is a Glibc extension and so this code does not compile
on Musl libc any more after this patch.
secure_getenv is only intended to be used in setuid binaries, in
order that they should not trust their environment. It simply returns
NULL if the binary is running setuid. If runc was installed setuid,
the user can already do anything as root, so it is game over, so this
check is not needed.
=> Use getenv not secure_getenv

libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go, vendor.conf, vendor/github.com/opencontainers/selinux/README.md, vendor/github.com/opencontainers/selinux/go-selinux/label/label.go, vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go, vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
Work is ongoing in the kernel to support different kernel
keyrings per user namespace.  We want to allow SELinux to manage
kernel keyrings inside of the container.
Currently when runc creates the kernel keyring it gets the label which runc is
running with ususally `container_runtime_t`, with this change the kernel keyring
will be labeled with the container process label container_t:s0:C1,c2.
Container running as container_t:s0:c1,c2 can manage keyrings with the same label.
This change required a revendoring or the SELinux go bindings.
github.com/opencontainers/selinux.
=> Need to setup labeling of kernel keyrings.

libcontainer/process_linux.go
Whenever processes are spawned using nsexec, a zombie runc:[1:CHILD]
process will always be created and will need to be reaped by the parent
Fixes https://github.com/opencontainers/runc/issues/2022
=> Fixes regression causing zombie runc:[1:CHILD] processes

vendor.conf, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
On some machines when setting the SELinux key labels to "", we are seeing
failures that cause runc to fail.  Even if SELinux is disabled.
This check will ignore callers calling SELinux Set*Label functions with ""
when SELinux is disabled.
=> Fix SELinux failures on disabled SELinux Machines

exec.go, utils_linux.go
Signed-off-by: Lifubang <lifubang@acmcoder.com>
1. Fix regression introduced by https://github.com/opencontainers/runc/pull/2012/commits/cd96170c10b35a37f90040fe55529185b9a5ec30 , the related commit is in https://github.com/opencontainers/selinux/commit/e5c68ba81868de0c57b61832c2197cb31008a40e#diff-08374585d1f5b66358d612f6292a3fae
There is no `if processLabel == "" {` check now.
Fixed by #2032
2. Fixes #2030 check nil for `selinuxLabel` before we `label.SetKeyLabel`, this is also introduced by https://github.com/opencontainers/runc/pull/2012/commits/cd96170c10b35a37f90040fe55529185b9a5ec30 ;
Because the validate is : https://github.com/opencontainers/runc/blob/84cba4cbc1767353ae9d999c61f62a50c538589f/libcontainer/configs/validate/validator.go#L96-L107
Fixed by #2032
3. Fix if we use …
=> Add selinux validate in runc exec

vendor.conf, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
=> Vendor in latest selinux code for keycreate errors

libcontainer/cgroups/systemd/apply_nosystemd.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/factory_linux.go
This will permit us to extend the internals of systemd.Manager to include further information about the system, such as whether cgroupv1, cgroupv2 or both are in effect.
Furthermore, it allows a future refactor of moving more of UseSystemd() code into the factory initialization function.
=> Move systemd.Manager initialization into a function in that module

libcontainer/specconv/spec_linux.go
We discovered in umoci that setting a dummy type of "none" would result
in file-based bind-mounts no longer working properly, which is caused by
a restriction for when specconv will change the device type to "bind" to
work around rootfs_linux.go's ... issues.
However, bind-mounts don't have a type (and Linux will ignore any type
specifier you give it) because the type is copied from the source of the
bind-mount. So we should always overwrite it to avoid user confusion.
Ref: opencontainers/runc#1753
Ref: openSUSE/umoci#294
=> specconv: always set "type: bind" in case of MS_BIND

utils_linux.go
Signed-off-by: Xiao YongBiao <xyb4638@gmail.com>
=> `r.destroy` can defer exec in `runner.run` method.

main.go
commit a1460818288b8addfe9b70c8931da83864251f7a introduced a change to
write to /dev/stderr by default.  Do not reopen the file in this case,
but use directly the fd 2.
Closes: https://github.com/opencontainers/runc/issues/2056
Closes: https://github.com/kubernetes/kubernetes/issues/77615
Closes: https://github.com/cri-o/cri-o/issues/2368
=> main: not reopen /dev/stderr

libcontainer/process_linux.go
In the exception handling of initProcess.start(), we need to add the
missing IntelRdtManager.Destroy() handler in defer func.
=> libcontainer: intelrdt: add missing destroy handler in defer func

libcontainer/container_linux_test.go
This test needs to handle the case of configs.NEWCGROUP
as Namespace's type.
=> libcontainer: fix TestGetContainerState to check configs.NEWCGROUP

libcontainer/specconv/spec_linux_test.go
This commit changes the value of seccomp test for clone syscall.
Also hardcoded values should be changed because it is unclear to
understand what flags are tested.
Related issues:
* https://github.com/containerd/containerd/pull/3314
* https://github.com/moby/moby/pull/39308
* https://github.com/opencontainers/runtime-tools/pull/694
=> libcontainer: change seccomp test for clone syscall

libcontainer/cgroups/utils.go, libcontainer/cgroups/utils_test.go
The hugetlb cgroup control files (introduced here in 2012:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=abb8206cb0773)
use "KB" and not "kB"
(https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/mm/hugetlb_cgroup.c?h=v5.0#n349).
The behavior in the kernel has not changed since the introduction, and
the current code using "kB" will therefore fail on devices with small
amounts of ram (see
https://github.com/kubernetes/kubernetes/issues/77169) running a kernel
with config flag CONFIG_HUGETLBFS=y
As seen from the code in "mem_fmt" inside hugetlb_cgroup.c, only "KB",
"MB" and "GB" are used, so the others may be removed as well.
Here is a real world example of the files inside the
"/sys/kernel/mm/hugepages/" directory:
- "hugepages-64kB"
- …
=> Fix cgroup hugetlb size prefix for kB

Makefile
Some package managers download the archive instead of cloning the git repo.
When they do that, the call to git fails.
This commit allows package managers to provide the COMMIT value via environment.
=> Allow to define `COMMIT` by env

contrib/completions/bash/runc
I wanted  to use this bash completion to complete new options like Intel RDT/MBA.
But I found that was not updated.
Could you review modification?
=> Update bash completion for v1.0.0 release

tests/integration/exec.bats, tests/integration/multi-arch.bash
Currently, the id verification in integration test failed on arm
platform due to the inconsistent /etc/group in the busybox images
for arm and x86. To be specific, the nogroup id in x86 is 99 while
that in arm is 65534.
99 is old id for nogroup, and no longer be used in recent system,
so sync the busybox image for arm and x86 to the image in busybox
github. Also change the id verification rule in integration test.
Signed-off-by: Howard Zhang <howard.zhang@arm.com>
=> Update busybox source and fix runc exec bug

tests/integration/update.bats
weight, leafWeight, and weightDevice are removed in kernel 5.0
https://github.com/torvalds/linux/commit/f382fb0bcef4c37dc049e9f6963e3baf204d815c
https://github.com/opencontainers/runtime-spec/issues/1015
=> integration: remove blkio.weight (unavailable in kernel 5.0)

libcontainer/README.md
`Init` on the `Process` struct specifies whether the process is the first process in the container. This needs to be set to `true` when running the container.
=> doc: First process in container needs `Init: true`

libcontainer/cgroups/systemd/apply_systemd.go
Remove libcontainer detection for systemd features
Transient units (and transient slice units) have been available for quite a long time and RHEL 7 with systemd v219 (likely the oldest OS we care about at this point) supports that. A system running a systemd without these features is likely to break a lot of other stuff that runc/libcontainer care about.
Regarding delegated slices, modern systemd doesn't allow it and runc/libcontainer run fine on it, so we might as well just stop requesting it on older versions of systemd which allowed it. (Those versions never really changed behavior significantly when that option was passed anyways.)
Fixes #2108.
@youurayy Would you be willing to test this commit in your environment, confirm that it fixes the aforementioned issue and also everything …
=> Remove libcontainer detection for systemd features

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/cpu_v2.go, libcontainer/cgroups/fs/cpuset_v2.go, libcontainer/cgroups/fs/freezer_v2.go, libcontainer/cgroups/fs/io_v2.go, libcontainer/cgroups/fs/memory_v2.go, libcontainer/cgroups/fs/pids_v2.go, libcontainer/cgroups/fs/utils.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/cgroups/systemd/unified_hierarchy.go, libcontainer/cgroups/utils.go, libcontainer/configs/blkio_device.go, libcontainer/configs/cgroup_linux.go, libcontainer/container_linux.go
add support to libcontainer for handling a cgroups v2 unified hierarchy.
The implementation tries to reuse the existing data structures already defined for cgroups v1.  It is not an exhaustive implementation as it doesn't cover reading/writing all the files available with cgroups v2 (e.g. there is no support yet for writing to `memory.low` or `memory.min`) that have no corresponding mapping in cgroups v1 and in the data structures already defined.  Also, there is no support yet for controllers that need eBPF such as `devices`.
The only exceptions with new fields added are `CpuWeight` and `CpuMax` (defined in `libcontainer/configs/cgroup_linux.go`).
=> libcontainer: initial support for cgroups v2

.travis.yml, Dockerfile
I noticed there's still a mention of Go 1.6 in the README;
https://github.com/opencontainers/runc/blob/master/README.md#building
> It must be built with Go version 1.6 or higher in order for some features to function properly.
Not sure if we want to keep that mention, or if it's a bit redundant now that Go versions older than 1.6 reached EOL
=> Update to Go 1.12 and drop obsolete versions

man/runc-checkpoint.8.md, man/runc-create.8.md, man/runc-delete.8.md, man/runc-events.8.md, man/runc-exec.8.md, man/runc-kill.8.md, man/runc-list.8.md, man/runc-pause.8.md, man/runc-ps.8.md, man/runc-restore.8.md, man/runc-resume.8.md, man/runc-run.8.md, man/runc-spec.8.md, man/runc-start.8.md, man/runc-state.8.md, man/runc-update.8.md, man/runc.8.md
The man-pages are using pre-formatted section to display the options for
all commands. The result on my system never looked correct:
```
OPTIONS
--bundle value, -b value  path to the root [...]
--console-socket value    path to an AF_UNIX [...]
```
The first line was always indented less than the other lines.
This commit makes the option block a pre-formatted block (as intended???) by
using 4 spaces instead of 3 spaces.
In addition the man-pages did not specify their name and section
correctly. This adds something like `% runc-run "8"` to all man-pages to
have correct title `runc-run(8)` instead of 'NAME()' and it also adds
the section to the title: 'System Manager's Manual'.
This also fixes the use of `>` and `<` at multiple places. The markdown
source files were using "`<container-id>`" …
=> man: fix man-pages

restore.go
```
test@ubuntu:~/busybox$ runc --root ./runc checkpoint test
open /home/test/busybox/checkpoint/descriptors.json: permission denied
```
Because we need 0755, not 0655 permission, please see:
https://github.com/opencontainers/runc/blob/472fe623a76a039c438429345c0ccf71dc7722e8/libcontainer/container_linux.go#L927 
Signed-off-by: Lifubang <lifubang@acmcoder.com>
=> criu image path permission error when checkpoint rootless container

libcontainer/rootfs_linux.go
convert a "cgroup" mount to "cgroup2" when the system uses cgroups v2
unified hierarchy.
=> cgroup: support mount of cgroup2

notify_socket.go
When runc is started as a `Type=notify` systemd service, runc opens up its own listening socket inside the container to act as a proxy between the container and systemd for passing notify messages.
The domain socket that runc creates is only writeable by the user running runc however, so if the container has a different UID/GID then nothing inside the container will be able to write to the socket.
The fix is to change the permissions of the notify listener socket to 0777.
Signed-off-by: Joe Burianek <joe.burianek@pantheon.io>
=> Change the permissions of the notify listener socket to rwx for everyone

libcontainer/container_linux.go, libcontainer/rootfs_linux.go, libcontainer/rootfs_linux_test.go
Fixes #2128
This allows proc to be bind mounted for host and rootless namespace usecases but
it removes the ability to mount over the top of proc with a directory.
```bash
> sudo docker run --rm  apparmor
docker: Error response from daemon: OCI runtime create failed:
container_linux.go:346: starting container process caused "process_linux.go:449:
container init caused \"rootfs_linux.go:58: mounting
\\\"/var/lib/docker/volumes/aae28ea068c33d60e64d1a75916cf3ec2dc3634f97571854c9ed30c8401460c1/_data\\\"
to rootfs
\\\"/var/lib/docker/overlay2/a6be5ae911bf19f8eecb23a295dec85be9a8ee8da66e9fb55b47c841d1e381b7/merged\\\"
at \\\"/proc\\\" caused
\\\"\\\\\\\"/var/lib/docker/overlay2/a6be5ae911bf19f8eecb23a295dec85be9a8ee8da66e9fb55b47c841d1e381b7/merged/proc\\\\\\\"
cannot be mounted because it is …
```
=> Only allow proc mount if it is procfs

libcontainer/apparmor/apparmor.go, libcontainer/utils/utils_unix.go, vendor.conf, vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
This is an additional mitigation for CVE-2019-16884. The primary problem
is that Docker can be coerced into bind-mounting a file system on top of
/proc (resulting in label-related writes to /proc no longer happening).
While we are working on mitigations against permitting the mounts, this
helps avoid our code from being tricked into writing to non-procfs
files. This is not a perfect solution (after all, there might be a
bind-mount of a different procfs file over the target) but in order to
exploit that you would need to be able to tweak a config.json pretty
specifically (which thankfully Docker doesn't allow).
Specifically this stops AppArmor from not labeling a process silently
due to /proc/self/attr/... being incorrectly set, and stops any
accidental fd leaks because /proc/self/fd/... …
=> *: verify operations on /proc/... are on procfs

libcontainer/container_linux.go
Prevent unprivileged users from being able to read `descriptors.json`
cc: @avagin @adrianreber
=> checkpoint: Set descriptors.json file mode to 0600

README.md
Hi all,
When I attempted to run a rootless container I got the following error:
```bash
container_linux.go:337: starting container process caused "process_linux.go:302: running exec setns process for init caused \"exit status 39\""
```
This occurred because:
```bash
$ cat /proc/sys/kernel/unprivileged_userns_clone
0
```
After setting this to 1, I was able to run a rootless container.
=> Adds info about `userns` for rootless containers

libcontainer/cgroups/utils.go
This is needed for the fsv2 cgroups to work when there is a unified mountpoint.
=> Set unified mountpoint in find mnt func

libcontainer/cgroups/fs/io_v2.go, libcontainer/cgroups/utils.go
`/proc/cgroups` is meaningless for v2 and should be ignored.
https://github.com/torvalds/linux/blob/v5.3/Documentation/admin-guide/cgroup-v2.rst#deprecated-v1-core-features
* Now `GetAllSubsystems()` parses `/sys/fs/cgroup/cgroup.controller`, not `/proc/cgroups`.
The function result also contains "pseudo" controllers: `{"devices", "freezer"}`.
As it is hard to detect availability of pseudo controllers, pseudo controllers are always assumed to be available.
* Now `IOGroupV2.Name()` returns `"io"`, not `"blkio"`.
Fix #2155 #2156
=> cgroup2: do not parse /proc/cgroups

libcontainer/rootfs_linux.go
Bind-mount `/sys/fs/cgroup` when we are in UserNS but CgroupNS is not unshared,
because we cannot mount `cgroup2`.
This behavior correspond to crun v0.10.2.
https://github.com/containers/crun/blob/4325a78320852aa5dacb4d403ae01b241413068c/src/libcrun/linux.c#L433-L459
Fix #2158
=> cgroup2: allow mounting /sys/fs/cgroup in UserNS without unsharing CgroupNS

libcontainer/cgroups/fs/cpuset_v2.go
=> cgroup2: cpuset_v2: skip Apply when no limit is specified

libcontainer/cgroups/cgroups.go, libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/systemd/apply_nosystemd.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/cgroups/systemd/unified_hierarchy.go, libcontainer/container_linux_test.go
Implemented `runc ps` for cgroup v2 , using a newly added method `m.GetUnifiedPath()`.
Unlike the v1  implementation that checks `m.GetPaths()["devices"]`, the v2 implementation does not require the device controller to be available.
=> cgroup2: implement `runc ps`

Makefile, libcontainer/cgroups/systemd/apply_nosystemd.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/cgroups/systemd/unified_hierarchy.go
The `static_build` build tag was introduced in e9944d0f
to remove build warnings related to systemd cgroup driver
dependencies. Since then, those dependencies have changed and
building the systemd cgroup driver no longer imports dlopen.
After this change, runc builds will always include the systemd
cgroup driver.
This fixes #2008.
Signed-off-by: James Peach <jpeach@apache.org>
=> Remove the static_build build tag.

libcontainer/cgroups/ebpf/ebpf.go
=> cgroup2: ebpf: increase RLIM_MEMLOCK to avoid BPF_PROG_LOAD error

events.go, types/events.go
The event types are now part of a dedicated public `types` package
within runc to be able to unmarshal the output `runc events` directly.
cc @mrunalp @cyphar
=> Make event types public

.travis.yml, libcontainer/cgroups/cgroups_test.go, libcontainer/cgroups/fs/apply_raw_test.go, libcontainer/integration/checkpoint_test.go, libcontainer/integration/exec_test.go
As the baby step, only unit tests are executed.
Failing tests are currently skipped and will be fixed in follow-up PRs.
Fix #2124
=> .travis.yml: add Fedora 31 vagrant box (for cgroup2)

Makefile
e.g. `make CONTAINER_ENGINE="sudo podman" unittest` (for ease of cgroup2 testing)
=> Makefile: allow overriding `docker` command

libcontainer/container_linux.go, tests/integration/helpers.bash, tests/integration/tty.bats
Fixes #2183, a race condition in checking for a dead process while waiting for the exec fifo to open:
* Moves the wait for the blocking fifo open (happy path) and the 100ms poll for a missing/zombie process into the same loop
* When the missing/zombie process check fires, does a non-blocking open/read of the fifo to see if the process already completed, and only returns the "container process is already dead" error if that fails.
To test this, I inserted a synthetic 150ms delay in the awaitFifoOpen path after opening the fifo (simulating a slow send on the fifoOpened channel losing the race to the 100ms dead process detection timeout), and the integration suite passed (this PR includes https://github.com/opencontainers/runc/pull/2186 which fixes an existing race condition in one of the …
=> Fix race checking for process exit and waiting for exec fifo

tests/integration/helpers.bash, tests/integration/tty.bats
This fixes a race condition in the tty `runc run [terminal=false]` integration test (found while testing https://github.com/opencontainers/runc/pull/2185).
https://github.com/opencontainers/runc/blob/7496a9682535c8ca143e981116f5b67463ad1d69/tests/integration/tty.bats#L203-L209
Currently, the test assumes that as soon as `runc state` returns information about the container, it is running and `testcontainer test_busybox running` should succeed.
When the container start is slow (because of load or synthetic delay), the `runc state` command can return a `created` state, allowing `wait_for_container` to succeed, but letting the `testcontainer test_busybox running` command fail.
This race can be demonstrated by synthetically slowing down the transition from created to running:
```diff
diff …
```
=> Fix race in tty integration test with slow container startup

libcontainer/cgroups/cgroups.go, libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/systemd/apply_nosystemd.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/cgroups/systemd/unified_hierarchy.go, libcontainer/container_linux_test.go, libcontainer/specconv/spec_linux.go, libcontainer/specconv/spec_linux_test.go
libcontainer: export createCgroupConfig
A `config.Cgroups` object is required to manipulate cgroups v1 and v2 using
libcontainer.
Export `createCgroupConfig` to allow API users to create `config.Cgroups`
objects using directly libcontainer API.
libcontainer: add method to get cgroup config from cgroup Manager
`configs.Cgroup` contains the configuration used to create cgroups. This
configuration must be saved to disk, since it's required to restore the
cgroup manager that was used to create the cgroups.
Add method to get cgroup configuration from cgroup Manager to allow API users
save it to disk and restore a cgroup manager later.
fixes #2176
=> libcontainer: export and add new methods to allow cgroups manipulation

libcontainer/cgroups/fs2/fs2.go, libcontainer/integration/checkpoint_test.go
~~update criu to the latest revision on criu-dev branch (v3.13 is not enough to fix the issue)~~
~~Fix #2196~~
**EDIT:** Changed PR to skip the tests until Ubuntu kernel gets fixed (https://github.com/opencontainers/runc/pull/2198#issuecomment-571124087)
contains https://github.com/opencontainers/runc/pull/2206
=> temporarily disable CRIU tests

libcontainer/rootfs_linux.go
mount(2) will blindly follow symlinks, which is a problem because it
allows a malicious container to trick runc into mounting /proc to an
entirely different location (and thus within the attacker's control for
a rename-exchange attack).
This is just a hotfix (to "stop the bleeding"), and the more complete
fix would be finish libpathrs and port runc to it (to avoid these types
of attacks entirely, and defend against a variety of other /proc-related
attacks). It can be bypased by someone having "/" be a volume controlled
by another container.
Fixes: CVE-2019-19921
Fixes #2197
=> rootfs: do not permit /proc mounts to non-directories

libcontainer/cgroups/utils.go, libcontainer/specconv/spec_linux.go, update.go
Fix #2166 
Added conversion for cpu.weight v2 from cpu.shares
Signed-off-by: Boris Popovschi <zyqsempai@mail.ru>
=> Added conversion for cpu.weight v2

docs/systemd-properties.md, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/cgroups/systemd/unified_hierarchy.go, libcontainer/configs/cgroup_linux.go, libcontainer/specconv/spec_linux.go, libcontainer/specconv/spec_linux_test.go
In case systemd is used as a cgroups driver for container, it creates a scope
(aka transient unit) dedicated to a container (usually named `runc-$ID.scope`). 
This PR adds an ability to set arbitrary properties for the systemd unit via
runtime spec annotations.
Add the following to runtime spec (`config.json`):
```json
"annotations": {
"org.systemd.property.TimeoutStopSec": "300",
"org.systemd.property.CollectMode":"'inactive-or-failed'"
},
```
and start the container (e.g. `runc --systemd-cgroup run $ID`).
The above will set the following systemd parameters:
* `TimeoutStopSec` to 2 minutes and 3 seconds;
* `CollectMode` to "inactive-or-failed".
The values in spec should be in the gvariant format ([see docs here](https://developer.gnome.org/glib/stable/gvariant-text.html)).
To figure out …
=> Allow to set systemd scope properties via annotations

Makefile, README.md, tests/rootless.sh
I found rootless test could select test path. 
So, this commit modifies Makefile for rootless test to select test path.
=> Add rootless testpath in Makefile

man/md2man-all.sh
Took me awhile to figure out why it wasn't finding my go-md2man... centos image doesn't have `which` in it.
So this is just a little more convenient and one less required build dep.
=> Use "command -v" shell builtin instead of "which"

libcontainer/process_linux.go
In initProcess#start, there is deferred func :
```
defer func() {
```
Since the error return is not named, the above check doesn't cover all the cases.
e.g. a few lines below:
```
if _, err := io.Copy(p.messageSockPair.parent, p.bootstrapData); err != nil {
return newSystemErrorWithCause(err, "copying bootstrap data to pipe")
```
The check in deferred func doesn't check either err or, the actual returned error.
This PR changes the error return to be named.
=> Use named error return for initProcess#start

libcontainer/container_linux.go
linuxContainer.Signal() can race with another call to say Destroy()
which clears the container's initProcess. This can cause a nil pointer
dereference in Signal().
This patch will synchronize Signal() and Destroy() by grabbing the
container's mutex as part of the Signal() call.
Closes #2251
Signed-off-by: Pradyumna Agrawal <pradyumnaa@vmware.com>
=> Synchronize the call to linuxContainer.Signal()

notify_socket.go, signals.go, start.go, utils_linux.go
if NOTIFY_SOCKET is used, do not block the main runc process waiting for events on the notify socket.  Bind mount the parent directory of the notify socket, so that "start" can create the socket and it is still accessible from the container.
=> sd-notify: do not hang when NOTIFY_SOCKET is used with create

main.go
If we provide `--root`, we shold not check the XDG_RUNTIME_DIR env value.
For example:
```
test@test:~/busybox$ runc --root ./runc list
ERRO[0000] mkdir /run/user/0/runc: permission denied    
mkdir /run/user/0/runc: permission denied
```
This error is unrelated, because we use ./runc as root dir.
Actually, at that time, we use `--root` first.
But we check the value of XDG_RUNTIME_DIR and create related folder too early.
By the way, if we don't provide `--root`, we should provide the information of `XDG_RUNTIME_DIR env` when there is an permission error.
=> fix rootless container: unrelated error with root flag

libcontainer/container_linux.go, libcontainer/integration/checkpoint_test.go, libcontainer/restored_process.go
@adrianreber  reported that the checkpoint test stated failing:
```
=== RUN   TestCheckpoint
--- FAIL: TestCheckpoint (0.38s)
checkpoint_test.go:297: Did not restore the pipe correctly:
```
The problem here is when we start exec.Cmd, we don't call its wait
method. This means that we don't wait for cmd.goroutines and so we don't
know when all data will be read from process pipes.
=> restore: fix a race condition in process.Wait()

libcontainer/cgroups/fs2/cpu.go, libcontainer/cgroups/utils.go, libcontainer/cgroups/utils_test.go, libcontainer/specconv/spec_linux.go, update.go
* TestConvertCPUSharesToCgroupV2Value(0) was returning 70369281052672, while the correct value is 0
* ConvertBlkIOToCgroupV2Value(0) was returning 32, while the correct value is 0
* ConvertBlkIOToCgroupV2Value(1000) was returning 4, while the correct value is 10000
* CpuMax wasn't converted at all
Fix #2244
Fix #2243
Follow-up to #2212 #2213
=> cgroup2: fix conversion

libcontainer/sync.go
These were added in 244c9fc4 (#1018) alongside `procConsole` and the associated handling.  `procConsole` and that handling were removed in 00a0ecf5 (#1356), but 00a0ecf5 missed this comment.
=> libcontainer/sync: Drop procConsole transaction from comments

Dockerfile
When github is giving HTTP 404 (or other error), it still sends some
document (to be viewed in a browser), but we have tar on the other end
of the pipe, so the end result is like this:
> Step 13/13 : RUN . tests/integration/multi-arch.bash     && curl -o- -sSL `get_busybox` | tar xfJC - ${ROOTFS}
> 4872 ---> Running in ad84646a69f3
> 4873xz: (stdin): File format not recognized
> 4874tar: Child returned status 1
> 4875tar: Error is not recoverable: exiting now
> 4876The command '/bin/sh -c . tests/integration/multi-arch.bash     && curl -o- -sSL `get_busybox` | tar xfJC - ${ROOTFS}' returned a non-zero code: 2
Add -f switch to curl, so it will display an HTTP error and exit:
> curl: (22) The requested URL returned error: 404 Not Found
> xz: (stdin): File format not recognized
> tar: Child …
=> Dockerfile: add -f to curl

libcontainer/specconv/spec_linux_test.go
`Process` of `Spec struct` is a pointer:
```go
Process *Process `json:"process,omitempty"`
```
When calling `CreateLibcontainerConfig()` with  `opts.Spec.Process: nil`, runc will panic.
I added a new test case `TestNullProcess` in `libcontainer/specconv`, it will failed with:
```sh
=== RUN   TestNullProcess
--- FAIL: TestNullProcess (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x540029]
goroutine 20 [running]:
testing.tRunner.func1(0xc42007e9c0)
/usr/lib/golang/src/testing/testing.go:622 +0x29d
panic(0x57c280, 0x861a20)
/usr/lib/golang/src/runtime/panic.go:489 +0x2cf …
```
=> specconv: fix null spec.Process making runc panic

utils_linux.go
From runner#run:
```
status, err := handler.forward(process, tty, detach)
r.terminate(process)
}
if detach {
return 0, nil
}
r.destroy()
return status, err
```
If forward() returns non-nil error, destroy() would be called twice: once on line 352 and once in the deferred func.
This PR avoids the duplicate call to destroy().
=> Avoid duplicate calls to runner#destroy

libcontainer/cgroups/systemd/unified_hierarchy.go, libcontainer/cgroups/utils.go, libcontainer/intelrdt/intelrdt.go
Please see the individual commits for details.
=> Assorted minor nits in libcontainer

checkpoint.go
If checkpointing a container with '--leave-running' runc started to print the following message:
`ERRO[0000] container is not destroyed`
The message is correct, because CRIU did not terminate the process, but as that was requested by the user the message is wrong.
So now the container is only destroyed if the user did not specify '--leave-running'.
Fixes: #2253
=> checkpoint: remove error message with --leave-running

libcontainer/cgroups/systemd/unified_hierarchy.go
To the best of my knowledge, it has been decided to drop the kernel
memory controller from the cgroupv2 hierarchy, so "kernel memory limits"
do not exist if we're using v2 unified.
So, we need to ignore kernel memory setting. This was already done in
non-systemd case (see commit 88e8350de), let's do the same for systemd.
This fixes the following error:
> container_linux.go:349: starting container process caused "process_linux.go:306: applying cgroup configuration for process caused \"open /sys/fs/cgroup/machine.slice/runc-cgroups-integration-test.scope/tasks: no such file or directory\""
@AkihiroSuda @mrunalp PTAL
=> cgroupv2: don't try to set kmem for systemd case

libcontainer/cgroups/fs2/memory.go, libcontainer/cgroups/fs2/pids.go
Cgroup v1 kernel doc [1] says:
> We can write "-1" to reset the ``*.limit_in_bytes(unlimited)``.
and cgroup v2 kernel documentation [2] says:
> - If a controller implements an absolute resource guarantee and/or
>  limit, the interface files should be named "min" and "max"
>  respectively.  If a controller implements best effort resource
>  guarantee and/or limit, the interface files should be named "low"
>  and "high" respectively.
>
>  In the above four control files, the special token "max" should be
>  used to represent upward infinity for both reading and writing.
Allow -1 value to still be used for v2, converting it to "max"
where it makes sense to do so.
This fixes the following issue:
> runc update test_update --memory-swap -1:
> error while setting cgroup v2: [write …
=> cgroupv2: use "max" for negative values

libcontainer/cgroups/fscommon/fscommon.go, libcontainer/cgroups/fscommon/fscommon_test.go
Golang 1.14 introduces asynchronous preemption which results into
applications getting frequent EINTR (syscall interrupted) errors when
invoking slow syscalls, e.g. when writing to cgroup files.
As writing to cgroups is idempotent, it is safe to retry writing to the
file whenever the write syscall is interrupted.
Note that this PR also bumps the golang version in the test image `Dockerfile` so that the fix can be verified.
=> Retry writing to cgroup files on EINTR error

libcontainer/cgroups/fs2/defaultpath.go, libcontainer/intelrdt/intelrdt.go, libcontainer/user/user.go
The Err() method should be called after the Scan() loop, not inside it.
Found by
git grep -A3 -F '.Scan()' | grep Err
The line we are parsing looks like this
> flags         : fpu vme de pse <...>
so look for "flags" as a prefix, not substring.
=> bifio.Scan.Err usage nits

Dockerfile
Debian buster is the current stable, so might be good to switch to that version; also did some refactoring of the dockerfile (see individual commits for details).
I'll open a follow-up PR to update to go 1.13, but thought to first make the switch to "buster" to keep changes smaller.
=> Dockerfile: some refactoring, and switch to "buster" variant

libcontainer/cgroups/systemd/apply_nosystemd.go, libcontainer/cgroups/systemd/apply_systemd.go, libcontainer/cgroups/systemd/unified_hierarchy.go, libcontainer/integration/exec_test.go, utils_linux.go
This allows us to catch and report any failures in initializing the systemd dbus connection.
=> Separate systemd dbus connection initialization from running check

libcontainer/container_linux.go
It turns out that ioutil.Readfile wraps the error in a *os.PathError.
Since we cannot guarantee compilation with golang >= v1.13, we are
manually unwrapping the error.
Signed-off-by: Kieron Browne <kbrowne@pivotal.io>
=> Actually check for syscall.ENODEV when checking if a container is paused

.travis.yml, Dockerfile, libcontainer/container_linux.go, libcontainer/integration/checkpoint_test.go
The newest CRIU version supports freezer v2 and this tells runc to use it if new enough or fall back to non-freezer based process freezing on cgroup v2 system.
The Travis tests running on Fedora 31 with cgroup2 on Vagrant had the CRIU parts disabled because of a couple of problems.
One problem was a bug in runc and CRIU handling that Andrei fixed in #2226 
In addition four patches from the upcoming  CRIU 3.14 are needed for minimal cgroup2 support (freezer and mounting of cgroup2). With Andrei's fix and the CRIU cgroup2 support and the runc CRIU cgroup2 integration it is now possible to run the checkpoint integration tests again on the FedoraVagrant cgroup2 based integration test.
This also updates the Dockerfile to use buster instead of stretch for the container (needed for the container …
=> Add minimal cgroup2 checkpoint/restore support

libcontainer/container_linux.go
Using `GetPaths` from cgroupv2 unified hierarchy code is deprecated
and this function will (hopefully) be removed.
Use `GetUnifiedPath()` for v2 case.
There are more cases like this that we still need to fix, but this one is a low hanging fruit :)
=> libct/isPaused: don't use GetPaths from v2 code

libcontainer/container_linux.go
When performing checkpoint or restore of cgroupv2 unified hierarchy,
there is no need to call getCgroupMounts() / cgroups.GetCgroupMounts()
as there's only a single mount in there.
This eliminates the last internal (i.e. runc) use of
`cgroups.GetCgroupMounts()` for v2 unified case. Unfortunately, there
are external ones (e.g. moby/moby) so we can't yet let it
return an error.
@adrianreber PTAL
=> cgroupv2: don't use GetCgroupMounts for criu c/r

libcontainer/container_linux.go
Signed-off-by: Ted Yu <yuzhihong@gmail.com>
In linuxContainer#criuSwrk, criuServer is potentially closed twice.
See line 1468:
```
defer criuServer.Close()
```
and the criuServer.Close() call following cmd.Start().
This PR removed the duplicate Close() call.
=> Avoid double close of criuServer

libcontainer/container_linux.go
Signed-off-by: Ted Yu <yuzhihong@gmail.com>
Currently isPathInPrefixList returns false if match is found in the prefix list.
This PR reverts the return value so that the return value reflects the natural meaning of the method name.
=> isPathInPrefixList return value should be reverted

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/kmem.go, libcontainer/cgroups/fs2/pids.go, libcontainer/cgroups/fscommon/fscommon.go, libcontainer/cgroups/utils.go, libcontainer/container_linux.go
This set makes use of errors.Unwrap() where possible to get to an underlying error. The biggest motivation is to simplify the code.
The feature requires go 1.13 but since merging https://github.com/opencontainers/runc/pull/2256 we are already not supporting go 1.12 (which is an unsupported release anyway).
=> Use errors.Unwrap() where possible

.travis.yml, Vagrantfile
* Switch from VirtualBox to KVM because GCE (used in Travis) doesn't officially support VirtualBox:
https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances
* Increase HW resources: 512MB -> 2GB, 1 vCPU -> 2 vCPUs
* Cache `/home/travis/.vagrant.d/boxes`
=> vagrant: switch from VirtualBox to KVM + increase HW resources

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/kmem.go, libcontainer/cgroups/fs2/pids.go, libcontainer/cgroups/fscommon/fscommon.go, libcontainer/cgroups/utils.go, libcontainer/container_linux.go
My previous attempt (#2280) was a bit immature (though it worked).
Using errors.Unwrap() is not the best thing to do, since it returns
nil in case of an error which was not wrapped. More to say, 
errors package provides more elegant ways to check for underlying
errors, such as errors.As() and errors.Is().
Revert #2280, and use errors.Is() and errors.As()
Make use of errors.Is() and errors.As() where appropriate to check
the underlying error. The biggest motivation is to simplify the code.
The feature requires go 1.13 but since merging #2256 we are already
not supporting go 1.12 (which is an unsupported release anyway).
=> Use errors.As() and errors.Is() to unwrap errors

libcontainer/container_linux.go
Signed-off-by: Ted Yu <yuzhihong@gmail.com>
This PR restores the close of criuServer with a comment explaining the purpose of the close.
=> Restore close of criuServer

libcontainer/container_linux_test.go
CI was failing on cgroup v2 because `mockCgroupManager.GetUnifiedPath()` was returning an error.
Now the function returns the value of `mockCgroupManager.unifiedPath`, but the value is currently not used in the tests.
Fix #2286
=> Fix TestGetContainerStateAfterUpdate on cgroup v2

libcontainer/cgroups/fs2/fs2.go
otherwise the memoryStats and hugetlbStats maps are not initialized
and GetStats() segfaults when using them.
=> libcontainer: use cgroups.NewStats

libcontainer/cgroups/fs2/memory.go
Commit 6905b72154642 (PR #2272) treats all negative values as "max",
citing cgroup v1 compatibility as a reason. In fact, in
cgroup v1 only -1 is treated as "unlimited", and other
negative values usually calse an error.
Treat -1 as "max", pass other negative values as is
(the error will be returned from the kernel).
Fixes: 6905b72154642 (PR #2272)
=> cgroupv2: only treat -1 as "max"

libcontainer/cgroups/fs2/memory.go, libcontainer/cgroups/systemd/unified_hierarchy.go, libcontainer/cgroups/utils.go, libcontainer/cgroups/utils_test.go
The resources.MemorySwap field from OCI is memory+swap, while cgroupv2
has a separate swap limit, so subtract memory from the limit (and make
sure values are set and sane).
Make sure to set MemorySwapMax for systemd, too. Since systemd does not
have MemorySwapMax for cgroupv1, it is only needed for v2 driver.
* v2: return -1 on any negative value, add unit test
* v3: treat any negative value other than -1 as error
=> cgroupv2: fix setting MemorySwap

.travis.yml
`cgroup-v2` was marked `allow_failures` because of the flakiness of VirtualBox VM: dc7d0bf
The flakiness seems to have gone away since we switched from VirtualBox to QEMU/KVM and increased HW resources: b8eed86
Close #2301
=> travis: move `cgroup-v2` out of `allow_failures`

libcontainer/cgroups/systemd/unified_hierarchy.go
In createCgroupsv2Path , deferred func removes intermediate directory on error.
However, the path for intermediate directory was global.
This PR properly removes the intermediate directory.
=> Properly remove intermediate directory

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/cgroups/fs/stats_util_test.go, libcontainer/cgroups/stats.go
Making information on page usage by type and NUMA node available.
=> Exposing memory.numa_stats

.travis.yml, Vagrantfile, tests/integration/cgroups.bats, tests/integration/events.bats, tests/integration/helpers.bash, tests/integration/update.bats
This refactors integration test helpers a bit, and adds some initial tests for cgroupv2.
Split into logical small(er) commits for the sake of easier reviewing, so better to review it commit by commit.
This is far from complete, but is it mergeable and already helped to find a surprising number of bugs:
* https://github.com/opencontainers/runc/pull/2272 cgroupv2: use "max" for negative values (and a followup: https://github.com/opencontainers/runc/pull/2300)
* https://github.com/opencontainers/runc/pull/2270 cgroupv2: don't try to set kmem for systemd case
* https://github.com/opencontainers/runc/pull/2288 cgroupv2: fix setting MemorySwap
* https://github.com/opencontainers/runc/pull/2299 cgroupv2: fix fs2 driver initialization
* https://github.com/opencontainers/runc/issues/2298 cgroupv2 …
=> Initial integration tests for cgroupv2

exec.go, tests/integration/tty.bats
If container's config.json have `"terminal": true` setting in its
"process" section, runc exec assumes that stdin (fd 0) is a terminal
and tries to use it.
This leads to the following error in case stdin is not a terminal:
> ERRO[0000] exec failed: provided file is not a console
So, even if -t/--tty is not set, exec uses stdin as a terminal.
It does not help that urfave/cli v1 parser we use does not allow
to use `-t no` or `-t false`.
Since the settings in config.json is probably for the container run/start,
not for the auxiliary process started inside a container with exec, do
not use a setting from there, only treating stdin as a terminal in case
`-t` is explicitly given.
Fixes https://github.com/opencontainers/runc/issues/1627
=> runc exec: don't enable terminal unless -t is set

libcontainer/cgroups/fs2/defaultpath.go
When the cgroupv2 fs driver is used without setting cgroupsPath,
it picks up a path from /proc/self/cgroup. On a host with systemd,
such a path can look like (examples from my machines):
- /user.slice/user-1000.slice/session-4.scope
- /user.slice/user-1000.slice/user@1000.service/gnome-launched-xfce4-terminal.desktop-4260.scope
- /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
This cgroup already contains processes in it, which prevents to enable
controllers for a sub-cgroup (writing to cgroup.subtree_control fails
with EBUSY or EOPNOTSUPP).
Obviously, a parent cgroup (which does not contain tasks) should be used.
Fixes: #2298
=> cgroupv2: fix fs2 driver default path

libcontainer/container_linux.go
In linuxContainer#Restore, 
```
netns, err := os.Open(nsPath)
```
The deferred close of netns should be after err check.
Otherwise we would encounter nil-dereference.
=> Defer netns.Close() after error check

libcontainer/specconv/example.go
I think the runc example should join cgroup namespace by default if we use cgroup v2.
=> cgroupv2: default join cgroup namespace in runc example

.travis.yml, Vagrantfile
1. it was not working previously because of a typo
2. when a typo is removed, important packages such
as container-selinux are not updated, so let's
just remove this flag to avoid confusion.
Fixes: 84583eb1a4a5a53 (#2295)
It is not needed since commit 89c108b.
=> CI cleanups

libcontainer/system/linux.go
PR_SET_CHILD_SUBREAPER is defined in x/sys/unix.
=> libcontainer: use x/sys/unix instead of the hardcoded value

libcontainer/specconv/example.go
=> libcontainer: use consts of Namespace from runtime-spec

Dockerfile
_this is a replacement for #2307, see some initial discussion in there_
The bats testing framework we use for integration test is not maintained
since 2015 and was superceded by bats-core [1]. More to say, we were
using an unreleased version and relying on some features of it
(unfortunately I don't remember now what are those features exactly).
As Debian still packages very old version of bats from the old repo,
so let's Use recent bats-core from the new, supposedly better maintained,
github repo.
[1] https://github.com/sstephenson/bats/pull/269
=> Dockerfile: use bats-core

libcontainer/container_linux.go
Commit 9a0184b10f474b (PR #2259) meant to enable using cgroup v2 freezer
for criu >= 3.14, but it looks like it is doing something else instead.
The logic here is:
- for cgroup v1, set `FreezeCgroup`, if available
- for cgroup v2, only set `FreezeCgroup` for criu >= 3.14
- do not use `GetPaths()` in case v2 is used
(this method is obsoleted for v2 and will be removed)
=> libcontainer: fix Checkpoint wrt cgroupv2

Vagrantfile, libcontainer/container_linux.go, libcontainer/integration/checkpoint_test.go, libcontainer/rootfs_linux.go, tests/integration/checkpoint.bats
Fixes: https://github.com/opencontainers/runc/issues/2328
=> Fix cgroupv2 checkpoint/restore

checkpoint.go
Obviously, either `--pre-dump` or `--leave-running` implies
that we don't want to remove the container.
Found while working on checkpoint integration tests.
Fixes: 87712d288 (PR #2260)
=> checkpoint: don't print error if --pre-dump is set

libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go, tests/integration/helpers.bash, tests/integration/update.bats
fix #2287 
`runc --systemd-cgroup update does not update systemd scope`
As pointed out by @kolyshkin `The cause of this is Set() method of systemd.UnifiedManager, which only uses fsManager to set the updated values.`
So when we use systemd driven cgroup v2, we should use `SetUnitProperties` method to update container resource constraints.
=> fix data inconsistent when runc update in systemd driven cgroup

.travis.yml, Vagrantfile
Since we already have to build everything and run integration tests
on the Vagrant Fedora 31 host (in order to test how runc talks to
systemd), let's do the same for unit tests (otherwise we build
everything twice).
=> travis: run vagrant tests on the host

.travis.yml, libcontainer/cgroups/fs2/create.go, libcontainer/cgroups/fs2/fs2.go, tests/integration/cgroups.bats, tests/integration/update.bats, tests/rootless.sh
Fix #2339 (regression in 813cb3eb94659971c69c0dd19b2d5a9737891f15)
=> fs2: fix cgroup.subtree_control EPERM on rootless + add CI

Makefile
This is a series of cleanups for Makefile, which also fixes https://github.com/opencontainers/runc/issues/2354. Please see individual commits for description
=> Makefile fixes and improvements

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go
fix #2313(relate to #2310) #2344 
To fix #2313 
We can check whether `StartTransientUnit` succeeds or not with the value from the channel.
If we got `failed`, we should run `ResetFailedUnit` and return the error.
```
[root@localhost systemdtest]# runc --systemd-cgroup run -d test
WARN[0000] signal: killed                               
ERRO[0000] cannot detect unified path                   
ERRO[0000] container_linux.go:349: starting container process caused "process_linux.go:306: applying cgroup configuration for process caused \"StartTransientUnit job is not done: failed\"" 
container_linux.go:349: starting container process caused "process_linux.go:306: applying cgroup configuration for process caused \"StartTransientUnit job is not done: failed\""
```
The error `ERRO[0000] cannot …
=> check that StartTransientUnit/StopUnit succeeds

docs/terminals.md
I realised that the terminal documentation which covers detached
terminals fails to mention that callers need to make themselves a
subreaper. Probably a good idea to mention this. I've also included a
minor comparison to LXC.
=> docs: terminals: mention subreaper requirement

Vagrantfile
Fedora 32 comes with systemd 245, which supports delegation of cpuset controller to unprivileged users (ref: #2281)
=> Vagrantfile: use Fedora 32 (and remove unused Podman)

libcontainer/cgroups/fs2/defaultpath.go, libcontainer/cgroups/fs2/defaultpath_test.go
Function `defaultPath` always parses `/proc/self/cgroup`, but
the resulting value is not always used.
Avoid unnecessary reading/parsing by moving the code
to just before its use.
Modify the test case accordingly.
=> cgroups/fs2: don't always parse /proc/self/cgroup

libcontainer/generic_error.go, libcontainer/rootfs_linux.go
genericError.Error() was formatting the underlying error using `%q`; as a
result, quotes in underlying errors were escaped multiple times, which
caused the output to become hard to read, for example (wrapped for readability):
```
container_linux.go:345: starting container process caused "process_linux.go:430:
container init caused \"rootfs_linux.go:58: mounting \\\"/foo.txt\\\"
to rootfs \\\"/var/lib/docker/overlay2/f49a0ae0ec6646c818dcf05dbcbbdd79fc7c42561f3684fbb1fc5d2b9d3ad192/merged\\\"
at \\\"/var/lib/docker/overlay2/f49a0ae0ec6646c818dcf05dbcbbdd79fc7c42561f3684fbb1fc5d2b9d3ad192/merged/usr/share/nginx/html\\\"
caused \\\"not a directory\\\"\"": unknown
```
With this patch applied:
```
container_linux.go:348: starting container process caused: process_linux.go:438:
container init …
```
=> Improve readability of errors

libcontainer/container_linux.go
In waitForCriuLazyServer(), if fd.Write() returns error, current code would return without closing fd.
This PR closes the fd in above case to avoid leak.
=> Close fd in case fd.Write() returns error

Dockerfile, Vagrantfile
* Dockerfile: bump criu to version π (3.14)
* Vagrantfile: use criu 3.14 from testing
*  Vagrantfile: install less packages
=> Use criu 3.14

libcontainer/cgroups/fs2/memory.go, libcontainer/cgroups/systemd/v2.go, libcontainer/cgroups/utils.go
fix #2369
I think we should let cgroup fs/systemd driver can use 0 to disable memory swap in cgroup v2.
=> let runc disable swap in cgroup v2

libcontainer/container_linux.go, libcontainer/notify_linux_v2.go, tests/integration/events.bats
fix #2351 
Because there is no `oom notifier` in `cgroup v2` now.
I think we should use `Inotify` to watch `OOM` in `memory.events`.
=> fix runc events error in cgroup v2

checkpoint.go, main.go, utils.go, utils_linux.go
1. Remove a function `fatalf()` which were only used once.
2. Fix error "stuttering" (printing the error twice).
=> Logging nits

.travis.yml, Vagrantfile, libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/user.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go, libcontainer/factory_linux.go, rootless_linux.go, tests/integration/cgroups.bats, tests/integration/helpers.bash, tests/integration/update.bats, tests/rootless.sh, utils_linux.go
Tested with both Podman (master) and Moby (master), on Ubuntu 19.10 .
```console
$ podman --cgroup-manager=systemd run -it --rm --runtime=runc \
--cgroupns=host --memory 42m --cpus 0.42 --pids-limit 42 alpine
/ # cat /proc/self/cgroup
0::/user.slice/user-1001.slice/user@1001.service/user.slice/libpod-132ff0d72245e6f13a3bbc6cdc5376886897b60ac59eaa8dea1df7ab959cbf1c.scope
/ # cat
/sys/fs/cgroup/user.slice/user-1001.slice/user@1001.service/user.slice/libpod-132ff0d72245e6f13a3bbc6cdc5376886897b60ac59eaa8dea1df7ab959cbf1c.scope/memory.max
44040192
/ # cat
/sys/fs/cgroup/user.slice/user-1001.slice/user@1001.service/user.slice/libpod-132ff0d72245e6f13a3bbc6cdc5376886897b60ac59eaa8dea1df7ab959cbf1c.scope/cpu.max
42000 100000
/ # cat
/sys/fs/cgroup/user.slice/user-1001.slice/user@1001.service/user …
```
=> cgroup v2: support rootless systemd

go.mod, go.sum, libcontainer/cgroups/ebpf/devicefilter/devicefilter.go, libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go, vendor/github.com/cilium/ebpf/asm/instruction.go, vendor/github.com/cilium/ebpf/internal/unix/types_linux.go, vendor/github.com/cilium/ebpf/internal/unix/types_other.go, vendor/github.com/cilium/ebpf/run-tests.sh, vendor/modules.txt
_Note: this is a carry of https://github.com/opencontainers/runc/pull/2350_
This PR fixes a big endian issue and modify the tests accordingly.
The solution is based on the same fix as containers/crun@07bae05
=> s390x: fix big endian issue

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go, libcontainer/container_linux.go, libcontainer/factory_linux.go, libcontainer/notify_linux.go, libcontainer/notify_linux_test.go
This is a set of patches aiming to prepare the codebase for #2386 
Please review commits one by one.
=> cgroup refactoring

libcontainer/cgroups/cgroups.go, libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs2/fs2.go, libcontainer/cgroups/systemd/unsupported.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go, libcontainer/container_linux.go, libcontainer/container_linux_test.go
This unties the Gordian Knot of using GetPaths in cgroupv2 code.
The problem is, the current code uses GetPaths for three kinds of things:
1. Get all the paths to cgroup v1 controllers to save its state (see
(*linuxContainer).currentState(), (*LinuxFactory).loadState()
methods).
2. Get all the paths to cgroup v1 controllers to have the setns process
enter the proper cgroups in `(*setnsProcess).start()`.
3. Get the path to a specific controller (for example,
`m.GetPaths()["devices"]`).
Now, for cgroup v2 instead of a set of per-controller paths, we have only
one single unified path, and a dedicated function `GetUnifiedPath()` to get it.
This discrepancy between v1 and v2 cgroupManager API leads to the
following problems with the code:
- multiple if/else code blocks that have to treat v1 …
=> Simplify cgroup paths handling in v2 via unified v1/v2 API

libcontainer/specconv/spec_linux.go, libcontainer/specconv/spec_linux_test.go
The change ensures that the passed in value of NoNewPrivileges under spec.Process
is reflected in the container config generated by specconv.CreateLibcontainerConfig
Closes #2397
Signed-off-by: Pradyumna Agrawal <pradyumnaa@vmware.com>
=> Honor spec.Process.NoNewPrivileges in specconv.CreateLibcontainerConfig

Vagrantfile
CRIU 3.14 has made its way to the F32 stable repo, let's use it.
=> Vagrantfile: use criu from stable repo

events.go, libcontainer/cgroups/fs/cpuacct.go, libcontainer/cgroups/fs/cpuacct_test.go, libcontainer/cgroups/stats.go, types/events.go
This pull request introduces reading of cpuacct.usage_all with unit tests for reading stats from cpuacct cgroup.
=> Add reading of information from cpuacct.usage_all

events.go, libcontainer/intelrdt/cmt.go, libcontainer/intelrdt/cmt_test.go, libcontainer/intelrdt/intelrdt.go, libcontainer/intelrdt/mbm.go, libcontainer/intelrdt/mbm_test.go, libcontainer/intelrdt/monitoring.go, libcontainer/intelrdt/monitoring_test.go, libcontainer/intelrdt/stats.go, types/events.go
This pull request introduces the reading of Intel RDT Memory Bandwidth Monitoring statistics.
=> Add RDT Memory Bandwidth Monitoring (MBM) and Cache Monitoring Technology (CMT) statistics.

libcontainer/cgroups/fs2/create.go, tests/rootless.sh
After this commit: https://github.com/opencontainers/runc/commit/60c647e3b8e0d04cc8fe85b957ba2addfcc4fc4f 
Runc enable `threaded` mode in cgroup v2 by default.
If the cgroupPath is set to a absolute path like `/docker/********`, the memory subsystem can't be used by this mode.
So, I think we should use `domain` mode by default.
=> cgroupv2: don't enable threaded mode by default

libcontainer/cgroups/fs2/memory.go
Never write empty string to memory.swap.max
Because the empty string means set swap to 0.
For example:
with memory limit:
```
"memory": {
"limit": 33554432,
"swap": 33558528
}
```
The value of `memory.swap.max` is 4096.
After we run `runc update --memory 33554432 test`, the value of `memory.swap.max` becomes 0.
This is a regression introduced by #2370 . I'm so sorry.
=> cgroupv2: never write empty string to memory.swap.max

libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/utils.go, libcontainer/cgroups/utils_test.go
The function `GetClosestMountpointAncestor` is not very efficient,
does not really belong to cgroup package, and is only used once
(from fs/cpuset.go).
The removal is done in two stages/commits:
Prepare to remove it by replacing with the implementation based on
the `github.com/moby/sys/mountinfo` parser.
This commit is here to make sure the proposed replacement passes the
unit test.
Funny, but the unit test need to be slightly modified since it
supplies the wrong mountinfo (space as the first character, empty line
at the end).
Validated by
```
$ go test -v -run Ance
=== RUN   TestGetClosestMountpointAncestor
--- PASS: TestGetClosestMountpointAncestor (0.00s)
PASS
ok  	github.com/opencontainers/runc/libcontainer/cgroups	0.002s
```
Actually remove `GetClosestMountpointAncestor`, move the …
=> libct/cgroup: rm GetClosestMountpointAncestor using moby/sys/mountinfo parser

checkpoint.go, delete.go, events.go, libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/fs/devices.go, libcontainer/cgroups/fs/stats_util_test.go, libcontainer/cgroups/systemd/unsupported.go, libcontainer/configs/validate/rootless.go, libcontainer/configs/validate/validator.go, libcontainer/container_linux.go, libcontainer/init_linux.go, libcontainer/keys/keyctl.go, libcontainer/process_linux.go, libcontainer/seccomp/seccomp_linux.go, libcontainer/sync.go, list.go, ps.go, update.go, utils_linux.go
Signed-off-by: John Hwang <John.F.Hwang@gmail.com>
Short 3 line nil check to ensure spec.Process exists before validating its contents.
Closes #2392
=> Add nil check of spec.Process in validateProcessSpec()

libcontainer/cgroups/fs/cpuset.go
The compilation error had ocurred because of a bad rebase during #2401 and #2413
Replaces #2415
=> fix "libcontainer/cgroups/fs/cpuset.go:63:14: undefined: fmt"

Makefile
This sequence (and syntax) is taken directly from containerd's Makefile:
https://github.com/containerd/containerd/blob/4e08c2de67ec514b5602eea47804d41dfeabdc72/Makefile.linux#L21-L26
=> Remove "-buildmode=pie" from platforms that don't support it

libcontainer/cgroups/devices/devices_emulator.go, libcontainer/cgroups/devices/devices_emulator_test.go
I forgot to include this in the original patchset.
=> cgroups: add copyright header to devices.Emulator implementation

libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go, tests/integration/helpers.bash, tests/integration/update.bats
This fixes a few systemd cgroup bugs for both v1 and v2, and adds tests for systemd limit values (which uncover the bugs being fixed).
In particular, the bug fixes are:
* allow to set `TasksMax=infinity` (aka `pids.limit: -1`) [v1 and v2]
* set `MemoryLow` (aka `memory.reservation`) [v2 only]
* update `CPUQuotaPerSecUSec` for some cases [v1 only]
The integration test improvements are:
* simplify `check_systemd_value` usage
* add missing checks for systemd's `MemoryMax` / `MemoryLimit`
* add checks for systemd's `MemoryLow` and `MemorySwapMax`
* add checks for systemd's `TasksMax`
* add cgroupv1 systemd CPU checks (`CPUShares` and `CPUQuotaPerSecUSec`)
* add a test that sets `pids.limit=-1`
=> Fix setting some systemd limits, add more tests

libcontainer/cgroups/fs2/create.go, libcontainer/cgroups/fs2/fs2.go, tests/integration/cgroups.bats
fix #2394 
1. Partially revert "CreateCgroupPath: only enable needed controllers"
Because if we update a resource which did not limited in the beginning, it will
have no effective.
2. Returns err if we use an non enabled controller, or else the user may feel success, but actually
there are no effective.
For #2367 , I think we don't need fully revert https://github.com/opencontainers/runc/commit/4b4bc995ad4ee4679ffbe38f1672be01c24256fc , because rootless need some part in it to check errors.
=> Partially revert "CreateCgroupPath: only enable needed controllers"

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/systemd/v2.go, libcontainer/cgroups/utils.go, tests/integration/update.bats
This fixes two nuances in memory+swap update handling, and finally enables cgroupv2 swap checks in `tests/integration/update.bats`.
Commit 18ebc51b3cc3 "Reset Swap when memory is set to unlimited (-1)"
(see PR #1127) added handling of the case when a user updates the container
limits to set memory to unlimited (-1) but do not set any other limits.
Apparently, in this case, if swap limit was previously set, kernel fails
to set `memory.limit_in_bytes` to -1 if `memory.memsw.limit_in_bytes` is
not set to -1.
What the above commit fails to handle correctly is the request when
Memory is set to -1 and MemorySwap is set to some specific limit N
(where N > 0). In this case, the value of N is silently discarded
and MemorySwap is set to -1 instead.
This is wrong thing to do, as the limit set, even …
=> Fix some cases of swap setting

libcontainer/cgroups/systemd/v1.go, tests/integration/update.bats
This is a quick-n-dirty fix the regression introduced by commit
06d7c1d (in PR #2423), which made it impossible to only set CpuQuota
(without the CpuPeriod). It partially reverts the above commit,
and adds a test case.
The proper fix is in #2428.
=> cgroupv1: minimal fix for cpu quota regression

libcontainer/cgroups/fs2/fs2.go, tests/integration/delete.bats
fix #2403 
If we have subcgroups in a cgroup path, we should remove it recursively.
=> remove cgroup path recursively in cgroup v2

libcontainer/cgroups/fs2/fs2.go, tests/integration/delete.bats
1. In case there are no sub-cgroups (which is probably a common case), a single rmdir should be faster than iterating through the list of files (as suggested at https://github.com/opencontainers/runc/pull/2412#discussion_r428376762)
2. Use unix.Rmdir() to save one more syscall since os.Remove() tries unlink(2) first which fails on a directory, and only then tries rmdir(2).
3. Re-use rmdir in the second remove attempt.
And some test case fixups:
1. __runc does not set $status, so the check is misleading.
2. Add set +eux to the nest.sh script so we can error out early, and see
what is going on.
3. Doing "echo +io" > cgroup.controllers is giving an error on my
machine ("sh: write error: Operation not supported"). It is probably
fine to just enable pids controller.
4. Add status check for …
=> cgroups/fs2: make removeCgroupPath faster

libcontainer/container_linux.go
In linuxContainer#criuSwrk(), the deferred func may wait on criuProcess for a second time, if the following has been executed (around line 1640):
```
st, err = criuProcess.Wait()
```
This PR adds check for st so that there is no redundant wait.
Note: there is already deferred criuClientCon.Close() on line 1476
=> Wait for criuProcess once

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs/cpu.go, libcontainer/cgroups/systemd/v1.go
Commit 4e65e0e90a5884 added a check for cpu shares. Apparently, the
kernel allows to set a value higher than max or lower than min without
an error, but the value read back is always within the limits.
The check (which was later moved out to a separate CheckCpushares
function) is always performed after setting the cpu shares, so let's
move it to the very place where it is set.
=> cgroupv1: check cpu shares in place

libcontainer/container_linux.go, libcontainer/process_linux.go, tests/integration/cgroups.bats, tests/integration/delete.bats, tests/integration/helpers.bash
Fix #2356.
~~Contains https://github.com/opencontainers/runc/pull/2418~~
- - -
Note: this behavior is different from crun v0.13.
crun joins "crun-exec` group rather than the init group: https://github.com/containers/crun/commit/af1080b175cac63fe1c42397bfe3cca982a93896
The next version of crun will switch to the init cgroup: https://github.com/containers/crun/pull/365
=> cgroup2: exec: join the cgroup of the init process on EBUSY

tests/integration/events.bats, tests/integration/helpers.bash, tests/integration/update.bats
I ran the integration tests on an Ubuntu 19.04 host. To my surprise, I got two failures that this PR addresses. Both are caused by the fact that the memory.memsw control is turned off by default in Ubuntu 19.04 kernel (you need to add `swapaccount=1` to enable it).
The fixes are:
In case memory+swap cgroup control is not available, the test case fails:
```    
```
The fix is to reuse `SYSTEM_MEM` since the "unlimited" value is the same for mem and mem+swap.
For v2, mem+swap is always present. For v1, check it once and set a
variable which is used below.
This also removes CGROUP_MEMORY for v2 case since it's no longer used.
In case swap cgroup control is not available, the "event oom" test gives
the following error:
```
```
When I try to run the test without setting the swap limit, the …
=> integration tests fixes for no swap ctrl case

tests/integration/update.bats
Fix #2046
Previously, the test was failing with EINVAL during writing 500001 to `/sys/fs/cgroup/cpu,cpuacct/runc-cgroups-integration-test/test-cgroup/cpu.rt_runtime_us`, because `/sys/fs/cgroup/cpu,cpuacct/runc-cgroups-integration-test/cpu.rt_runtime_us` was initialized with 0.
The issue had not been caught in Ubuntu 18.04 CI because it doesn't support rt.
Tested on Ubuntu 20.04 and CentOS 7.8
=> test "update rt period and runtime": fix up runtime and period

libcontainer/cgroups/fs2/cpu.go, libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go, libcontainer/cgroups/utils.go, libcontainer/cgroups/utils_test.go, libcontainer/configs/cgroup_linux.go, libcontainer/specconv/spec_linux.go, tests/integration/update.bats, update.go
_this is loosely based on https://github.com/opencontainers/runc/pull/2428 but I am trying to make things right this time_
Seting CPU quota and period independently does not make much sense, but historically runc allowed it and this needs to be supported to not break compatibility.
This PR fixes the following issues:
systemd/v1, systemd/v2 and fs2 cgroup drivers reset the period to default 100000 during `runc update` if it is not set explicitly. This makes the behavior inconsistent with the one when fs driver is used (it leaves the period at the old value).
The issue is fixed by reusing the old (previously set) value for period/quota, if a new period/quota is not specified during the update.
systemd/v1, systemd/v2 and fs2 cgroup drivers ignore the CPU period during start/run, if CPU quota …
=> Cpu quota fixes, try II

libcontainer/container_linux.go
_~~NOTE: this builds on top of and currently includes #2341. Will rebase once that one is merged. The commit to review is the last one.~~ Rebased_
This relies on https://github.com/checkpoint-restore/criu/pull/1069 (which ~~is not merged yet!~~ was recently merged)
and emulates the previous behavior by writing `\0` and closing status
fd (as it was done by criu).
=> use lazy-pages ready notification for criu >= 3.15

libcontainer/cgroups/cgroups.go, libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/fs2/fs2.go, libcontainer/cgroups/systemd/unsupported.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go, libcontainer/container_linux.go, libcontainer/container_linux_test.go, tests/integration/kill.bats, tests/integration/ps.bats
fix #2337 
Because when the container is in stopped state, the cgroup path has been deleted by systemd driver.
=> fix path error in systemd when stopped

libcontainer/cgroups/fs/apply_raw.go, libcontainer/cgroups/systemd/v1.go, libcontainer/container_linux_test.go
This is a fixup for 
1. using `GetPaths()` instead of `Path()`
2. accessing `m.paths` map without lock
mostly introduced by #2338 and #2391.
=> Paths nits

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go, tests/integration/helpers.bash, tests/integration/update.bats
_This is currently based on and includes #2458 and will be rebased once that one is merged. Please only review the last commit._
For some reason, runc systemd drivers (both v1 and v2) never set
systemd unit property named `CPUQuotaPeriod` (known as
`CPUQuotaPeriodUSec` on dbus and in `systemctl show` output).
Set it, and add a check to all the integration tests. The check is less
than trivial because, when not set, the value is shown as "infinity" but
when set to the same (default) value, shown as "100ms", so in case we
expect 100ms (period = 100000 us), we have to _also_ check for
"infinity".
Fixes https://github.com/opencontainers/runc/issues/2465
=> cgroups/systemd: add setting CPUQuotaPeriod prop

libcontainer/cgroups/utils.go
Not sure why but the errors from scanner were ignored. Such errors
can happen if open(2) has succeeded but the subsequent read(2) fails.
=> libct/cgroups/readProcsFile: return an error if read failed

Dockerfile, Vagrantfile.centos7, Vagrantfile.fedora32, libcontainer/configs/config.go, libcontainer/configs/config_linux_test.go, libcontainer/configs/config_test.go, libcontainer/container_linux.go, libcontainer/factory_linux_test.go, libcontainer/init_linux.go, libcontainer/integration/exec_test.go, libcontainer/process_linux.go, libcontainer/rootfs_linux.go, libcontainer/specconv/spec_linux.go, libcontainer/specconv/spec_linux_test.go, libcontainer/standard_init_linux.go, libcontainer/state_linux.go, tests/integration/helpers.bash, tests/integration/hooks.bats, tests/integration/multi-arch.bash
Hello!
This PR implements the new `CreateRuntime` hook as defined in https://github.com/opencontainers/runtime-spec/blob/master/config.md#posix-platform-hooks
This is a fairly simple change, `CreateRuntime` are basically `prestart` hooks with the requirement of being called after the now deprecated `prestart` hooks.
I've done of refactoring to not have too much duplication of code by adding a function: `(*Hooks) RunHooks(name HookName, spec *specs.State) error`.
This allows us to have a nicer statement in the code:
```golang
if err := c.config.Hooks.RunHooks(configs.Prestart, s); err != nil {
return err
}
// Rather than
for i, hook := range c.config.Hooks.Prestart {
if err := hook.Run(s); err != nil {
return newSystemErrorWithCausef(err, "running prestart hook %d", i)
}
}
```
I'm looking …
=> Add CreateRuntime, CreateContainer and StartContainer Hooks

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/systemd_test.go
there have been cases observed where instead of `v$VER.0-$OS` the systemdVersion returned is just `$VER`. handle this case
Signed-off-by: Peter Hunt <pehunt@redhat.com>
=> systemd: parse systemdVersion when only an int is returned

libcontainer/container_linux.go
linuxContainer#Set(), if call to intelRdtManager#Set() returns error, we try to set configs back.
However, only intelRdtManager#Set() is called.
This PR adds the call to cgroupManager#Set(), similar to the call on line 217.
=> Set configs back when intelrdt configs cannot be set

tests/integration/checkpoint.bats
When looking into https://github.com/opencontainers/runc/issues/2475 I noticed there are no CRIU errors shown for runc restore. Amend the script with showing errors like in other cases.
While at it
- fix EOL whitespace
- fix exit code check in `simple_cr`
=> fixups to tests/int/checkpoint.bats

libcontainer/cgroups/fs/fs.go, libcontainer/cgroups/systemd/v1.go
Make things faster and code more readable by simplification and code removal.
=> libct/cgroups/fs: simplify/speedup freezer code

libcontainer/init_linux.go, libcontainer/user/user.go
if some error occurs at pty.Resize(), pty.Close() will not be called
=> make sure pty.Close() will be called and fix comment

libcontainer/cgroups/fs/devices.go, libcontainer/cgroups/fs/fs.go, libcontainer/cgroups/fs2/devices.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go, libcontainer/configs/cgroup_linux.go, libcontainer/container_linux.go
The kubelet uses libct/cgroups code to set up cgroups. It creates a
parent cgroup (kubepods) to put the containers into.
The problem (for cgroupv2 that uses eBPF for device configuration) is
the hard requirement to have devices cgroup configured results in
leaking an eBPF program upon every kubelet restart.  program. If kubelet
is restarted 64+ times, the cgroup can't be configured anymore.
Work around this by adding a SkipDevices flag to Resources.
A check was added so that if SkipDevices is set, such a "container"
can't be started (to make sure it is only used for non-containers).
Fixes https://github.com/opencontainers/runc/issues/2474
=> libct/cgroups: add SkipDevices to Resources

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/v1.go, tests/integration/delete.bats
some hierarchies were created directly by .Apply() on top of systemd managed cgroups.  systemd doesn't manage these and as a result we leak these cgroups.
=> cgroup, systemd: cleanup cgroups 

Dockerfile
There is a -v flag to unittest, integration, rootlessintegration tests inside container in Makefile.
IMO, it do not have to copy source code to container.
Signed-off-by: Xiaodong Liu <liuxiaodong@loongson.cn>
=> fix redundant source code copy issue

Makefile
This change would let me specify my own PREFIX so that I can reuse
Makefile targets for building rpm packages.
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
@mrunalp @cyphar PTAL
=> allow customizable PREFIX variable

.travis.yml, libcontainer/integration/template_test.go
Test command : `make localunittest`
Test logs:
```
FAIL: TestPidsSystemd (0.08s)
utils_test.go:55: exec_test.go:630: unexpected error: container_linux.go:353: starting container process caused: process_linux.go:326: applying cgroup configuration for process caused: mountpoint for devices not found
FAIL: TestRunWithKernelMemorySystemd (0.07s)
exec_test.go:713: runContainer failed with kernel memory limit: container_linux.go:353: starting container process caused: process_linux.go:326: applying cgroup configuration for process caused: mkdir : no such file or directory
```
Root cause:
TestPidsSystemd: The  cgroup root path is  `integration/test` when the test container is stating. The devices subsystem can not find under this root path, then casue apply cgroup error. The code show as …
=> fix TestPidsSystemd and TestRunWithKernelMemorySystemd test error

Vagrantfile.centos7, Vagrantfile.fedora32
Fedora mirrors are not very stable recently, leading to CI failures
(seen in multiple recent PRs) that usually look like this:
> sudo: make: command not found
In fact it's caused by dnf failure to read metadata from mirrors:
> Errors during downloading metadata for repository 'updates':
>     Downloading successful, but checksum doesn't match. Calculated: <....>
> Error: Failed to download metadata for repo 'updates': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
The error went undetected due to lack of exit code check.
This PR:
- adds `set -e -u -o pipefail` so the script will fail early (and do the same for centos7 vagrantfile);
- adds a retry loop with a sleep around dnf invocation.
=> tests/fedora32: retry dnf

libcontainer/cgroups/fs/blkio.go, libcontainer/cgroups/fs/cpu.go, libcontainer/cgroups/fs/cpuacct.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/fs/devices.go, libcontainer/cgroups/fs/freezer.go, libcontainer/cgroups/fs/fs.go, libcontainer/cgroups/fs/hugetlb.go, libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/name.go, libcontainer/cgroups/fs/net_cls.go, libcontainer/cgroups/fs/net_prio.go, libcontainer/cgroups/fs/perf_event.go, libcontainer/cgroups/fs/pids.go, libcontainer/cgroups/systemd/v1.go
This contains some minor cleanups and optimizations, but mostly just code removal.
~~TODO: add~~
~~* https://github.com/opencontainers/runc/commit/db45ce7f21d33a54e14492b6ef6816e3eafcf1fc~~
~~* https://github.com/opencontainers/runc/commit/44a02d2dfe6d7c2db7e2fa4b326d41771ce656d5~~
~~once https://github.com/opencontainers/runc/pull/2496 is merged~~
=> libct/cgroups/fs: code cleanups

Vagrantfile.centos7, tests/integration/checkpoint.bats, tests/integration/helpers.bash
Enable criu tests on centos 7 by using criu from Adrian's repo
(https://copr.fedorainfracloud.org/coprs/adrian/criu-el7/)
=> tests/centos7: add criu

.travis.yml
Travis reports following warnings which are fixed with this commit.
```
root: deprecated key sudo (The key `sudo` has no effect anymore.)
root: missing os, using the default linux
root: key matrix is an alias for jobs, using jobs
```
=> Fix .travis.yml warnings

libcontainer/devices/devices.go, libcontainer/devices/devices_test.go
(mode&S_IFCHR == S_IFCHR) is the wrong way of checking the type of an
inode because the S_IF* bits are actually not a bitmask and instead must
be checked using S_IF*. This bug was neatly hidden behind a (major == 0)
sanity-check but that was removed by [me][1].
In addition, add a test that makes sure that HostDevices() doesn't give
rubbish results -- because [we broke this and fixed this before][2].
[1]: 24388be71e1a ("configs: use different types for .Devices and .Resources.Devices")
[2]: 3ed492ad33f3 ("Handle non-devices correctly in DeviceFromPath")
Fixes: b0d014d0e1a4 ("libcontainer: one more switch from syscall to x/sys/unix")
=> devices: correctly check device types

libcontainer/cgroups/fs/blkio.go, libcontainer/cgroups/fs/cpu.go, libcontainer/cgroups/fs/cpu_test.go, libcontainer/cgroups/fs/cpuacct.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/fs/devices.go, libcontainer/cgroups/fs/freezer.go, libcontainer/cgroups/fs/fs.go, libcontainer/cgroups/fs/hugetlb.go, libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/name.go, libcontainer/cgroups/fs/net_cls.go, libcontainer/cgroups/fs/net_prio.go, libcontainer/cgroups/fs/perf_event.go, libcontainer/cgroups/fs/pids.go
In manager.Apply() method, a path to each subsystem is obtained by
calling d.path(sys.Name()), and the sys.Apply() is called that does
the same call to d.path() again.
d.path() is an expensive call, so rather than to call it twice, let's
reuse the result.
This results the number of times we parse mountinfo during container
start from 62 to 34 on my setup.
=> libct/cgroups/fs: rework Apply()

libcontainer/cgroups/fs/fs.go, libcontainer/cgroups/fs/fs_test.go
...by checking the default path first.
Quick benchmark shows it's about 5x faster on an idle system, and the
gain should be much more on a system doing mounts etc.
This is an alternative to #2497. I don't like it much because it adds code rather than removes it.
=> libct/cgroups/GetCgroupRoot: make it faster

libcontainer/container_linux.go
Trying to checkpoint a container out of a pod in cri-o fails with:
> `Error (criu/namespaces.c:1081): Can't dump a pid namespace without the process init`
Starting with the upcoming CRIU release 3.15, CRIU can be told to ignore the PID namespace during checkpointing and to restore processes into an existing network namespace.
With the changes from this PR and CRIU 3.15 it is possible to checkpoint a container out of a pod in cri-o.
=> Tell CRIU to use an external pid namespace if necessary

libcontainer/cgroups/v1_utils.go
In case cgroupPath is under the default cgroup prefix, let's try to
guess the mount point by adding the subsystem name to the default
prefix, and resolving the resulting path in case it's a symlink.
In most cases, given the default cgroup setup, this trick
should result in returning the same result faster, and avoiding
/proc/self/mountinfo parsing which is relatively slow and problematic.
Be very careful with the default path, checking it is
- a directory;
- a mount point;
- has cgroup fstype.
If something is not right, fall back to parsing mountinfo.
While at it, remove the obsoleted comment about mountinfo parsing.  The
comment belongs to findCgroupMountpointAndRootFromReader(), …
=> cgroupv1/FindCgroupMountpoint: add a fast path

tests/integration/checkpoint.bats, tests/integration/hooks.bats
TL;DR: this allows to show logs from failed runc restore.
Bats scripts are run with `set -e`. This is well known and obvious,
and yet there are a few errors with respect to that, including a few
"gems" by yours truly :(
1. bats scripts are run with `set -e`, meaning that `[ $? -eq 0 ]` is
useless since the execution won't ever reach this line in case of
non-zero exit code from a preceding command. So, remove all such
checks, they are useless and misleading.
2. bats scripts are run with `set -e`, meaning that `ret=$?` is useless
since the execution won't ever reach this line in case of non-zero
exit code from a preceding command.
In particular, the code that calls runc restore needs to save the exit
code, show the errors in the log, and only when check the exit code and
fail if it's …
=> tests/int: fix error handling and logging

Makefile
_separated from #2538_
I have noticed that `go vet` from golang 1.13 ignores the vendor/
subdir, downloading all the modules when invoked in Travis CI env.
As the other go commands, in 1.13 it needs explicit -mod=vendor
flag, so let's provide one.
PS once golang 1.13 is unsupported, we will drop it.
=> Makefile: fix go vet/fmt

go.mod, go.sum, vendor/github.com/syndtr/gocapability/capability/enum.go, vendor/github.com/syndtr/gocapability/capability/enum_gen.go, vendor/modules.txt
CAP_PERFMON and CAP_BPF were introduced in kernel 5.8: https://kernelnewbies.org/Linux_5.8#Introduce_CAP_BPF_and_CAP_PERFMON_security_capabilities
CAP_CHECKPOINT_RESTORE was merged on the master recently and will be available in the next version of the kernel. https://github.com/torvalds/linux/commit/124ea650d3072b005457faed69909221c2905a1f
=> support CAP_PERFMON, CAP_BPF, and CAP_CHECKPOINT_RESTORE

libcontainer/cgroups/fs/fs_test.go
_this comes from https://github.com/opencontainers/runc/pull/2497 which is now closed_
All the test cases are doing the same checks, only input differs,
so we can unify those using a test data table.
While at it:
- use t.Fatalf where it makes sense (no further checks are possible);
- remove the "XXX" comments as we won't get rid of cgroup Name/Parent.
PS I tried using t.Parallel() as well but it did not result in any
noticeable speedup, so I dropped it for simplicity.
=> cgroups/fs tests: unify TestInvalid*Cgroup*

libcontainer/integration/exec_test.go
The only two tests that are still skipped on v2 are kmem
and invalid CpuShares test -- since v2 does not support either.
=> libct/integration: enable some tests for cgroupv2

Makefile, tests/integration/cgroups.bats, tests/integration/checkpoint.bats, tests/integration/create.bats, tests/integration/delete.bats, tests/integration/events.bats, tests/integration/exec.bats, tests/integration/hooks.bats, tests/integration/kill.bats, tests/integration/list.bats, tests/integration/mask.bats, tests/integration/mounts.bats, tests/integration/pause.bats, tests/integration/ps.bats, tests/integration/root.bats, tests/integration/spec.bats, tests/integration/start.bats, tests/integration/start_detached.bats, tests/integration/state.bats, tests/integration/tty.bats, tests/integration/update.bats
This PR
- fixes (or adds annotations to ignore) all the shellcheck warnings for .bats files;
- add shellcheck to the CI cycle.
TODO (not in this PR):
- fix shellcheck warnings for helpers.bash
~~This currently includes #2548; I'll rebase once it's merged.~~ rebased
=> Add shellcheck to bats files

libcontainer/cgroups/fs/fs.go, libcontainer/cgroups/fs2/fs2.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/utils.go, tests/integration/delete.bats, tests/integration/helpers.bash
This set is a followup to https://github.com/opencontainers/runc/pull/2503. It does the following:
- moves cleaning of paths map to `RemovePaths` so its callers don't have to;
- adds `cgroups.RemovePath` (code move from `fs2.removeCgroupPath`);
- optimizes `cgroups.RemovePaths()` by reusing `RemovePath` instead of `os.RemoveAll`;
- adds a test case of cgroupv1 + sub-cgroups removal.
=> cgroupv1 removal nits

tests/integration/checkpoint.bats, tests/integration/delete.bats
Those are caused by merging #2506 after #2549 without a rebase.
Fixes: #2559 
The failures were:
```
In tests/integration/delete.bats line 64:
for i in $(seq 1); do
^-^ SC2034: i appears unused. Verify use (or export if used externally).
In tests/integration/delete.bats line 65:
runc run -d --console-socket $CONSOLE_SOCKET test_busybox
^-------------^ SC2086: Double quote to prevent globbing and word splitting.
Did you mean: 
runc run -d --console-socket "$CONSOLE_SOCKET" test_busybox
In tests/integration/delete.bats line 92:
eval path=\$${name}/foo
^-----^ SC2086: Double quote to prevent globbing and word splitting.
Did you mean: 
eval path=\$"${name}"/foo
In tests/integration/delete.bats line 93:
echo $path
^---^ SC2154: path is referenced but not assigned.
^---^ SC2086: Double quote to …
```
=> shellcheck CI files

tests/integration/tty.bats, tty.go, utils_linux.go
This fixes the following failure (and the likes):
```    
sudo runc run -b bundle ctr </dev/null
WARN[0000] exit status 2
ERRO[0000] container_linux.go:367: starting container process caused: process_linux.go:459: container init caused:
```
The "exit status 2" with no error message is caused by SIGHUP
which is sent to init by the kernel when we are losing the
controlling terminal. If we choose to ignore that, we get
the same result, this time caused by panic in console.Current(),
which is addressed by [1].
Otherwise, the issue here is simple: the code assumes stdin
is opened to a terminal, and fails to work otherwise. Some
standard Linux tools (e.g. stty, top) do the same (modulo panic),
while some others (reset, tput) use the trick of trying
all the three std streams (starting with …
=> Fix run/exec with terminal: true in case stdin is not a terminal

libcontainer/state_linux.go
./runc spec
add pid ns config to config.json
```
{
"type": "pid",
"path": "/proc/1/ns/pid"
}
```
"./runc run hello" in a console and "./runc exec -t hello ash" in another console, and then exit container.
we will see the following erros,
```
/ # exit
ERRO[0036] Failed to remove paths: map[memory:/sys/fs/cgroup/memory/user.slice/hello blkio:/sys/fs/cgroup/blkio/user.slice/hello hugetlb:/sys/fs/cgroup/hugetlb/hello net_cls:/sys/fs/cgroup/net_cls,net_prio/hello freezer:/sys/fs/cgroup/freezer/hello cpuset:/sys/fs/cgroup/cpuset/hello cpu:/sys/fs/cgroup/cpu,cpuacct/user.slice/hello cpuacct:/sys/fs/cgroup/cpu,cpuacct/user.slice/hello pids:/sys/fs/cgroup/pids/user.slice/hello net_prio:/sys/fs/cgroup/net_cls,net_prio/hello perf_event:/sys/fs/cgroup/perf_event/hello …
```
=> Make sure signalAllProcesses is invoked in the function of destroy when container shares pid namespace

tests/integration/dev.bats, tests/integration/exec.bats
Apparently, newer busybox image changed "nogroup" group name to "nobody",
breaking a few test cases that depended on the name.
Fix those tests by switching to numeric IDs.
This test started to fail, as it expected the output from
`id` to be
uid=1000 gid=1000 groups=100(users),65534(nogroup)
while the actual output is now
uid=1000 gid=1000 groups=100(users),65534(nobody)
Apparently, busybox image changed group name.
As we're only interested in ids, not names, and to fix the test,
let's use `id -G`.
These tests expect group name to be "nogroup", while recent busybox
changed that to "nobody".
Use numeric uids/gids to fix.
=> tests/int: fix wrt busybox's nogroup->nobody change

libcontainer/seccomp/seccomp_linux.go, libcontainer/seccomp/seccomp_unsupported.go, main.go
Printing these information would be helpful to debug runtime-related errors.
```console
$ runc --version
runc version 1.0.0-rc91+dev
commit: bdbc3b06b4690dbb29838cb8358969451f21e62e
spec: 1.0.2-dev
go: go1.14.6
libseccomp: 2.4.3
```
=> add Go version and libseccomp version to `runc --version`

libcontainer/cgroups/fs/fs.go, libcontainer/cgroups/systemd/v1.go
Limit the use of `getSubsystemPath()` and `d.path()` functions, reusing the `m.paths` instead.
See individual commit descriptions for details.
Number of times mountinfo was parsed during `runc --systemd-cgroup run` of a busybox container running `sleep 1` went down from 50 to 19 as a result of these changes.
=> cgroups/v1: optimize path usage

tests/integration/checkpoint.bats
Another set of fixes to aim in debugging of https://github.com/opencontainers/runc/issues/2475.
For previous fixes, see #2476, #2509, and #2548.
Individual commits description follows
For test cases where we used pipes for container's stdin/stdout/stderr,
stderr was redirected to the same pipe as stdout, which practically
means it is lost.
These redirects to fd is needed not because we check that container is
working by writing to its stdin and reading from stdout (see
check_pipes), but also because bats redirects test stdout/stderr to a
file, which makes c/r impossible (as the file is outside of container).
This is why we can't just do something like `2>stderr.log`, and have
to do what is done in this commit.
Introduce and use another pipe for stdout, to be used for both runc run
and …
=> tests/integration/checkpoint.bats: fix showing errors, rm unused code

Makefile
Commit a08ab87fe added these targets. Alas, the `go mod tidy` never
worked. Here is the relevant part of the `vendor` target in `Makefile`:
https://github.com/opencontainers/runc/blob/892477ca26638b214dc79150a09ba3565b93137d/Makefile#L128-L130
which is essentially
```bash
export GO111MODULE=on $(GO) mod tidy && ...
```
which exports a bunch of variables, such as `go`, `mod`, and `tidy`
(or would export those if they existed), but does not run `go mod tidy`.
The fix would be to add a semicolon after the `export` statement,
but since `GO111MODULE` is not really needed here (maybe some older
golang versions needed it?), let's just drop it.
With this dropped, && does not make any sense, so drop it, too.
NOTE that if someone tries
GO111MODULE=off make vendor
it will fail, but I guess it is …
=> Makefile: fix vendor and verify-dependencies

libcontainer/container_linux.go, libcontainer/process_linux.go
If the procRun state has been synced and the runc-create process has
been killed for some reason, the runc-init[2:stage] process will be
leaky. And the runc command also fails to parse root directory because
the container doesn't have state.json.
In order to make it possible to clean the leaky runc-init[2:stage]
process , we should store the status before sync procRun.
```before
current workflow:
[  child  ] <-> [   parent   ]
procHooks   --> [run hooks]
<-- procResume
procReady   --> [final setup]
<-- procRun
( killed for some reason)
( store state.json )
```
```expected
expected workflow:
[  child  ] <-> [   parent   ]
procHooks   --> [run hooks]
<-- procResume
procReady   --> [final setup]
store state.json
<-- procRun
```
Signed-off-by: Wei Fu <fuweid89@gmail.com>
=> libcontainer: Store state.json before sync procRun

go.mod, go.sum, libcontainer/cgroups/fs/fs.go, libcontainer/cgroups/fs2/fs2.go, libcontainer/cgroups/fscommon/fscommon.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/v1_utils.go, libcontainer/configs/cgroup_linux.go, libcontainer/integration/exec_test.go, libcontainer/specconv/spec_linux.go, tests/integration/cgroups.bats, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/modules.txt
Add support for unified resource map (as per [1]), and add some test
cases for the new functionality.
[1] https://github.com/opencontainers/runtime-spec/pull/1040
Fixes: #2563
The biggest issue, I think, is that the mapping of the "unified" parameters
to systemd properties is not implemented, meaning there can be cases
where systemd unit settings and in-kernel cgroup settings won't agree.
I don't think it can cause any issues, but it's just doesn't look right.
=> libct/cgroups: support Cgroups.Resources.Unified

tests/integration/cgroups.bats, tests/integration/checkpoint.bats, tests/integration/delete.bats, tests/integration/dev.bats, tests/integration/helpers.bash, tests/integration/mask.bats, tests/integration/mounts.bats, tests/integration/spec.bats, tests/integration/start_detached.bats, tests/integration/start_hello.bats, tests/integration/umask.bats, tests/integration/update.bats
Most notable one is spec.bats simplification and speedup.
The rest is nits and minor fixes.  Please see individual commits for details.
=> tests/integration: nits

libcontainer/capabilities_linux.go
See individual commit messages for details
=> Libcontainer: refactor capabilities code and remove RHEL6 workaround

libcontainer/container_linux.go, libcontainer/process_linux.go, tests/integration/cgroups.bats
In case cgroup configuration is invalid (some parameters can't be set
etc.), p.manager.Set fails, the error is returned, and then we try to
remove cgroups (by calling p.manager.Destroy) in a defer.
The problem is, the container init is not yet killed (as it is killed in
the caller, i.e. (*linuxContainer).start), so cgroup removal fails like
this:
> time="2020-09-26T07:46:25Z" level=warning msg="Failed to remove cgroup (will retry)" error="rmdir /sys/fs/cgroup/net_cls,net_prio/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod28ce6e74_694c_4b77_a953_dc01e182ac76.slice/crio-f6984c5eeb6c6b49ff3f036bdcb9ded317b3d0b2469ebbb35705442a2afd98c2.scope: device or resource busy"
> ...
> time="2020-09-26T07:46:27Z" level=error msg="Failed to remove cgroup" error="rmdir …
=> runc run: fix removing cgroups on error; improve logging on error

libcontainer/cgroups/systemd/common.go
In case it takes more than 1 second for systemd to create a unit,
startUnit() times out with a warning and then runc proceeds
(to create cgroups using fs manager and so on).
Now runc and systemd are racing, and multiple scenarios are possible.
In one such scenario, by the time runc calls systemd manager's Apply()
the unit is not yet created, the dbusConnection.SetUnitProperties()
call fails with "unit xxx.scope not found", and the whole container
start also fails.
To eliminate the race, we need to return an error in case the timeout is
hit.
To reduce the chance to fail, increase the timeout from 1 to 30 seconds,
to not error out too early on a busy/slow system (and times like 3-5
seconds are not unrealistic).
While at it, as the timeout is quite long now, make sure to not leave
a stray …
=> libct/cgroups/systemd: eliminate runc/systemd race

libcontainer/cgroups/fs/hugetlb_test.go
The names of these templates overlapped with some local variables, which made reading the code somewhat confusing.
Changing them to a const, given that these were not updated anywere.
=> libcontainer/cgroups: use const for templates

checkpoint.go
strings.Split() isn't the best solution for this, as it will not handle (e.g.) IPv6 addresses.
=> checkpoint: setPageServer: use net.SplitHostPort instead of strings.Split

Makefile
DESTDIR should only be used while installing.
To test:
make DESTDIR=$(pwd)/inst PREFIX=/usr install install-man install-bash
Before this commit, this would result in installing to `/usr`
rather than `$(pwd)/usr`.
Fixes: https://github.com/opencontainers/runc/issues/2571
=> Makefile: fix DESTDIR handling

libcontainer/cgroups/fs2/hugetlb.go, libcontainer/cgroups/fscommon/fscommon.go, libcontainer/cgroups/fscommon/utils.go
This is mostly error message fixes, doc improvements, and other minor cleanups.
This used to be a part of #2598
=> libct/cgroups/fscommon: nits

libcontainer/intelrdt/intelrdt.go, libcontainer/intelrdt/intelrdt_test.go
It might be a tad slower but it surely more correct and well maintained,
so it's better to use it than rely on a custom implementation which is
kind of hard to get entirely right.
This (together with / after) #2599 removes the last custom mountinfo
parser from the codebase (we had five of those).
=> libcontainer/intelrdt: use moby/sys/mountinfo

libcontainer/system/proc.go
As noticed in https://github.com/opencontainers/runc/pull/2612#discussion_r497636110, GetProcessStartTime was deprecated over three Years ago in 439eaa3584402d239297f278cc1f22c08dbdcc17 (https://github.com/opencontainers/runc/pull/1489), so we may as well remove it now.
=> libcontainer/system: remove deprecated GetProcessStartTime

libcontainer/cgroups/fs2/freezer.go
`errors.Wrap(err, "some error")` returns `nil` if `err` is `nil`, so it's slightly clearer to just return early than to set the error to `nil` and call `errors.Wrap()`. This is also somewhat defensive in case we decide to replace `errors.Wrap()` for golang's native `%w` wrapping.
=> setFreezer: explicitly return nil

.github/workflows/golangci-lint.yml
It is set to only check the new code, so this should help maintainers to see any new issues introduced by PRs.
To see the example how it works, check https://github.com/kolyshkin/runc/pull/1
Fixes: #2617
=> CI: add golangci-lint via github actions

libcontainer/cgroups/fs/hugetlb.go, libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs2/hugetlb.go, libcontainer/cgroups/fs2/memory.go, libcontainer/nsenter/nsenter_test.go
these looked quite redundant, and could be replaced by just concatenating the strings instead
=> libcontainer: remove redundant strings.Join()

libcontainer/cgroups/fs2/create.go, libcontainer/cgroups/fs2/defaultpath_test.go, libcontainer/cgroups/fscommon/utils.go, libcontainer/init_linux.go, libcontainer/integration/exec_test.go, libcontainer/intelrdt/intelrdt.go, libcontainer/logs/logs_linux_test.go, libcontainer/network_linux.go
Perform trimming before converting to a string, which should be somewhat more performant.
There may be more cases where we could process variables as byte before converting to strings; see https://medium.com/go-walkthrough/go-walkthrough-bytes-strings-packages-499be9f4b5bd
Also removed some unneeded conversions, caught by my IDE
=> libcontainer: prefer bytes.TrimSpace() over strings.TrimSpace()

libcontainer/intelrdt/monitoring_test.go
This file mode is unintentional apparently.
=> libcontainer/intelrdt: modify the incorrect file mode

libcontainer/cgroups/utils.go, libcontainer/cgroups/utils_test.go
ioutil.ReadFile does a stat() on every entry and returns a slice of
os.Stat structures. What we need here is just a file name.
This change both simplifies and speeds up the code a bit
(30% on my laptop).
This is a function to convert huge page sizes (obtained by reading
/sys/kernel/mm/hugepages directory entries) to strings user for hugetlb
cgroup controller resource files. Those strings are when used to get the
hugetlb resource statistics.
This function used external library, floating point numbers, and can
(theoretically) produce invalid values, since the kernel only uses KB,
MB, and GB suffixes.
Rewrite it to produce the same strings as used in the kernel (see [1]).
As a result, it's also faster (about 11x on my laptop -- see below), more
future-proof (entries that do not start with …
=> Fix/improve GetHugePageSize

libcontainer/factory_linux.go
Tiny adjust `LinuxFactory.StartInitialization()` method, I think this may be more readability and clean. 
First, get environment variables are together in `var` statement at the head of the method.  The init order are also consistent with the variable declaration.
And second, `it, pipe, consoleSocket, fifofd` are the args for `i, err := newContainerInit(it, pipe, consoleSocket, fifofd)` 
Signed-off-by: Jeff Zvier <zvier20@gmail.com>
=> cleancode: adjust and make it more readability

libcontainer/cgroups/fs/cpuacct.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/fs/kmem.go, libcontainer/cgroups/fs2/create.go, libcontainer/cgroups/fs2/fs2.go, libcontainer/cgroups/fs2/hugetlb.go, libcontainer/cgroups/fs2/pids.go, libcontainer/cgroups/fscommon/fscommon_test.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/utils.go
This switches all code under libcontainer/cgroups that reads or writes cgroup files to use appropriate functions from `fscommon`. This used to be part of #2598.
Besides, it slightly refactors `fs/cpuset.go` code.
=> libct/cgroups: switch to fscommon.{Read,Write}File

libcontainer/cgroups/utils.go, libcontainer/init_linux.go, libcontainer/intelrdt/intelrdt.go
mostly a test to see if golang-ci-lint picks up these changes in CI as well (not sure if the "nolint" tags work everywhere; they can be somewhat hit and miss
=> fix some linting issues

docs/cgroup-v2.md, libcontainer/cgroups/systemd/user.go
Closes #2582 
This PR adds a more helpful error message when `$DBUS_SESSION_BUS_ADDRESS` does not exist. I've tried to make the error message itself distro-agnostic but in the docs I've used the example in the issue.
Signed-off-by: Aos Dabbagh <aosdab@gmail.com>
=> Rootless systemd dbus friendlier error

main.go, utils.go
Converting relative root path to absolute, so flag is relative to the current directory.
```
runc --root myroot state a
{
"ociVersion": "1.0.2-dev",
"id": "a",
"pid": 403514,
"status": "created",
"bundle": "/root/container/mybundle",
"rootfs": "/root/container/mybundle/rootfs",
"created": "2020-10-03T02:04:11.259347723Z",
"owner": ""
}
````
Fixes #2613
=> Convert root path to absolute on create command

contrib/cmd/recvtty/recvtty.go, libcontainer/cgroups/systemd/common.go, libcontainer/configs/validate/validator.go, libcontainer/configs/validate/validator_test.go, libcontainer/container_linux.go, libcontainer/integration/checkpoint_test.go, libcontainer/integration/exec_test.go, libcontainer/nsenter/nsenter_test.go, libcontainer/seccomp/config.go, libcontainer/user/user_test.go, libcontainer/utils/utils_test.go, notify_socket.go, tty.go
Fixing some issues from https://github.com/opencontainers/runc/issues/2627
contrib/cmd/recvtty/recvtty.go:108:20: Error return value of `console.ClearONLCR` is not checked (errcheck)
libcontainer/cgroups/systemd/common.go:377:3: S1023: redundant `return` statement (gosimple)
libcontainer/configs/validate/validator.go:231:5: S1002: should omit comparison to bool constant, can be simplified to `!symLink` (gosimple)
libcontainer/container_linux.go:1531:2: S1006: should use for {} instead of for true {} (gosimple)
libcontainer/integration/checkpoint_test.go:238:2: SA4006: this value of `process` is never used (staticcheck)
libcontainer/integration/checkpoint_test.go:258:12: S1030: should use stdout.String() instead of string(stdout.Bytes()) (gosimple) …
=> Fixing some lint issues

libcontainer/integration/exec_test.go, libcontainer/process_linux.go
If the cgroup's init process doesn't complete successfully, Wait returns a
non-nil error. We should still kill all the processes in the cgroup in that
case, if process namespace is shared. Otherwise, it may result in process leak.
Fixes #2632
Signed-off-by: Chaitanya Bandi <kbandi@cs.stonybrook.edu>
=> Kill processes in cgroup even if process Wait fails

libcontainer/intelrdt/stats.go
If the values of CMT and MBM counters are zero, they will be omitted as
empty items when getting Intel RDT stats.
Remove 'omitempty' property from CMT and MBM counters to display zero
values.
=> libcontainer/intelrdt: remove 'omitempty' property from CMT and MBM counters

libcontainer/rootfs_linux.go
In a case where the host /proc mount has already been overmounted, the
MS_MOVE handling would get ENOENT when trying to hide (for instance)
"/proc/bus" because it had already hidden away "/proc". This revealed
two issues in the previous implementation of this hardening feaure:
1. No checks were done to make sure the mount was a "full" mount (it is
a mount of the root of the filesystem), but the kernel doesn't permit
a non-full mount to be converted to a full mount (for reference, see
mnt_already_visible). This just removes extra busy-work during setup.
2. ENOENT was treated as a critical error, even though it actually
indicates the mount doesn't exist and thus isn't a problem. A more
theoretically pure solution would be to store the set of mountpoints
to be hidden and only ignore the …
=> rootfs: handle nested procfs mounts for MS_MOVE

contrib/completions/bash/runc
This setting cannot complete `--systemd-cgroup` currently.
This is a minor fix and I think it is easy to review.
=> Update bash completion to support systemd-cgroup

libcontainer/cgroups/fs/blkio.go, libcontainer/cgroups/fs/cpu.go, libcontainer/cgroups/fs/cpuacct.go, libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/util_test.go, libcontainer/cgroups/fs2/cpu.go, libcontainer/cgroups/fs2/io.go, libcontainer/cgroups/fs2/memory.go, libcontainer/cgroups/fscommon/fscommon.go, libcontainer/cgroups/fscommon/open.go, libcontainer/cgroups/utils.go
_This is part III from https://github.com/opencontainers/runc/pull/2598, preparing the code to use `openat2()`_
Move the functionality of opening a cgroup file into a separate
function, `OpenFile`, which, similar to `ReadFile` and `WriteFile`,
use separate dir and file arguments.
Change `ReadFile` and `WriteFile` to rely on `OpenFile`, and use lower-level
read and write instead of ones from ioutil.
It changes the semantics of `WriteFile` a bit -- it no longer uses
`O_CREAT` flag. This is good for real cgroup as there is no need to try
creating the files in there, but can potentially break WriteFile users
-- previously, `EPERM` error was returned for non-existing files, and
now it's `ENOENT`.
This also breaks the fs/fs2 unit tests since they write to pseudo-cgroup
files inside a test …
=> libct/cg: introduce and use fscommon.OpenFile

libcontainer/cgroups/systemd/v1.go, libcontainer/integration/checkpoint_test.go, libcontainer/integration/exec_test.go, libcontainer/integration/execin_test.go, libcontainer/integration/seccomp_test.go, libcontainer/integration/template_test.go
Commit f57bb2fe3db set it to /sys/fs/cgroup which is somewhat confusing
as now tests create cgroups that look like this on the filesystem:
- /sys/fs/cgroup/memory/sys/fs/cgroup
- /sys/fs/cgroup/devices/sys/fs/cgroup
... etc.
but it worked!
It seems that some(?) tests were still not working properly with systemd because of invalid configuration.
Similar to what libcontainer/specconv does, add the functionality to set proper cgroup parameters for systemd.
This fixes all the tests.
Fixes: #2473
----
This PR also fixes the root cause of the breakage, which calls for
a separate story to be told. Gather around, kids, let me tell it to you.
Commit a1d5398afa91b0cb10 ("Respect container's cgroup path") added a
`cgroupPath` argument to `FindCgroupMountpoint` to make runc/libcontainer
work in a …
=> libcontainer/integration: fix cgroupv1 + systemd tests

libcontainer/factory_linux.go, libcontainer/intelrdt/intelrdt.go, libcontainer/intelrdt/intelrdt_test.go, update.go
This is a set of patches for IntelRdtManager refactoring. 
It is similar to part of the cgroup refactoring in #2387.
No functional change.
Please review commits one by one.
=> libcontainer/intelrdt: IntelRdtManager refactoring

libcontainer/integration/exec_test.go
~~73d93eeb0192 (part of https://github.com/opencontainers/runc/pull/2600) missed one update in 'TestPIDHostInitProcessWait' and now the unit tests are broken.~~
Edit: It was a merge issue between https://github.com/opencontainers/runc/pull/2633 (Introduced 'TestPIDHostInitProcessWait') & https://github.com/opencontainers/runc/pull/2600 (was opened before 'TestPIDHostInitProcessWait' was present). No idea why the CI didn't catch this problem.
I found it while having a weird linter failure not related to my changes in https://github.com/opencontainers/runc/pull/2660. 
ref https://travis-ci.org/github/opencontainers/runc/jobs/738208029#L345
cc @mrunalp  @kolyshkin
=> libcontainer/integration: fix unit test

libcontainer/rootfs_linux.go, tests/integration/mounts.bats
Based on the comments, this will mount the filesystem rw, then chmod, and finally remount it with ro.
Fixes #2246
Signed-off-by: Eduardo Vega  <edvegavalerio@gmail.com>
=> Fix mount error when chmod RO tmpfs

tests/integration/mounts.bats
CI on the master has been broken due to this.
https://travis-ci.org/github/opencontainers/runc/builds/739817745
Not sure why we couldn't catch this before merging it.
=> shfmt mounts.bats to pass `make validate`

.travis.yml
We had to use shfmt from git master/HEAD in commit 069fddfa1 as at the
time there was no released/tagged version that supports bats syntax.
Now there is (https://github.com/mvdan/sh/releases/tag/v3.2.0),
so let's pin it to avoid sudden regressions caused by changes in master
branch.
=> ci: pin shfmt to v3.2.0

tests/integration/checkpoint.bats, tests/integration/create.bats, tests/integration/debug.bats, tests/integration/delete.bats, tests/integration/events.bats, tests/integration/exec.bats, tests/integration/helpers.bash, tests/integration/start_detached.bats, tests/integration/start_hello.bats
Bats' run should only be used when we want to check both the command
output and its non-zero exit status.
Otherwise, we can rely on implicit exit code check (as the tests are
run with set -e), or use if, etc.
1. Fix the check, mostly by changing `cat hello` to `echo hello`,
and checking for `"hello"` (whole string) rather than `*"hello"*` (substring).
Previously, `cat hello` generated `cat: hello: no such file or directory`
error message, which `run` added to `$output` and
so the check for $output containing `hello` worked!
2. Simplify the test by not using the subshell and the `run`.
The only catch is, fd 3 is used by bats itself, so we have to use
fd 4 and thus --preserve-fds 2.
In its current form, it is complicated, unreliable, and error prone (TOCTOU etc)
Using `runc delete -f` will …
=> tests/integration: rm excessive run use; fix exec --preserve-fds test

libcontainer/rootfs_linux.go
if we are remounting root read only when in a user namespace, make
sure the existing flags (e.g. MS_NOEXEC, MS_NODEV) are maintained
otherwise the mount fails with EPERM.
=> linux: fix remount readonly in a user namespace

libcontainer/container_linux.go
runc already tells CRIU to restore into an existing network or PID namespace if there is a path to a namespace specified in config.json.
PID and network have special handling in CRIU using CRIU's inherit_fd interface.
For UTS, IPC and MOUNT namespaces CRIU can join those existing namespaces using CRIU's join_ns interface.
This is especially interesting for environments where containers are running in a pod which already has running containers (pause for example) with namespaces configured and the restored container needs to join these namespaces.
CRIU has no support to join an existing CGROUP namespace (yet?) why restoring a container with a path specified to a CGROUP namespace will be aborted by runc.
CRIU would have support to restore a container into an existing time namespace, but …
=> restore: tell CRIU to use existing namespaces

events.go, libcontainer/configs/validate/validator.go, libcontainer/container_linux_test.go, libcontainer/factory_linux.go, libcontainer/intelrdt/intelrdt.go, libcontainer/intelrdt/intelrdt_test.go, update.go, utils_linux.go
Rename CAT and MBA enabled flags to be consistent with others.
No functional change.
=> libcontainer/intelrdt: rename CAT and MBA enabled flags

docs/terminals.md
This commit removes the unnecessary ampersand.
Especially, it causes the error of "ambiguous redirect" when use bash.
=> docs: terminals: modify the example of Pass-Through mode.

.travis.yml, Vagrantfile.fedora33
release note: https://docs.fedoraproject.org/en-US/fedora/f33/release-notes/sysadmin/Distribution/
The vagrant image seems to still use ext4 as the rootfs.
```
$ sudo ssh default 'sh -exc "uname -a && systemctl --version && df -T"'
+ uname -a
Linux localhost.localdomain 5.8.15-301.fc33.x86_64 #1 SMP Thu Oct 15 16:58:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
+ systemctl --version
systemd 246 (v246.6-3.fc33)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
+ df -T
Filesystem     Type     1K-blocks    Used Available Use% Mounted on
devtmpfs       devtmpfs    995536       0    995536   0% /dev
tmpfs          tmpfs      1013572       0   1013572   0% …
```
=> CI: update Fedora to 33

README.md, docs/cgroup-v2.md
After a lot of refactoring, our cgroup v1 and v2 drivers now have same level of implementation quality,
so we can move the v2 driver out of experimental.
Close #2663
=> Move cgroup v2 out of experimental

libcontainer/intelrdt/cmt.go, libcontainer/intelrdt/intelrdt.go
Intel RDT sub-features can be selectively disabled or enabled by kernel
command line. See "rdt=" option details in kernel document:
https://www.kernel.org/doc/Documentation/admin-guide/kernel-parameters.txt
But Cache Monitoring Technology (CMT) feature is not correctly checked
in init() and getCMTNumaNodeStats() now. If CMT is disabled by kernel
command line (e.g., rdt=!cmt,mbmtotal,mbmlocal,l3cat,mba) while hardware
supports CMT, we may get following error when getting Intel RDT stats:
runc run c1
runc events c1
ERRO[0005] container_linux.go:200: getting container's Intel RDT stats
caused: open /sys/fs/resctrl/c1/mon_data/mon_L3_00/llc_occupancy: no
such file or directory
Fix CMT feature check in init() and GetStats() call paths.
=> libcontainer/intelrdt: fix CMT feature check

Dockerfile
The current URL now gives 404. I looked in there and found that
apparently Debian_Unstable becomes Debian_10. Fix the URLs accordingly.
=> Dockefile: fix path to skopeo repo

go.mod, go.sum, vendor/github.com/cilium/ebpf/abi.go, vendor/github.com/cilium/ebpf/elf_reader.go, vendor/github.com/cilium/ebpf/internal/btf/btf.go, vendor/github.com/cilium/ebpf/internal/btf/ext_info.go, vendor/github.com/cilium/ebpf/internal/btf/fuzz.go, vendor/github.com/cilium/ebpf/internal/btf/types.go, vendor/github.com/cilium/ebpf/internal/feature.go, vendor/github.com/cilium/ebpf/internal/syscall.go, vendor/github.com/cilium/ebpf/map.go, vendor/github.com/cilium/ebpf/prog.go, vendor/github.com/cilium/ebpf/readme.md, vendor/github.com/cilium/ebpf/run-tests.sh, vendor/github.com/cilium/ebpf/syscalls.go, vendor/modules.txt
full diff: https://github.com/cilium/ebpf/compare/v0.1.0...v0.2.0
- btf: add go-fuzz targets
- btf: avoid Type copy in FuncProto.walk
- btf: check err in loadSpecFromVmlinux
- btf: handle type name flavours
- CI: test on 5.9 kernel
- cmd/bpf2go: output ELF .o next to the .go file
- link: add AttachSkLookup
- Remove two unused functions
- Support LSM attach
- use buffered I/O to cut down on read syscalls
- Various doc link fixes
=> vendor: github.com/cilium/ebpf v0.2.0

tests/integration/README.md
We switched to bats-core in commit d4bc7c10ecda77c7c97572229f50914dd7c85d6a (https://github.com/opencontainers/runc/pull/2336), so updating the instructions to match.
=> integration: update README to link to bats-core

.github/workflows/validate.yml, .travis.yml, Makefile
This moves a few checks from Travis to github actions.
=> More GitHub actions

tests/integration/tty.bats
Just saw the timeout being hit on CI (Fedora 33 vagrant VM on Travis)
here (https://github.com/opencontainers/runc/pull/2599#issuecomment-734999958), so let's increase it.
=> tests/int/tty.bats: increase timeout

.github/workflows/test.yml
This is Ubuntu 20.04 so alas cgroup v1 testing only.
The upside is it's pretty fast :fast_forward: we have results of unit + integration tests
for both go 1.14 and 1.15 within 5 minutes. This seems useful now when travis-ci.org
is throttling jobs :disappointed: 
rootless tests take longer time so we run them in parallel
with non-rootless ones. Also, to balance the time, we run
unit tests when rootless is not set. IOW, 'rootless' in job
name means it's only rootless integration tests, and no rootless
means it's unit tests, integration tests with fs driver, and
integration tests with systemd driver.
Note, `script` is used to run integration tests to provide a tty
(which by default is not available on gh actions).
=> ci: add integration / unit tests to github actions

contrib/cmd/recvtty/recvtty.go
Related to #2627.
Saves us a few lines of code.
It looks like we need to wait for the both copy goroutines to finish,
not just the one that happens to finish first.
Fixes the following errcheck linter warnings
> contrib/cmd/recvtty/recvtty.go:115:10: Error return value of `io.Copy` is not checked (errcheck)
>               io.Copy(os.Stdout, c)
>                      ^
> contrib/cmd/recvtty/recvtty.go:120:11: Error return value of `io.Copy` is not checked (errcheck)
>                       io.Copy(c, os.Stdin)
>                              ^
> contrib/cmd/recvtty/recvtty.go:175:11: Error return value of `io.Copy` is not checked (errcheck)
>                       io.Copy(devnull, master)
>                              ^
=> recttty: nits

libcontainer/cgroups/devices/devices_emulator.go, libcontainer/cgroups/devices/devices_emulator_test.go, libcontainer/cgroups/ebpf/devicefilter/devicefilter.go, libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go, libcontainer/cgroups/fs/devices.go, libcontainer/cgroups/fs/devices_test.go, libcontainer/cgroups/fs2/devices.go, libcontainer/cgroups/systemd/common.go, libcontainer/configs/cgroup_linux.go, libcontainer/configs/config.go, libcontainer/configs/devices.go, libcontainer/devices/device.go, libcontainer/devices/device_unix.go, libcontainer/devices/device_windows.go, libcontainer/devices/devices.go, libcontainer/devices/devices_test.go, libcontainer/integration/template_test.go, libcontainer/rootfs_linux.go, libcontainer/specconv/spec_linux.go, libcontainer/specconv/spec_linux_test.go
Move the Device-related types to libcontainer/devices, so that the package can be used in isolation. Aliases have been created in libcontainer/configs for backward compatibility.
=> libcontainer: isolate libcontainer/devices

.github/workflows/validate.yml
1. Use ubuntu-20.04 instead of ubuntu-latest to fix warnings like
> Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details,
> see https://github.com/actions/virtual-environments/issues/1816
2. Minor formatting fixes, remove redundant name: etc.
=> .github/workflows/validate: nits

libcontainer/nsenter/cloned_binary.c
By all rights this patch shouldn't be necessary, but we've had cases where a customer has had other weird issues (`-EINVAL` from the read-only mount setup as well as all of the writeable partitions set to `noexec`) which ends up hitting errors that could be avoided if `SYS_memfd_create` was defined.
But ultimately this is fixing a SLE problem, so I'd be fine with carrying it downstream if it looks ugly (which it does).
<hr>
Some libc versions still in use by distributions (such as SLE) do not
define SYS_memfd_create even though the kernel supports the feature.
Since the syscall numbers are fixed, we can just hard-code them if
__NR_memfd_create is not defined.
We only do this for a handful of architectures, since containers aren't
widely supported on every possible Linux architecture. …
=> nsenter: hard-code memfd_create(2) syscall numbers

libcontainer/cgroups/utils.go, libcontainer/container_linux.go, libcontainer/integration/exec_test.go, libcontainer/integration/execin_test.go, libcontainer/intelrdt/monitoring.go
This fixes some sensible linter warnings, and silence a few that do not make much sense. Please see individual commits for details.
With this other PRs (#2694, #2696, #2700), we are down to 3 warnings (plus a lot of `errcheck` ones which are to be addressed separately):
```console
$ golangci-lint run -D errcheck ./...
libcontainer/cgroups/ebpf/ebpf.go:35:12: SA1019: prog.Attach is deprecated: use link.RawAttachProgram instead.  (staticcheck)
if err := prog.Attach(dirFD, ebpf.AttachCGroupDevice, unix.BPF_F_ALLOW_MULTI); err != nil {
^
libcontainer/cgroups/ebpf/ebpf.go:39:13: SA1019: prog.Detach is deprecated: use link.RawDetachProgram instead.  (staticcheck)
if err := prog.Detach(dirFD, ebpf.AttachCGroupDevice, unix.BPF_F_ALLOW_MULTI); err != nil {
^
libcontainer/container_linux.go:32:2: …
```
=> Misc linter nits

libcontainer/cgroups/fscommon/open.go
_(based on previous work in PRs #2604, #2605, #2635; originally part of #2598)_
In case `openat2` is available, it will be used to guarantee
that we're not accessing anything other than cgroupfs[2] files.
In cases when `openat2` is not available, or when cgroup has a
non-standard prefix (not `"/sys/fs/cgroup"`, which might theoretically
be the case on some very old installs and/or very custom systems),
fall back to using `securejoin` + `os.Open` like we did before.
=> libcontainer/cgroups/fscommon: add openat2 support

libcontainer/cgroups/utils_test.go, libcontainer/cgroups/v1_utils.go
The `all` argument was introduced by commit f5579964014 (PR #1049) specifically
for use by cAdvisor (see https://github.com/google/cadvisor/pull/1476), but there were no test cases added,
so it was later accidentally broken by 5ee0648bfbe037bcf4b (#1817) which started incrementing
`numFound` unconditionally.
Fix this (by not checking `numFound` when `all` is true), and add a
simple test case to avoid future regressions.
PS It appears to be that cadvisor is the only user of `all=true` functionality.
If we could eliminate it, we would remove `all=true` entirely, but it's not clear
how to do that. I sincerely hope one day cgroup v1 is going away entirely,
including all this code.
=> libct/cgroup/utils: fix GetCgroupMounts(all=true)

libcontainer/rootfs_linux.go
With lxcfs commit, slabinfo should can be mounted:
"proc_fuse: add /proc/slabinfo with slab accounting memcg"
https://github.com/lxc/lxcfs/commit/1cc68c8bfa
Signed-off-by: Feng Sun <loyou85@gmail.com>
=> checkProcMount: add /proc/slabinfo to whitelist

libcontainer/cgroups/fscommon/fscommon.go
A file descriptor should be closed after reading.
Signed-off-by: Paweł Szulik <pawel.szulik@intel.com>
=> libctl/cgroups/fscommon: close fd

libcontainer/factory_linux.go, libcontainer/intelrdt/cmt.go, libcontainer/intelrdt/intelrdt.go, libcontainer/intelrdt/mbm.go, utils_linux.go
Use sync.Once to init Intel RDT when needed for a small speedup to
operations which do not require Intel RDT.
Simplify IntelRdtManager initialization in LinuxFactory.
=> libcontainer/intelrdt: rm init() from intelrdt.go

libcontainer/init_linux.go, tests/integration/cwd.bats, tests/rootless.sh
_This is a carry of https://github.com/opencontainers/runc/pull/2685, adding test cases for it, as well for https://github.com/opencontainers/runc/pull/2086 to make sure there is no regression. Most work was done by @haircommander, I just tinkered with the tests. Original description from Peter follows._
----
commit 5e0e67d moved the chdir to be one of the
first steps of finalizing the namespace of the container.
However, this causes issues when the cwd is not accessible by the user running runc, but rather
as the container user.
Thus, setupUser has to happen before we call chdir. setupUser still happens before setting the caps,
so the user should be privileged enough to mitigate the issues fixed in 5e0e67d (I've tested it on my machine, so I believe it does not regress)
----
Closes: …
=> libct/init_linux: reorder chdir to fix EPERM

libcontainer/integration/execin_test.go
Do help to debug https://github.com/opencontainers/runc/issues/2425.
Previous commit 1909051b9cf (PR #2701) modified the code in the wrong place.
=> libct/int/execin_tty: do help debug a flake

contrib/cmd/recvtty/recvtty.go, libcontainer/init_linux.go, libcontainer/integration/execin_test.go, tty.go, utils_linux.go
The TestExecInTTY test case is sometimes failing like this:
> execin_test.go:332: unexpected carriage-return in output "PID USER TIME COMMAND\r\n 1 root 0:00 cat\r\n 7 root 0:00 ps\r\n"
or this:
> execin_test.go:332: unexpected carriage-return in output "PID USER TIME COMMAND\r\n 1 root 0:00 cat\n 7 root 0:00 ps\n"
(this is easy to repro with `go test -run TestExecInTTY -count 1000`).
This is caused by a race between
- an `Init()` (in this case it is is `(*linuxSetnsInit.Init()`, but
`(*linuxStandardInit).Init()` is no different in this regard),
which creates a pty pair, sends pty master to runc, and execs
the container process,
and
- a parent runc process, which receives the pty master fd and calls
`ClearONLCR()` on it.
One way of fixing it would be to add a synchronization mechanism …
=> Fix a race in tty code leading to \r in output

tests/integration/multi-arch.bash
Due to https://github.com/docker-library/busybox/pull/94 the URLs
to get busybox has *just* changed, so the current URLs give HTTP 404.
Fix the URLs accordingly to bring CI back to :heavy_check_mark: 
NOTE there can be many improvements made to this script, but
the whole point of this PR is to fix CI, and we can work on the rest
of it separately.
=> tests/int/multi-arch.bash: fix busybox URL

libcontainer/init_linux.go
I noticed this was the only place in this function where we didn't handle errors on freezing/thawing. Logging as a warning, consistent with the other cases.
=> libcontainer: signalAllProcesses(): log warning when failing to thaw

tests/integration/hooks.bats
This particular test downloads and unpacks debian from setup(),
but then in many cases the actual test is skipped because it
requires root and no_systemd.
Let's skip it earlier.
=> tests/int/hooks.bats: skip earlier

.github/workflows/validate.yml
This check (for commit subject being short) only make sense for pull
requests, and it fails on pushes to master (i.e. on merges, see e.g.
https://github.com/opencontainers/runc/runs/1711154129?check_suite_focus=true)
Make sure it's only run for pull requests.
=> gha: don't check commits on push

contrib/cmd/recvtty/recvtty.go, libcontainer/init_linux.go, libcontainer/integration/execin_test.go, tty.go
This reverts part of https://github.com/opencontainers/runc/pull/2723, which caused a regression (#2747), and also disables the TestExecInTTY as it is racy per #2425 and I have no idea yet how to fix it.
Fixes: #2747
=> Partially revert #2723

.github/workflows/test.yml, Makefile, Vagrantfile.centos7, script/validate-c
Github Actions execution environments lack tty, which is needed for
integration tests. We have used script utility before to provide a fake
tty, but it appears to be buggy on CentOS 7.
Since we use ssh anyway to access Vagant VM, add -tt to forcefully
allocate a tty.
Apparently, neither "TERM=xterm" nor "stty size" is needed for
the tests to work, so remove those, too.
The benefits of this are:
- simpler code;
- more robust error reporting (I saw failed tests but zero exit code on CentOS 7, presumably an issue with script).
(this also carries some minor cleanups from #2730)
=> GHA: use ssh -tt instead of script tool (and fix CI failure reporting)

events.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/fs/cpuset_test.go, libcontainer/cgroups/fscommon/utils.go, libcontainer/cgroups/stats.go, types/events.go
Adds statistics for cpuset cgroup
Signed-off-by: Piotr Wagner <piotr.wagner@intel.com>
=> Add cpuset statistics

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go, tests/integration/update.bats
Support for systemd properties AllowedCPUs and AllowedMemoryNodes
was added by commit 13afa58d0e46ceb0, but only for unified resources
of systemd v2 driver.
This adds support for Cpu.Cpus and Cpu.Mems resources to
both systemd v1 and v2 cgroup drivers. If systemd is not new
enough to support the properties, a  warning is logged.
An integration test is added to check that the settings work.
While at it:
- log a warning in a different place checking systemd version;
- add version check to systemd unified support handling.
=> libc/cg: convert r.CPU.Cpus/Mems to systemd props

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/v2.go
A recent commit a35cad3b225f8d (PR #2727) added warnings about systemd being
too old. While those warnings are valid, they break some existing tests (e.g. https://github.com/cri-o/cri-o/issues/4509),
and also don't add much value to a user (IOW no one is going to upgrade
systemd because runc says it's old).
Demote those to warnings.
=> libct/cg: demote "systemd is too old" to debug

.github/workflows/validate.yml
It currently takes close to 2 minutes to build docker image
(which is currently only used for cross compilation).
Let's see if caching docker layers will help.
=> gha: cache docker layers to speed up make runcimage

libcontainer/container_linux.go
While working on a test case for #2715, I got the following warning:
> level=warning msg="unable to terminate initProcess" error="exit status 1"
Obviously, the warning is bogus since the initProcess is terminated.
This is happening because terminate() can return errors from either
Kill() or Wait(), and the latter returns an error if the process has
not finished successfully (i.e. exit status is not 0 or it was killed).
Check for a particular error type and filter out those errors.
=> libct: suppress bogus "unable to terminate" warnings

libcontainer/cgroups/systemd/user.go, rootless_linux.go
`shouldUseRootlessCgroupManager()` was always returning true when we are inside a userns.
If the systemd OwnerUID is 0, we have rootful systemd inside the userns, and we can just use the rootful cgroup driver.
Fix #2724
=>  systemd: fix rootful-in-userns regression

libcontainer/configs/config_test.go
Test that CommandHook actually executes a new process with the given env
variables, parameters and json state.
This commit also solves an issue with the previous approach that was calling
'os.Exit(0)' failing to signal test failures.
cc @alban 
Fixes: #2765
=> libcontainer/configs: improve unit tests

libcontainer/user/user.go, libcontainer/user/user_test.go, libcontainer/utils/utils.go
For #941
Replaces #1821
Rewrite #1080
Closes #1821 
On master it still fails to compile the test on 32bit arch.
```
$ GOARCH=386 go test -v ./libcontainer/user/
libcontainer/user/user_test.go:448:38: constant 2147483648 overflows int
FAIL    github.com/opencontainers/runc/libcontainer/user [build failed]
FAIL
```
=> Fix int overflow in test on 32 bit system

libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go, libcontainer/cgroups/systemd/cpuset_test.go, libcontainer/cgroups/utils_test.go
Remove or comment out some `t.Logf` statements in unit tests. See individual commits for details.
=> ci/unit tests: decrease verbosity

libcontainer/rootfs_linux.go
Commit 9c1242ecb ("Add white list for bind mount chec", Jan 6 2016)
added a set of entries under /proc which we allow to be mounted to,
for the benefit of lxcfs-like fuse-backed hack to have container's
own version of /proc/meminfo etc.
For some reason, the allow list check is performed at the very
beginning of the function, which is not optimal.
Move the check to the end -- at this point in the code we already
know we're under /proc, so it make sense to consult the allow list.
This makes the code slightly more logical and hopefully slightly faster.
=> libct/checkProcMounts: optimize

libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/cgroups/fs/name.go
This is a rewrite of getPageUsageByNUMA, fixing a number of issues.
0. Fix a panic for lines that do not contain `=` (first commit, by @Ace-Tang).
1. Be less strict to unknown contents, i.e. skip it. This makes the
function more future-proof. Before this commit, if a line like
"a=b" is encountered, the function returns an error, which is
propagated all the way up to and returned by (CgroupManager).GetStats.
2. Be more strict to contents it recognizes, i.e. return an error.
In case the first field in the line is recognized (e.g. "total=123",
the rest of the line should be in format "N<id>=<value> ...".
3. Optimize. Before this commit, addNUMAStatsByType was called for every
item in the line, which is excessive and might even be slow in case
there are many NUMA nodes. It is enough to look …
=> libct/cg/fs: getPageUsageByNUMA: rewrite/optimize, fix panic, add more tests

libcontainer/cgroups/fs/cpuset.go
The merge 6eed6e579596 broke the build because ab27e12cebf1 ("Implement
GetStat for cpuset cgroup.") dropped the errors import which was used by
c85cd2b3254a ("libct/cg/fs/cpuset: don't parse mountinfo") and the CI
wasn't retriggered.
Fix this by just importing "github.com/pkg/errors" again.
=> cgroupfs: cpuset: fix broken build

libcontainer/seccomp/patchbpf/enosys_linux.go
The correct way to do that conversion according to
https://pkg.go.dev/syscall#Errno is:
```
err = nil
if errno != 0 {
err = errno
}
```
In this case the error check will always report a false positive in
unix.RawSyscall(unix.SYS_SECCOMP, ...), probably nobody has faced this
problem because the code takes the other path in most of the cases.
I found that while rebasing https://github.com/opencontainers/runc/pull/2682. 
cc @cyphar
=> libcontainer: fix bad conversion from syscall.Errno to error

.github/workflows/test.yml
download.fedoraproject.org gives HTTP 404 at times
(I think I have seen it at least 3 times this week),
breaking the CI. Let's give it another chance.
=> ci/gha/fedora: retry vagrant up

utils.go
We use github.com/pkg/errors to produce an error in many places.
One of its benefits is error comes with a stack trace.
Let's print that stack trace if --debug is given.
Example:
ERRO[0000] container id cannot be empty
DEBU[0000] container id cannot be empty
main.init
github.com/opencontainers/runc/utils_linux.go:28
runtime.doInit
runtime/proc.go:5652
runtime.main
runtime/proc.go:191
runtime.goexit
runtime/asm_amd64.s:1374
=> Show error stack trace if --debug is given

.github/workflows/validate.yml, .golangci.yml
This is to enable seccomp build tag (some linters do use tags,
some don't).
Related to https://github.com/opencontainers/runc/issues/2778
~~NOTE i have temporary added a commit to test/report all the issues
(rather than only those brought by a PR) -- this is needed to see how
the newly added commit with a build tag works. I will remove the commit later.~~ Removed
=> .golangci.yml: add

libcontainer/cgroups/fs2/devices.go
In the past we incorrectly handled eBPF errors in two ways:
1. We would only ignore errors if there was an allow rule in the list
(this doesn't make sense because for security purposes we only care
if a *deny* rule is being ignored). Arguably this is a security flaw
but you would only get an error from bpf(2) in rare cases, and thus
is not a big enough deal to go through security review.
2. If we were in a rootless container we would still return an error
even though bpf(2) is blocked for rootless containers.
Fixes #2792 
=> cgroup2: devices: handle eBPF skipping more correctly

libcontainer/cgroups/ebpf/devicefilter/devicefilter.go, libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go, tests/integration/dev.bats, tests/integration/testdata/dev_access_test.c
I was trying to expose a host character device to a container on a system with `cgroup v2` enabled. Looks like there is an issue with  permissions checking in the device filtering `ebpf` program that is loaded and attached to the container's cgroup.
This PR fixes the issue when a call to 
access(dev_name, F_OK)
from a container fails with `EPERM` error even though the permissions for the device file are set to `rw`. The problem is not reproducible with `rwm` as in this case the check for permissions is skipped. Similar solution is used in systemd:
https://github.com/systemd/systemd/blob/8e45c72cf581a2224725469376d13ca4dcd77a74/src/core/bpf-devices.c#L145
I built and verified locally the proposed solution and also fixed the unit-tests accordingly. Hope the fix might be usefull. …
=> ebpf: fix device access check

README.md
Note that validate currently fails on master -- this is tracked
in https://github.com/opencontainers/runc/issues/2627.
=> README: add gha badges

.github/workflows/test.yml
As the final go 1.16 is released, rc1 is no longer available.
This fixes our CI.
=> ci/gha: bump go 1.16-rc1 -> 1.16.x; fix gha ci

libcontainer/devices/devices.go, libcontainer/devices/devices_test.go, libcontainer/specconv/spec_linux.go
The file mode of the device does not contain file type bits
`mode &^ unix.S_IFMT` should be added when setting device.FileMode.
Fix containerd: https://github.com/containerd/containerd/pull/5028
Discussions about FileMode: https://github.com/opencontainers/runtime-spec/pull/1082
=> libcontainer: fix the file mode of the device

libcontainer/README.md
Hi there!
In latest version v1.0.0-rc93 of runc, the following code written in [README.md for libcontainer](https://github.com/opencontainers/runc/blob/master/libcontainer/README.md) is not working, so I updated the README.md
```
config := &configs.Config{
Rootfs: "/your/path/to/rootfs",
Capabilities: &configs.Capabilities{
Bounding: []string{
"CAP_CHOWN",
"CAP_DAC_OVERRIDE",
"CAP_FSETID",
"CAP_FOWNER",
"CAP_MKNOD",
"CAP_NET_RAW",
"CAP_SETGID",
"CAP_SETUID",
"CAP_SETFCAP",
"CAP_SETPCAP",
"CAP_NET_BIND_SERVICE",
"CAP_SYS_CHROOT",
"CAP_KILL",
"CAP_AUDIT_WRITE",
},
Cgroups: &configs.Cgroup{
Name:   "test-container",
Parent: "system",
Resources: &configs.Resources{
MemorySwappiness: nil,
Devices:          specconv.AllowedDevices, // This code is not working(cannot use specconv.AllowedDevices …
```
=> Update README.md for libcontainer

libcontainer/cgroups/fs2/memory.go
In cgroup v2, the "cache" value from cgroup v1 is called "file" in v2.
There are no values called "cache" in v2.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/mm/memcontrol.c?id=31caf8b2a847214be856f843e251fc2ed2cd1075#n1521
=> Fix memory stats for cache in fs2

libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go
All cgroup managers has Apply() and Set() methods:
- Apply is used to create a cgroup (and, in case of systemd,
a systemd unit) and/or put a PID into the cgroup (and unit);
- Set is used to set various cgroup resources and limits.
The fs/fs2 cgroup manager implements the functionality as described above.
The systemd v1/v2 manager deviate -- it sets *most* of cgroup limits
(those that can be projected to systemd unit properties) in Apply(),
and then again *all* cgroup limits in Set (first indirectly via systemd
properties -- same as in Apply, then via cgroupfs).
This commit removes setting the cgroup limits from Apply,
so now the systemd manager behaves the same way as the fs manager.
Fixes: #2813
=> libct/cgroups/systemd: don't set limits in Apply

tests/integration/README.md, tests/integration/cgroups.bats, tests/integration/checkpoint.bats, tests/integration/create.bats, tests/integration/cwd.bats, tests/integration/debug.bats, tests/integration/delete.bats, tests/integration/dev.bats, tests/integration/events.bats, tests/integration/exec.bats, tests/integration/helpers.bash, tests/integration/hooks.bats, tests/integration/kill.bats, tests/integration/list.bats, tests/integration/mask.bats, tests/integration/mounts.bats, tests/integration/no_pivot.bats, tests/integration/pause.bats, tests/integration/ps.bats, tests/integration/root.bats, tests/integration/seccomp.bats, tests/integration/spec.bats, tests/integration/start.bats, tests/integration/start_detached.bats, tests/integration/start_hello.bats, tests/integration/state.bats, tests/integration/tty.bats, tests/integration/umask.bats, tests/integration/update.bats
The ultimate idea is to parallelize running the integration tests.
So far just some preliminary cleanups, mostly resulting in simpler setup/cleanup
and laying the ground for parallel tests (every test is run in its own set of dirs and cgroups).
=> tests/int: cleanups

.github/workflows/test.yml, Makefile, libcontainer/configs/config.go, libcontainer/integration/checkpoint_test.go
1. As reported by go test -race ./libcontainer/configs:
```
=== RUN   TestCommandHookRunTimeout
==================
WARNING: DATA RACE
Read at 0x00c000202230 by goroutine 23:
os/exec.(*Cmd).Wait()
/usr/lib/golang/src/os/exec/exec.go:502 +0x91
github.com/opencontainers/runc/libcontainer/configs.Command.Run()
/home/kir/go/src/github.com/opencontainers/runc/libcontainer/configs/config.go:390 +0x58c
github.com/opencontainers/runc/libcontainer/configs_test.TestCommandHookRunTimeout()
/home/kir/go/src/github.com/opencontainers/runc/libcontainer/configs/config_test.go:223 +0x3ed
testing.tRunner()
/usr/lib/golang/src/testing/testing.go:1123 +0x202
Previous write at 0x00c000202230 by goroutine 27:
os/exec.(*Cmd).Wait()
/usr/lib/golang/src/os/exec/exec.go:505 +0xb4 …
```
=> Fix data races, enable testing with -race

libcontainer/cgroups/cgroups.go, libcontainer/cgroups/fs/cpu.go, libcontainer/cgroups/fs/cpu_test.go, libcontainer/cgroups/fs/fs.go, libcontainer/cgroups/fs/memory.go, libcontainer/cgroups/fs/memory_test.go, libcontainer/cgroups/fs2/cpu.go, libcontainer/cgroups/fs2/fs2.go, libcontainer/cgroups/fs2/hugetlb.go, libcontainer/cgroups/fs2/memory.go, libcontainer/cgroups/fscommon/utils.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go, libcontainer/container_linux.go, libcontainer/container_linux_test.go, libcontainer/notify_linux_v2.go, libcontainer/process_linux.go, tests/integration/cgroups.bats, tests/integration/update.bats
This improves runc error reporting in cases where memory limit is set too low.
NOTE that while this is clearly an enhancement I want this in rc94 because
- it does not change runc behavior other than error text;
- it helps a lot with some issues reported by customers.
On cgroup v1 + fs driver, setting memory.limit_in_bytes results in EBUSY. This is reported as
> ERRO[0000] container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: failed to write "1000": write /sys/fs/cgroup/memory/user.slice/user-1000.slice/session-1011.scope/xe3/memory.limit_in_bytes: device or resource busy
To decipher the error a user needs to know that EBUSY is returned by the kernel when the limit …
=> Better handle hitting the memory limit

.github/workflows/test.yml, libcontainer/seccomp/patchbpf/enosys_linux_test.go
Run unit tests on i386. This might help to uncover some issues in the code related to 32-bit arches.
=> ci/gha: add i386 unit test

libcontainer/factory_linux.go, libcontainer/factory_linux_test.go
This commit adjusts the file mode to use the latest golang style
Related to #2625
BTW, I think we should not only modify the file mode from the old style to the latest style but also check whether the current implementation sets proper file permissions.
So, I will create the PRs each subsystem or codes and I may create the new issue to summarize this activity.
=> libcontainer/factory*: adjust the file mode

.github/workflows/validate.yml, tests/integration/get-images.sh
Sometimes github gives up 5xx errors, for example:
> panic: getImages error exit status 1 (output: curl: (22) The requested URL returned error: 502
> Failed to get https://github.com/docker-library/busybox/raw/dist-i386/stable/glibc/busybox.tar.xz
(from https://github.com/opencontainers/runc/pull/2807#issuecomment-791031846)
This is unfortunate but temporary, and adding --retry should handle
at least some cases, improving CI stability.
=> curl: add --retry 5

tests/integration/checkpoint.bats
Sometimes the test fails without any clear diagnostics:
> not ok 16 checkpoint --lazy-pages and restore
> (in test file tests/integration/checkpoint.bats, line 191)
>  `[ "$out" = "0000000 000000 0000001" ]' failed
> ...
> criu failed: type NOTIFY errno 3\nlog file: work-dir/dump.log
We look for and print errors via grep, but in the above case
there are nothing that is denoted error in the log.
So, let's show the damn log in its entirely (note it is only shown
if test fails).
Hope it will help with #2760
=> tests/checkpoint: show full log lazy pages cpt

go.mod, go.sum, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/state.go, vendor/modules.txt
just to keep up with upstream
full diff: https://github.com/opencontainers/runtime-spec/compare/e6143ca7d51d...a8c4a9ee0f6b
=> go.mod: runtime-spec v1.0.3-0.20210316141917-a8c4a9ee0f6b

libcontainer/container_linux.go, tests/integration/checkpoint.bats
This tries to fix https://github.com/opencontainers/runc/issues/2748
This change is motivated by the work in https://github.com/kubernetes/kubernetes/pull/97194
During restore CRIU mounts all mounts as they were during checkpointing. Using nested bind mounts this can lead to situation where a mountpoint in the parent bind mount is missing.
During initial container creation 'runc' mounts a bind mount and then creates the mountpoints for nested mountpoints.
This PR changes `runc` to also mount all bind mounts before telling CRIU to restore the container to re-create missing mountpoints.
=> Correctly restore containers with nested bind mounts

libcontainer/apparmor/apparmor_linux.go
I recalled I added a similar change in containerd, but didn't upstream it here. Also removing `bytes.HasPrefix()` in favor of just checking the first character
=> libcontainer/apparmor: use sync.Once for AppArmor detection

libcontainer/capabilities/capabilities.go, libcontainer/capabilities/capabilities_linux_test.go
This extracts the refactoring commits from https://github.com/opencontainers/runc/pull/2854
=> capabilities.Caps: use a map for capability-types

script/check-config.sh
CONFIG_SECCOMP_FILTER is actually used in runc.
=> script/check-config.sh: add CONFIG_SECCOMP_FILTER

libcontainer/cgroups/fs2/io.go, libcontainer/cgroups/utils.go, libcontainer/cgroups/utils_test.go, tests/integration/cgroups.bats
if bfq is not loaded, then io.bfq.weight is not available. io.weight
should always be available and is the next best equivalent thing.
Signed-off-by: Daniel Dao <dqminh89@gmail.com>
=> fs2: fallback to setting io.weight if io.bfq.weight

init.go, libcontainer/container_linux.go, libcontainer/container_linux_test.go, libcontainer/factory_linux.go, libcontainer/init_linux.go, libcontainer/logs/logs.go, libcontainer/logs/logs_linux_test.go, libcontainer/process_linux.go, libcontainer/restored_process.go, libcontainer/setns_init_linux.go, libcontainer/standard_init_linux.go, main.go, tests/integration/debug.bats, tests/integration/exec.bats
_(originally developed in #2487; decided to split for clarity)_
Sometimes debug.bats test cases are failing like this (issue #2756):
```
not ok 27 global --debug to --log --log-format 'json'
```
It happens more often while writing to disk.
The issue is caused by the fact that runc spawns log forwarding goroutine
(`ForwardLogs`) but does not wait for it to finish, resulting in missing
debug lines from nsexec.
`ForwardLogs` itself, though, never finishes, because it reads from a
reading side of a pipe whose writing side is not closed. This is
especially true in case of `runc create`, which spawns `runc init` and
exits; meanwhile `runc init` waits on exec fifo for some undetermined long
time before doing execve.
So, to fix the issue described above, we need to:
1. Make runc create/run/exec …
=> Fix init log forwarding race

.github/workflows/test.yml
For deflaking CI failures during `vagrant up`
=> CI: cache ~/.vagrant.d/boxes

tests/integration/checkpoint.bats
This is to help debug https://github.com/opencontainers/runc/issues/2805
=> tests/int/cpt: better debug

script/check-config.sh
SELinux and AppArmor are always enabled since runc v1.0.0-rc93
=> script/check-config.sh: add SELinux and AppArmor

libcontainer/container_linux.go, libcontainer/integration/exec_test.go
_this is an alternative for https://github.com/opencontainers/runc/pull/2794_
TL;DR: Fix two cases of fd leaks on run, added a test case to avoid more in the future.
1. **libct: close execFifo after start**
Apparently, the parent never closes execFifo fd. Not a problem for runc
per se, but can be an issue for a user of libcontainer.
2. **libct: close log pipe**
~~Otherwise we have one extra fd opened after container.Run.~~
Commit removed (obsoleted by #2835)
3. **libct/int: add TestFdLeaks**
This is a very simple test that checks that container.Run do not leak
opened file descriptors.
In fact it does, so we have to add two exclusions:
1. `/sys/fs/cgroup` directory is opened once per lifetime in `prepareOpenat2()`,
provided that cgroupv2 is used and openat2 is available. This
works as …
=> libct: fix some container.Run fd leaks, add fd leak test

libcontainer/seccomp/patchbpf/enosys_linux.go, libcontainer/seccomp/patchbpf/enosys_linux_test.go
Not reading from the seccomp pipe might get the ExportBRF function stuck
on writing to the seccomp pipe if its buffer is full (i.e. the writer
wrote more than 65K of data). Reading from the read end of the pipe
asynchronously prevents this from happening.
We have seen the issue in real environments when the system is under heavy load. No idea why it does not always happen, but as demonstrated by the unit test, the issue is real.
(Potentially) related issue:
https://github.com/opencontainers/runc/issues/2530#issuecomment-800690556
https://github.com/opencontainers/runc/issues/2865
cc @cloudfoundry/cf-garden
=> Ensure the seccomp pipe is being read while exporting bpf

go.mod, go.sum, libcontainer/capabilities/capabilities.go, libcontainer/capabilities/capabilities_linux_test.go, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/sirupsen/logrus/hooks/test/test.go, vendor/modules.txt
full diff: https://github.com/opencontainers/runtime-spec/compare/a8c4a9ee0f6b...1c3f411f0417
- Fix seccomp notify inconsistencies
- seccomp: Add missing const for seccomp notify action
- schema/defs-linux: Fix inconsistencies with seccomp notify
- Proposal: runtime should ignore capabilities that cannot be granted
This updates handling of capabilities to match the updated runtime specification,
in https://github.com/opencontainers/runtime-spec/pull/1094.
Prior to that change, the specification required runtimes to produce a (fatal)
error if a container configuration requested capabilities that could not be
granted (either the capability is "unknown" to the runtime, not supported by the
kernel version in use, or not available in the environment that the runtime
operates in).
This caused …
=> capabilities: WARN, not ERROR, for unknown / unavailable capabilities

libcontainer/configs/validate/rootless.go, libcontainer/configs/validate/validator.go
Noticed this when looking through the changes in https://github.com/opencontainers/runc/pull/2855
(this one will need to be updated if that one is merged first)
=> libcontainer/configs/validate: make Validate() less DRY

go.mod, go.sum, vendor/github.com/moby/sys/mountinfo/mountinfo.go, vendor/github.com/moby/sys/mountinfo/mountinfo_filters.go, vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go, vendor/modules.txt
full diff: https://github.com/moby/sys/compare/v0.4.0...v0.4.1
github.com/moby/sys/mountinfo v0.4.1
-----------------------------------------
- Fix PrefixFilter() being too greedy
- TestMountedBy*: add missing pre-checks
- Documentation improvements
=> go.mod: github.com/moby/sys/mountinfo v0.4.1

libcontainer/configs/config.go
Commit ccdd75760c1f2d2be2dbb21522b67ceab28fd901 (https://github.com/opencontainers/runc/pull/2229) introduced the HookName type for hooks, but only set this type on the Prestart const, but not for the other hooks.
=> libcontainer/configs: add missing type for hooknames

libcontainer/container_linux.go, tests/integration/cgroups.bats, tests/integration/checkpoint.bats, tests/integration/delete.bats, tests/integration/helpers.bash, tests/integration/update.bats
Fixes https://github.com/opencontainers/runc/issues/2805
See all commits for descriptions. Most important ones are:
"checkpoint --lazy-pages and restore" test sometimes fails on restore
in our CI on Fedora 33 when systemd cgroup driver is used:
> (00.076104) Error (compel/src/lib/infect.c:1513): Task 48521 is in unexpected state: f7f
> (00.076122) Error (compel/src/lib/infect.c:1520): Task stopped with 15: Terminated
> ...
> (00.078246) Error (criu/cr-restore.c:2483): Restoring FAILED.
I think what happens is
1. The test runs runc checkpoint in lazy-pages mode in background.
2. The test runs criu lazy-pages in background.
3. The test runs runc restore.
Now, all three are working in together: criu restore restores, criu
lazy-pages listens for page faults on a uffd and fetch missing pages …
=> tests/int: some refactoring, fix a flake

libcontainer/init_linux.go, tests/integration/cwd.bats
Alas, the EPERM on chdir saga continues...
Unfortunately, the there were two releases between when https://github.com/opencontainers/runc/commit/5e0e67d76cc99d76c8228d48f38f37034503f315  was released
and when the workaround https://github.com/opencontainers/runc/pull/2712 was added.
Between this, folks started relying on the ability to have a workdir that the container user doesn't have access to.
Since this case was previously valid, we should continue support for it.
Now, we retry the chdir:
Once at the top of the function (to catch cases where the runc user has access, but container user does not)
and once after we setup user (to catch cases where the container user has access, and the runc user does not)
Add a test case for this as well.
Signed-off-by: Peter Hunt <pehunt@redhat.com>
=> libct/init_linux: retry chdir to fix EPERM (regression in rc93)

go.mod, go.sum, vendor/github.com/containerd/console/README.md, vendor/github.com/containerd/console/console_unix.go, vendor/github.com/containerd/console/go.mod, vendor/github.com/containerd/console/go.sum, vendor/github.com/containerd/console/pty_freebsd_cgo.go, vendor/github.com/containerd/console/pty_freebsd_nocgo.go, vendor/github.com/containerd/console/pty_unix.go, vendor/github.com/containerd/console/tc_freebsd_cgo.go, vendor/github.com/containerd/console/tc_freebsd_nocgo.go, vendor/modules.txt
This is to include https://github.com/containerd/console/pull/51
Fixes: https://github.com/opencontainers/runc/issues/2896
* fix terminal for big-endian architectures like s390 (regression in rc93)
=> vendor: bump containerd/console to 1.0.2

libcontainer/cgroups/fs/fs.go, libcontainer/cgroups/fs2/fs2.go, libcontainer/cgroups/systemd/v2.go
PR #2812 (commit 5d0ffbf9c81f) added OOM kill count checking and better container
start/run/exec error reporting in case we hit OOM.
It also introduced warnings like these:
> level=warning msg="unable to get oom kill count" error="openat2 /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/test_hello/memory.events: no such file or directory"
In case of rootless containers, unless cgroup is delegated or systemd is
used, runc can not create a cgroup and thus it fails to get OOM kill
count. This is expected, and the warning should not be shown in this
case.
=> libct/cg: don't return OOMKillCount error when rootless

libcontainer/rootfs_linux.go, tests/integration/start_hello.bats
Currently, runc fails like this when used from rootless podman
with host PID namespace:
> $ podman --runtime=runc run --pid=host --rm -it busybox sh
> WARN[0000] additional gid=10 is not present in the user namespace, skip setting it
> Error: container_linux.go:380: starting container process caused:
> process_linux.go:545: container init caused: readonly path /proc/asound:
> operation not permitted: OCI permission denied
(Here /proc/asound is the first path from OCI spec's readonlyPaths).
The code uses `MS_BIND|MS_REMOUNT` flags that have a special meaning in
the kernel ("keep the flags like nodev, nosuid, noexec as is").
For some reason, this "special meaning" trick is not working for the
above use case (rootless + host PID namespace)~~, and I don't know~~
~~how to reproduce this …
=> runc run: fix readonly path error for rootless + host pidns

libcontainer/cgroups/fs2/cpu.go
This adds cfs throttle stats to cgroup v2.
More info here: https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html
Tried adding a test, but cgroup v2 have no tests, and the test infrastructure is tightly coupled with cgroup v1. Adding test infra to v2 is outside the scope of this PR.
=> Add cfs throttle stats to cgroup v2

tests/fuzzing/oss_fuzz_build.sh
THis fixes incorrect module path and also add proper tags for
FuzzUIDMap.
Bug: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32109#c1
Signed-off-by: Daniel Dao <dqminh89@gmail.com>
=> Fix oss-fuzz build

libcontainer/cgroups/fs/freezer.go
Function `(*FreezerGroup).Set` has a few paths where in can return an
error. In any case, if an error is returned, we failed to freeze,
and we need to thaw to avoid leaving the cgroup in a stuck state.
This is a continuation of #2791 and #2774, addressing #2753 and similar bugs.
=> libct/cg/fs/freezer: make sure to thaw on failure

libcontainer/configs/validate/validator.go, libcontainer/configs/validate/validator_test.go, libcontainer/specconv/spec_linux.go
According to OCI spec, mount destination MUST be an absolute path. We never validate it, I think we should.
Add validation to both specconv and configs/validate, and error out on non-abs paths.
=> Validate mounts

libcontainer/container_linux.go, libcontainer/init_linux.go, libcontainer/rootfs_linux.go, libcontainer/specconv/example.go, tests/integration/cgroups.bats
In case of rootless, cgroup2 mount is not possible (see https://github.com/opencontainers/runc/issues/2158
for more details), so since commit 9c81440fb5a7 runc bind-mounts the whole
/sys/fs/cgroup into container.
Problem is, if cgroupns is enabled, /sys/fs/cgroup inside the container
is supposed to show the cgroup files for this cgroup, not the root one.
The fix is to pass through and use the cgroup path in case cgroup2
mount failed, cgroupns is enabled, and the path is non-empty.
Before:
$ ./runc run aaa
/sys/fs/cgroup
/sys/fs/cgroup/user.slice
/sys/fs/cgroup/user.slice/user-1000.slice
/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service
...
-r--r--r--    1 nobody   nogroup          0 Feb 24 02:22 /sys/fs/cgroup/cgroup.controllers
142 /sys/fs/cgroup/cgroup.procs
cat: can't open …
=> Fix cgroup2 mount for rootless case

libcontainer/logs/logs.go, main.go
This helps a lot to find out where the errors come from.
Before:
> level=warning msg="lstat /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/test_hello: no such file or directory"
After:
> level=warning msg="lstat /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/test_hello: no such file or directory" func=github.com/opencontainers/runc/libcontainer.destroy file="github.com/opencontainers/runc/libcontainer/state_linux.go:44"
Presumably this comes with an overhead, but I guess no one is using
`--debug` by default anyway.
PS I'd love to cut the 'github.com/opencontainers/runc/` prefix but don't see an easy way to :-\
=> logging: enable file/line info if --debug is set

libcontainer/cgroups/fs/fs_test.go, libcontainer/cgroups/fscommon/open.go, libcontainer/cgroups/fscommon/utils_test.go
Commit 88e8350de28 (PR #2169), among the other things, replaced filepath.Join with
securejoin.SecureJoin for both reads and writes to cgroupfs.
Commits e76ac1c054 and 31f0f5b7e03a (PR #2604) switched more code to use
`fscommon.ReadFile` (and thus `securejoin`). Commit 0228226e6d (PR #2635) introduced
`fscommon.OpenFile` (which uses `securejoin` as a fallback if `openat2(2)` is not available,
which is the case for older kernels), and commit c95e69007c4 (PR #2635) switched
most of cgroup/fs[2] code to use it.
As a result, `fs.GetStats()` method became noticeable slower, mostly due
to securejoin calling `os.Lstat` and `filepath.Clean`.
Using securejoin as a security measure for cgroupfs files is
not well justified, as cgroupfs do not contain symlinks, and none of the
code using it have …
=> Fix fsmanager.GetStats performance (regression in rc93)

libcontainer/cgroups/systemd/common.go
These are deprecated, but pkg.go.dev does not make that very clear; https://pkg.go.dev/github.com/coreos/go-systemd/v22/dbus#Conn.StopUnitContext
It also does a really lame job at pointing out that you're reading the "latest version" of an "ancient" release
relates to https://github.com/opencontainers/runc/pull/2923
=> cgroups/systemd: replace deprecated dbus functions

libcontainer/nsenter/cloned_binary.c
We shouldn't refuse to build on architectures just because we don't know
what the syscall number of memfd_create(2) is. In addition, use the
correct defined(...) macros for ppc64 (these are the ones glibc uses).
Fixes: 3aead32ea246 ("nsenter: hard-code memfd_create(2) syscall numbers")
=> cloned_binary: switch from #error to #warning for SYS_memfd_create

Makefile
This is required for environments/build systems where a specific
go version / command needs to be used.
Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>
=> Makefile: allow overriding go command by environment

libcontainer/integration/checkpoint_test.go, libcontainer/integration/exec_test.go, libcontainer/integration/execin_test.go, libcontainer/integration/seccomp_test.go, libcontainer/integration/template_test.go, libcontainer/integration/utils_test.go
Please see individual commits for details. Nothing serious, but improved container names and cgroups randomization might help to reduce flakes.
=> libct/int: misc cleanups and fixes

libcontainer/cgroups/fs/freezer.go
I hate to keep adding those kludges (for earlier ones, see #2918, #2791, #2774)
but lately TestFreeze (and TestSystemdFreeze) from libcontainer/integration
fails a lot (see #2907).
The failure comes and goes, and is probably this is caused by a slow host
allocated for the test, and a slow VM on top of it.
To remediate, add a small sleep on every 25th iteration in between
asking the kernel to freeze and checking its status.
In the worst case scenario (failure to freeze), this adds about 0.4 ms
(40 x 10 us) to the duration of the call.
It is hard to measure how this affects CI as GHA plays a roulette when
allocating a node to run the test on, but it seems to help. With
additional debug info, I saw somewhat frequent "frozen after 24 retries"
or "frozen after 49 retries", meaning it succeeded …
=> freezer: add delay after freeze

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/dbus.go, libcontainer/cgroups/systemd/v2.go, libcontainer/integration/exec_test.go
TL;DR: fixes a regression (open fd leak) caused by PR #2923. *This is an alternative to #2936.*
When running libcontainer/integration/TestSystemdFreeze 2000 times,
I got "too many open files" error after a while:
```console
[vagrant@localhost integration]$ sudo -E PATH=$PATH ./integration.test -test.v -test.run Freeze -test.count 2000
<...>
=== RUN   TestFreeze
--- PASS: TestFreeze (0.28s)
=== RUN   TestSystemdFreeze
--- PASS: TestSystemdFreeze (0.42s)
=== RUN   TestFreeze
utils_test.go:86: exec_test.go:536: unexpected error: container_linux.go:380: starting container process caused: process_linux.go:338: starting init process command caused: fork/exec /proc/self/exe: too many open files
--- FAIL: TestFreeze (0.16s)
=== RUN   TestSystemdFreeze
utils_test.go:86: exec_test.go:536: …
```
=> libct/cg/sd: fix dbus connection leak (alternative)

checkpoint.go, restore.go, tests/integration/checkpoint.bats
Criu creates symlink named "parent" under image-path while doing
interactive checkpoint, without checking wether symlink points to
right place. This patch corrects related test case.
Signed-off-by: Liu Hua <weldonliu@tencent.com>
=> tiny fix iterative checkpoint test case

EMERITUS.md
It's long past due that we recognise former maintainers for their work.
=> EMERITUS: recognise previous maintainers

libcontainer/integration/checkpoint_test.go, libcontainer/integration/utils_test.go
Please see individual commits for details. Nothing major but nice to have.
=> libcontainer/integration: nits

libcontainer/intelrdt/intelrdt_test.go
1. These tests can't be run in parallel since they do check
a global variable (`mbaScEnabled`).
2. `findIntelRdtMountpointDir()` relies on `mbaScEnabled` to be initially
set to the default value (`false`) and this the test fails if run
more than once:
> go test -count 2
> ...
> intelrdt_test.go:243: expected mbaScEnabled=false, got true
>    --- FAIL: TestFindIntelRdtMountpointDir/Valid_mountinfo_with_MBA_Software_Controller_disabled (0.00s)
Fixes: 2c70d2384 (PR #2606)
=> libct/intelrdt: fix unit test

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/cpuset.go, libcontainer/cgroups/systemd/cpuset_test.go, libcontainer/cgroups/systemd/v2.go
It's both a useful function, and sufficiently complex to discourage copying
Signed-off-by: Peter Hunt <pehunt@redhat.com>
=> libctr/cg/systemd: export rangeToBits

.github/workflows/validate.yml, libcontainer/cgroups/ebpf/devicefilter/devicefilter.go, libcontainer/cgroups/fs/memory.go, libcontainer/integration/seccomp_test.go, libcontainer/seccomp/patchbpf/enosys_linux_test.go, libcontainer/system/proc.go
Most of these were false positives or cases where we want to ignore the
lint, but the change to the BPF generation is actually useful.
Follow-up to #2781
=> *: clean up remaining golangci-lint failures

Makefile, main.go
Two things:
1. `runc -v`: set default for, always show `main.version`
Apparently not everyone compiles runc via the provided Makefile. For
example, one can just run `go build`, in which case `version` variable
is left empty, which leads to:
$ ./runc -v
runc version spec: 1.0.2-dev
go: go1.16.3
Surely, the main problem here is runc was built in a wrong way, but the
second problem is such output is very confusing -- it may seem that we
have runc 1.0.2.
To solve, make sure to _always_ add version (even if empty), plus set a
default value in case someone compiles runc in a wrong way.
$ ./runc -v
runc version unknown
spec: 1.0.2-dev
go: go1.16.3
NOTE this does not change anything in case runc is compiled normally
(via the Makefile).
2. `Makefile`: use `git describe` for `COMMIT`
Use `git …
=> Fix/improve runc -v

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/v1.go
_Fixes the source of the error seen at https://github.com/opencontainers/runc/pull/2944#issuecomment-834819690_
Historically, we never returned an error from failed `startUnit`
or `stopUnit`. The `startUnit` case was fixed by commit 3844789 (PR #2614).
It is time to fix `stopUnit`, too. The reasons are:
1. Ignoring an error from `stopUnit` means an unexpected trouble down the
road, for example a failure to create a container with the same name:
> time="2021-05-07T19:51:27Z" level=error msg="container_linux.go:380: starting container process caused: process_linux.go:385: applying cgroup configuration for process caused: Unit runc-test_busybox.scope already exists."
2. A somewhat short timeout of 1 second means the cgroup might
actually be removed a few seconds later but we might have a …
=> libct/cg/sd: return error from stopUnit

tests/integration/dev.bats
The "runc run [device cgroup allow rm block device]" test calls lsblk
three times to get device name, minor and major number. This creates a
potential problem when the devices are changed between the calls.
Simplify the code by using bash read together with IFS (as there's no
way to have lsblk output MAJOR:MINOR pair without a semicolon).
Note that head -n 1 is not needed as read already reads a single line.
=> tests/int/dev: only call lsblk once

libcontainer/cgroups/fs2/io.go, libcontainer/cgroups/fs2/io_test.go
Kubelet and cAdvisor depend on the metrics having the same values as in
cgroupv1, but we didn't correctly map the number of read and write IOs
to the correct cgroupv1 stats table (blkio.io_serviced).
In addition, don't leak any extra stats in our output -- if users need
that information we can always add a new field for it.
Change-log entry:
```
* cgroupv2: correctly convert "number of IOs" statistics in a cgroupv1-compatible way (#2967, #2964)
* cgroupv2: support larger than 32-bit IO statistics on 32-bit architectures
```
Fixes #2967
Reported-by: Yashpal Choudhary <yashpal.c1995@gmail.com>
=> cgroup2: map io.stats to v1 blkio.stats correctly

docs/terminals.md
Explain where the "/dev/tty: no such device or address" error is coming
from, and provide ways to solve the issue.
For more background, see https://github.com/opencontainers/runc/issues/2970
=> docs/terminals.md: add troubleshooting

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/systemd_test.go
This fixes `isDbusError` function, introduced by commit bacfc2c. Due to a
type error it was not working at all.
This also fixes the whole "retry on dbus disconnect" logic, introduced
in PR #2923. Most probably it was not working at all before this fix.
This also fixes a regression in `startUnit` (and `cgroupManager.Apply()`),
which should never return "unit already exists" error but it did (#2996).
A test case is added to check that the last issue is fixed.
Fixes: bacfc2c
Fixes: https://github.com/opencontainers/runc/issues/2996
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1941456
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1965545
* cgroups/systemd: fixed "retry on dbus disconnect" logic introduced in rc94
* cgroups/systemd: fixed returning "unit already exists" error from a …
=> [rc94 regression] libct/cg/sd: fix dbus error handling

libcontainer/configs/cgroup_linux.go, update.go
Since `runc update` CLI is not able to modify devices (and it is not clear
how to implement that properly), let's set `SkipDevices=true`,
so that a cgroup controller won't try to update devices cgroup.
This helps use cases when some other device management (NVIDIA GPUs)
applies its configuration on top of what runc does.
Make sure we do not save `SkipDevices` into `state.json`.
This is an alternative to https://github.com/opencontainers/runc/pull/2988.
* `runc update` no longer updates cgroup devices configuration.
=> runc update: skip devices

libcontainer/cgroups/ebpf/ebpf_linux.go
It turns out that the cilium eBPF library doesn't degrade gracefully if
BPF_F_REPLACE is not supported, so we need to work around it by treating
that case as we treat the more-than-one program case.
Fixes: d0f2c25f521e ("cgroup2: devices: replace all existing filters when attaching")
=> cgroupv2: ebpf: check for BPF_F_REPLACE support and degrade gracefully 

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go, tests/integration/dev.bats
1. Fix handling of `SkipDevices` option -- it should be what it literally means,
i.e. do not set any device-related options.
2. Revert the part of commit 108ee85 which skipped the freeze
when the `SkipDevices` is set. Apparently, the freeze is needed on
update even if no `Device*` properties are being set.
3. Add `runc update` to "runc run [device cgroup deny]" test.
Fixes: 752e7a8
Fixes: 108ee85
Fixes: #3014
=> libct/cg/sd: fix "SkipDevices" handling

.github/workflows/test.yml
Tiny spelling fix - it's called "docker", not "dockre".
Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>
=> github: workflows: fix tiny typo

libcontainer/cgroups/fs/blkio.go, libcontainer/cgroups/fs/blkio_test.go
- Update the blkio cgroup to support the BFQ I/O Scheduler, that has
replaced CFQ in the Linux kernel.
- BFQ is controlled through blkio.bfq.weight[_device] instead of
CFQ's blkio.weight[_device] in cgroups v1.
- BFQ does not support blkio.leaf_weight[_device], so that behavior
remains untouched.
- Do not change behavior on legacy CFQ systems.
- Enable using blkio weights on BFQ systems.
Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>
=> libcontainer/cgroups/fs/blkio: support BFQ weight[_device]

libcontainer/integration/update_test.go, tests/integration/update.bats
... and remove the one from tests/integration.
The idea is similar to the one for the test case being removed -- try
updating device rules many times to make sure we are not leaking eBPF
programs after every update/Set(). This is better though as we can
really change the device rules every time (which "runc update" can't)
and check that the rule is applied.
The test works, but I see the following warning (on Fedora 34, cgroup v2):
```
WARN[0000] found more than one filter (2) attached to a cgroup -- removing extra filters! 
```
=> libct/int: add device update test

go.mod, go.sum, libcontainer/cgroups/ebpf/ebpf_linux.go, vendor/github.com/cilium/ebpf/CONTRIBUTING.md, vendor/github.com/cilium/ebpf/link/kprobe.go, vendor/github.com/cilium/ebpf/link/platform.go, vendor/github.com/cilium/ebpf/link/program.go, vendor/modules.txt
The `errors.Is(err, unix.EINVAL)` check in `haveBpfProgReplace()` was broken because the `cilium/ebpf` library did not "wrap" errors: https://github.com/cilium/ebpf/blob/v0.6.0/link/program.go#L72
So the eBPF support of runc was broken for kernel prior to 5.6.
The fix for the above is https://github.com/cilium/ebpf/pull/320. This PR bumps cilium/ebpf to include the fix.
Fixes: #3008
- - -
Tested in Moby CI https://github.com/moby/moby/pull/42450
=> update cilium/ebpf to fix haveBpfProgReplace() check

libcontainer/container_linux.go, libcontainer/criu_opts_linux.go, man/runc-restore.8.md, restore.go
Restoring an SELinux enabled container with Podman will result in a container with the exactly same SELinux process labels as during checkpointing. CRIU takes care of all the process labels.
Restoring multiple copies of a checkpointed container will result in all containers having the same SELinux process labels, which might be undesired.
When looking at Pods all container in a Pod share the process label of the infrastructure container. To restore a container into and existing Pod it is necessary to tell CRIU to restore the container with the infrastructure container process label.
CRIU supports setting different process labels using `--lsm-profile` for a long time and this just passes the process label information from runc to CRIU.
Unfortunately CRIU has a bug as no one was using the …
=> Allow restoring with a different LSM profile

libcontainer/init_linux.go
> container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"setenv: invalid argument\"": unknown
xref kubernetes/kubernetes#102732
Pick the judgment logic from `os.Setenv`, and added clear error message 
https://github.com/golang/go/blob/27f83723e98d8e3795a07bdca2b3a8155b0d72b3/src/syscall/env_unix.go#L97-L130
=> Returns clearer error message for Setenv

libcontainer/container_linux.go
Sump/restrore logs are very useful when process fails.
So put them to image path defaultly，otherwise these files
will be deleted when container exits.
Signed-off-by: Liu Hua <weldonliu@tencent.com>'
* checkpoint/restore: if `--work-path` is not specified, it defaults to the value of `--image-path` (same as `criu` does).
=> checkpoint: set default work-dir to image-path

libcontainer/container_linux.go, tests/integration/checkpoint.bats
runc resolves symlink before doing bind mount. So
we should save original path while formatting CriuReq for
checkpoint.
Signed-off-by: Liu Hua <weldonliu@tencent.com>
=> checkpoint: resolve symlink for external bind mount

tests/integration/no_pivot.bats
Since today, the test is failing like this on GHA CI (and also happens to fail on my machine with a recent F34 kernel):
not ok 70 runc run --no-pivot must not expose bare /proc
#
Apparently, a recent kernel commit [db2e718a47984b9d](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=db2e718a47984b9d71ed890eb2ea36ecf150de18) prevents
root from doing `unshare -r` unless it has `CAP_SETFCAP`.
Add the capability for this specific test.
Fixes: #3050
=> tests/int/no_pivot: fixup for new kernels

libcontainer/standard_init_linux.go, libcontainer/system/linux.go
When running a script from an azure file share interrupted syscall
occurs quite frequently, to remedy this add retries around execve
syscall, when EINTR is returned.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1917662
=> retry unix.EINTR for container init process

tests/integration/no_pivot.bats
_This is a backport of PR #3051 to release-1.0 branch to fix CI. Clean cherry-pick, no issues, original description follows._
The test is failing like this:
not ok 70 runc run --no-pivot must not expose bare /proc
#
Apparently, a recent kernel commit db2e718a47984b9d prevents
root from doing unshare -r unless it has CAP_SETFPCAP.
Add the capability for this specific test.
(cherry picked from commit 1bbeadae72603c44932d46ade275219dbf718950)
=> [1.0] tests/int/no_pivot: fix for new kernels

libcontainer/nsenter/nsexec.c
Hi!
We've found these bugs while rebasing https://github.com/opencontainers/runc/pull/2576. The bug is that we are closing an fd that is already closed, and as we ignore close(2) failures we never realized.
It was not a big deal in runc master, it seems, as that close fails and is otherwise ignored. However, when working on PR #2576 we are opening a new fd, sometimes between the two close(2) calls, the fd number is reused (allocates the lower available fd) and the second close(2) was closing this new open fd that reused the number.
I've create two patches: one to remove the bogus close, and another one to check failures on close(2) so this bug does not happen again (as long as we continue to check for close failures :)). I've also verified that if we check for close failures on the close …
=> libcontainer: Don't close already closed fds and bail on close(2) failures

libcontainer/standard_init_linux.go, libcontainer/system/linux.go
_Backport of PR #3045 to release-1.0 branch. ~~Draft, needs to be rebased on top of PR #3075 to fix CI.~~_
When running a script from an azure file share interrupted syscall
occurs quite frequently, to remedy this add retries around execve
syscall, when EINTR is returned.
Signed-off-by: Maksim An <maksiman@microsoft.com>
(cherry picked from commit e39ad6505995a9e3c098fa4b91d39d266f4e27ba)
[Minor conflict in libcontainer/standard_init_linux.go due to missing
commit e918d021399e62 -- resolved manually]
```
Bugfixes:
* Fixed occasional runc exec/run failure ("interrupted system call") on an Azure volume.
```
=> [1.0] retry unix.EINTR for container init process

tests/integration/dev.bats
Add CAP_SYSLOG to ensure that /dev/kmsg can be accesses on systems where
the sysctl kernel.dmesg_restrict = 1.
=> tests/int/dev: add CAP_SYSLOG to /dev/kmsg tests

libcontainer/user/user.go, libcontainer/user/user_test.go
_This is a backport of #3062 to 1.0 branch. Clean cherry-pick, no issues. Original description follows._
Lines in /etc/group longer than 64 characters breaks the current
implementation of group parser. This is caused by bufio.Scanner
buffer limit.
Fix by re-using the fix for a similar problem in golang os/user,
namely https://go-review.googlesource.com/c/go/+/283601
(fixing a similar bug in golang os/user, https://github.com/golang/go/issues/43636).
Add some tests.
Fixes: #3036 
Reported-by: @erict-square 
Co-authored-by: @andreybokhanko
```
Bugfixes:
* Fixed "unable to find groups ... token too long" error with /etc/group containing lines longer than 64K characters (#3036)
```
=> [1.0] libct/user: fix parsing long /etc/group lines

libcontainer/intelrdt/intelrdt.go, libcontainer/intelrdt/intelrdt_test.go, libcontainer/intelrdt/stats.go, libcontainer/specconv/spec_linux.go
A bunch of cleanups for the code in `libcontainer/intelrdt`, mostly to simplify or remove the code, with occasional minor improvements and one nil dereference fix. See individual commit for details.
Please review commit-by-commit.
=> libcontainer/intelrdt: cleanups

libcontainer/cgroups/fs/freezer.go, libcontainer/cgroups/systemd/systemd_test.go
This is the same as #3065 with a few nitpicks and minor fixes on top.
Fixes the issue (frozen containers) that led to runc bump to 1.0.0 reverted in kubernetes.
Diff from #3065 (not including commit messages):
```diff
diff --git a/libcontainer/cgroups/fs/freezer.go b/libcontainer/cgroups/fs/freezer.go
index 734fc46a..4baa2798 100644
--- a/libcontainer/cgroups/fs/freezer.go
+++ b/libcontainer/cgroups/fs/freezer.go
@@ -129,8 +129,8 @@ func (s *FreezerGroup) GetState(path string) (configs.FreezerState, error) {
case "THAWED":
return configs.Thawed, nil
case "FROZEN":
-                       // Check freezer state for current control group to check
-                       // if it is frozen, or if it is one of its ancestors.
+                       // Find out whether the cgroup is frozen …
```
=> Make cgroup freezer only care about current control group (carry #3065)

.golangci.yml, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/fscommon/utils.go, libcontainer/cgroups/utils.go, libcontainer/container_linux.go, libcontainer/devices/device_unix.go, libcontainer/notify_linux_v2.go
While reviewing a PR I [found](https://github.com/opencontainers/runc/pull/3065/commits/5c8d36ba95cd581f72c63afd9cac125683f313bd#r665570457) we do not enable unconvert linter.
Enable it, and fix initially reported warnings (surprisingly not too many).
=> ci: enable unconvert linter, fix its warnings

libcontainer/cgroups/fs/freezer.go, libcontainer/cgroups/systemd/systemd_test.go
_This is a backport of PR #3081 to 1.0._
Fixes the issue (frozen containers) that led to runc bump to 1.0.0 reverted in kubernetes.
See also: #3065.
```
Bugfixes:
* cgroupv1/systemd: fix freezing cgroup after Set if a parent cgroup is frozen (#3085)
```
=> [1.0] Make cgroup freezer only care about current control group

.github/workflows/test.yml, .github/workflows/validate.yml
_backport of #3089_
A CI is needed after PR merges.
=> [1.0] ci/gha: run on release-* branches after a push and on tags

libcontainer/cgroups/systemd/v2.go, tests/integration/update.bats
_Backport of #3067 to release-1.0. Cherry-picked with a trivial conflict due to missing b60e2edf75539b144374a_.
```
- cgroup/systemd/v2: don't freeze cgroup on Set. (#3092)
```
=> [1.0] Don't freeze cgroup on update for systemd cgroup v2 

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/systemd_test.go, libcontainer/cgroups/systemd/v1.go, libcontainer/integration/exec_test.go, libcontainer/integration/template_test.go, libcontainer/integration/utils_test.go
_~~based on (and currently includes) #3081 and #3067. Keeping this a draft before those two are merged.~~_
1. Fix the inability to freeze the container using its `Set()` method (with `r.Freezer` set to `Frozen`). Add a test.
2. Avoid unnecessary freeze/thaw from system v1 driver. Add a test.
Review commit-by-commit. Please see individual commits for details.
=> cgroups: Set: fix freeze, avoid unnecessary freeze from systemd v1

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/systemd_test.go, libcontainer/cgroups/systemd/v1.go, libcontainer/integration/exec_test.go, libcontainer/integration/template_test.go, libcontainer/integration/utils_test.go
**NOTE this requires https://github.com/opencontainers/runc/pull/3092 as the tests added also test the issue fixed by it. Draft until #3082 and #3092 are merged.**
_backport of #3082 to 1.0. Mostly clean cherry-pick, with a single trivial conflict in include ()_.
1. Fix the inability to freeze the container using its Set() method (with r.Freezer set to Frozen). Add a test.
2. Avoid unnecessary freeze/thaw from system v1 driver. Add a test.
```markdown
- cgroup/systemd/v1:  avoid unnecessary freeze on Set. (#3093)
```
=> [1.0] cgroups: Set: fix freeze, avoid unnecessary freeze from systemd v1

.cirrus.yml, .github/workflows/test.yml
ref: issue #3078 
Cirrus allows using 16 CPUs and 64GB RAM in total.
(We have two Vagrant VMs, so 8 CPUs and 32GB RAM for each)
Cirrus needs to be enabled via https://github.com/marketplace/cirrus-ci
(cc @caniszczyk @cyphar)
Build logs in my fork repo: https://cirrus-ci.com/github/AkihiroSuda/runc
TODO (once this is merged, added by @kolyshkin)
* Remove fedora and centos jobs from required in https://github.com/opencontainers/runc/settings/branches for both `master` and `release-*` (btw why do we have two sets of rules if they are supposed to be the same?)
* Add new jobs in there.
=> Use Cirrus CI for Vagrant tests

README.md
"`runc` X.Y.Z should implement the X.Y version of the specification." is no longer correct.
runc v1.1 will be probably released ahead of OCI Runtime Spec v1.1.
=> README.md: remove abandoned versioning policy

init.go, libcontainer/nsenter/nsexec.c, libcontainer/process_linux.go, main.go
Remove some code from runc init which is not needed. Please review commit-by-commit.
1. Remove option parsing from runc init.
2. Remove cgroupns sync mechanism (as pointed out in #2446 and in TODO).
=> runc init: remove some code

exec.go, man/runc-exec.8.md, tests/integration/exec.bats, utils.go
Noticing that `runc exec` exit status is not documented, I ended up with this.
Currently there's no way to distinguish between the two cases:
- runc exec failed;
- the command executed returned 1.
This was possible before commit 8477638aab5a, as runc exec exited with
the code of 255 if exec itself has failed. The code of 255 is the same
convention as used by e.g. ssh.
Re-introduce the feature, document it, and add some tests so it won't be
broken again.
```
New functionality:
* runc exec now produces exit code of 255 when the exec failed.
This may help in distinguishing between runc exec failures
(such as invalid options, non-running container or non-existent
binary etc.) and failures of the command being executed. (#3073)
=> runc exec: fail with exit code of 255

libcontainer/seccomp/config.go, libcontainer/seccomp/seccomp_linux.go, tests/integration/start_hello.bats
This fixes using runc with podman on my system (Fedora 34).
> $ podman --runtime $(pwd)/runc run --rm --memory 4M fedora echo it works
> Error: unable to start container process: error adding seccomp filter rule for syscall bdflush: permission denied: OCI permission denied
The problem is, libseccomp returns EPERM when a redundant rule (i.e. the
rule with the same action as the default one) is added, and podman (on
my machine) sets the following rules in config.json:
```json
....
"seccomp": {
"defaultAction": "SCMP_ACT_ERRNO",
"architectures": [
"SCMP_ARCH_X86_64",
"SCMP_ARCH_X86",
"SCMP_ARCH_X32"
],
"syscalls": [
{
"names": [
"bdflush",
"io_pgetevents",
....
],
"action": "SCMP_ACT_ERRNO",
"errnoRet": 1
},
....
```
(Note that defaultErrnoRet is not set, but it defaults to 1).
With this …
=> seccomp: skip redundant rules

libcontainer/cgroups/fs/cpu.go, tests/integration/update.bats
_This is a partial backport of #3090 (first commit -- the fix itself -- only) to release-1.0 branch. Test case and cleanups are omitted as those are too big and do not add much value to this branch._
As reported in issue #3084, sometimes setting CPU quota period fails
when a new period is lower and a parent cgroup has CPU quota limit set.
This happens as in cgroup v1 the quota and the period can not be set
together (this is fixed in v2), and since the period is being set first,
`new_limit = old_quota/new_period` may be higher than the parent cgroup
limit.
The fix is to retry setting the period after the quota, to cover all
possible scenarios.
Add a test case to cover a regression caused by an earlier version of
this patch (ignoring a failure of setting invalid period when quota is
not …
=> [1.0] libct/cg/v1: work around CPU quota period set failure

libcontainer/seccomp/seccomp_linux.go, tests/integration/start_hello.bats
Backport of #3109 (partial -- last commit only) to release-1.0 branch. Original description follows.
----
This fixes using runc with podman on my system (Fedora 34).
> $ podman --runtime `pwd`/runc run --rm --memory 4M fedora echo it works
> Error: unable to start container process: error adding seccomp filter rule for syscall bdflush: permission denied: OCI permission denied
The problem is, libseccomp returns EPERM when a redundant rule (i.e. the
rule with the same action as the default one) is added, and podman (on
my machine) sets the following rules in config.json:
<....>
"seccomp": {
"defaultAction": "SCMP_ACT_ERRNO",
"architectures": [
"SCMP_ARCH_X86_64",
"SCMP_ARCH_X86",
"SCMP_ARCH_X32"
],
"syscalls": [
{
"names": [
"bdflush",
"io_pgetevents",
<....>
],
"action": "SCMP_ACT_ERRNO", …
=> [1.0] libct/seccomp: skip redundant rules

Makefile, script/release.sh
This is a manual backport of PR #3099 (commits 61e201abb2d5e4c and
18f434e10a7ebb4a) to release-1.0 branch.
Done manually as the changes are small, and cherry-picking results
in a conflict due to commit 015fa29afd missing from release-1.0 branch.
=> [1.0] script/release.sh: make builds reproducible

libcontainer/nsenter/nsexec.c
As reported in issue #3119, there is a race in nsexec logging
that can lead to garbled json received by log forwarder, which
complains about it with a "failed to decode" error.
This happens because dprintf (used since the very beginning of nsexec
logging introduced in commit ba3cabf932943) relies on multiple write(2)
calls, and with additional logging added by 64bb59f5920b15d (appeared in rc94)
a race is possible between runc init parent and its children.
The fix is to prepare a string and write it using a single call to
write(2).
Fixes: #3119
Practically, though, debug logging is not needed in 99.9% of all cases,
and so PR #3114 (commit https://github.com/opencontainers/runc/pull/3114/commits/b1bc76248c642660269a0764b02bf7ed2aa77605) eliminates the possibility
of it having this race in …
=> libct/nsenter: fix logging race in nsexec (regression in rc94)

libcontainer/nsenter/nsexec.c
This is a backport of https://github.com/opencontainers/runc/pull/3120 to release-1.0 branch,
fixing rare but critical issue #3119.
----
As reported in issue #3119, there is a race in nsexec logging
that can lead to garbled json received by log forwarder, which
complains about it with a "failed to decode" error.
This happens because dprintf (used since the very beginning of nsexec
logging introduced in commit ba3cabf932943) relies on multiple write(2)
calls, and with additional logging added by 64bb59f5920b15d (appeared in rc94)
a race is possible between runc init parent and its children.
The fix is to prepare a string and write it using a single call to
write(2).
(cherry picked from commit fb6ba046b999f3fcb5bab2aa5048a4a66fdf1526) …
=> [1.0] fix logging race in nsexec (regression in rc94)

libcontainer/nsenter/nsexec.c
The contents of the pointer returned on asprintf() error are undefined
i.e., it can be anything there. We set it to NULL on error so that
free() afterwards won't get a garbage pointer.
This patch applies the above to message and stage as well to be
consistent with what we do for json.
Signed-off-by: Kailun Qin <kailun.qin@intel.com>
=> libct/nsenter: nullify pointer on asprintf error

.cirrus.yml
The reason for this PR is CI fails on yum sometimes (seen twice today, last time at https://github.com/opencontainers/runc/pull/3151#issuecomment-897377886).
1. Remove redundant yum commands.
2. Add a sleep+retry on fail loop to yum.
=> .cirrus.yml: simplify for centos, retry yum

libcontainer/nsenter/nsexec.c
According to C standards, `size_t` is always an unsigned integer type.
Thus, checking unsigned expressions to be less than zero is not needed.
Signed-off-by: Kailun Qin <kailun.qin@intel.com>
=> libct/nsenter: no need to check size_t less than 0

.github/workflows/validate.yml
Today we support the seccomp build tag only that is used by default.
However, we are not testing that compiling without any build tag works.
I found the CI didn't catch this when working on #2682, that the CI was
green but compilation without build tags was broken.
We test compilation without build tags only, compilation with the only
build tag supported is done extensively in other actions.
Signed-off-by: Rodrigo Campos <rodrigo@kinvolk.io>
=> CI: Validate compilation without buildtags

libcontainer/nsenter/nsexec.c
_This is an alternative to #3165 / #3154._
Commit 2bab4a5 resulted in a warning from gcc:
nsexec.c: In function ‘write_log’:
nsexec.c:171:2: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
171 |  write(logfd, json, ret);
|  ^~~~~~~~~~~~~~~~~~~~~~~
As there's nothing we can or want to do in case write fails,
let's just tell the compiler we're not going to use it.
Fixes: 2bab4a5
=> libct/nsenter: fix unused-result warning

.codespellrc, .github/workflows/validate.yml, docs/systemd.md, libcontainer/cgroups/devices/devices_emulator.go, libcontainer/cgroups/ebpf/ebpf_linux.go, libcontainer/cgroups/fs/cpuset.go, libcontainer/cgroups/fs/stats_util_test.go, libcontainer/cgroups/stats.go, libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/systemd_test.go, libcontainer/container_linux.go, libcontainer/nsenter/nsenter_test.go, libcontainer/rootfs_linux.go, libcontainer/standard_init_linux.go, tests/integration/hooks.bats, update.go
Fix a bunch of warnings from codespell, and add a CI job to validate to automate it.
Note that
1. I had to use pip to install codespell, as the version provided with Ubuntu 20.04 is way old.
2. The two exceptions I had to add to codespellrc are:
- `CLOS` (a term used by intelrtd);
- `creat `(syscall name used in tests/integration/testdata/seccomp_*.json).
=> Fix codespell warnings, add codespell to ci

libcontainer/nsenter/nsexec.c
_Backport of #3168 to release-1.0. Draft until that one is merged._
Commit 2bab4a5 resulted in a warning from gcc:
nsexec.c: In function ‘write_log’:
nsexec.c:171:2: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
171 |  write(logfd, json, ret);
|  ^~~~~~~~~~~~~~~~~~~~~~~
As there's nothing we can or want to do in case write fails,
let's just tell the compiler we're not going to use it.
Fixes: 2bab4a5
(cherry picked from commit db8330c9e516ac359e199b999c5321c73aaffabf)
=> [1.0] libct/nsenter: fix unused-result warning

.github/workflows/test.yml
Add testing against criu-dev branch instead of a released version
(happens to be criu v3.15 at the moment), to check how it works.
This is just a single job, and it is not required (i.e. its success is not needed to get a PR merged).
Maybe we need to add a similar one for fedora (to better test cgroup v2).
=> ci/gha: add latest criu-dev test run

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/systemd_test.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v1_test.go, libcontainer/configs/cgroup_linux.go
This is a combo of #3143, ~~#3151,~~ and #3161, which aims to be both fast and correct for all use cases.
From #3143 -- fixes to getting and checking device properties;
~~From #3151 -- fast(er) path in freezeBeforeSet (in case devices.list is empty we can skip getting unit properties);~~
From #3161 -- SkipFreezeOnSet knob for kubernetes.
From #3148 -- test cases (those are also cherry-picked in #3143)
Aimed to fix kubernetes/kubernetes#104280 (once we backport, release 1.0.2, and vendor it to kubernetes)
=> libct/cg/sd/v1: fix freezeBeforeSet (alt 2)

libcontainer/cgroups/systemd/common.go, libcontainer/cgroups/systemd/systemd_test.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v1_test.go, libcontainer/configs/cgroup_linux.go
_A backport of #3166 to 1.0 branch. Original description follows._
----
This is a combo of #3143, ~~#3151,~~ and #3161, which aims to be both fast and correct for all use cases.
From #3143 -- fixes to getting and checking device properties;
~~From #3151 -- fast(er) path in freezeBeforeSet (in case devices.list is empty we can skip getting unit properties);~~
From #3161 -- SkipFreezeOnSet knob for kubernetes.
From #3148 -- test cases (those are also cherry-picked in #3143)
Aimed to fix kubernetes/kubernetes#104280 (once we backport, release 1.0.2, and vendor it to kubernetes)
=> [1.0] libct/cg/sd/v1: fix freezeBeforeSet (alt 2)

libcontainer/cgroups/devices/devices_emulator.go, libcontainer/cgroups/ebpf/devicefilter/devicefilter.go, libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go, libcontainer/devices/device.go, libcontainer/rootfs_linux.go, libcontainer/specconv/spec_linux.go
> I noticed this while reviewing https://github.com/opencontainers/runc/pull/3110. Opening as draft to see if there's any failures in CI, and because this will conflict with that PR
Possibly there was a specific reason to use a rune for this, but I noticed
that there's various parts in the code that has to convert values from a
string to this type. Using a string as type for this can simplify some of
that code.
=> libct/devices: change devices.Type to be a string

libcontainer/cgroups/devices/devices_emulator.go, libcontainer/cgroups/devices/devices_emulator_test.go
Looking into data generated by setting
GODEBUG="inittrace=1"
I have noticed this line:
init github.com/opencontainers/runc/libcontainer/cgroups/devices @1.2 ms, 0.020 ms clock, 10512 bytes, 133 allocs
This is the leader for both bytes and allocs among the packages from
this repo, and all of it is caused by a single regex:
var devicesListRegexp = regexp.MustCompile(`^([abc])\s+(\d+|\*):(\d+|\*)\s+([rwm]+)$`)
It seems that the same parsing can be done without relying on
a regular expression, no decrease in readability or correctness
(including catching all invalid input), and 2x faster (according to
the benchmark added), and also hopefully makes runc start
slightly faster and leaner.
Before:
BenchmarkParseLine-4   	  176240	      6768 ns/op	    6576 B/op	      64 allocs/op
After: …
=> libct/cg/devices: stop using regex

libcontainer/cgroups/fs/fs.go, libcontainer/cgroups/fs2/defaultpath.go, libcontainer/cgroups/systemd/v1.go, libcontainer/cgroups/systemd/v2.go, libcontainer/configs/cgroup_linux.go
This was initially added by commits 41d9d2651301a2 and 4a8f0b4db492,
apparently to implement `docker run --cgroup container:ID` (https://github.com/moby/moby/pull/19244),
which was never merged. Therefore, this code is not and was never used.
It needs to be removed mainly because having it makes it much harder to
understand how cgroup manager works (because with this in place we have
not one or two but three sets of cgroup paths to think about).
Note if the paths are known and there is a need to add a PID to existing
cgroup, cgroup manager is not needed at all -- something like
cgroups.WriteCgroupProc or cgroups.EnterPid is sufficient (and the
latter is what runc exec uses in (*setnsProcess).start). If, for some reason,
the cgroup manager is still needed, it's better to write a separate …
=> libct/cg: rm dead code to improve clarity

libcontainer/cgroups/devices/devices_emulator.go, libcontainer/cgroups/ebpf/devicefilter/devicefilter.go, libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go, libcontainer/devices/device.go, libcontainer/rootfs_linux.go, libcontainer/specconv/spec_linux.go
This reverts commit 814f3ae1d93d35280eefd359be73f473519e7036. This
changed the on-disk state which breaks runc when it has to operate on
containers started with an older runc version. Working around this is
far more complicated than just reverting it.
Fixes #3179
Ref #3159
=> Revert "libct/devices: change devices.Type to be a string"

.gitignore, Makefile, contrib/cmd/sd-helper/helper.go, libcontainer/cgroups/fs/cpu.go, tests/integration/helpers.bash, tests/integration/update.bats
_This is based on (and currently includes) #3175._
I. As reported in issue #3084, sometimes setting CPU quota period fails
when a new period is lower and a parent cgroup has CPU quota limit set.
This happens as in cgroup v1 the quota and the period can not be set
together (this is fixed in v2), and since the period is being set first,
`new_limit = old_quota/new_period` may be higher than the parent
cgroup limit.
The fix is to retry setting the period after the quota, to cover all
possible scenarios.
Add a test case to cover a regression caused by an earlier version of
this patch (ignoring a failure of setting invalid period when quota is
not set).
Fixes: #3084
Closes: #2044
II. Add a test case for an issue fixed by the previous commit.
Unfortunately, this is somewhat complicated as …
=> libct/cg/v1: work around CPU quota period set failure

libcontainer/configs/intelrdt.go, libcontainer/configs/validate/validator.go, libcontainer/container_linux.go, libcontainer/intelrdt/intelrdt.go, libcontainer/intelrdt/intelrdt_test.go, libcontainer/intelrdt/util_test.go, libcontainer/specconv/spec_linux.go
- Handle ClosID parameter of IntelRdt. Makes it possible to use
pre-configured classes/ClosIDs and avoid running out of available IDs
which easily happens with per-container classes.
- libcontainer/intelrdt: verify ClosID existence
Check that the ClosID directory pre-exists if no L3 or MB schema has
been specified. Conform with the following line from runtime-spec
(config-linux):
*If closID is set, and neither of l3CacheSchema and memBwSchema are
set, runtime MUST check if corresponding pre-configured directory
closID is present in mounted resctrl. If such pre-configured directory
closID exists, runtime MUST assign container to this closID and
generate an error if directory does not exist.*
- Add a TODO note for verifying existing schemata against L3/MB
parameters.
- Run unit tests …
=> libcontainer/intelrdt: support ClosID parameter

libcontainer/cgroups/fs/fs.go, libcontainer/cgroups/fs/rdma.go, libcontainer/cgroups/fs2/fs2.go, libcontainer/cgroups/fscommon/rdma.go, libcontainer/cgroups/fscommon/rdma_test.go, libcontainer/cgroups/stats.go, libcontainer/cgroups/systemd/v1.go, libcontainer/configs/cgroup_linux.go, libcontainer/configs/rdma.go, libcontainer/specconv/spec_linux.go
RDMA controller/cgroup support is added with Linux kernel 4.11.
Similar format is used by cgroup-v2
Reference
https://www.kernel.org/doc/Documentation/cgroup-v1/rdma.txt
=> Add support for rdma cgroup introduced in Linux Kernel 4.11

man/runc-run.8.md, run.go, tests/integration/run.bats, utils_linux.go
To close #2817
As described in #2817, for some times, we need to analyze the container's resource usage, so we expect runc does not delete the container after it exits.
(by @kolyshkin)
```
New features:
* runc run: new `--keep` option to skip removal exited containers artefacts.
This might be useful to check the state (e.g. of cgroup controllers) after
the container has￼exited. (#2817)
```
=> proposal: add --keep to runc run

libcontainer/configs/validate/validator.go, libcontainer/container_linux.go, libcontainer/error.go, libcontainer/factory_linux.go
This is the alternative to #3056, addressing review comment from https://github.com/opencontainers/runc/pull/3033#discussion_r661966694.
`ConfigError` type was added by commit e918d021399e62, while removing runc's
own error system, to preserve a way for a libcontainer user to distinguish
between a configuration error and something else.
The way ConfigError is implemented requires a different type of check
(compared to all other errors defined by error.go). An attempt was made
to rectify this, but the resulting code became even more complicated.
As no one is using this functionality (of differentiating a "bad config"
type of error from other errors), let's just drop the ConfigError type.
=> libct/error.go: rm ConfigError (alt)

libcontainer/cgroups/file.go, libcontainer/cgroups/file_test.go
1. While looking into https://github.com/opencontainers/runc/issues/3026, I started writing a test case and found out that 
`OpenFile("/sys/fs/cgroup", name)` falls back to using open and fstatfs.
This is caused by a peculiarities of its `dir` and `name` arguments handling,
and was never discovered before because of the fallback.
Fix the bug, add the test cases.
2. Improve the error message for case like in the issue #3026, based on @cyphar suggestion.
See commit messages for more details.
=> libct/cg/OpenFile: fix/improve openat2 handling

libcontainer/nsenter/nsenter_test.go
Fix and improve nsenter_test.go (originally part of #3114).
=> libct/nsenter/nsenter_test.go: fix and improve

script/release.sh
openSUSE comes with `site-config` package, which makes configure select
`${prefix}/lib64` as `libdir` on x86_64, unless explicitly specified.
Since release.sh relies on a particular libdir path (for pkgconfig), this
site-config feature breaks things:
```
+ make -C /home/kir/git/runc PKG_CONFIG_PATH=/tmp/tmp.QgIJ1sR5c9/lib/pkgconfig COMMIT_NO= EXTRA_FLAGS=-a 'EXTRA_LDFLAGS=-w -s -buildid=' static
make[1]: Entering directory '/home/kir/git/runc'
CGO_ENABLED=1 go build -trimpath -a -tags "seccomp netgo osusergo" -ldflags "-extldflags -static -X main.gitCommit=v1.0.0-204-g963e0146 -X main.version=1.0.0+dev -w -s -buildid=" -o runc .
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
```
To fix, we have to explicitly …
=> script/release.sh: fix for opensuse

libcontainer/container_linux.go, tests/integration/checkpoint.bats
[From @kolyshkin: This is a respin of #2902 which was reverted in #3043]
runc resolves symlink before doing bind mount. So
we should save original path while formatting CriuReq for
dump and restore.
"checkpoint: resolve symlink for external bind mount" is merged as 
da22625f6986f0ef196eaa1f8bb6adce098f0fb7 (PR #2902) previously. And reverted
in commit 70fdc0573dced3464e9c31d674559f77c1de3973 (PR #3043) duo to behavior changes
caused by commit 0ca91f44f1664da834bc61115a849b56d22f595f (Fixes: CVE-2021-30465)
Signed-off-by: Liu Hua <weldonliu@tencent.com>
(by @kolyshkin)
```Bugfixes:
* runc checkpoint/restore: fixed for containers with an external bind mount
which destination is a symlink. (#3047).
```
=> checkpoint: resolve symlink for external bind mount (take II)

libcontainer/system/proc.go, libcontainer/system/proc_test.go
1. Add a test case that tests parentheses in command.
2. Replace individual comparisons with `reflect.DeepEqual`.
This also fixes wrong `%`-style types used in `Fatalf` statements.
3. Replace `Fatalf` with `Errorf` so we don't bail out on the first
failure, and do not check result on error.
4. Add two benchmarks.
1. Remove PID field. It is totally useless -- we already know the PID.
2. Rewrite `parseStat()` to make it faster and more correct:
- do not use `fmt.Scanf` as it is very slow;
- avoid splitting data into 20+ fields, of which we only need 2 (should also help garbage collector);
- make sure to not panic on short lines and other bad input;
- add some bad input tests (some fail with old code);
- use `LastIndexByte` instead of `LastIndex` where appropriate.
Benchmarks:
before (from …
=> libct/system.Stat: fix panic, speed up, add benchmarks

init.go, libcontainer/logs/logs.go, libcontainer/logs/logs_linux_test.go, main.go
This makes `runc --debug` logs more readable, along with some refactoring and logs tests improvements (originally part of #3114).
- init.go, main.go: don't use logs.ConfigureLogging
- libct/logs: remove ConfigureLogging
- Improve libct/logs and its tests
- libct/logs: test: make more robust
- libct/logs: parse log level implicitly
- libct/logs: do not show caller in nsexec logs
- runc --debug: shorter caller info
The biggest user-facing change is how debug logs are more clean / less cluttered:
```console
$ runc --debug run x
ERRO[0000]github.com/opencontainers/runc/utils.go:61 main.fatalWithCode() JSON specification file config.json not found
$ runc --debug run -d x
DEBU[0000]github.com/opencontainers/runc/libcontainer/logs/logs.go:69 …
```
=> Logging improvements

libcontainer/cgroups/systemd/dbus.go
Wrap the error with `"failed to connect to dbus (hint: for rootless containers, maybe you need to install dbus-user-session package, see https://github.com/opencontainers/runc/blob/master/docs/cgroup-v2.md): %w"`.
---
Before:
```console
$ docker --context=rootless run -it --rm alpine
docker: Error response from daemon: OCI runtime create failed: unable to start
container process: unable to apply cgroup configuration: unable to start unit
"docker-7ef2c29ccafc1ed9c7fd9859337e5b79870d8ccb282f560e43060a847a6c5310.scope"
(properties [{Name:Description Value:"libcontainer container
7ef2c29ccafc1ed9c7fd9859337e5b79870d8ccb282f560e43060a847a6c5310"} {Name:Slice
Value:"user.slice"} {Name:PIDs Value:@au [6286]} {Name:Delegate Value:true}
{Name:MemoryAccounting Value:true} {Name:CPUAccounting …
```
=> rootless+cgroup2+systemd: improve error message when dbus-user-session is not installed

libcontainer/configs/config.go, libcontainer/seccomp/seccomp_linux.go
Carry of #2564.
Two new seccomp actions have been added to the libseccomp-golang
dependency, which can be now supported by runc, too.
ActKillThread kills the thread that violated the rule. It is the same as
ActKill. All other threads from the same thread group will continue to
execute.
ActKillProcess kills the process that violated the rule. All threads in
the thread group are also terminated. This action is only usable when
libseccomp API level 3 or higher is supported.
Signed-off-by: Sascha Grunert <sgrunert@redhat.com>
=> Add support for seccomp actions ActKillThread and ActKillProcess
