opencontainers/runc

- exec.go
- init.go
- libcontainer/nsenter/nsexec.c
- utils_linux.go
~~_(this is based on and includes https://github.com/opencontainers/runc/pull/3157; only review the last 5 commits)_~~
Currently, if the log level is not set to e.g. "debug", runc init sends
some debug logs to the parent, which parses and discards it.
It is better to not send those in the first place.
Amend nsexec.c to honor `_LIBCONTAINER_LOGLEVEL`.
> nsexec.c: don't write logs that are to be discarded

- create.go
- delete.go
- restore.go
- run.go
- start.go
- utils_linux.go
_Separated out of #3131 and reworked_
1. Remove unneeded newlines from error messages.
2. Simplify startContainer call, fix `runc restore` not checking `--pid-file` argument.
3. Wrap `runc create` and `runc run` errors.
> runc cli: nits

- libcontainer/cgroups/systemd/dbus.go
Cherry-pick https://github.com/opencontainers/runc/pull/3186 (clean)
> [1.0] rootless+cgroup2+systemd: improve error message when dbus-user-session is not installed #3186

- libcontainer/container_linux.go
- tests/integration/delete.bats
runc delete -f is not working for a paused container, since in cgroup v1
SIGKILL does nothing if a process is frozen (unlike cgroup v2, in which
you can kill a frozen process with a fatal signal).
Theoretically, we only need this for v1, but doing it for v2 as well is
OK.
```
Bugfixes:
* runc delete -f now succeeds (rather than timeouts) on a paused container (#3134)
```
> runc delete -f: fix for cg v1 + paused container

- contrib/cmd/sd-helper/helper.go
- libcontainer/cgroups/fs/fs.go
- libcontainer/cgroups/fs/fs_test.go
- libcontainer/cgroups/fs/paths.go
- libcontainer/cgroups/fs2/defaultpath.go
- libcontainer/cgroups/fs2/fs2.go
- libcontainer/cgroups/manager/manager_test.go
- libcontainer/cgroups/manager/new.go
- libcontainer/cgroups/systemd/systemd_test.go
- libcontainer/cgroups/systemd/v1.go
- libcontainer/cgroups/systemd/v1_test.go
- libcontainer/cgroups/systemd/v2.go
- libcontainer/configs/cgroup_linux.go
- libcontainer/factory_linux.go
- libcontainer/factory_linux_test.go
- libcontainer/integration/checkpoint_test.go
- libcontainer/integration/template_test.go
- libcontainer/integration/utils_test.go
- libcontainer/specconv/spec_linux.go
- utils_linux.go
_This ~~is based on and currently includes #3215.~~ used to be part of #3131._
High level overview:
* allow cgroup instantiation (`NewManager`) to return errors;
* initialize cgroup paths during instantiation, so paths are always available
(and now we can use a new instance for e.g. `Destroy` or `Exists`,
which was not possible before);
* simplifies cgroup manager instantiation, replacing the complicated
logic of choosing a cgroup manager with a simple `manager.New()` call.
* fixes some panics in cgroup manager (with `Resources==nil`).
This helps further commits, and makes cgroup manager easier to use
from e.g. Kubernetes.
Fixes: https://github.com/opencontainers/runc/issues/3177
Fixes: https://github.com/opencontainers/runc/issues/3178
```
libcontainer API changes:
* New configs.Cgroup …
```
> cgroup: make paths available, simplify getting manager

- .github/workflows/test.yml
- Dockerfile
Apparently (https://criu.org/index.php?title=Packages&diff=5197&oldid=5196) criu PPA repo, used for GHA CI, is replaced with the OBS repo (already used by Dockerfile), so let's use it.
While at it, modify the Dockefile to
* update the repo URL to use Debian_11 (which was not available before);
* fix the apt-key deprecation warning from Dockerfile.
See individual commits for more details.
This brings criu 3.16 to the table! 🎉
> CI/GHA: switch to OBS criu repo, bring in criu 3.16

- Dockerfile
- Makefile
- script/lib.sh
- script/release.sh
- script/seccomp.sh
Commit f30244ee1b22223cf (PR #3197) broke the scenario of using Dockefile for
anything but making a release. This happened because it installed
native libseccomp build to a temporary directory, and so linking against
libseccomp required setting a few environment variables.
Let's fix this, and simplify libseccomp installation. Instead of using
temporary directories, let's install native libseccomp to a specified
directory, all the cross-builds to its subdirectories, and set
PKG_CONFIG_PATH and LD_LIBRARY_PATH in Dockerfile so that the built
library will found by pkg-config and the dynamic linker (without setting
LD_LIBRARY_PATH, ld picks up distro-provided libseccomp.so).
While at it, fix some nit picks introduced by the abovementioned commit.
This fixes building runc in  make targets like …
> Dockerfile: fix for seccomp

- libcontainer/cgroups/systemd/v2.go
Delete all child cgroup in container cgroup, otherwise it will failed to delete the container cgroup.
Close https://github.com/opencontainers/runc/issues/3225
Signed-off-by: Kang Chen <kongchen28@gmail.com>
(by @kolyshkin)
```
Bugfixes:
* cgroup v2 systemd manager: delete sub-cgroups on cgroup delete
```
> Remove sub cgroup when container exits

- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
- libcontainer/integration/exec_test.go
Runtime spec [says](https://github.com/opencontainers/runtime-spec/blob/0d6cc581aeeaacee38ce707ae651a0e122f76852/config-linux.md#sysctl):
> sysctl (object, OPTIONAL) allows kernel parameters to be modified at
> runtime for the container. For more information, see the sysctl(8)
> man page.
and sysctl(8) says:
> variable
>    The name of a key to read from. An example is
>    kernel.ostype. The '/' separator is also accepted in place of a '.'.
[Apparently](https://github.com/kubernetes/kubernetes/pull/102393#issuecomment-939047989), runc config validator do not support sysctls with `/` as a
separator. Fortunately this is a one-line fix.
Add some more test data where `/` is used as a separator.
Related to: https://github.com/kubernetes/kubernetes/pull/102393
> libct/configs/validate: allow / in sysctl names

- .cirrus.yml
- Vagrantfile.fedora
- tests/integration/cgroups.bats
- tests/integration/helpers.bash
- tests/integration/userns.bats
Use Fedora 35 for testing; fix two test issues caused by the newer kernel.
This includes/carries #3258 and obsoletes #3260.
Closes: #3258
Closes: #3260
> ci/cirrus: use Fedora 35

- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
Fixes #3256 
see  
- https://github.com/opencontainers/runc/pull/3254/files#r739936786 
- https://github.com/kubernetes/kubernetes/pull/102393#discussion_r661550379
Fix the sysctl conversion function according to the linux ssyctl conversion definition.
```
Note that either "/" or "."  may be used as separators within
sysctl variable names. If the first separator is a slash,
remaining slashes and dots are left intact. If the first
separator is a dot, dots and slashes are interchanged.
"kernel.domainname=foo" and "kernel/domainname=foo" are
equivalent and will cause "foo" to be written to
/proc/sys/kernel/domainname. Either
"net.ipv4.conf.enp3s0/200.forwarding" or
"net/ipv4/conf/enp3s0.200/forwarding" may be used to refer to
/proc/sys/net/ipv4/conf/enp3s0.200/forwarding. A glob glob(7) …
```
> Fix the conversion of sysctl variable dots and slashes

- .cirrus.yml
noticed that this was using an older version of Go 1.16
> ci/cirrus: update to Go 1.17.3

- contrib/completions/bash/runc
- exec.go
- libcontainer/factory_linux.go
- man/runc-exec.8.md
- tests/integration/cgroups.bats
_This is the final part of changes from #3131, depending on (already merged) #3214, #3215, #3216, #3217._
This bugged me a few times during runc development. A new container is
run, and suddenly runc init is stuck, 🎶 and nothing ever happens, and
I wonder... 🎶
Figuring out that the cause of it is (pre-created) frozen cgroup is not
very obvious (to say at least), and neither Ctrl-C nor Ctrl-Z work.
The fix is to add a check that refuses to exec in a paused container.
A (very bad) alternative to that would be to thaw the cgroup.
Implement the fix, add a test case.
Update: it has been noted that exec in a paused container might be
a legitimate use case. Added `--ignore-paused` flag, documented, tested.
Currently runc allows multiple containers to share the same cgroup (for
example, by having …
> run create/run/exec: refuse bad cgroup

- .cirrus.yml
- Vagrantfile.fedora
A bug in systemd-249.6-2.fc35.x86_64 prevents rootless containers from
start when systemd manager is used (see https://bugzilla.redhat.com/show_bug.cgi?id=2022571).
A possible workaround is to exclude the package from the update list;
unfortunately this revealed another bug: "config exclude" is not working
in dnf shell (see https://bugzilla.redhat.com/show_bug.cgi?id=2022041).
A workaround to that is specify excludes as an option.
This should fix our CI for the time being.
Fixes: #3266
> Vagrantfile.fedora: exclude systemd from upgrade

- .github/workflows/test.yml
- Dockerfile
This was a temporary kludge (see PR #3246), which is no longer required.
This reverts commit c5ca778fa835aa7c4c0700e824f1b54fa52222c6.
> Revert "ci: temporarily disable criu repo gpg check"

- libcontainer/init_linux.go
- libcontainer/process_linux.go
- libcontainer/rootfs_linux.go
When I tried to start a rootless container under a different/wrong user,
I got:
```console
$ ../runc/runc --systemd-cgroup --root /tmp/runc.$$ run 445
ERRO[0000] runc run failed: operation not permitted
```
This is obviously not good enough. With this commit, the error is:
```console
ERRO[0000] runc run failed: fchown fd 9: operation not permitted
```
Alas, there are still some code that returns unwrapped errnos from
various unix calls.
This is a followup to commit d8ba4128b299a8 (part of PR #3011) which wrapped
many, but not all, bare unix errors. Do wrap some more, using either os.PathError
or os.SyscallError.
While at it,
- use os.SyscallError instead of os.NewSyscallError;
- use errors.Is(err, os.ErrXxx) instead of os.IsXxx(err).
> libct: wrap more unix errors

- libcontainer/integration/checkpoint_test.go
- tests/integration/dev.bats
_TL;DR: backports of #3112 and #3069 to release-1.0 branch to fix CI broken by upstream updates._
The ParentImage set by the test should be a path relative to
ImagesDirectory, pointing to a parent images directory (created
by pre-dump).
The parent directory is created by TempDir and so its name is not
constant but has a variable suffix. So, the config was pointing to
a non-existent directory.
This left unnoticed by criu as it assumed the parent image does not
exist, and performed a full dump.
Since criu PR https://github.com/checkpoint-restore/criu/pull/1403 (will be a part of criu 3.16) that is no longer the
case -- the invalid parent path is treated as an error, and so our
test fails like this:
```
== RUN   TestCheckpoint
checkpoint_test.go:145: === /tmp/criu070876105/dump.log === …
```
> [1.0] fix ci

- libcontainer/specconv/spec_linux.go
- libcontainer/specconv/spec_linux_test.go
This is a set of improvements for libct/specconv. See individual commits for details.
The refactoring should help #3227
> libct/specconv: reduce init allocations, use global maps, refactor

- libcontainer/specconv/spec_linux.go
- libcontainer/specconv/spec_linux_test.go
This is a followup to #3281, addressing some review comments.
1. Decapitalize errors.
2. Rename isValidName to checkPropertyName.
3. Make it return a specific error.
> libct/specconv: nits

- libcontainer/container_linux.go
- libcontainer/specconv/spec_linux.go
Using null bytes as control characters for sending strings via netlink
opens us up to a user explicitly putting a null byte in a mount string
(which JSON will happily let you do) and then causing us to open a mount
path different to the one expected.
In practice this is more of an issue in an environment such as
Kubernetes where you may have path-based access control policies (which
are more susceptible to these kinds of flaws).
Found by Google Project Zero.
Fixes: 9c444070ec7b ("Open bind mount sources from the host userns")
Reported-by: Felix Wilhelm <fwilhelm@google.com>
> specconv: do not permit null bytes in mount fields

- libcontainer/process_linux.go
There is no need to run hooks when `Config.Hooks` is just an empty map,
(dlv) p p.config.Config.Hooks
github.com/opencontainers/runc/libcontainer/configs.Hooks []
Signed-off-by: Dave Chen <dave.chen@arm.com>
> Avoid non-op when the list of `Hooks` is empty

- .cirrus.yml
- .github/workflows/test.yml
- Dockerfile
- Vagrantfile.fedora
- libcontainer/rootfs_linux.go
- tests/integration/mounts_sshfs.bats
As reported in https://github.com/containers/podman/issues/12205, in a case where read-only fuse (sshfs)
mount is used as a volume without specifying ro flag, the kernel fails
to remount it (when adding various flags such as nosuid and nodev),
returning EPERM.
Here's the relevant strace line:
> [pid 333966] mount("/tmp/bats-run-PRVfWc/runc.RbNv8g/bundle/mnt", "/proc/self/fd/7", 0xc0001e9164, MS_NOSUID|MS_NODEV|MS_REMOUNT|MS_BIND|MS_REC, NULL) = -1 EPERM (Operation not permitted)
I was not able to reproduce it with other read-only mounts as the source
(tried tmpfs, read-only bind mount, and an ext2 mount), so somehow this
might be specific to fuse.
The fix is to check whether the source has RDONLY flag, and retry the
remount with this flag added.
A test case (which was kind of hard to …
> Fix failure with rw bind mount of a ro fuse

- Vagrantfile.fedora
Since https://bugzilla.redhat.com/2022041 is fixed (in
systemd-249.7-2.fc35), the exclude kludge can be dropped.
This partially reverts commit b028ecb352c56269 (#3273).
> Vagrantfile.fedora: revert excluding systemd

- .cirrus.yml
- .github/workflows/test.yml
- Dockerfile
- Vagrantfile.fedora34
- libcontainer/rootfs_linux.go
- tests/integration/mounts_sshfs.bats
_This is a backport of #3283 to release-1.0 branch. See original PR for details._
Fixes: containers/podman#12205
> [1.0] Fix failure with rw bind mount of a ro fuse

- libcontainer/cgroups/fs/fs.go
- libcontainer/cgroups/fs/hugetlb.go
- libcontainer/cgroups/fs/hugetlb_test.go
- libcontainer/cgroups/fs2/hugetlb.go
- libcontainer/cgroups/utils.go
- libcontainer/cgroups/utils_test.go
~~_(this is based on and currently includes PR #3233)_~~
1. Since GetHugePageSize do not have any external users (checked by
sourcegraph), and no internal user ever uses its second return value
(the error), let's drop it.
2. Rename GetHugePageSize -> HugePageSizes (drop the Get prefix as per
Go guidelines, add suffix since we return many sizes).
3.  Implement lazy init for `HugePageSizes`
I have noticed that libct/cg/fs allocates 8K during init on every runc
execution:
> init github.com/opencontainers/runc/libcontainer/cgroups/fs @1.5 ms, 0.028 ms clock, **8512 bytes, 13 allocs**
Apparently this is caused by the global `HugePageSizes` variable initialization,
which is only used from `GetStat`s (i.e. it is never used by the runc binary itself).
Remove it, and use `HugePageSizes()` directly …
> libct/cg: refactor/improve/rename GetHugePageSize -> HugePageSizes

- libcontainer/cgroups/fs2/hugetlb.go
Cherry-pick https://github.com/opencontainers/runc/pull/3233
(I assume cherry-picking https://github.com/opencontainers/runc/pull/3234 is not necessary)
> [1.0] libct/cg/fs2: fix GetStats for unsupported hugetlb

- libcontainer/rootfs_linux.go
- tests/integration/mounts.bats
_This is a backport of #3276 to release-1.0 branch. Original description follows._
_NOTE: draft pending merge of ~~#3282 and~~ #3276._
----
Commit fb4c27c4b79c7d (PR #2570, went into v1.0.0-rc93) fixed a bug with
read-only tmpfs, but introduced a bug with read-only /dev (#3248).
This happens because /dev is a tmpfs mount and is therefore remounted
read-only a bit earlier than before.
To fix,
1. Revert the part of the above commit which remounts all tmpfs mounts
as read-only in mountToRootfs.
2. Reuse finalizeRootfs (which is already used to remount /dev
read-only) to also remount all ro tmpfs mounts that were previously
mounted rw in mountPropagate.
Add a test case to validate the fix and prevent future regressions;
make sure it fails before the fix:
```
✗ runc run [ro /dev mount]
(in …
```
> [1.0] Fix failure with read-only /dev in spec

- .golangci.yml
- checkpoint.go
- libcontainer/cgroups/devices/devices_emulator.go
- libcontainer/cgroups/ebpf/devicefilter/devicefilter.go
- libcontainer/cgroups/fs/blkio_test.go
- libcontainer/factory_linux.go
- libcontainer/init_linux.go
- libcontainer/integration/exec_test.go
- libcontainer/integration/seccomp_test.go
- libcontainer/integration/utils_test.go
- notify_socket.go
- tty.go
- utils_linux.go
It looks like unparam is a meaningful linter.
All commits except one are small and easy to review.
> Enable unparam linter; fix/mute existing warnings

- libcontainer/cgroups/systemd/v2.go
This is a backport of https://github.com/opencontainers/runc/pull/3226 to release-1.0 branch, fixing issue #3225.
Note it's not a clean backport as 1.0 lacks fsMgr field, and we do not want to instantiate one, so the commit was changed:
```diff
-       err := m.fsMgr.Destroy()
-       // fsMgr.Destroy has handled ErrNotExist
+       err := cgroups.RemovePath(m.path)
+       // cgroups.RemovePath has handled ErrNotExist
```
```
Bugfixes:
* cgroup v2 systemd manager: delete sub-cgroups on cgroup delete
```
> [1.0] Remove sub cgroup when container exits

- script/release.sh
_backport of #3200 to release-1.0 branch_
openSUSE comes with site-config package, which makes configure select
${prefix}/lib64 as libdir on x86_64, unless explicitly specified.
Since release.sh relies on a particular libdir path (for pkgconfig), it
breaks things:
> + make -C /home/kir/git/runc PKG_CONFIG_PATH=/tmp/tmp.QgIJ1sR5c9/lib/pkgconfig COMMIT_NO= EXTRA_FLAGS=-a 'EXTRA_LDFLAGS=-w -s -buildid=' static
> make[1]: Entering directory '/home/kir/git/runc'
> CGO_ENABLED=1 go build -trimpath -a -tags "seccomp netgo osusergo" -ldflags "-extldflags -static -X main.gitCommit=v1.0.0-204-g963e0146 -X main.version=1.0.0+dev -w -s -buildid=" -o runc .
> Package libseccomp was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libseccomp.pc'
To fix, we …
> [1.0] script/release.sh: fix for opensuse

- .github/workflows/test.yml
_This is the same as https://github.com/opencontainers/runc/pull/3021 but for release-1.0._
Add Go 1.17, grop 1.15 from CI; since 1.17 release 1.15 is unsupported.
Keep 1.13 in 1.0 branch, since an older version of Docker/Moby might use it.
Keep 1.16 in Dockerfile, since this is a stable branch.
> [1.0]: ci: add go 1.17, drop go 1.15

- libcontainer/cgroups/systemd/v2.go
- libcontainer/configs/cgroup_linux.go
- libcontainer/specconv/spec_linux.go
- tests/integration/cgroup_delegation.bats
Delegating cgroups to the container enables more complex workloads,
including systemd-based workloads.  The OCI runtime-spec was
recently updated to explicitly admit such delegation, through
specification of cgroup ownership semantics:
https://github.com/opencontainers/runtime-spec/pull/1123
Pursuant to the updated OCI runtime-spec, change the ownership of
the container's cgroup directory and particular files therein, when
using cgroups v2 and when the cgroupfs is to be mounted read/write.
As a result of this change, systemd workloads can run in isolated
user namespaces on OpenShift when the sandbox's cgroupfs is mounted
read/write.
It might be possible to implement this feature in other cgroup
managers, but that work is deferred.
> chown cgroup to process uid in container namespace

- .github/workflows/validate.yml
- .golangci-extra.yml
This adds a new GHA CI job which runs a few extra linters. This is only
done for pull requests, and should only warn about new code.
The justification is simple: we want more linters, but since this is not
a new project, adding a new linter meaning we have to fix all the
existing warnings. In some cases having all the warnings fixed is
difficult and takes time, plus it is usually a low priority task.
Therefore, we are stuck with inability to add new linters because we
can't fix all their warnings. Meanwhile, new pull requests add more
code which is not linted.
This is an attempt to break this vicious cycle. Let's enable godot
and revive for now and see how it is going.
> ci: enable extra linters for new code

- tests/integration/helpers.bash
- tests/integration/hooks.bats
1. tests/int: ability to specify binary
This can be used to specify a different runc binary, for example:
sudo -E RUNC=$PWD/runc.mine tests/integration/cwd.bats
A different (but compatible enough) runtime also works:
sudo -E RUNC=/usr/local/bin/crun tests/integration/cwd.bats
2. tests/int: use update_config in hooks test
Using "$@" instead of $1 in update_config() allows us to use it from
hooks.bats, where jq is used with more options than usual.
> libct/int: minor improvements

- CHANGELOG.md
This will make releases much simpler. I've back-filled the changelog
with everything since runc 1.0.0 (there's not much point going further
back than that).
> CHANGELOG: add an in-repo changelog file

- libcontainer/nsenter/nsenter_unsupported.go
Commit 4d1d6185abda6a5d43eac75f77242488b81f8937 added this
nsenter_unsupported.go file in order for nsenter to be a valid (but
empty, non-functional) Go package on unsupported platforms.
As a result, runc can be build successfully without CGO, which results
in a non-working and hard-to-debug binary (see issue #3330).
As the functionality of being able to compile a package which is
definitely not working is questionable, and I can't think of any use
cases, let's remove the file.
With this, runc can no longer be build without CGO:
[kir@kir-rhat runc]$ CGO_ENABLED=0 make runc
go build -trimpath "-buildmode=pie"  -tags "seccomp" -ldflags "-X main.gitCommit=v1.0.0-452-g00f56786-dirty -X main.version=1.1.0-rc.1+dev " -o runc .
go build github.com/opencontainers/runc/libcontainer/nsenter: build …
> Refuse to build runc without nsenter

- libcontainer/intelrdt/intelrdt.go
For the Nth time I wanted to replace parsing mountinfo with
statfs and the check for superblock magic, but it is not possible
since some code relies of mount options check which can only
be obtained via mountinfo.
Add a note about it.
Currently a draft, pending #3306 merge.
> libct/intelrdt: explain why mountinfo is required

- libcontainer/specconv/spec_linux.go
> libct/specconv: rm empty key from mountPropagationMapping

- libcontainer/factory_linux.go
Commit 7cfb107f2c5be3 started using unix.Geteuid(), unix.Getegid() as
uid/gid argument for chown. It seems that it should have removed chown
entirely, since, according to mkdir(2),
> The newly created directory will be owned by the effective user ID of
> the process. If the directory containing the file has the
> set-group-ID bit set, or if the filesystem is mounted with BSD
> group semantics (mount -o bsdgroups or, synonymously mount -o grpid),
> the new directory will inherit the group ownership from its parent;
> otherwise it will be > owned by the effective group ID of the process.
So, the only effect of the chown after mkdir is ignoring the sgid bit
on the parent directory (which is probably not the right thing to do).
> libct: Create: rm unneeded chown

- libcontainer/init_linux.go
TL;DR: do not chown `/dev/std{in,out,err}` if there's no need; ignore EROFS when chown fails.
For the context, see https://github.com/containers/podman/pull/12954
Please review commit-by-commit.
> Fix working with read-only /dev

- .github/workflows/test.yml
- libcontainer/factory_linux.go
Release notes: https://go.dev/blog/go1.18beta1
This is just for CI.
> ci: add go 1.18beta1

- list.go
It is possible that parallel execution of `runc list` with `runc delete` will result in `runc list` fatal failure. Fix this.
Bonus: some refactoring.
Please review with --ignore-all-space ("Hide whitespace" checked on GH).
> runc list: fix race with runc delete + nits

- libcontainer/init_linux.go
This is a backport of #3345 to 1.1 branch, needed for newer Podman (see https://github.com/containers/podman/pull/12954).
See original PR for details.
> [1.1] Fix working with read-only /dev

- CHANGELOG.md
- contrib/completions/bash/runc
- libcontainer/container_linux.go
- libcontainer/factory_linux.go
- main.go
- man/runc.8.md
- tests/integration/checkpoint.bats
- tests/integration/helpers.bash
- utils_linux.go
This was introduced in an initial commit, back in the day when criu was
a highly experimental thing. Today it's not; most users who need it have
it packaged by their distro vendor.
The usual way to run a binary is to look it up in directories listed in
$PATH. This is flexible enough and allows for multiple scenarios (custom
binaries, extra binaries, etc.). This is the way criu should be run.
Make `--criu` a hidden option (thus removing it from help). Remove the
option from man pages, integration tests, etc. Remove all traces of
CriuPath from data structures.
Add a warning that `--criu` is ignored and will be removed.
_This used to be part of #3316._
> runc: remove --criu option

- libcontainer/container.go
- libcontainer/container_linux.go
Upon running tests via `make test`, I encountered flaky failures, I'll look into those and see if they have something to do with my host because I noticed the same behavior on `main` too.
Addresses #3343
> libcontainer: remove "pausing" state

- libcontainer/configs/mount.go
- libcontainer/integration/exec_test.go
- libcontainer/rootfs_linux.go
Those were added by commit 59c5c3ac0 back in Apr 2015, but AFAICS were
never used and are obsoleted by more generic container hooks (initially
added by commit 05567f2c944 in Sep 2015).
> libct: Mount: rm {Pre,Post}mountCmds

- signals.go
Here's how it looks now:
```console
$ runc --debug exec ctid sleep 1h
...
DEBU[0000]signals.go:102 main.(*signalHandler).forward() sending signal to process urgent I/O condition
DEBU[0000]signals.go:102 main.(*signalHandler).forward() sending signal to process urgent I/O condition
DEBU[0022]signals.go:102 main.(*signalHandler).forward() sending signal to process terminated
DEBU[0022]signals.go:102 main.(*signalHandler).forward() sending signal to process urgent I/O condition
```
This is obviously not very readable.
Use unix.SignalName, and add PID while we're at it.
With this commit:
```console
DEBU[0000]signals.go:103 main.(*signalHandler).forward() forwarding signal 23 (SIGURG) to 891345
DEBU[0020]signals.go:103 main.(*signalHandler).forward() forwarding signal 45 () to 891345 …
```
> signals: fix signal name debug print

- signals.go
Foreground runc exec and runc run forwards all the signals (that it can)
to the process being run.
Since Go 1.14, go runtime uses SIGURG for async preemptive scheduling.
This means that runc regularly receives SIGURG and, in case of
foreground runc run/exec, it gets forwarded to the container process.
For example:
[kir@kir-rhat runc]$ sudo ./runc --debug exec xx67 sleep 1m
...
DEBU[0000] child process in init()
DEBU[0000] setns_init: about to exec
DEBU[0000]signals.go:102 main.(*signalHandler).forward() sending signal to process urgent I/O condition
DEBU[0000]signals.go:102 main.(*signalHandler).forward() sending signal to process urgent I/O condition
DEBU[0000]signals.go:102 main.(*signalHandler).forward() sending signal to process urgent I/O condition
...
Or, with slightly better debug …
> runc run/exec: ignore SIGURG

- libcontainer/README.md
- libcontainer/configs/validate/rootless.go
- libcontainer/configs/validate/rootless_test.go
- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
- libcontainer/container_linux.go
- libcontainer/container_linux_test.go
- libcontainer/factory_linux.go
- libcontainer/factory_linux_test.go
- libcontainer/intelrdt/intelrdt.go
- libcontainer/intelrdt/intelrdt_test.go
- libcontainer/process_linux.go
- libcontainer/specconv/spec_linux_test.go
- utils_linux.go
- vendor/golang.org/x/sys/execabs/execabs.go
- vendor/modules.txt
_This used to be part of #3316._
This set cleanups LinuxFactory, removing some interfaces, option functions etc. Lots of changes, but mostly removal.
This removes about 6K of code and 5K of data from the binary, reducing its overall size by 0.1% (not counting debuginfo, i.e. for a stripped binary) without any change in functionality.
More importantly, this improves readability a notch by simplifying some code and data structures, and removing about 200 lines of code and tests.
> Factory cleanup

- .github/workflows/validate.yml
- tests/integration/events.bats
- tests/integration/helpers.bash
1. This valid warning is reported by shellcheck v0.8.0:
```
In tests/integration/helpers.bash line 38:
KERNEL_MINOR="${KERNEL_VERSION#$KERNEL_MAJOR.}"
^-----------^ SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.
Did you mean:
KERNEL_MINOR="${KERNEL_VERSION#"$KERNEL_MAJOR".}"
```
Fix this.
2. These (invalid) warnings are also reported by the new version:
```
In tests/integration/events.bats line 13:
@test "events --stats" {
^-- SC2030 (info): Modification of status is local (to subshell caused by @bats test).
In tests/integration/events.bats line 41:
[ "$status" -eq 0 ]
^-----^ SC2031 (info): status was modified in a subshell. That change might be lost.
```
Basically, this is happening because shellcheck do not really track
the call …
> ci: shellcheck: update to 0.8.0, fix/suppress new warnings

- exec.go
- libcontainer/container_linux.go
- libcontainer/utils/utils.go
- libcontainer/utils/utils_test.go
* libct/utils: SearchLabels: optimize
Using strings.Split generates temporary strings for GC to collect.
Rewrite the function to not do that.
Also, add a second return value, so that the caller can distinguish
between an empty value found and no key found cases.
Fix the test accordingly.
* libct: handleCriuConfigurationFile: use utils.SearchLabels
The utils.Annotations was used here before only because it made it
possible to distinguish between "key not found" and "empty value" cases.
With the previous commit, utils.SearchLabels can do that, and so it
makes sense to use it.
> libcontainer: optimize utils.SearchLabels

- CHANGELOG.md
- libcontainer/nsenter/cloned_binary.c
After adding some debug info to cloned_binary.c I found out that
is_self_cloned() is not working right when runc binary is on tmpfs,
resulting in one extra re-exec of runc.
With some added debug:
$ mkdir bin
$ sudo mount -t tmpfs tmp bin
$ sudo cp runc bin
$ sudo ./bin/runc --debug exec xxx true
DEBU[0000] nsexec[763590]: => is_self_cloned
DEBU[0000] nsexec[763590]: got seals 1 (want 15)
DEBU[0000] nsexec[763590]: <= is_self_cloned, is_cloned = 0
DEBU[0000] nsexec[763590]: try_bindfd: 5
DEBU[0000] nsexec[763590]: re-exec itself...
DEBU[0000] nsexec[763590]: => is_self_cloned
DEBU[0000] nsexec[763590]: got seals 1 (want 15)
DEBU[0000] nsexec[763590]: <= is_self_cloned, is_cloned = 0
DEBU[0000] nsexec[763590]: try_bindfd: -1
DEBU[0000] nsexec[763590]: fallback to make_execfd: 5
DEBU[0000] …
> libct/nsenter: fix extra runc re-exec on tmpfs

- libcontainer/specconv/spec_linux.go
- libcontainer/specconv/spec_linux_test.go
See commits for details.
Mostly done because the comment was misleading, not in line with what the code did.
Fix the code, so now the comment is fine.
> libct/specconv: checkPropertyName speedup

- libcontainer/container_linux.go
- tests/integration/exec.bats
As `runc exec --cgroup` means: run the process in an (existing) sub-cgroup(s), so I think we should ensure the given path in the param is a sub-cgroup path.
> ensure the path is a sub-cgroup path

- libcontainer/configs/validate/validator.go
Don't require CAT or MBA because we don't detect those correctly (we
don't support L2 or L3DATA/L3CODE for example, and in the future
possibly even more). With plain "ClosId mode" we don't really care: we
assign the container to a pre-configured CLOS without trying to do
anything smarter.
Moreover, this was a duplicate/redundant check anyway, as for CAT and
MBA there is another specific sanity check that is done if L3 or MB
is specified in the config.
> configs/validate: looser validation for RDT

- .github/workflows/validate.yml
- libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go
- libcontainer/process_linux.go
- update.go
and format sources using gofumpt 0.2.1 (which is uncluded to that golangci-lint version).
> ci: bump golangci-lint to v1.44, golangci-lint-action to v3

- libcontainer/container_linux.go
- tests/integration/exec.bats
Backport of https://github.com/opencontainers/runc/pull/3381 to 1.1.
> [1.1] runc exec --cgroup: ensure the path is a sub-cgroup path

- checkpoint.go
- list.go
- main.go
- restore.go
- rootless_linux.go
- utils.go
- utils_linux.go
This is mostly some minor refactoring, making things cleaner.
The only significant change is `runc --root non-existent-dir list` now reports an error for non-existent root directory. The error is not reported in case a default root is used.
This is a preparation for #3373.
> Assorted CLI nitpicks

- libcontainer/cgroups/systemd/user.go
1. Properly escape the value of dbus address spec.
2. Remove using `systemctl --user --no-pager show-environment` because:
- is does the same thing we do (get address from `DBUS_SESSION_BUS_ADDRESS` or try to construct it from `XDG_RUNTIME_DIR`);
- it fails when both those variables are unset:
$ echo $DBUS_SESSION_BUS_ADDRESS, $XDG_RUNTIME_DIR
unix:path=/run/user/1000/bus, /run/user/1000
$ systemctl --user --no-pager show-environment | grep DBUS_SESS
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
$ unset DBUS_SESSION_BUS_ADDRESS
$ systemctl --user --no-pager show-environment | grep DBUS_SESS
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
$ unset XDG_RUNTIME_DIR
$ systemctl --user --no-pager show-environment | grep DBUS_SESS
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS …
> libct/cg/sd: simplify DetectUserDbusSessionBusAddress

- libcontainer/cgroups/systemd/v2.go
_Backport of #3389 to 1.1. Original description follows._
----
Apparently, not all files listed in `/sys/kernel/cgroup/delegate` must
exist in every cgroup, so we should ignore `ENOENT`.
Dot not ignore `ENOENT` on the directory itself though.
Change cgroupFilesToChown to not return `.`, and refactor it to not do
any dynamic slice appending in case we're using the default built-in
list of files.
Fixes: 35d20c4e0
> [1.1] libct/cg/sd/v2: fix ENOENT on cgroup delegation

- libcontainer/configs/validate/validator.go
_Backport of https://github.com/opencontainers/runc/pull/3382._
----
Don't require CAT or MBA because we don't detect those correctly (we
don't support L2 or L3DATA/L3CODE for example, and in the future
possibly even more). With plain "ClosId mode" we don't really care: we
assign the container to a pre-configured CLOS without trying to do
anything smarter.
Moreover, this was a duplicate/redundant check anyway, as for CAT and
MBA there is another specific sanity check that is done if L3 or MB
is specified in the config.
Signed-off-by: Markus Lehtonen <markus.lehtonen@intel.com>
(cherry picked from commit 1d5c331042acbce433e48a2f3a277f8e08fe998c)
> [release-1.1] configs/validate: looser validation for RDT

- tests/integration/seccomp-notify.bats
This PR fixes a typo in the name of a test (reported in #3415) and, while I was there, I also looked at all the tests in that file and made sure the name was correct. While doing so, I added a 1 line sentence to clarify the intent, as other tests in that file already do.
Fixes: #3415 
cc @mauriciovasquezbernal @alban
> tests: Improve seccomp-notify test names and description

- tests/integration/delete.bats
The following failure was observed in CI (on centos-stream-8 in
integration-cgroup suite):
not ok 42 runc delete
(from function `fail' in file tests/integration/helpers.bash, line 338,
in test file tests/integration/delete.bats, line 30)
`[ "$output" = "" ] || fail "cgroup not cleaned up correctly: $output"' failed
....
cgroup not cleaned up correctly: /sys/fs/cgroup/pids/system.slice/tmp-bats\x2drun\x2d68012-runc.IPOypI-state-testbusyboxdelete-runc.zriC8C.mount
/sys/fs/cgroup/cpu,cpuacct/system.slice/tmp-bats\x2drun\x2d68012-runc.IPOypI-state-testbusyboxdelete-runc.zriC8C.mount
...
Apparently, this is a cgroup systemd creates for a mount unit which
appears then runc does internal /proc/self/exe bind-mount. The test
case should not take it into account.
Fix the find arguments to look for …
> tests/int: runc delete: fix flake, enable for rootless

- tests/integration/cgroups.bats
- tests/integration/checkpoint.bats
- tests/integration/cwd.bats
- tests/integration/help.bats
- tests/integration/helpers.bash
- tests/integration/hooks.bats
- tests/integration/list.bats
- tests/integration/root.bats
- tests/integration/update.bats
- tests/rootless.sh
Fix all existing cases where `set -u` can be problematic, and add it globally for all tests.
This is a way to prevent the code doing something really bad when a
variable it uses is not set. Good to have since it helps to catch some
logical errors etc.
This also fixes a bug of not running CRIU tests; see https://github.com/opencontainers/runc/pull/3367#discussion_r823305088 for details.
For brevity, this PR concentrates on enabling `set -u` only. Various cleanups on top of it are in #3369.
> tests: add `set -u`

- README.md
- libcontainer/README.md
1. README,libct/README: fix pkg.go.dev badges
What used to be godoc.org is now pkg.go.dev, and while the old URLs
still work, they might be broken in the future.
Updated badges are generated via https://pkg.go.dev/badge/
2. README: add cirrus-ci status badge
> README,libct/README: fix pkg.go.dev badges

- .cirrus.yml
Add centos-stream-9 to our CI matrix. It runs natively on Cirrus CI and is therefore faster than Fedora job (4 minutes instead of 13 minutes).
centos-stream-9 currently has:
- kernel 5.14.0-71.el9
- criu 3.15
so it is quite similar to Fedora 35 at the moment (and this, I guess, explains why we have no issues).
I was thinking at dropping Fedora but decided to keep it since while it does not make much sense now, with a newer Fedora it definitely will (newer kernels etc.)
> CI/cirrus: add centos-stream-9

- delete.go
- libcontainer/container.go
- libcontainer/container_linux.go
- libcontainer/container_linux_test.go
- libcontainer/factory_linux.go
- libcontainer/factory_linux_test.go
- libcontainer/integration/utils_test.go
- libcontainer/process_linux.go
- libcontainer/state_linux.go
- libcontainer/state_linux_test.go
- notify_socket.go
- utils_linux.go
~~_Based on and currently includes #3373. Draft until that one is merged._~~
The only implementation of `BaseContainer` and `Container` is `linuxContainer`. It does not make
sense to have an interface with a single implementation, and we do not
foresee other types of containers being added to runc.
- Remove `BaseContainer` and`Container` interfaces, moving their methods
documentation to `linuxContainer`.
- Rename `linuxContainer` to `Container`.
- Adopt users from using interface to using struct.
Continuing the spring cleaning started in #3354. Loosely based on parts of #3316.
> libct: rm BaseContainer and Container interfaces

- libcontainer/cgroups/utils.go
In case `statfs("/sys/fs/cgroup/unified")` fails with any error other
than `ENOENT`, current code panics. As `IsCgroup2HybridMode` is called from
`libcontainer/cgroups/fs`'s `init` function, this means that any user of
libcontainer may panic during initialization, which is ugly.
Avoid panicking; instead, do not enable hybrid hierarchy support and
report the error (under debug level, not to confuse anyone).
Basically, replace the panic with "turn off hybrid mode support"
(which makes total sense since we were unable to statfs its root).
This is an alternative to #3432. The bug is originally reported by @liggitt
in https://github.com/kubernetes/kubernetes/pull/109029#pullrequestreview-922146797
> libct/cg: IsCgroup2HybridMode: don't panic

- .cirrus.yml
_Backport of #3427 to 1.1. Original description follows._
----
Add centos-stream-9 to our CI matrix. It runs natively on Cirrus CI and is therefore faster than Fedora job (4 minutes instead of 13 minutes).
centos-stream-9 currently has:
- kernel 5.14.0-71.el9
- criu 3.15
so it is quite similar to Fedora 35 at the moment (and this, I guess, explains why we have no issues).
I was thinking at dropping Fedora but decided to keep it since while it does not make much sense now, with a newer Fedora it definitely will (newer kernels etc.)
> [1.1] add centos-stream-9

- .github/workflows/test.yml
- .github/workflows/validate.yml
Since we have renamed our default branch (https://github.com/opencontainers/runc/issues/3250), GHA CI is no longer testing
it (see https://github.com/opencontainers/runc/actions).
Fix this.
> ci/gha: run on main branch

- .github/workflows/test.yml
Since the recent bump of actions/setup-go to v3 (commit
9d2268b9dbd5421f0), specifying "stable:" is no longer needed
when we want to try a beta or rc version of Go.
Remove it.
(This is a followup to https://github.com/opencontainers/runc/pull/3454#issuecomment-1095575483)
> ci/gha: remove stable: when installing Go

- .cirrus.yml
- .github/workflows/validate.yml
- Makefile
- contrib/cmd/seccompagent/gen-seccomp-example-cfg.sh
- man/md2man-all.sh
- script/check-config.sh
This _almost_ fixes the TODO item for shellcheck.
Please review commit-by-commit; see individual commits for details.
> shellcheck/shfmt more files; run check-config in CI

- .github/workflows/validate.yml
- .golangci-extra.yml
There is no need to parallelize lint and lint-extra jobs,
and they only differ with the arguments to golangci-lint.
Given that the longest time spent in these jobs is installing
libseccomp-dev, and that the second linter run can probably
benefit a lot from caching, it makes sense to merge them.
Move lint-extra from a separate job to a step in lint job.
> ci/gha: convert lint-extra from a job to a step

- libcontainer/rootfs_linux.go
- libcontainer/rootfs_linux_test.go
The `CAP_CHECKPOINT_RESTORE` linux capability provides the ability to update `/proc/sys/kernel/ns_last_pid`. However, because this "file" is under `/proc`, and by default both K8s and CRI-O specify that `/proc/sys` should be mounted as Read-Only, even with the capability specified, a process will not be able to write to `ns_last_pid`.
To get around this, a pod author can specify a volume mount and a host path to bind-mount `/proc/sys/kernel/ns_last_pid`. However, `runc` does not allow specifying mounts under `/proc`.
This PR adds `/proc/sys/kernel/ns_last_pid` to the `validProcMounts` string array to enable a pod author to mount `ns_last_pid` as read-write. The default remains unchanged; unless explicitly requested as a volume mount, `ns_last_pid` will remain read-only regardless of …
> Allow mounting of /proc/sys/kernel/ns_last_pid

- .github/workflows/test.yml
- .github/workflows/validate.yml
By default, GHA CI jobs have lots of permissions, which is not good as it can be used by malicious GH actions to e.g. write to the repo.
Most jobs that we have only require to read the repo. Some require to read PRs as well.
Set permissions accordingly.
For details, see
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
Inspired by #3430 
Closes: #3430
> ci/gha: limit jobs permissions

- tests/integration/cgroups.bats
- tests/integration/checkpoint.bats
- tests/integration/create.bats
- tests/integration/delete.bats
- tests/integration/dev.bats
- tests/integration/exec.bats
- tests/integration/helpers.bash
- tests/integration/list.bats
- tests/integration/mask.bats
- tests/integration/pause.bats
- tests/integration/ps.bats
- tests/integration/run.bats
- tests/integration/start_detached.bats
- tests/integration/start_hello.bats
- tests/integration/tty.bats
- tests/integration/update.bats
- tests/integration/userns.bats
- tests/rootless.sh
~~_Based on and currently includes #3367 ~~and #3371~~. Draft until those are merged._~~
This is a set of bash code cleanups for integration tests, mostly done for correctness, uniformity, and readability.
Please review commit by commit, and see individual commit messages for details.
> tests/int: nits and cleanups

- tests/integration/helpers.bash
As a result, cgroup v1 only tests are being skipped 🤦🏻 
Fixes: a2123baf63fd
> tests/int: fix a bad typo

- libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go
- libcontainer/specconv/spec_linux.go
Looking through git blame, this was added by commit 9fac18329
aka "Initial commit of runc binary", most probably by mistake.
Obviously, a container should not have access to tun/tap device, unless
it is explicitly specified in configuration.
Now, removing this might create a compatibility issue, but I see no
other choice.
Aside from the obvious misconfiguration, this should also fix the
annoying
> Apr 26 03:46:56 foo.bar systemd[1]: Couldn't stat device /dev/char/10:200: No such file or directory
messages from systemd on every container start, when runc uses systemd
cgroup driver, and the system runs an old (< v240) version of systemd
(the message was presumably eliminated by [1]).
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1945929
[1] …
> Remove tun/tap from the default device rules

- Vagrantfile.fedora
Currently Fedora CI is broken on all PRs. This is caused by the updated git,
as a result we can no longer build runc via sudo from Vagrant:
ssh default 'sudo -i make -C /vagrant localunittest'
make: Entering directory '/vagrant'
fatal: unsafe repository ('/vagrant' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /vagrant
go build -trimpath "-buildmode=pie"  -tags "seccomp" -ldflags "-X main.gitCommit= -X main.version=1.1.0+dev " -o runc .
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
make: Leaving directory '/vagrant'
This commit should fix this.
> Vagrantfile.fedora: fix build wrt new git

- .github/workflows/test.yml
- .github/workflows/validate.yml
- Vagrantfile.fedora
- libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go
- libcontainer/factory_linux.go
- libcontainer/process_linux.go
- update.go
This is a backport of
* #3471
* #3400
* #3370
* #3326 (partial, only commit 907aefd43cd91d4452ca79f0aea8b6ae594c6e95)
to release-1.1 branch, fixing broken CI. See original PRs for description.
> [1.1] Make CI green again

- .github/workflows/test.yml
- Dockerfile
- Makefile
- libcontainer/seccomp/config.go
- libcontainer/seccomp/patchbpf/enosys_linux.go
- script/lib.sh
This can be split into a few groups:
1. Dockerfile fixes.
2. Makefile fixes.
3. Enabling static PIE for arm64 and amd64.
4. Enabling riscv64.
> release: build riscv64 binary, build static PIE if supported

- libcontainer/cgroups/systemd/dbus.go
This fixes dbus.ErrClosed checker in "retry on dbus disconnect" logic, introduced in PR https://github.com/opencontainers/runc/pull/2923.  `dbus.ErrClosed` is not a  dbus.Error.
It can reproduce in kubelet:
1. start kubelet
2. `systemctl restart dbus` in this node
3. schedule some pod to this node. The pod will failed to start `dbus: connection closed by user`
So kubernetes need to bump libct with this fix.
Signed-off-by: Kang Chen <kongchen28@gmail.com>
> libct/cg/sd: check dbus.ErrClosed instead of isDbusError

- libcontainer/cgroups/systemd/dbus.go
This is a backport of https://github.com/opencontainers/runc/pull/3475 to release-1.1 branch. Original description follows:
----
This fixes dbus.ErrClosed checker in "retry on dbus disconnect" logic, introduced in PR https://github.com/opencontainers/runc/pull/2923.  `dbus.ErrClosed` is not a  dbus.Error.
It can reproduce in kubelet:
1. start kubelet
2. `systemctl restart dbus` in this node
3. schedule some pod to this node. The pod will failed to start `dbus: connection closed by user`
So kubernetes need to bump libct with this fix.
> [1.1] libct/cg/sd: check dbus.ErrClosed instead of isDbusError

- .github/workflows/validate.yml
This job is failing with "No space left on device" lately, and this
helps to fix it.
Besides, it seems that caching does not help to shorten execution times
(validate/release job succeeds in under 8 minutes now; ymmv).
----
This is a forward-port of #3479 to main branch.
> ci: drop docker layer caching from release job

- libcontainer/seccomp/patchbpf/enosys_linux.go
- libcontainer/seccomp/patchbpf/enosys_linux_test.go
On s390x, syscalls above 255 are multiplexed using the (now otherwise
unused) setup(2) syscall (syscall number 0). If the kernel supports the
syscall then it will correctly translate the syscall number such that
seccomp will correctly detect it -- however, for unknown syscalls the
syscall number remains unchanged. This can be verified by running the
following program under strace:
int main(void)
{
scmp_filter_ctx ctx = seccomp_init(SCMP_ACT_TRAP);
seccomp_load(ctx);
return syscall(439, AT_FDCWD, "asdf", X_OK, 0);
}
Which will then die with the following signal (on pre-5.8 kernels):
--- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP,
si_call_addr=0x3ffb3006c22, si_syscall=__NR_setup,
si_arch=AUDIT_ARCH_S390X} ---
(Note that the si_syscall is __NR_setup, not __NR_faccessat2.)
As a result, the …
> [1.1] seccomp: enosys: always return -ENOSYS for setup(2) on s390(x)

- .github/workflows/validate.yml
This job is failing with "No space left on device" lately, and this
helps to fix this.
Besides, it seems that caching does not help to shorten execution times.
> [1.1] ci: drop docker layer caching from release job

- Makefile
- go.mod
- go.sum
- vendor/github.com/urfave/cli/README.md
- vendor/github.com/urfave/cli/docs.go
- vendor/github.com/urfave/cli/flag.go
- vendor/modules.txt
This removes the runc dependency on cpuguy83/md2man and
russross/blackfriday, which saves more than 400 KB (more than 300 KB
once stripped) from the binary.
> vendor: bump urfave/cli, add urfave_cli_no_docs tag

- script/seccomp.sh
Add checking of downloaded tarball checksum.
In case it doesn't match the hardcoded value, the error is like this:
libseccomp-2.5.4.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
In case the checksum for a particular version is not specified in the
script, the error will look like this:
./script/seccomp.sh: line 29: SECCOMP_SHA256[${ver}]: unbound variable
In case the the hardcoded value in the file is of wrong format/length,
we'll get:
sha256sum: 'standard input': no properly formatted SHA256 checksum lines found
In any of these cases, the script aborts (due to set -e).
Addresses https://github.com/opencontainers/runc/pull/3480#pullrequestreview-982570157
> script/seccomp.sh: check tarball sha256

- libcontainer/rootfs_linux.go
- libcontainer/rootfs_linux_test.go
> [1.1] Allow mounting of /proc/sys/kernel/ns_last_pid

- libcontainer/nsenter/nsexec.c
Remove upper bound in integer sanity check
to not restrict the number of socket-activated
sockets passed in.
Closes #3488
Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>
Is this a correct way to fix the bug? (I am not familiar with __runc__)
> libcontainer: relax getenv_int sanity check

- libcontainer/nsenter/nsexec.c
This is a backport of #3489 to release-1.1 branch.
Remove upper bound in integer sanity check
to not restrict the number of socket-activated
sockets passed in.
> [1.1] libcontainer: relax getenv_int sanity check

- libcontainer/cgroups/devices/systemd.go
systemd emits very loud warnings when the path specified doesn't exist
(which can be the case for some of our default rules). We don't need the
ruleset we give systemd to be completely accurate (we discard some kinds
of wildcard rules anyway) so we can safely skip adding these.
> cgroups: systemd: skip adding device paths that don't exist

- libcontainer/cgroups/systemd/common.go
> [1.1] cgroups: systemd: skip adding device paths that don't exist

- libcontainer/rootfs_linux.go
- tests/integration/userns.bats
Due to a bug in commit 9c444070ec7, mountFd is not cleared and
its value might be used for the subsequent mounts.
As mountFd is ignored for all but bind mounts, and bind mounts have
their own mountFd, this is a non-issue, except when the following very
specific set of conditions is met:
- userns (and mountns) are used
- cgroupns is not used
- cgroup v1 is used
- the mount for /sys/fs/cgroup is after the bind mount in spec
The bug manifests because cgroup v1 `/sys/fs/cgroup` mount
is internally transformed into a bunch of bind mounts (and those
bind mounts are using stale mountFd).
The bug manifests itself in either one of these two ways
(randomly, not entirely sure why):
1. One of /sys/fs/cgroup sub-mounts fails to mount.
2. The cgroup bind mounts succeed, but use the mountFd from the …
> libct: fix mounting via wrong proc fd

- libcontainer/nsenter/nsexec.c
kill(stage2_pid, SIGKILL) maybe will kill all processes except the process itself and init when the stage2_pid equals -1.
Signed-off-by: Guodong Zhu <guodong9211@gmail.com>
> libct/nsenter: switch to sane_kill()

- .github/workflows/validate.yml
- libcontainer/factory_linux.go
> Bump golangci-lint, fix an error path

- libcontainer/rootfs_linux.go
- tests/integration/userns.bats
Backport of #3510 to release-1.1 branch. The original description follows.
----
Due to a bug in commit 9c444070ec7, when the user and mount namespaces
are used, and the bind mount is followed by the cgroup mount in the
spec, the cgroup is mounted using the bind mount's mount fd.
This can be reproduced with podman 4.1 (when configured to use runc):
```console
$ podman run --uidmap 0:100:10000 quay.io/libpod/testimage:20210610 mount
Error: /home/kir/git/runc/runc: runc create failed: unable to start container process: error during container init: error mounting "cgroup" to rootfs at "/sys/fs/cgroup": mount /proc/self/fd/11:/sys/fs/cgroup/systemd (via /proc/self/fd/12), flags: 0x20502f: operation not permitted: OCI permission denied
```
or manually with the spec mounts containing something …
> [1.1] libct: fix mounting via wrong proc fd

- libcontainer/integration/checkpoint_test.go
- tests/integration/helpers.bash
Older criu versions fails to work with userns due to changes in glibc's
rseq. Skip a test if an older criu version is found.
Fixes (well, works around): https://github.com/opencontainers/runc/issues/3532
> CI: workaround CentOS Stream 9 criu issue

- libcontainer/integration/checkpoint_test.go
- tests/integration/checkpoint.bats
- tests/integration/delete.bats
- tests/integration/helpers.bash
1. Backport #3392 aka 728571c16fc05d2b823fdef59aba2bf69be409cf
2. Fix CI failure due to some GHA changes related to cgroups.
3. Partial backport of 6e1d476aaddc (tests/int changes only).
4. Backport #3539.
> [1.1] CI fixes

- libcontainer/nsenter/nsexec.c
Backport of https://github.com/opencontainers/runc/pull/3501 to release-1.1 branch.
Signed-off-by: guodong <guodong9211@gmail.com>
> [1.1] libct/nsenter: switch to sane_kill()

- libcontainer/intelrdt/intelrdt.go
- Relates to #3181 
Reading `/proc/cpuinfo` is a surprisingly expensive operation. [Since kernel version 4.12][1], opening `/proc/cpuinfo` on an x86 system can block for around 20 milliseconds while the kernel samples the current CPU frequency. There is [a very recent patch][2] which gets rid of the delay, but has yet to make it into the mainline kernel. Regardless, kernels for which opening `/proc/cpuinfo` takes 20ms will continue to be run in production for years to come. libcontainer only opens `/proc/cpuinfo` to read the processor feature flags so all the delays to get an accurate snapshot of the CPU frequency are just wasted time.
If we wanted to, we could interrogate the CPU features directly from userspace using the `CPUID` instruction. However, Intel and AMD CPUs have flags in …
> libct/intelrdt: skip reading /proc/cpuinfo

- go.mod
- go.sum
- libcontainer/configs/config.go
- libcontainer/seccomp/seccomp_linux.go
- libcontainer/specconv/spec_linux.go
- tests/integration/seccomp.bats
- vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
- vendor/modules.txt
List of seccomp flags defined in runtime-spec:
* SECCOMP_FILTER_FLAG_TSYNC
* SECCOMP_FILTER_FLAG_LOG
* SECCOMP_FILTER_FLAG_SPEC_ALLOW
Note that runc does not apply SECCOMP_FILTER_FLAG_TSYNC. It does not
make sense to apply the seccomp filter on only one thread; other threads
will be terminated after exec anyway.
See similar commit in crun:
https://github.com/containers/crun/commit/fefabffa2816ea343068ed036a86944393db189a
Note that SECCOMP_FILTER_FLAG_WAIT_KILLABLE_RECV (introduced by
https://git.kernel.org/pub/scm/linux/kernel/git/kees/linux.git/commit/?id=c2aa2dfef243
in Linux 5.19-rc1) is not added yet because Linux 5.19 is not released
yet.
-----
Tests:
```
$ make localintegration
...
ok 103 runc run [seccomp] (SECCOMP_FILTER_FLAG_*)
```
cc @rata @saschagrunert
> seccomp: add support for flags

- libcontainer/standard_init_linux.go
- libcontainer/system/linux.go
When starting a new container, and the very last step of executing of a
user process fails (last lines of `(*linuxStandardInit).Init)`, it is too
late to print a proper error since both the log pipe and the init pipe
are closed.
This is partially mitigated by using exec.LookPath() which is supposed
to say whether we will be able to execute or not. Alas, it fails to do
so when the binary to be executed resides on a filesystem mounted with
noexec flag.
A workaround is to use access(2) with X_OK flag. Alas, it is not
working when runc itself is a setuid (or setgid) binary. In this case,
faccessat2(2) with AT_EACCESS can be used, but it is only available
since Linux v5.8.
So, use faccessat2(2) with AT_EACCESS if available. If not, fall back to
access(2) for non-setuid runc, and do nothing for …
> Fix error from runc run on noexec fs

- libcontainer/standard_init_linux.go
- libcontainer/system/linux.go
Backport of #3522 to release-1.1 branch. See the original PR for details.
Draft until the original PR is merged.
> [1.1] Fix error from runc run on noexec fs

- .github/workflows/test.yml
When golang 1.19 is used to build unit tests on 386, it fails like this:
```
sudo -E PATH="$PATH" -- make GOARCH=386 CGO_ENABLED=1 localunittest
<...>
go test -timeout 3m -tags "seccomp"  -v ./...
<...>
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): relocation target __stack_chk_fail_local not defined
runtime/cgo(.text): relocation target __stack_chk_fail_local not defined
```
The fix is to add `CGO_CFLAGS=-fno-stack-protector`
See also:
- …
> ci/gha: fix cross-386 job vs go 1.19

- .github/workflows/test.yml
- .github/workflows/validate.yml
- README.md
- go.mod
- go.sum
- libcontainer/cgroups/devices/ebpf_linux.go
- libcontainer/cgroups/utils.go
- libcontainer/configs/validate/validator.go
- libcontainer/specconv/spec_linux.go
- libcontainer/sync.go
- libcontainer/user/user.go
This makes go 1.18 a minimally required version, removing go 1.17 from and adding go 1.19 to CI.
Also:
> Add go 1.19, require go 1.18, drop go 1.17

- .github/workflows/test.yml
Backport of #3556 to release-1.1 branch, to fix a CI job.
----
When golang 1.19 is used to build unit tests on 386, it fails like this:
```
sudo -E PATH="$PATH" -- make GOARCH=386 CGO_ENABLED=1 localunittest
<...>
go test -timeout 3m -tags "seccomp"  -v ./...
<...>
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): relocation target __stack_chk_fail_local not defined
runtime/cgo(.text): relocation target __stack_chk_fail_local not defined
```
The fix is to add …
> [1.1] ci/gha: fix cross-386 job vs go 1.19

- .codespellrc
- tests/integration/cgroup_delegation.bats
Recently released codespell 2.2 adds some more false positives,
such as:
./Makefile:78: ro ==> to, row, rob, rod, roe, rot
./Makefile:88: ro ==> to, row, rob, rod, roe, rot
./notify_socket.go:51: ro ==> to, row, rob, rod, roe, rot
./LICENSE:128: complies ==> compiles
./go.sum:59: BU ==> BY
./types/features/features.go:17: ro ==> to, row, rob, rod, roe, rot
./libcontainer/rootfs_linux.go:52: ro ==> to, row, rob, rod, roe, rot
./libcontainer/rootfs_linux.go:166: ro ==> to, row, rob, rod, roe, rot
...
./tests/integration/cgroup_delegation.bats:38: inh ==> in
...
To fix:
- exclude go.sum;
- add ro and complies to the list of ignored words;
- s/inh/inherit in cgroup_delegation.bats.
> ci: fix for codespell 2.2

- libcontainer/cgroups/devices/systemd.go
- tests/integration/dev.bats
This is a forward port of #3554 to the main branch. Original description follows.
----
A regression reported for runc v1.1.3 says that after systemctl
daemon-reload runc exec fails:
> exec failed: unable to start container process: open /dev/pts/0: operation not permitted: unknown
Apparently, with commit 7219387eb7db69b we are no longer adding
"DeviceAllow=char-pts rwm" rule (because os.Stat("char-pts") returns
ENOENT).
The bug can only be seen after "systemctl daemon-reload" because runc
also applies the same rules manually (by writing to devices.allow for
cgroup v1), and apparently reloading systemd leads to re-applying the
rules that systemd has (thus removing the char-pts access).
The fix is to do os.Stat only for "/dev" paths.
Also, emit a warning that the path was skipped. Since the …
> Fix failed exec after systemctl daemon-reload

- .codespellrc
- tests/integration/cgroup_delegation.bats
Backport of #3561 to release-1.1 branch. Original description follows.
----
Recently released codespell 2.2 adds some more false positives,
such as:
./Makefile:78: ro ==> to, row, rob, rod, roe, rot
./Makefile:88: ro ==> to, row, rob, rod, roe, rot
./notify_socket.go:51: ro ==> to, row, rob, rod, roe, rot
./LICENSE:128: complies ==> compiles
./go.sum:59: BU ==> BY
./types/features/features.go:17: ro ==> to, row, rob, rod, roe, rot
./libcontainer/rootfs_linux.go:52: ro ==> to, row, rob, rod, roe, rot
./libcontainer/rootfs_linux.go:166: ro ==> to, row, rob, rod, roe, rot
....
./tests/integration/cgroup_delegation.bats:38: inh ==> in
...
To fix:
- exclude go.sum;
- add ro and complies to the list of ignored words;
- s/inh/inherit in cgroup_delegation.bats.
Signed-off-by: Kir Kolyshkin …
> [1.1] ci: fix for codespell 2.2

- libcontainer/cgroups/systemd/common.go
- tests/integration/dev.bats
A regression reported for runc v1.1.3 says that after systemctl
daemon-reload runc exec fails:
> exec failed: unable to start container process: open /dev/pts/0: operation not permitted: unknown
Apparently, with commit 7219387eb7db69b we are no longer adding
"DeviceAllow=char-pts rwm" rule (because os.Stat("char-pts") returns
ENOENT).
The bug can only be seen after "systemctl daemon-reload" because runc
also applies the same rules manually (by writing to devices.allow for
cgroup v1), and apparently reloading systemd leads to re-applying the
rules that systemd has (thus removing the char-pts access).
The fix is to do os.Stat only for "/dev" paths.
Also, emit a warning that the path was skipped. Since the original idea
was to emit less warnings, demote the level to debug.
Note this also …
> [1.1] Fix failed exec after systemctl daemon-reload (regression in 1.1.3)

- libcontainer/seccomp/patchbpf/enosys_linux.go
- libcontainer/seccomp/seccomp_linux.go
- tests/integration/seccomp.bats
Commit 58ea21daefea8e3447db added support for seccomp flags such as
SPEC_ALLOW, but it does not work, as since commit 7a8d7162f9d72f20d83ea
we do not use libseccomp-golang's Load(), but handle flags separately in patchbfp.
This fixes setting SPEC_ALLOW flag.
Add a comment to not forget to amend `filterFlags` when adding new flags.
Add a test case that the flags are set as expected (see the second commit for details).
Fixes: https://github.com/opencontainers/runc/issues/3582
> seccomp: do not ignore SPEC_ALLOW flag

- .cirrus.yml
- tests/integration/helpers.bash
Turns out, CentOS 7 image used in Cirrus CI had EPEL repo configured, and now it's not. This, together with a "feature" of older yum NOT returning an error when some of the packages requested are not found, resulted in failures in tests that use `jq` and `fuse-sshfs`.
The fix is to add/enable EPEL repo.
1.1 backport: https://github.com/opencontainers/runc/pull/3618
> Fix centos 7 ci

- .cirrus.yml
This is a followup to https://github.com/opencontainers/runc/pull/3614. Apparently, GCE fixed the centos 7 image issue, which broke our CI for the second time.
Let's install EPEL conditionally, so it will work either way.
> cirrus-ci: install EPEL on CentOS 7 conditionally

- .cirrus.yml
Backport of #3628 to 1.1 branch.
----
This is a followup to #3614 / #3618. Apparently, GCE fixed the centos 7 image issue, which broke our CI for the second time.
Let's install EPEL conditionally, so it will work either way.
> [1.1] cirrus-ci: install EPEL on CentOS 7 conditionally

- libcontainer/cgroups/fs/fs.go
- libcontainer/cgroups/fs2/fs2.go
- libcontainer/cgroups/systemd/devices.go
- libcontainer/cgroups/systemd/freeze_test.go
- libcontainer/cgroups/systemd/v1.go
- libcontainer/cgroups/systemd/v2.go
It's more idiomatic Go to define interfaces on the receiver, and constructors to return concrete types.
This patch changes various constructors to return a concrete type, with the exceptions of NewWithPaths, which needs the abstraction as it switches between implementations.
> libcontainer/cgroups: return concrete types

- libcontainer/cgroups/systemd/cpuset.go
- libcontainer/cgroups/systemd/cpuset_test.go
- tests/integration/helpers.bash
- tests/integration/update.bats
Runc parses cpuset range to bits in the case of cgroup v2 + systemd as cgroup driver. The byte order representation differs from systemd expectation, which will set different cpuset range in systemd transient unit if the length of parsed byte array exceeds one.
...
"resources": {
...
"cpu": {
"cpus": "10-23"
}
},
...
[Scope]
AllowedCPUs=0-7 10-15
The cpuset.cpus in cgroup will also be set to wrong value after reloading systemd manager configuration.
0-7,10-15
This patch simply reverses the byte order at the end of  RangeToBits().
Please help to verify the patch and any comments and suggestions are welcome!
> cgroups: cpuset: fix byte order while parsing cpuset range to bits

- libcontainer/cgroups/systemd/common.go
The original code depended on the origin filesystem to have /dev/{block,char} populated. This is done by udev normally and while is very common non-containerized systemd installs, it's very easy to start systemd in a container created by runc itself and not have /dev/{block,char} populated. When this occurs, the following error output is observed:
$ docker run hello-world
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error reopening /dev/null inside container: open /dev/null: operation not permitted: unknown.
/dev/null can't be opened because it was not added to the deviceAllowList, as there was no /dev/char directory. The change here utilizes the fact that when …
> [1.1] Fixes inability to use /dev/null when inside a container

- tests/integration/seccomp.bats
On ARM, mkdirat(2) is used instead of mkdir(2), thus the seccomp rules needs to be amended accordingly.
This is a change similar to one in commit e119db7a23c773ca9 (PR #3525), but it evaded the test case added in commit 58ea21dae (PR #3390) as it took a long time to merge, and we don't have ARM CI.
Fixes: 58ea21dae ("seccomp: add support for flags")
Reported-by: Ryan Phillips <rphillips@redhat.com>
> tests/int/seccomp: fix flags test on ARM

- .github/workflows/validate.yml
This tag points to the latest v3 version (currently v3.0.11).
Mainly done to avoid cluttering git history with multiple minor v3 upgrades (see e.g. #3634, #3624, #3621, #3566, #3557, #3528, #3505, #3458).
This (using the x.y.z version format) has happened due to #3444; I guess there was no `v3` tag back then.
NB: do not accept dependabot PRs that switch from `vN` to `vX.Y.Z`
> ci/gha: use v3 tag for actions/cache

- libcontainer/seccomp/seccomp_linux.go
This makes libseccomp produce a BPF which uses a binary tree for
syscalls (instead of linear set of if statements).
This should speed up doing syscalls from containers that were created
from OCI spec containing lots of seccomp rules.
> libct/seccomp: enable seccomp binary tree optimization

- .editorconfig
- .github/workflows/validate.yml
- Makefile
1. Bump shfmt to v3.5.1. Release notes:
https://github.com/mvdan/sh/releases
2. Since shfmt v3.5.0, specifying `-l bash` (or `-l bats`) is no longer
necessary. Therefore, we can use shfmt to find all the files.
Add `.editorconfig` to ignore `vendor` subdirectory.
3. Use shfmt docker image, so that we don't have to install anything
explicitly. This greatly simplifies the shfmt CI job. Add
localshfmt target so developers can still use a local shfmt binary
when necessary.
> ci: bump shfmt to 3.5.1, simplify CI setup

- go.mod
- go.sum
- libcontainer/cgroups/fs2/fs2.go
- libcontainer/cgroups/fs2/memory.go
- libcontainer/cgroups/systemd/v2.go
- libcontainer/configs/cgroup_linux.go
- libcontainer/specconv/spec_linux.go
- tests/integration/update.bats
- update.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
- vendor/modules.txt
This is aimed at solving the problem of cgroup v2 memory controller
behavior which is not compatible with that of cgroup v1.
In cgroup v1, if the new memory limit being set is lower than the
current usage, setting the new limit fails.
In cgroup v2, same operation succeeds, and the container is OOM killed.
Introduce a new setting, memory.checkBeforeUpdate, and use it to mimic
cgroup v1 behavior.
Note that this is not 100% reliable because of TOCTOU, but this is the
best we can do.
Fixes: https://github.com/opencontainers/runc/issues/3509
~~Currently a draft, pending https://github.com/opencontainers/runtime-spec/pull/1158 merge.~~
> runc update: implement memory.checkBeforeUpdate

- libcontainer/process_linux.go
Init State Error message was using the err variable instead of uerr, which has been fixed now. The error message should not show "nil" now.
Developer Certificate of Origin
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 660 York Street, Suite 102,
San Francisco, CA 94110 USA
Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source …
> Fixed Init State Error Variable

- checkpoint.go
If checkpointing has failed, the container is kept running. We do not want to, and we can't remove it in such case.
Do not try to remove the container if there's an error from checkpointing.
This avoids an unclear error message from destroy() saying "container still running" or "container paused".
While at it, avoid using defer since it does not make a lot of sense here.
Fixes: #3577
> runc checkpoint: destroy only on success

- notify_socket.go
- notify_socket_test.go
Add synchronization to how runc reports container readiness to systemd.
It was previously possible for runc to terminate  immediately after sending the READY signal. This was sometimes too quick for systemd to find out the sender's cgroup. As a consequence, systemd would ignore the READY signal.
Fixes: #3293
> notify_socket.go: use sd_notify_barrier mechanism

- tests/integration/delete.bats
_TL;DR: this is a forward-port of https://github.com/opencontainers/runc/pull/3538/commits/f46c0dad655e33cf29d38da94b265d982a835f88 (part of #3538) to main branch, fixing a CI flake caused by a GHA CI env peculiarity._
A couple of test cases in delete.bats check that a particular cgroup
exists (or doesn't exist) using find. This is now resulting in errors
like these:
find: ‘/sys/fs/cgroup/blkio/azsec’: Permission denied
find: ‘/sys/fs/cgroup/blkio/azsec_clamav’: Permission denied
find: ‘/sys/fs/cgroup/cpu,cpuacct/azsec’: Permission denied
find: ‘/sys/fs/cgroup/cpu,cpuacct/azsec_clamav’: Permission denied
find: ‘/sys/fs/cgroup/memory/azsec’: Permission denied
find: ‘/sys/fs/cgroup/memory/azsec_clamav’: Permission denied
leading to test case failures.
Apparently, GHA runs something else on …
> ci: fix delete.bats for GHA

- tests/integration/get-images.sh
> tests/integration/get-images.sh: fix busybox.tar.xz URL

- features.go
- libcontainer/seccomp/config.go
- libcontainer/seccomp/patchbpf/enosys_linux.go
- libcontainer/seccomp/seccomp_linux.go
- libcontainer/seccomp/seccomp_unsupported.go
- libcontainer/specconv/spec_linux.go
- tests/integration/seccomp.bats
- types/features/features.go
~~_Currently a draft pending #3580 merge. When reviewing as a draft, please skip the first 2 commits (they are from #3580)._~~
This PR reworks seccomp flags support:
- adds new functions `KnownFlags()`, `SupportedFlags()` and `FlagSupported()` to seccomp pkg;
- adds showing of known and supported seccomp filter flags to `runc features`;
- consolidates/deduplicates code that handles flags (as much as possible);
- changes the default (when no flags are set) to have `SPEC_ALLOW`, if supported (crun does that).
~~TODO: fix the seccomp flags test to use runc features and not depend on kernel version (maybe in a separate PR).~~
> seccomp: refactor flags support; add flags to features, set SPEC_ALLOW by default

- checkpoint.go
- libcontainer/container_linux.go
- man/runc-checkpoint.8.md
- man/runc-restore.8.md
- restore.go
- tests/integration/checkpoint.bats
- tests/integration/helpers.bash
This patchset fixes a few issues and adds support for `--manage-cgroups-mode ignore`. This option allows to restore a container into a different cgroup than the original one. A test case is added to check that it works as expected.
Loosely based on https://github.com/opencontainers/runc/pull/3447 and my earlier work from 2021.
Closes: https://github.com/opencontainers/runc/pull/3447
Also, this uses the new mode in lazy checkpoint/restore test, hopefully fixing this test flakiness.
Fixes: https://github.com/opencontainers/runc/issues/2760
Fixes: https://github.com/opencontainers/runc/issues/2924
Fixes: https://github.com/opencontainers/runc/issues/2475
PS I am thinking whether this (`--manage-cgroups-mode ignore` should become a default in 1.2.0, because …
> checkpoint/restore: implement --manage-cgroups-mode ignore

- libcontainer/nsenter/nsexec.c
First, check if strdup() fails and error out.
While we are there, the else case was missing brackets, as we only need to check ret in the else case. Fix that too
Signed-off-by: Rodrigo Campos <rodrigoca@microsoft.com>
> nsexec: Check for errors in write_log()

- contrib/completions/bash/runc
- libcontainer/cgroups/fs/cpu.go
- libcontainer/cgroups/fs2/cpu.go
- libcontainer/configs/cgroup_linux.go
- libcontainer/specconv/spec_linux.go
- tests/integration/cgroups.bats
- tests/integration/helpers.bash
- tests/integration/update.bats
- update.go
runtime-spec: https://github.com/opencontainers/runtime-spec/pull/1136
> libct/cg: support SCHED_IDLE for runc cgroupfs

- libcontainer/cgroups/systemd/common.go
- libcontainer/cgroups/systemd/systemd_test.go
- libcontainer/factory_linux.go
Don't get me wrong, I love regular expressions. But the regexp package is somewhat big and slow, and we can do just fine without.
Remove two last uses of regexp in runc code (modulo tests).
**This saves about 200K (2.3%) from the resulting binary, without losing any of the functionality.**
~~Currently a draft pending~~
> Do not use regexp

- .clang-format
For the sake of developers who have LSP configured to auto-format the code upon save (that would me with my new nvim setup), let's not auto-format the C code when using clangd.
Initially I tried to write a set of rules for clang-format which is identical to what we use (indent with a handful of options invoked from cfmt target in Makefile), but it appears to be impossible.
> Disable clang-format

- libcontainer/init_linux.go
- tests/integration/exec.bats
In #3355 the check whether the STDIO file descriptors point to /dev/null was removed which can cause /dev/null to change ownership e.g. when using docker exec on a running container:
$ ls -l /dev/null
crw-rw-rw- 1 root root 1, 3 Aug 1 14:12 /dev/null
$ docker exec -u test 0ad6d3064e9d ls
$ ls -l /dev/null
crw-rw-rw- 1 test root 1, 3 Aug 1 14:12 /dev/null
This PR reintroduces that check and fixes the issue for me on runc v1.1.{3,4} (I did not find any information about this change being intentional, if it was feel free to close this PR).
Fixes: #3674
> libcontainer: skip chown of /dev/null caused by fd redirection

- Dockerfile
After #3718 merge, updated git in golang:1.19-bullseye image results in failure to build a release:
make -C /go/src/github.com/opencontainers/runc PKG_CONFIG_PATH=/opt/libseccomp/lib/pkgconfig COMMIT_NO= EXTRA_FLAGS=-a 'EXTRA_LDFLAGS=-w -s -buildid=' static
make[1]: Entering directory '/go/src/github.com/opencontainers/runc'
fatal: detected dubious ownership in repository at '/go/src/github.com/opencontainers/runc'
To add an exception for this directory, call:
git config --global --add safe.directory /go/src/github.com/opencontainers/runc
go build -trimpath -buildmode=pie -a -tags "seccomp urfave_cli_no_docs netgo osusergo" -ldflags "-X main.gitCommit= -X main.version=1.1.0+dev -linkmode external -extldflags --static-pie -w -s -buildid=" -o runc .
error obtaining VCS status: exit status …
> Dockerfile: fix build wrt new git

- libcontainer/init_linux.go
- tests/integration/exec.bats
This is a backport of https://github.com/opencontainers/runc/pull/3707 to release-1.1 branch, fixing #3674.
Clean cherry-pick, no issues.
> [1.1] libcontainer: skip chown of /dev/null caused by fd redirection

- libcontainer/nsenter/nsexec.c
This is a backport of #3712 for release 1.1 branch.
---
First, check if strdup() fails and error out.
While we are there, the else case was missing brackets, as we only need to check ret in the else case. Fix that too
Signed-off-by: Rodrigo Campos <rodrigoca@microsoft.com>
(cherry picked from commit 5ce511d6a65809be3fc58f8e2df585abb9c616d6)
> [1.1] nsexec: Check for errors in write_log()

- libcontainer/cgroups/devices/systemd_test.go
centos-9 unit test sometimes fails with:
```    
=== RUN   TestPodSkipDevicesUpdate
systemd_test.go:114: container stderr not empty: basename: missing operand
Try 'basename --help' for more information.
--- FAIL: TestPodSkipDevicesUpdate (0.11s)
```
I'm not sure why the container output is an error in basename. It seems
likely that the bashrc in that distro is kind of broken. Let's just run
a sleep command and forget about bash.
Fixes: #3742 
Signed-off-by: Rodrigo Campos <rodrigoca@microsoft.com>
> tests: Fix weird error on centos-9

- Makefile
clang is pretty strict while gcc ignores this error:
```
#34 0.279 go build -trimpath -buildmode=pie  -tags "seccomp urfave_cli_no_docs netgo osusergo" -ldflags "-X main.gitCommit=v1.1.0-402-gb199fb2e -X main.version=1.1.0+dev -linkmode external -extldflags --static-pie " -o runc .
#34 5.352 # github.com/opencontainers/runc
#34 5.352 /usr/local/go/pkg/tool/linux_amd64/link: running x86_64-linux-gnu-clang failed: exit status 1
#34 5.352 clang: error: unsupported option '--static-pie'; did you mean '-static-pie'?
#34 5.352
#34 5.384 make: *** [Makefile:69: static] Error 2
```
> Makefile: fix typo in LDFLAGS_STATIC

- README.md
- docs/spec-conformance.md
- go.mod
- go.sum
- vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
- vendor/modules.txt
runc now implements the [OCI Runtime Spec v1.1.0-rc.1](https://github.com/opencontainers/runtime-spec/tree/v1.1.0-rc.1) for the `linux` platform.
The following features are not implemented yet:
Spec version | Feature                                  | PR
-------------|------------------------------------------|----------------------------------------------------------
v1.0.0       | `SCMP_ARCH_PARISC`                       | Unplanned, due to lack of users
v1.0.0       | `SCMP_ARCH_PARISC64`                     | Unplanned, due to lack of users
v1.0.2       | `.linux.personality`                     | [#3126](https://github.com/opencontainers/runc/pull/3126)
v1.1.0-rc.1  | `.linux.resources.cpu.burst`             | [#3205](https://github.com/opencontainers/runc/pull/3205)
v1.1.0-rc.1  | …
> go:mod: runtime-spec v1.1.0-rc.1; add docs/spec-conformance.md

- libcontainer/nsenter/nsexec.c
I was adding it to new code I was writing, and for completeness I added to this case too.
Signed-off-by: Rodrigo Campos <rodrigoca@microsoft.com>
> nsexec: Add debug logs to send mount sources

- spec.go
Fixes [#3727](https://github.com/opencontainers/runc/issues/3727#issue-1573797885)
> Fix runc crushes when parsing invalid JSON specification file

- libcontainer/setns_init_linux.go
- tests/integration/umask.bats
Signed-off-by: Wang-squirrel <wang.xiaosong1@zte.com.cn>
> Add support for umask when exec container

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/config.yml
- SECURITY.md
After merging this PR, the "Report a security vulnerability" button will appear in "New issue" screen.
Demo: https://github.com/containerd/nerdctl/issues
(nerdctl's button is linked to GitHub Advisory, but I think the button will be just linked to https://github.com/opencontainers/runc/blob/main/SECURITY.md for runc, unless we enable GitHub Advisory for runc)
> Add `.github/ISSUE_TEMPLATE/config.yml`

- .github/ISSUE_TEMPLATE/config.yml
`contact_links` without `about` properties are not shown in https://github.com/opencontainers/runc/issues/new/choose
> .github/ISSUE_TEMPLATE/config.yml: fix contact links

- libcontainer/nsenter/nsexec.c
Older kernels may return EINVAL on unshare when a process is reading runc's /proc/$PID/status or /proc/$PID/maps. This was fixed by kernel commit 12c641ab8270f ("unshare: Unsharing a thread does not require unsharing a vm") in Linux v4.3.
For CentOS 7, the fix was backported to CentOS 7.7 (kernel 3.10.0-1062).
To work around this kernel bug, let's retry on EINVAL a few times.
Not adding a test case as the fix is short and obvious, and the repro is somewhat complicated (see #3705).
Closes: #3705
> nsexec: retry unshare on EINVAL

- libcontainer/specconv/spec_linux.go
From https://github.com/torvalds/linux/commit/caaef1ba8c9ee7a54b53dd8bf4bb7e8658185583 :
> In fact SB_POSIXACL is an internal flag, and accepting MS_POSIXACL on
> the mount(2) interface is possibly a bug.
Fix #3738
> specconv: avoid mapping "acl" to MS_POSIXACL

- libcontainer/rootfs_linux.go
- tests/integration/mask.bats
Commit 3291d66b9844 introduced a check for /proc and /sys, making sure the destination (dest) is a directory (and not e.g. a symlink).
Later, a hunk from commit 0ca91f44f switched from using `filepath.Join` to `SecureJoin` for `dest`. As `SecureJoin` follows and resolves symlinks, the check whether dest is a symlink no longer works.
To fix, do the check without/before using SecureJoin.
Add integration tests (stolen from #3756) to make sure we won't regress.
_This is an alternative to #3756._
Fixes: #3751
Fixes: CVE-2023-27561
> Prohibit /proc and /sys to be symlinks

- libcontainer/utils/cmsg.go
fix wrong notes for ```const MaxNameLen```
> fix wrong notes for `const MaxNameLen`

- libcontainer/rootfs_linux.go
- tests/integration/mask.bats
- backport of https://github.com/opencontainers/runc/pull/3773
- fixes https://github.com/opencontainers/runc/issues/3751
- fixes CVE-2023-27561
Commit 3291d66b9844 introduced a check for /proc and /sys, making sure the destination (dest) is a directory (and not e.g. a symlink).
Later, a hunk from commit 0ca91f44f switched from using filepath.Join to SecureJoin for dest. As SecureJoin follows and resolves symlinks, the check whether dest is a symlink no longer works.
To fix, do the check without/before using SecureJoin.
Add integration tests to make sure we won't regress.
(cherry picked from commit 0d72adf96dda1b687815bf89bb245b937a2f603c)
> [1.1 backport] Prohibit /proc and /sys to be symlinks

- libcontainer/nsenter/nsexec.c
This is a backport of #3772 to the release-1.1 branch. Original description follows.
----
Older kernels may return EINVAL on unshare when a process is reading runc's /proc/$PID/status or /proc/$PID/maps. This was fixed by kernel commit 12c641ab8270f ("unshare: Unsharing a thread does not require unsharing a vm") in Linux  v4.3.
For CentOS 7, the fix was backported to CentOS 7.7 (kernel 3.10.0-1062).
To work around this kernel bug, let's retry on EINVAL a few times.
Reported-by: zzyyzte <zhang.yu58@zte.com.cn>
(cherry picked from commit cecb039d24d9cef17cc37df9d7cd338b83436138)
> [1.1] nsexec: retry unshare on EINVAL

- libcontainer/cgroups/devices/systemd_test.go
There is some kind of a race in CentOS 7 which sometimes result in one of these tests failing like this:
systemd_test.go:136: mkdir /sys/fs/cgroup/hugetlb/system.slice/system-runc_test_pods.slice: no such file or directory
or
systemd_test.go:187: open /sys/fs/cgroup/cpuset/system.slice/system-runc_test_pods.slice/cpuset.mems: no such file or directory
As this is only happening on CentOS 7, let's skip this test on this platform.
Fixes: #3743
> libct/cg/dev: skip flaky test of CentOS 7

- libcontainer/rootfs_linux.go
The setRecAttr is only called for "bind" case, as cases end with a return statement. Indeed, recursive mount attributes only make sense for bind mounts.
Move the code to under case "bind" to improve readability. No change in logic.
Fixes: 382eba4354d764aaff
Reported-by: Sebastiaan van Stijn <github@gone.nl>
> mountToRootfs: minor refactor

- tests/integration/mounts.bats
This is a backport of #3798 to release-1.1 branch, to fix the issues with the recently added test case, and thus fix some of the CI failures. See the original PR for details.
_Draft until #3798 is merged_
> [1.1] fix mount test

- CHANGELOG.md
- Makefile
1. Fix wrong old version in a github compare link.
2. Fix a typo in changelog (found by our CI codespell)
3. Moved 1.1.5 CVEs to a separate "Security" section (by @cyphar, see https://github.com/opencontainers/runc/pull/3796#issuecomment-1489656062)
1. Removed the changelog check for non-ASCII characters, as it was failing the `release` job:
```console
Run make verify-changelog
>! LC_ALL=C grep -n -P '[\x80-\xFF]' CHANGELOG.md
11:> 囚われた屈辱は
12:> 反撃の嚆矢だ
make: *** [Makefile:150: verify-changelog] Error 1
```
1. Added `verify-changelog` to `localrelease` target, as one more way to catch those errors early.
PS need to forward-port these changes as well as 1.1.4 and 1.1.5 changelogs to main branch.
> [1.1] CHANGELOG: fixes for 1.1.5

- CHANGELOG.md
- Makefile
This is a forward port of changes in the following release-1.1 PRs:
* #3564
* commit f19387a
* #3796
Mostly this adds 1.1.4 and 1.1.5 changes to the CHANGELOG.md in main branch.
> CHANGELOG: forward-port 1.1.4 and 1.1.5 changes 

- libcontainer/cgroups/systemd/common.go
- libcontainer/cgroups/systemd/v1.go
- libcontainer/cgroups/systemd/v2.go
- libcontainer/factory_linux.go
- tests/integration/cgroups.bats
This fixes the wrong logic of systemd cgroup manager's Apply method. For more details, see commit messages and #3780.
Fixes: #3780
Fixes: #3760
> Fix systemd cgroup driver's Apply

- docs/systemd.md
- libcontainer/cgroups/systemd/systemd_test.go
- libcontainer/cgroups/systemd/v2.go
- tests/integration/update.bats
Systemd v252 added support for setting cgroup v2 cpu.idle in https://github.com/systemd/systemd/pull/23299
The way it works is
- if CPUWeight == 0, cpu.idle is set to 1;
- if CPUWeight != 0, cpu.idle is set to 0.
This PR implements support for setting `cpu.idle` via systemd cgroup
v2 driver. In case CPUIdle is set to non-zero value, the driver sets
CPUWeight=0 property, which will result in systemd setting cpu.idle
to 1.
Unfortunately, there's no way to set cpu.idle to 0 without also changing
the CPUWeight value, so the driver doesn't do anything if CPUIdle is
explicitly set to 0. This case is handled by the fs driver which is
always used as a followup to setting systemd unit properties.
Also, handle cpu.idle set via unified map. In case it is set to non-zero
value, add CPUWeight=0 …
> cg/sd: support CPUWeight=idle (aka cpu.idle=1)

- tests/fuzzing/oss_fuzz_build.sh
As tests/fuzzing/oss_fuzz_build.sh is still in the list of oss-fuzz building scripts, fix the inaccurate location of fuzzer FuzzUIDMap.
P.S. If possible, I am willing to help synchronize with the harness from cncf-fuzzing and augment the fuzzing drivers for more.
> tests: Fix fuzzer location in oss-fuzz config

- libcontainer/cgroups/fs/paths.go
- libcontainer/cgroups/v1_utils.go
This is a followup to PR #3784.
These functions were added in ancient times, facilitating the docker-in-docker case when cgroup namespace was not available.
As pointed out in commit 2b28b3c2769 (PR #194), using init 1 cgroup is not correct because it won't work in case of host PID namespace.
The last user of GetInitCgroup was removed by commit 54e20217a86f117037e3f5 (PR #3784). GetInitCgroupPath was never used as far as I can see, nor was I able to find any external users.
Remove both functions. Modify the comment in libct/cg/fs.subsysPath to not refer to GetInitCgroupPath.
> libct/cg: rm GetInitCgroup[Path]

- libcontainer/cgroups/systemd/common.go
- libcontainer/cgroups/systemd/v1.go
- libcontainer/cgroups/systemd/v2.go
- libcontainer/factory_linux.go
- tests/integration/cgroups.bats
This is a backport of #3782 for 1.1 branch. The difference is, here we still allow a container to share a cgroup with another container, but only when systemd cgroup driver is NOT used.
In case of systemd cgroup driver, which can't add a PID into an existing cgroup, we error out early.
The reasons behind this approach is described in https://github.com/opencontainers/runc/pull/3782#discussion_r1151309112
Fixes: #3780
> [1.1] Fix systemd cgroup driver's Apply (and make CI green again)

- libcontainer/cgroups/systemd/common.go
- libcontainer/cgroups/systemd/systemd_test.go
- libcontainer/cgroups/systemd/v1.go
- libcontainer/cgroups/systemd/v2.go
- libcontainer/factory_linux.go
- tests/integration/cgroups.bats
There is some kind of a race in CentOS 7 which sometimes result in one of these tests failing like this:
systemd_test.go:136: mkdir /sys/fs/cgroup/hugetlb/system.slice/system-runc_test_pods.slice: no such file or directory
or
systemd_test.go:187: open /sys/fs/cgroup/cpuset/system.slice/system-runc_test_pods.slice/cpuset.mems: no such file or directory
As this is only happening on CentOS 7, let's skip this test on this platform.
Fixes: #3743
[This is a manual cherry-pick of main commit a7a836effa691edb6e / PR #3778.]
> [1.1] libct/cg/dev: skip flaky test of CentOS 7

- .cirrus.yml
This variable is used in curl to download a go release, so we are using the initial Go 1.19 release in Cirrus CI, not the latest Go 1.19.x release.
From the CI perspective, it makes more sense to use the latest release, so let's use 1.19.x here.
Add some ~~shell~~ `jq` magic to extract the latest minor release information
from the download page, and use it.
This brings Cirrus CI jobs logic in line with all the others (GHA,
Dockerfile), where by 1.20 we actually mean "latest 1.20.x".
Previous commits touching this:
* 5ecd40b9b 1.19
* 5211cc3f7 1.18 <-- I blame the author of this one 😄 
* 12a36265c 1.17.3
* 9f656dbb1 1.16.6
> ci/cirrus: use Go 1.19.x not 1.19

- libcontainer/cgroups/systemd/cpuset.go
- libcontainer/cgroups/systemd/cpuset_test.go
- tests/integration/helpers.bash
- tests/integration/update.bats
Better late than never, this is a backport of #3611 to release-1.1 branch. See the original PR for details.
> [1.1] cgroups: cpuset: fix byte order while parsing cpuset range to bits

- libcontainer/eaccess_go119.go
- libcontainer/eaccess_stub.go
- libcontainer/standard_init_linux.go
- libcontainer/system/linux.go
- tests/integration/start_hello.bats
This is a backport of #3753 to release-1.1 branch. Original description follows.
---
Fixes: #3715
Since PR #3522 (commit 957d97bcf43f41beef96) was made to fix issue #3520,
a few things happened:
- a similar functionality appeared in go 1.20 [1], so the issue
mentioned in the comment (being removed) is no longer true;
- a bug in runc was found [2], which also affects go [3];
- the bug was fixed in go 1.21 [4] and 1.20.2 [5];
- a similar fix was made to x/sys/unix.Faccessat [6].
The essense of the bug #3715 is, even if a (non-root) user that the container is
run as does not have execute permission bit set for the executable, it
should still work in case runc has the CAP_DAC_OVERRIDE capability set.
To fix #3715 without reintroducing the older bug [7]:
- drop own Eaccess implementation;
- …
> [1.1] Fix runc run "permission denied" when rootless

- libcontainer/cgroups/systemd/v1.go
Sometimes, the init process is not in the root cgroup. This can be noted by GetInitPath, which already scrubs the path of `init.scope`.
This was encountered when trying to patch the Kubelet to handle systemd being in a separate cpuset from root (to allow load balance disabling for containers). At present, there's no way to have libcontainer or runc manage cgroups in a hierarchy outside of the one init is in (unless the path contains `init.scope`, which is limiting)
> [1.1] libctr/cgroups: don't take init's cgroup into account

- libcontainer/cgroups/fs/fs.go
- libcontainer/cgroups/systemd/v1.go
This is just so that
- the container can join the misc controller;
- the `Destroy() can actually remove the cgroup.
This should fix the issue reported in https://github.com/kubernetes/kubernetes/issues/112124#issuecomment-1500659886
(cherry picked from commit 611bbacb3bbed377f8427ea398c800de526481f3 / PR #3815.
Proposed changelog entry:
```
- Bare minimal support for cgroup v1 misc controller. (#3823)
```
> [1.1] libct/cg: add misc controller to v1 drivers

- libcontainer/configs/config.go
- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
- libcontainer/integration/template_test.go
- libcontainer/specconv/spec_linux.go
- libcontainer/standard_init_linux.go
- tests/integration/run.bats
https://github.com/opencontainers/runtime-spec/pull/1156
> Implement to set a domainname

- man/runc-kill.8.md
Document the aspects of --all.
Reference: https://github.com/opencontainers/runc/pull/3812#issuecomment-1513680512
> runc-kill(8): amend the --all description

- libcontainer/container_linux.go
For the previous attempt to fix that (and added test cases), see commit 9087f2e827d971 (PR #2338).
Alas, it's not always working because of cgroup directory TOCTOU.
To solve this and avoid the race, add an error _after_ the operation. Implement it as a method that ignores the error that should be ignored. Instead of currentStatus(), use faster runType(), since we are not interested in Paused status here.
For Processes(), remove the pre-op check, and only use it after getting an error, making the non-error path more straightforward.
For Signal(), add a second check after getting an error. The first check is left as is because signalAllProcesses might print a warning if the cgroup does not exist, and we'd like to avoid that.
This should fix an occasional failure like this one:
not ok 84 …
> libct: fix a race with systemd removal

- libcontainer/cgroups/devices/systemd.go
- libcontainer/cgroups/systemd/common.go
- libcontainer/cgroups/systemd/v1.go
- libcontainer/cgroups/systemd/v2.go
This is a continuation of a saga that started in PR #3498 and continued in PR #3623.
Commit 343951a22b58c38feb added a call to os.Stat for the device path when generating systemd device properties, to avoid systemd warning for non-existing devices. The idea was, since systemd uses stat(2) to look up device properties for a given path, it will fail anyway. In addition, this allowed to suppress a warning like this from systemd:
> Couldn't stat device /dev/char/10:200
NOTE that this was done because:
- systemd could not add the rule anyway;
- runs puts its own set of rules on top of what systemd does.
Apparently, the above change broke some setups, resulting in inability to use e.g. /dev/null inside a container. My guess is this is because in cgroup v2 we add a second eBPF program, which is …
> libct/cg/sd: use systemd version when generating device properties

- libcontainer/cgroups/systemd/common.go
- libcontainer/cgroups/systemd/v1.go
- libcontainer/cgroups/systemd/v2.go
_This is a backport of #3842 to release-1.1 branch._
_Essentially, it reverts PR #3620 (which made its way into 1.1.5), and makes a check added by PR #3504 conditional, depending on systemd version used._
_Due to cgroup devices refactoring in main branch, this is a manual cherry-pick._
Fixes: #3671
Fixes: #3708
Also fixes the issue of printing an extra warnings (which breaks some k8s tests).
_Original description follows._
----
Commit 343951a22b58c38feb added a call to os.Stat for the device path when generating systemd device properties, to avoid systemd warning for non-existing devices. The idea was, since systemd uses stat(2) to look up device properties for a given path, it will fail anyway. In addition, this allowed to suppress a warning like this from systemd:
> Couldn't stat device …
> [1.1] libct/cg/sd: use systemd version when generating dev props

- libcontainer/cgroups/devices/systemd.go
- libcontainer/cgroups/devices/systemd_test.go
~~_This includes/depends on #3356, draft until merged._~~
1. Using strings.TrimPrefix instead of fmt.Sscanf.
2. Add a test case and a benchmark.
The benchmark shows some improvement, compared to the old
implementation:
```
name               old time/op    new time/op    delta
FindDeviceGroup-4    39.7µs ± 2%    26.8µs ± 2%  -32.63%  (p=0.008 n=5+5)
name               old alloc/op   new alloc/op   delta
FindDeviceGroup-4    6.08kB ± 0%    4.23kB ± 0%  -30.39%  (p=0.008 n=5+5)
name               old allocs/op  new allocs/op  delta
FindDeviceGroup-4       117 ± 0%         6 ± 0%  -94.87%  (p=0.008 n=5+5)
```
> libct/cg/sd: optimize and test findDeviceGroup

- libcontainer/init_linux.go
When given an environment variable that is invalid, it's not a good idea to output the contents in case they are supposed to be private (though such a container wouldn't start anyway so it seems unlikely there's a real way to use this to exfiltrate environment variables you didn't already know).
Reported-by: Carl Henrik Lunde <chlunde@ifi.uio.no>
/cc @chlunde
> init: do not print environment variable value

- libcontainer/console_linux.go
- libcontainer/container_linux.go
- libcontainer/mount_linux.go
- libcontainer/rootfs_linux.go
This is a followup to #3510, doing some refactoring of the code introduced by #2576.
This does the following:
1. Simplify `mount` call by removing the procfd argument, and use the new
simplified mount where procfd is not used. Now, the mount arguments are
the same as those of `unix.Mount`.
2. Introduce a new `mountWithFD` function, which is similar to the old
mount(), except it can take procfd for both source and target.
The new arguments are called `srcFD` and `dstFD`.
3. Modify the mount error to show both `srcFD` and `dstFD` so it's clear
which one is used for which purpose. This fixes the issue of having
a somewhat cryptic errors like this:
> mount /proc/self/fd/11:/sys/fs/cgroup/systemd (via /proc/self/fd/12), flags: 0x20502f: operation not permitted
(in which fd 11 is actually the …
> Refactor mountFd code

- .github/workflows/test.yml
1. Fix cross-i386 job failure due to issues with Ubuntu repo (see e.g. https://github.com/pwndbg/pwndbg/issues/1714)
2. Remove old kludges that are no longer needed.
> ci/gha: cross-i386: fix build, rm kludges

- .github/workflows/validate.yml
Since commit e3cf217cf1fa9248d153 (#3771) actions/setup-go@v4 uses caching implicitly.
Fix two cases of double caching.
> ci/gha: disable double caching

- libcontainer/factory_linux.go
- libcontainer/init_linux.go
- libcontainer/integration/execin_test.go
- libcontainer/integration/init_test.go
This is a preparation for #3385, separated out for easier review.
This is all cosmetical -- code move and removal, variables renaming, all that jazz.
> Some init code refactoring

- libcontainer/init_linux.go
_This is a backport of #3850 to release-1.1 branch. Original description follows._
When given an environment variable that is invalid, it's not a good idea to output the contents in case they are supposed to be private (though such a container wouldn't start anyway so it seems unlikely there's a real way to use this to exfiltrate environment variables you didn't already know).
Reported-by: Carl Henrik Lunde <chlunde@ifi.uio.no>
(cherry picked from commit 20e38fb2b1201325e7cd275afbb5c7d17ccfde60)
> [1.1] init: do not print environment variable value

- libcontainer/container_linux.go
_This is a backport of #3812 to release-1.1 branch. Original description follows._
----
For a previous attempt to fix that (and added test cases), see commit 9087f2e827d971.
Alas, it's not always working because of cgroup directory TOCTOU.
To solve this and avoid the race, add an error _after_ the operation. Implement it as a method that ignores the error that should be ignored. Instead of currentStatus(), use faster runType(), since we are not interested in Paused status here.
For Processes(), remove the pre-op check, and only use it after getting an error, making the non-error path more straightforward.
For Signal(), add a second check after getting an error. The first check is left as is because signalAllProcesses might print a warning if the cgroup does not exist, and we'd like to …
> [1.1] libct: fix a race with systemd removal

- .cirrus.yml
As of today, vagrant stopped working, my best guess is due to bad caching. Here's an excerpt from logs (https://cirrus-ci.com/task/6211443486359552?logs=vagrant#L59):
<blockquote>
...
vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes... Building native extensions. This could take a while... Installed the plugin 'vagrant-libvirt (0.12.1)'!
...
uname -s ; cat Vagrantfile.$DISTRO
Linux
...
Downloaded 481Mb in 4.096201s.
Cache hit for vagrant-8be35383dc00f23d080ff00b2a724c938d650254861f26b67624c28e3fe5e6ae! ...
Vagrant failed to initialize at a very early stage: The plugins failed to initialize correctly. This may be due to manual modifications made within the Vagrant home directory. ...
Error message given during initialization: …
> Fix Vagrant caching

- man/runc.8.md
1. Fix some missing punctuation, use proper case.
2. Remove "runc init" (previously removed from "runc --help" by commit 7a0302f0d79e32766).
> man/runc: fixes

- tests/integration/events.bats
This test is occasionally failing on CS9.
The test case always takes about 7 seconds on my laptop (decreasing
memory, using a different memory eater in shell etc. doesn't help).
Increase the number of iterations from 10 to 30 to make sure we don't
see any flakes.
Fixes: #3868
> tests/int: increase num retries for oom tests

- .cirrus.yml
- tests/integration/cgroups.bats
- tests/integration/delete.bats
- tests/integration/helpers.bash
We were not running localrootlessintegration test on CentOS Stream 9
because of some failures.
Fix those, and enable rootless integration with both systemd and fs drivers.
Amends: #3427
> ci/cirrus: enable some rootless tests on cs9

- tests/integration/events.bats
This is a backport of #3874 to release-1.1 branch, in an attempt to fix a flaky test.
> [1.1] tests/int: increase num retries for oom tests

- docs/systemd.md
Apparently, developer.gnome.org/documentation no longer hosts the documentation we used to refer to. Link to docs.gtk.org instead.
> docs/systemd: fix a broken link

- .github/workflows/validate.yml
- MAINTAINERS_GUIDE.md
- NOTICE
- contrib/completions/bash/runc
- libcontainer/SPEC.md
- libcontainer/nsenter/README.md
This adds a new CI check that there's no extra whitespace at EOL, and fixes all existing cases (not much).
Mostly doing it because my $EDITOR is configured to remove extra whitespace at EOL for most file types, and I don't want to introduce extra hunks when working on the docs.
The failed run looks like this:
```
MAINTAINERS_GUIDE.md:53:* Step 3: Accept (`LGTM`) or refuse a pull request. The relevant maintainers do 
NOTICE:11:United States and other governments.  
....
libcontainer/nsenter/README.md:12:So every time we  import package `nsenter`, the C code function `nsexec()` would be 
^^^ extra whitespace at EOL, please fix
```
> ci/gha: add space-at-eol check, fix existing issues

- .codespellrc
Remove some old exceptions (no longer needed), add a new one
(codespell 2.2.5 flags "(mis)features" in docs/terminal.md).
This fixes the CI
> .codespellrc: update for 2.2.5

- libcontainer/cgroups/systemd/v1.go
In code we have frozen the cgroup to avoid the processes get
an occasional "permission denied" error, while the systemd's application of device
rules is done disruptively. When the processes in the container can not
be frozen over 2 seconds (which defined in fs/freezer.go),
we still update the cgroup which resulting the container get an occasional
"permission denied" error in some cases.
This PR make sure to return error directly without updating cgroup, when freeze fails.
Fixes: #3803
> libct/cg/sd/v1: do not update non-frozen cgroup after frozen failed.

- libcontainer/process.go
This field used to hold a string representation of log level (like "debug" or "info"). Since commit 6c4a3b13d132aa4 this is now a string holding a numeric representation of log level (e.g. "4"). This was done in preparation to commit f1b703fc45dd6142, and simplifies things in a few places.
Let's document it.
Fixes: 6c4a3b13d132aa4
Reference: https://github.com/opencontainers/runc/pull/3385#discussion_r1175151837
> libct: document process.LogLevel field

- .codespellrc
Backport of #3907 to release-1.1 branch.
----
Remove some old exceptions (no longer needed), add a new one (codespell 2.2.5 flags "(mis)features" in docs/terminal.md).
> [1.1] .codespellrc: update for 2.2.5

- man/runc.8.md
This is a backport of #3887 to release-1.1 branch.
----
1. Fix some missing punctuation, use proper case.
2. Remove "runc init" (previously removed from "runc --help" by commit 7a0302f0d79e32766).
(cherry picked from commit 511c76143bba15712d4b5159aeef2f4903005809)
> [1.1] man/runc: fixes

- .github/workflows/test.yml
We used to skip testing rootless integration tests for systemd, because in case of cgroup v1 it does not support user delegation.
Since we added ubuntu 22.04 to the testing matrix, we can actually test rootless+systemd there.
Fixes: 953e1cc48547942481ff71f58fff7bb9cb76e5d2 (PR #3820)
> ci/gha: don't skip rootless+systemd on ubuntu 22.04

- libcontainer/cgroups/utils.go
Replace a panic with a warning, unless it's ENOENT and we're running in a user namespace. In the latter case, do the same as before, i.e. report the error but using a Debug logging level.
This prevents software that uses libcontainer from panicking in some exotic setups.
This will also print a warning on some very old systems which does not use /sys/fs/cgroup for cgroup mount point. My bet is such systems no longer exist.
Closes: #3745
> libct/cg: IsCgroup2UnifiedMode: don't panic

- libcontainer/rootfs_linux.go
- tests/integration/run.bats
When a directory already exists (or after a container is restarted) the perms of the directory being mounted to were being used even when a different permission is set on the tmpfs mount options.
This prepends the original directory perms to the mount options. If the perms were already set in the mount opts then those perms will win.
This eliminates the need to perform a chmod after mount entirely.
Fixes #3911
> Fix tmpfs mode opts when dir already exists

- libcontainer/rootfs_linux.go
- tests/integration/run.bats
_This is a backport of https://github.com/opencontainers/runc/pull/3912 to the release-1.1 branch. Original description follows._
---
When a directory already exists (or after a container is restarted) the perms of the directory being mounted to were being used even when a different permission is set on the tmpfs mount options.
This prepends the original directory perms to the mount options. If the perms were already set in the mount opts then those perms will win.
This eliminates the need to perform a chmod after mount entirely.
Fixes https://github.com/opencontainers/runc/issues/3911
> [1.1] Fix tmpfs mode opts when dir already exists

- .github/workflows/test.yml
- Dockerfile
- Makefile
- libcontainer/seccomp/config.go
- libcontainer/seccomp/patchbpf/enosys_linux.go
- script/lib.sh
This is necessary for [running on RISC-V using K3s](https://github.com/k3s-io/k3s/pull/7778).
Many projects - including K3s - depend on runc 1.1.x, so waiting for a 2.0.x release and then porting to any changes introduced may probably be a much larger effort. This includes all changes done in #3446, which are really minimal but necessary to support the new architecture.
With this patch I have successfully compiled and run K3s on a RISC-V QEMU VM and have verified that I can create Pods.
> Backport riscv64 support into 1.1.x

- docs/systemd.md
A backport of #3899 to release-1.1 branch.
----
Apparently, developer.gnome.org/documentation no longer hosts the documentation we used to refer to. Link to docs.gtk.org instead.
(cherry picked from commit 73b5dc027dc33959a3c48807ca70d9be6a64125c)
> [1.1] docs/systemd: fix a broken link

- .cirrus.yml
- tests/integration/cgroups.bats
This is a backport of #3553 to release-1.1 branch. Original description follows.
----
We were not running localrootlessintegration test on CentOS Stream 9
because of some failures.
Fix those, and enable rootless integration with both systemd and fs drivers.
Amends: #3427
> [1.1] ci/cirrus: enable some rootless tests on cs9

- libcontainer/cgroups/systemd/common.go
- tests/integration/cgroups.bats
- tests/integration/delete.bats
- tests/integration/helpers.bash
- tests/integration/update.bats
runc delete is supposed to remove all the container's artefacts. In case systemd cgroup driver is used, and the systemd unit has failed (e.g. oom-killed), systemd won't remove the unit (that is, unless the "CollectMode: inactive-or-failed" property is set).
Call reset-failed from manager.Destroy so the failed unit will be removed during "runc delete".
This fixes `Issue A` from #3780 (which, in its original form, can only be reproduced with RHEL/CentOS 9 systemd version < 252.14, i.e. before they've added https://github.com/redhat-plumbers/systemd-rhel9/pull/149). A test case that works with any recent systemd version is also added.
> runc delete: call systemd's reset-failed

- events.go
- libcontainer/cgroups/fs2/fs2.go
- libcontainer/cgroups/fs2/psi.go
- libcontainer/cgroups/fs2/psi_test.go
- libcontainer/cgroups/stats.go
- tests/integration/events.bats
- tests/integration/helpers.bash
- types/events.go
This is a carry over of #3679, adding support for PSI stats for cgroup v2 to cgroup manager' Stats(), as well as `runc events'. Mostly written by @dqminh, amended by @szuecs and @kolyshkin.
Closes: #3679
Closes: #3358
Closes: #3627
> libct/cg/stats: support PSI for cgroup v2

- libcontainer/cgroups/systemd/v1.go
This is a backport of https://github.com/opencontainers/runc/pull/3804 to release-1.1 branch. Original description follows.
---
In code we have frozen the cgroup to avoid the processes get an occasional "permission denied" error, while the systemd's application of device rules is done disruptively. When the processes in the container can not be frozen over 2 seconds (which defined in fs/freezer.go), we still update the cgroup which resulting the container get an occasional "permission denied" error in some cases.
Return error directly without updating cgroup, when freeze fails.
Fixes: #3803
> [1.1] libct/cg/sd/v1: do not update non-frozen cgroup after frozen failed.

- .github/workflows/validate.yml
- libcontainer/user/user.go
The exception was fixed by https://github.com/polyfloyd/go-errorlint/pull/12 which eventually made its way into golangci-lint.
> ci: bump golangci-lint to v1.53, remove fixed exception

- .gitignore
- Makefile
- contrib/cmd/fs-idmap/fs-idmap.go
- libcontainer/configs/mount_linux.go
- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
- libcontainer/container_linux.go
- libcontainer/factory_linux.go
- libcontainer/init_linux.go
- libcontainer/message_linux.go
- libcontainer/nsenter/idmap.h
- libcontainer/nsenter/nsexec.c
- libcontainer/rootfs_linux.go
- libcontainer/specconv/spec_linux.go
- libcontainer/standard_init_linux.go
- tests/integration/helpers.bash
- tests/integration/idmap.bats
This PR implements support for this runtime-spec change that added idmap mounts support: https://github.com/opencontainers/runtime-spec/pull/1143
We open the idmap source paths and call mount_setattr() in runc PARENT,
as we need privileges in the init userns for that, and then sends the
fds to the child process. For this fd passing we use the same mechanism
used in other parts of thecode, the `_LIBCONTAINER_` env vars.
The mount is finished (unix.MoveMount) from go code, inside the userns,
so we reuse all the prepareBindMount() security checks and the remount
logic for some flags too.
This PR only supports idmap mounts when userns are used AND the mappings
are the same specified for the userns mapping. This limitation is to
simplify the initial implementation, as all our users so far only …
> Support idmap mounts for volumes

- tests/integration/helpers.bash
- tests/integration/ps.bats
runc ps requires cgroup, but all the tests but one required root.
Add rootless cgroup requirement to setup to avoid repetition.
While at it, remove set_cgroups_path as it is not required (default cgroup path, derived from the container name, is used).
> tests/int/ps: enable for rootless

- libcontainer/README.md
- libcontainer/configs/config.go
- libcontainer/configs/config_linux.go
- libcontainer/configs/config_linux_test.go
- libcontainer/configs/validate/rootless.go
- libcontainer/configs/validate/rootless_test.go
- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
- libcontainer/container_linux.go
- libcontainer/integration/exec_test.go
- libcontainer/integration/template_test.go
- libcontainer/mount_linux.go
- libcontainer/rootfs_linux.go
- libcontainer/specconv/spec_linux.go
Hi.
This PR is a follow-up to #3717.
It fixes #3936 and #3935.
If you see any way to improve it, feel free to share.
Best regards.
> Renaming *Mappings fields and use int* for mountEntry.fd

- libcontainer/configs/config_linux.go
This is the follow-up to #3939 , Please see https://github.com/opencontainers/runc/pull/3939#discussion_r1269023899
As @thaJeztah and @fuweid indicated that `a nil slice has length 0`, so we can use the length of UIDMappings/GIDMappings to check whether it is an empty array or not.
> use the length of UIDMappings/GIDMappings to check whether empty or not

- CHANGELOG.md
1. This is a forword port of `CHANGELOG.md` changes from the release PR #3940 .
2. As we propose to release `v1.2.0-rc.0`, I think we should add some important announcements in `Unreleased` changes.
> [CHANGELOG] Forword port changelog after release 1.1.5

- contrib/completions/bash/runc
- create.go
- libcontainer/configs/config.go
- libcontainer/rootfs_linux.go
- libcontainer/specconv/spec_linux.go
- restore.go
- run.go
- tests/integration/mounts_sshfs.bats
- utils_linux.go
Currently bind mounts of filesystems with  `nodev`, `nosuid`, `noexec` options set fail in rootless mode if the same options are not set for the bind mount. For `ro` filesystems this was resolved by #2570 by remounting again with `ro`set. Follow the same approach for  `nodev`, `nosuid`, `noexec` .
This is a replacement for the now closed #3710
> Allow bind mounts of nodev,nosuid,noexec filesystems

- libcontainer/cgroups/devices/systemd.go
Since systemd v240 ([systemd commit 8e8b5d2e6d91180a](https://github.com/systemd/systemd/commit/8e8b5d2e6d91180a)), one can use
`/dev/{char,block}-MAJOR` syntax to specify that all `MAJOR:*`
devices of the type are allowed.
Use it, if available, since it's more straightforward, plus
we can skip somewhat expensive parsing of /proc/devices
~~(which also reminds me we need to merge #3357).~~
> libct/cg/sd: use systemd v240+ new MAJOR:* syntax

- libcontainer/mount_linux.go
- libcontainer/rootfs_linux.go
- tests/integration/run.bats
Fix #3952
When we call `unix.Mount`, if we use file mode bits from the bits with the type `fs.FileMode` directly, it will cause some bits missing.
Please refer: https://github.com/golang/go/blob/master/src/os/file.go#L258-L265
> Fix some file mode bits missing when doing mount syscall

- contrib/cmd/fs-idmap/fs-idmap.go
Here are some cleanups to the fs-idmap binary that we use in integration test to detect if a fs supports idmap mounts or not.
These are just minor cleanups, I'm not fixing any real bug we hit nor anything (I'm not aware of any).
cc @eiffel-fl
> contrib/fs-idmap: Minor cleanups

- libcontainer/mount_linux.go
- libcontainer/rootfs_linux.go
- tests/integration/run.bats
This the backport of #3956 to `release-1.1`, the original description is:
---
Fix #3952
When we call `unix.Mount`, if we use file mode bits from the bits with the type `fs.FileMode` directly, it will cause some bits missing.
Please refer: https://github.com/golang/go/blob/master/src/os/file.go#L258-L265 
---
More details: https://www.gnu.org/software/coreutils/manual/html_node/Mode-Structure.html
> [1.1] Fix some file mode bits missing when doing mount syscall

- libcontainer/utils/utils_unix.go
close_range(2) is far more efficient than a readdir of /proc/self/fd and then doing a syscall for each file descriptor.
> utils: use close_range(2) to close leftover file descriptors

- Dockerfile
- libcontainer/cgroups/file_test.go
- libcontainer/cgroups/manager/manager_test.go
- script/prepare-cgroup-v2.sh
- tests/integration/update.bats
For "make integration", the tests are run inside a Docker/Podman container. Problem is, if cgroup v2 is used, the in-container /sys/fs/cgroup/cgroup.subtree_control is empty.
The added script, used as Docker entrypoint, moves the current process into a sub-cgroup, and then adds all controllers in top-level cgroup.subtree_control.
Addresses https://github.com/opencontainers/runc/issues/3955
> Fix running tests under Docker/Podman and cgroup v2

- .cirrus.yml
- .github/workflows/test.yml
- go.mod
Go 1.21 is out, and go 1.19 is no longer supported.
This also fixes cirrus-ci failures seen recently (and happening because go 1.19 is no longer listed).
> ci: add go 1.21, rm go 1.19, fix cirrus jobs

- .github/workflows/test.yml
Since https://github.com/actions/setup-go/issues/368 is now fixed (in https://github.com/actions/setup-go/releases/tag/v4.1.0), there is no need to disable caching when using different distros.
> ci/gha: re-enable go caching

- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
- libcontainer/rootfs_linux.go
- tests/integration/idmap.bats
As [discussed here](https://github.com/opencontainers/runc/issues/3944#issuecomment-1669297461) it seems safer, at least for now, to revert the error and continue to throw a warning.
---
This reverts commit 881e92a3fd5eeef80bac57efbb1c822deed4f895 and adjust the code so the idmap validations are strict.
Fixes: #3944 
Updates: #3020 (There is no way to re-open it automatically, can someone re-open it?)
> Revert "libct/validator: Error out on non-abs paths"

- init.go
- libcontainer/README.md
- libcontainer/container_linux.go
- libcontainer/init_linux.go
- libcontainer/integration/init_test.go
~~_Based on and currently includes #3375. Draft until that one is merged._~~
~~_Based on and currently includes #3854. Draft until that one is merged._~~
This  moves logging setup out of `func init()` and into `StartInitialization()` (where it should belong);
This concludes the spring cleaning started in #3354 (promise). Loosely based on parts of #3316.
> init simplification

- .cirrus.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
- Dockerfile
- libcontainer/cgroups/file_test.go
- libcontainer/cgroups/manager/manager_test.go
- libcontainer/user/user.go
- script/prepare-cgroup-v2.sh
This is a partial backport of the following PRs:
* #3960
* #3814
* #3920
* #3822
* #3919  
The main theme is adding Go 1.21, plus some CI fixes.
> [1.1] Add go 1.21 to CI

- CHANGELOG.md
- libcontainer/cgroups/fs2/memory.go
- libcontainer/cgroups/fs2/memory_test.go
Backport of #3933 by @alexeldeib to release-1.1 branch. Original description follows. 
----
This aligns v2 usage calculations more closely with v1. Current node-level reporting for v1 vs v2 on the same machine under similar load may differ by ~250-750Mi.
Also return usage as combined swap + memory usage, aligned with v1 and non-root v2 cgroups.
`mem_cgroup_usage` in the kernel counts NR_FILE_PAGES
+ NR_ANON_MAPPED + `nr_swap_pages` (if swap enabled) [^0].
Using total - free results in higher "usage" numbers. This is likely due to various types of reclaimable memory technically counted as in use (e.g. inactive anon).
See also https://github.com/kubernetes/kubernetes/issues/118916 for more context
[^0]: https://github.com/torvalds/linux/blob/06c2afb862f9da8dc5efa4b6076a0e48c3fbaaa5/mm/memcon …
> [1.1] libct/cg/fs2: use `file` + `anon` + `swap` for usage

- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
- libcontainer/container_linux.go
- libcontainer/nsenter/nsexec.c
- libcontainer/specconv/spec_linux.go
- tests/integration/helpers.bash
- tests/integration/timens.bats
Fix up a few things that were flagged in the review of [the original timens PR](https://github.com/opencontainers/runc/pull/3876), namely around error handling and validation. In addition, add some basic smoke tests for timens.
> timens: minor cleanups

- Makefile
- contrib/cmd/recvtty/recvtty.go
- libcontainer/configs/mount_linux.go
- libcontainer/criu_linux.go
- libcontainer/init_linux.go
- libcontainer/integration/execin_test.go
- libcontainer/nsenter/nsexec.c
- libcontainer/process_linux.go
- libcontainer/rootfs_linux.go
- libcontainer/seccomp/patchbpf/enosys_linux.go
- libcontainer/seccomp/seccomp_linux.go
- libcontainer/seccomp/seccomp_unsupported.go
- libcontainer/setns_init_linux.go
- libcontainer/sync.go
- libcontainer/utils/cmsg.go
- libcontainer/utils/utils_unix.go
- tty.go
This is a partial carry of #3953, containing more-or-less simple changes from it.
The only differences from the commits in the original PR are:
- ported to current HEAD (a few conflicts due to recently merged PRs);
- fixed a misspelled word (syncrhonisation) in a commit message;
- fixed a small issue in an intermediate commit (see https://github.com/opencontainers/runc/pull/3953/commits/dbdc562b20791d5ed0f484246c4107083031db43#r1294110056);
- fixed a few cases of referring to old function names in doc and error messages;
- fixed error handling in RecvFile (`err` -> `Err`);
- added a commit that fixes the parseSync handling issue;
- added my Signed-off-by to some commits.
> Nsexec spring cleaning part I

- .github/workflows/test.yml
- .github/workflows/validate.yml
The default timeout is 360 minutes, which is way long for these jobs. If the CI (or a test) has stuck, we'd better know about it earlier than in 6 hours.
Set the timeouts for some [relatively] long running jobs conservatively:
- test and release jobs usually take ~10 minutes;
- lint job takes 1 minute (but can be a few times slower when we switch Go or golangci-lint version);
- cross-386 job takes about 2 minutes;
- the rest is seconds (and I am lazy to set timeouts everywhere).
Inspired by #3953/#3982.
> ci/gha: add job timeouts

- features.go
- go.mod
- go.sum
- vendor/github.com/opencontainers/runtime-spec/specs-go/features/features.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
- vendor/modules.txt
This PR just exposes the idmap support in the "features" subcommand.
cc @cyphar @AkihiroSuda
> features: Expose idmap support

- .github/workflows/validate.yml
- libcontainer/cgroups/file.go
- libcontainer/cgroups/fs/cpuset.go
- libcontainer/cgroups/utils.go
- libcontainer/criu_linux.go
- libcontainer/init_linux.go
- libcontainer/specconv/spec_linux.go
- libcontainer/system/linux.go
- notify_socket.go
- signals.go
golangci-lint v1.54.2 comes with errorlint v1.4.4, which contains
the fix (https://github.com/polyfloyd/go-errorlint/pull/47) whitelisting all errno comparisons for errors coming from
x/sys/unix.
Thus, these annotations are no longer necessary. Hooray!
> bump golangci-lint; remove nolint annotations for unix errno comparisons

- libcontainer/process_linux.go
- tests/integration/host-mntns.bats
If the container does not have own mount namespace configured (i.e. it shares the mount namespace with the host), its "prestart" (obsoleted) and "createRuntime" hooks are called twice, and its cgroups and Intel RDT settings are also applied twice.
The code being removed was originally added by commit 2f2764984 ("Move pre-start hooks after container mounts", Feb 17 2016). At that time, the syncParentHooks() was called from setupRootfs(), which was only used when the container config has mount namespace (NEWNS) enabled.
Later, commit 244c9fc426a ("*: console rewrite", Jun 4 2016) spli the relevant part of setupRootfs() into prepareRootfs(). It was still called conditionally (only if mount namespace was enabled).
Finally, commit 91ca331474b6b ("chroot when no mount namespaces is provided", …
> Fix for host mount ns containers

- libcontainer/cgroups/fs/paths.go
- update.go
> Fix File to Close

- contrib/completions/bash/runc
- docs/spec-conformance.md
- libcontainer/cgroups/fs/cpu.go
- libcontainer/cgroups/fs/cpu_test.go
- libcontainer/cgroups/fs/fs.go
- libcontainer/cgroups/fs2/cpu.go
- libcontainer/configs/cgroup_linux.go
- libcontainer/specconv/spec_linux.go
- man/runc-update.8.md
- tests/integration/helpers.bash
- tests/integration/update.bats
- update.go
> [Carry #3205] libct/cg: add CFS bandwidth burst for CPU

- libcontainer/specconv/spec_linux.go
From the Go specification:
> "1. For a nil slice, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary.
> libct/specconv: remove redundant nil check

- libcontainer/configs/validate/validator.go
The runtime spec now allows relative mount dst paths, so remove the comment saying we will switch this to an error later and change the error messages to reflect that.
This was changed in this runtime-spec PR: https://github.com/opencontainers/runtime-spec/pull/1225
---
I'm not 100% sure this new text is good, but invalid configuration seemed strong now. If you have better suggestions, please share them! :)
> validator: Relax warning for not abs mount dst path

- tests/integration/cgroups.bats
Fix #4019 
As the description in #4019 :
1. "runc run (cgroup v2 resources.unified only)"
change the memory limit from 10MB to 20MB.
2. "runc run (cgroup v2 resources.unified override)"
ensure the memory limit in `unified` is bigger than `.linux.resources.memory.limit`.
> [CI] increase memory.max in cgroups.bats

- libcontainer/cgroups/fs/memory.go
kmem.limit_in_bytes has been removed in upstream linux and this patch is queued to be backported to linux 6.1 stable:
- https://lore.kernel.org/linux-mm/20230705134434.GA156754@cmpxchg.org/T/
- https://www.spinics.net/lists/stable-commits/msg316619.html
Without this change to libcontainerd, GetStats() will return an error on the latest kernel(s). A downstream effect is that Kubernetes's kubelet does not start up. This fix was tested by ensuring that it unblocks kubelet startup when running on the latest kernel.
> Handle kmem.limit_in_bytes removal

- libcontainer/cgroups/fs/memory.go
kmem.limit_in_bytes has been removed in upstream linux and this patch is queued to be backported to linux 6.1 stable:
- https://lore.kernel.org/linux-mm/20230705134434.GA156754@cmpxchg.org/T/
- https://www.spinics.net/lists/stable-commits/msg316619.html
Without this change to libcontainerd, GetStats() will return an error on the latest kernel(s). A downstream effect is that Kubernetes's kubelet does not start up. This fix was tested by ensuring that it unblocks kubelet startup when running on the latest kernel.
> [1.1 backport] Handle kmem.limit_in_bytes removal

- libcontainer/dmz/Makefile
While addressing [this comment][link], I didn't realize the comment is shown every time we compile. Let's just move it out.
cc @cyphar @AkihiroSuda 
[link]: https://github.com/opencontainers/runc/pull/4024#discussion_r1337157087
---
Otherwise it is shown when compiling, like this:
```
gcc  -fno-asynchronous-unwind-tables -fno-ident -s -Os -nostdlib -lgcc -static -o runc-dmz _dmz.c
strip -gs runc-dmz
```
Having it before the target is equally clear and will not be shown while compiling.
> libct/dmz: Move comment out of the Makefile rule

- script/lib.sh
https://github.com/golang/go/wiki/GoArm#supported-operating-systems
> ARM on Linux. You must run an EABI kernel.
> These are generally known as armel for softfloat (compatible with ARMv5)
> or armhf for hardware floating point (ARMv6 and above).
Prior to this commit, the script was setting GOARM=6 for armel, GOARM=7 for armhf.
Fix #4033
> script/lib.sh: set GOARM=5 for armel, GOARM=6 for armhf

- libcontainer/seccomp/patchbpf/enosys_linux.go
- man/runc-update.8.md
Run codespell
codespell
shell: /usr/bin/bash -e {0}
env:
GO_VERSION: 1.20.x
./man/runc-update.8.md:45: limtis ==> limits
./libcontainer/seccomp/patchbpf/enosys_linux.go:92: explcitly ==> explicitly
Error: Process completed with exit code 65.
> fix two typos

- libcontainer/init_linux.go
syncrhonisation ==> synchronisation
This one is from recently merged #4003 which I forgot to retest with newer codespell.
> libct: fix a typo

- libcontainer/console_linux.go
- libcontainer/container_linux.go
- libcontainer/rootfs_linux.go
_(this is an alternative to #3563, implementing @cyphar [suggestion](https://github.com/opencontainers/runc/pull/3563#pullrequestreview-1138343099))_
Umask is problematic for Go programs as it affects other goroutines (see [1] for more details).
Instead of using it, let's just prop up with Chmod.
Note this patch misses the MkdirAll call in createDeviceNode. Since the runtime spec does not say anything about creating intermediary directories for device nodes, let's assume that doing it via mkdir with the current umask set is sufficient (if not, we have to reimplement MkdirAll from scratch, with added call to os.Chmod).
[1] https://github.com/opencontainers/runc/pull/3563#discussion_r990293788
> libct: use chmod instead of umask

- libcontainer/container_linux.go
- libcontainer/container_linux_test.go
- libcontainer/criu_linux.go
- libcontainer/factory_linux.go
- libcontainer/state_linux.go
The name `root` (or `containerRoot`) is confusing; one might think it is
the root of container's file system (the directory runc chroots into).
Rename to `stateDir` for clarity.
> Rename root to stateDir in struct Container

- docs/spec-conformance.md
In reviewing PR #4024 ("libct/dmz: Reduce the binary size using nolibc"), we noticed that we do not intend to actively support MIPS.
We do not intend to support i386 either.
This might be a breaking change for Debian, which has been officially providing runc packages for `i386`, `mips64el` and `mipsel`: https://packages.debian.org/bookworm/runc
> docs: clarify the supported architectures (No MIPS)

- libcontainer/nsenter/cloned_binary.c
- libcontainer/seccomp/patchbpf/enosys_linux.go
- man/runc-update.8.md
This fixes CI for release-1.1 branch
(cherry picked from commit 109dcadd9d1756258ba0ee096871d11c8581002e)
```
Run codespell
codespell
shell: /usr/bin/bash -e {0}
env:
GO_VERSION: 1.20.x
./man/runc-update.8.md:45: limtis ==> limits
./libcontainer/seccomp/patchbpf/enosys_linux.go:92: explcitly ==> explicitly
Error: Process completed with exit code 65.
```
---
This pr also fix an new typo:
```
Run codespell
codespell
shell: /usr/bin/bash -e {0}
env:
GO_VERSION: 1.20.x
./libcontainer/nsenter/cloned_binary.c:154: re-use ==> reuse
Error: Process completed with exit code 65.
```
> [1.1 backport] fix typos

- go.mod
- go.sum
- tests/integration/mounts.bats
- vendor/github.com/mrunalp/fileutils/fileutils.go
- vendor/github.com/mrunalp/fileutils/idtools.go
- vendor/modules.txt
Bump fileutils to v0.5.1, which fixes permissions of newly created directories to not depend on the value of umask (see mrunalp/fileutils#9).
Add a test case which fails like this before the fix:
mounts.bats
✗ runc run [tmpcopyup]
(in test file tests/integration/mounts.bats, line 28)
`[[ "${lines[0]}" == *'drwxrwxrwx'* ]]' failed
runc spec (status=0):
runc run test_busybox (status=0):
drwxr-xr-x    2 root     root            40 Oct  4 22:35 /dir1/dir2
Fixes #3991.
> Fix directory perms vs umask for tmpcopyup

- docs/spec-conformance.md
- libcontainer/configs/config.go
- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
- libcontainer/init_linux.go
- libcontainer/process.go
- libcontainer/setns_init_linux.go
- libcontainer/specconv/spec_linux.go
- libcontainer/standard_init_linux.go
- tests/integration/scheduler.bats
- utils_linux.go
_(this is a carry of #3962)_
Spec: https://github.com/opencontainers/runtime-spec/pull/1188
Close: #3895 #3962
> [Carry 3962] Support `process.scheduler`

- libcontainer/cgroups/devices/systemd_test.go
This test is as flaky as TestSkipDevices*, let's also t skip it on CentOS 7.
> ci: skip TestPodSkipDevicesUpdate on CentOS 7

- libcontainer/cgroups/fs/hugetlb.go
- libcontainer/cgroups/fs/hugetlb_test.go
- libcontainer/cgroups/fs2/hugetlb.go
- tests/integration/cgroups.bats
This adds support for `hugetlb.<pagesize>.rsvd` limiting and accounting.
The previous non-rsvd max/limit_in_bytes does not account for reserved
huge page memory, making it possible for a processes to reserve all the
huge page memory, without being able to allocate it (due to cgroup
restrictions).
In practice this makes it possible to successfully mmap more huge page
memory than allowed via the cgroup settings, but when using the memory
the process will get a SIGBUS and crash. This is bad for applications
trying to mmap at startup (and it succeeds), but the program crashes
when starting to use the memory. eg. postgres is doing this by default.
This also keeps writing to the old max/limit_in_bytes, for backward
compatibility.
More info can be found here: https://lkml.org/lkml/2020/2/3/1153 …
> libct/cg: support hugetlb rsvd

- libcontainer/dmz/Makefile
- libcontainer/dmz/README.md
- libcontainer/dmz/_dmz.c
This should make compilation work on all arches, doesn't matter if nolibc is supported there or not. If it is not supported, we just use the C stdlib.
**Please** review the `NOLIBC_GOARCHES` var, as that should have the GOARCH values that nolibc support. If we have a mistake there (i.e. put an arch that is not supported), compilation will fail on that arch.
I tried to be conservative on the arches to put there, but not just limit to the ones I can test (386 and amd64). **Please** review that part.
Fixes: #4037 
cc @cyphar @AkihiroSuda 
See below the commit msg.
---
When we added nolibc, we started using it unconditionally. But runc is currently being compiled on more arches than supported by nolibc, like MIPS.
Let's compile using stdlib if the arch we are compiling on is not supported by …
> libct/dmz: Support compiling on all arches

- .github/workflows/test.yml
For some reason, since today
curl -fSsl https://download.opensuse.org/repositories/devel:/tools:/criu/xUbuntu_20.04/Release.key
does not produce any error, but there's no output either.
~~Switch to wget.~~ Add -L to follow 3xx redirects.
While at it, ditch apt-key as it's not supposed to be used that way.
Fixes: #4078
> ci/gha: fix downloading Release.key

- .github/workflows/test.yml
_This is a backport of #4079 to release-1.1 branch._
Since today, the URL from download.opensuse.org started returning a HTTP 302 redirect, so -L option for curl is needed to follow it.
While at it, remove apt-key as per its man page recommendation:
> Note: Instead of using this command a keyring should be placed
> directly in the /etc/apt/trusted.gpg.d/ directory with a descriptive
> name and either "gpg" or "asc" as file extension.
> [1.1] ci/gha: fix downloading Release.key

- libcontainer/cgroups/file.go
Commit f34eb2c00 introduced a workaround to retry on EINTR due to changes in Go 1.14. It was fixed in Go 1.15 [1], meaning a custom retry loop is no longer necessary.
Keep the test case to avoid future regressions.
[1] https://github.com/golang/go/issues/38033
> libct/cg: remove retry on EINTR in

- libcontainer/cgroups/fs/hugetlb.go
- libcontainer/cgroups/fs/hugetlb_test.go
- libcontainer/cgroups/fs2/hugetlb.go
- tests/integration/cgroups.bats
- tests/integration/helpers.bash
This is a backport of #4073 and #4086 to release-1.1 branch.
----
This adds support for `hugetlb.<pagesize>.rsvd` limiting and accounting.
The previous non-rsvd max/limit_in_bytes does not account for reserved huge page memory, making it possible for a processes to reserve all the huge page memory, without being able to allocate it (due to cgroup restrictions).
In practice this makes it possible to successfully mmap more huge page memory than allowed via the cgroup settings, but when using the memory the process will get a SIGBUS and crash. This is bad for applications trying to mmap at startup (and it succeeds), but the program crashes when starting to use the memory. eg. postgres is doing this by default.
This also keeps writing to the old max/limit_in_bytes, for backward compatibility. …
> [1.1] libct/cg: support hugetlb rsvd

- contrib/completions/bash/runc
- create.go
- libcontainer/configs/config.go
- libcontainer/configs/mount_linux.go
- libcontainer/rootfs_linux.go
- libcontainer/specconv/spec_linux.go
- restore.go
- run.go
- tests/integration/mounts_sshfs.bats
- utils_linux.go
The original reasoning for this option was to avoid having mount options
be overwritten by runc. However, adding command-line arguments has
historically been a bad idea because it forces strict-runc-compatible
OCI runtimes to copy out-of-spec features directly from runc and these
flags are usually quite difficult to enable by users when using runc
through several layers of engines and orchestrators.
A far more preferable solution is to have a heuristic which detects
whether copying the original mount's mount options would override an
explicit mount option specified by the user. In this case, we should
return an error. You only end up in this path in the userns case, if you
have a bind-mount source with locked flags.
During the course of writing this patch, I discovered that several …
> rootfs: remove --no-mount-fallback and finally fix MS_REMOUNT

- libcontainer/cgroups/fs2/fs2.go
- libcontainer/cgroups/fs2/misc.go
- libcontainer/cgroups/fs2/misc_test.go
- libcontainer/cgroups/stats.go
Triggered by https://github.com/opencontainers/runc/discussions/3910.
Initial version based on v2 `HugetlbStats` and the new v2 memory unit tests.
Opens:
> libct/cg/stats: support misc for cgroup v2

- CHANGELOG.md
- libcontainer/cgroups/fs/memory.go
- libcontainer/cgroups/fs/memory_test.go
- libcontainer/cgroups/fs2/memory.go
- libcontainer/cgroups/fs2/memory_test.go
- libcontainer/cgroups/stats.go
> feat: add `swapOnlyUsage` in `MemoryStats`

- libcontainer/configs/validate/validator_test.go
We changed it in PR:
https://github.com/opencontainers/runtime-spec/pull/1225
But we missed to remove this comment.
> libct: Remove old comment

- .cirrus.yml
- README.md
- Vagrantfile.fedora
- libcontainer/container_linux.go
- libcontainer/dmz/README.md
- libcontainer/dmz/selinux.go
- libcontainer/dmz/selinux_compat.go
- tests/integration/selinux.bats
Unfortunately, runc-dmz does not play well with SELinux.
The preliminary discussion about that happened in https://github.com/opencontainers/runc/pull/3987#discussion_r1299384233, and as a result the `RUNC_DMZ=legacy` was introduced to disable the feature. Alas, the solution is not very practical, as users have to modify upper level runtimes to pass the env var to runc. Also, this is all-or-nothing approach.
The issue itself is described in #4057, and is fixed in [container-selinux v2.224.0].
For older distros, this PR adds a workaround (enabled by default). Here's a quote from libct/dmz/README (as added by this PR):
Older SELinux policy can prevent runc to execute the dmz binary. The issue is
fixed in [container-selinux v2.224.0]. Yet, some older distributions may not
have the fix, so …
> Add selinux-vs-dmz test case and a workaround

- internal/testutil/testutil.go
- libcontainer/cgroups/devices/systemd_test.go
- libcontainer/cgroups/file_test.go
It's flaky and we can do nothing about it.
Also, this is a chance to finally introduce our first `internal` package (even if for tests only), discussed in https://github.com/opencontainers/runc/issues/3028.
Fixes #3418.
> Skip TestWriteCgroupFileHandlesInterrupt on CentOS 7

- .cirrus.yml
This is a followup to #4053.
CentOS Stream 8 now comes with container-selinux 2:2.224.0-1.module_el8+712+4cd1bd69, so we only need the kludge for CentOS 7 (which, I guess, is the sole reason why we have this kludge at all).
This is only for CI.
> ci/cirrus: disable selinux-dmz kludge for centos-stream-8

- tests/integration/run.bats
Apparently, sometimes a short-lived "runc run" produces result with \r and sometimes without. As a result, we have an occasional failure of "runc run with tmpfs perms" test.
The solution (to the flaky test) is to use the first line of the output (like many other tests do).
Fixes: #4029
> tests/int: fix flaky "runc run with tmpfs perm"

- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
Bind-mounts cannot have any filesystem-specific "data" arguments, because the kernel ignores the data argument for MS_BIND and MS_BIND|MS_REMOUNT and we cannot safely try to override the flags because those would affect mounts on the host (these flags affect the superblock).
It should be noted that there are cases where the filesystem-specified flags will also be ignored for non-bind-mounts but those are kernel quirks and there's no real way for us to work around them. And users wouldn't get any real benefit from us adding guardrails to existing kernel behaviour.
See the discussion in opencontainers/runtime-spec#1222. I am a little worried this could break users, but I also would be very surprised if users were specifying flags to bind mounts that are always ignored.
Signed-off-by: Aleksa …
> configs: validate: add validation for bind-mount fsflags

- .gitignore
- Makefile
- contrib/cmd/pidfd-kill/pidfd-kill.go
- create.go
- exec.go
- libcontainer/container_linux.go
- libcontainer/init_linux.go
- libcontainer/process.go
- libcontainer/setns_init_linux.go
- libcontainer/standard_init_linux.go
- run.go
- tests/integration/helpers.bash
- tests/integration/pidfd-socket.bats
- utils_linux.go
The container manager like containerd-shim can't use cgroup.kill feature or freeze all the processes in cgroup to terminate the exec init process. It's unsafe to call kill(2) since the pid can be recycled. It's good to provide the pidfd of init process through the pidfd-socket. It's similar to the console-socket. With the pidfd, the container manager like containerd-shim can send the signal to target process safely.
And for the standard init process, we can have polling support to get exit event instead of blocking on wait4.
---------------------
Let me explain why the containerd-shim needs this feature for containerd init process.
Without pidfd, containerd-shim can't tell which process exits. It has to use reap all the zombies.
However, it requires all the fork/exec operations needs to …
> [feature request] *: introduce pidfd-socket flag

- checkpoint.go
- delete.go
- libcontainer/cgroups/utils.go
- libcontainer/container_linux.go
- libcontainer/init_linux.go
- libcontainer/state_linux.go
- tests/integration/delete.bats
- tests/integration/kill.bats
- utils_linux.go
This fixes a couple of regressions introduced in #3825, most related to
killing and destroying containers without own private PID namespace,
and with initial container process gone. In this scenario, container is
considered stopped, but there might be some leftover processes in
the container cgroup.
1. Commit f8ad20f made it impossible to kill those leftover processes.
Fix this by moving the check if container init exists to after the
special case of handling the container without own PID namespace.
2. `runc delete -f` is not killing leftover processes either, ignoring those.
3. `runc delete` in runc 1.1 and earier used to kill leftover processes.
I think this is a bug, as `delete` (without `-f`) is not supposed to kill
anything. With this PR, such error is reported.
4. Fix the minor …
> Fix `runc kill` and `runc delete` for containers with no init and no private PID namespace

- .gitignore
- Makefile
- contrib/cmd/remap-rootfs/remap-rootfs.go
- libcontainer/configs/config_linux.go
- libcontainer/configs/validate/rootless.go
- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
- libcontainer/init_linux.go
- libcontainer/integration/exec_test.go
- libcontainer/nsenter/nsexec.c
- libcontainer/specconv/spec_linux.go
- libcontainer/specconv/spec_linux_test.go
- libcontainer/userns/userns_maps.c
- libcontainer/userns/userns_maps_linux.go
- tests/integration/delete.bats
- tests/integration/events.bats
- tests/integration/helpers.bash
- tests/integration/idmap.bats
- tests/integration/kill.bats
- tests/integration/mounts.bats
- tests/integration/run.bats
- tests/integration/timens.bats
- tests/integration/userns.bats
This fixes #4122 along with several other issues I found while writing integration tests for joining namespace paths. In particular, this fixes the following issues:
* Starting a container in a target user namespace now works properly.
- ~~**NOTE** This requires calling the `nsenter` binary. I've taken care to ensure that we don't do this in any context other than the host, but I'm not super happy with this. The other option would be to self-exec but that would require changing up how `runc init` works as well so we could have two self-exec entrypoints. I'm not sure it's worth it.~~
- I've reimplemented this using CGo, by forking in C code and doing the `setns(2)` there. Technically it's a little dodgy to be doing work after a `fork(2)`, and while we don't do anything too complicated …
> *: fix several issues with namespace path handling

- CHANGELOG.md
- libcontainer/cgroups/fs/memory.go
- libcontainer/cgroups/fs/memory_test.go
- libcontainer/cgroups/fs2/memory.go
- libcontainer/cgroups/fs2/memory_test.go
- libcontainer/cgroups/stats.go
This is a 1.1 backport of https://github.com/opencontainers/runc/pull/4010
> [1.1] feat: add swapOnlyUsage in MemoryStats

- libcontainer/configs/config.go
- libcontainer/configs/config_linux.go
- libcontainer/container_linux.go
- libcontainer/specconv/spec_linux.go
- libcontainer/specconv/spec_linux_test.go
- libcontainer/userns/userns_maps_linux.go
It turns out that the error added in commit 09822c3da8ad ("configs: disallow ambiguous userns and timens configurations") causes issues with containerd and CRIO because they pass both userns mappings and a userns path.
These configurations are broken, but to avoid the regression in this one case, output a warning to tell the user that the configuration is incorrect but we will continue to use it if and only if the configured mappings are identical to the mappings of the provided namespace.
/cc @rata 
Fixes: 09822c3da8ad ("configs: disallow ambiguous userns and timens configurations")
Fixes #4133
> specconv: temporarily allow userns path and mapping if they match

- libcontainer/configs/config.go
- libcontainer/configs/config_linux.go
- libcontainer/configs/validate/rootless.go
- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
- libcontainer/container_linux.go
- libcontainer/integration/exec_test.go
- libcontainer/specconv/spec_linux.go
- libcontainer/specconv/spec_linux_test.go
- libcontainer/userns/userns_maps.c
- libcontainer/userns/userns_maps_linux.go
- tests/integration/run.bats
- tests/integration/userns.bats
This a partial backport of the key parts of #4124 as well as the needed fixes in #4134.
~~*Marking as a draft until #4134 is merged.*~~
Fixes #4122
> [1.1] *: fix several issues with userns path handling

- libcontainer/userns/usernsfd_linux.go
Before we merge #3985 , we should do `git rebase main` even though there is no conflict at that time.
> fix a (u|g)IDMappings type value convertion error

- libcontainer/mount_linux.go
This gives a more clear error message when idmap mounts are not supported on the source filesystem. For example, a k8s user will see this now in kubectl describe pod:
Warning  Failed     2s (x2 over 4s)  kubelet, 127.0.0.1  Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: failed to fulfil mount request: failed to set MOUNT_ATTR_IDMAP on /var/lib/kubelet/pods/f037a704-742c-40fe-8dbf-17ed9225c4df/volumes/kubernetes.io~empty-dir/hugepage: invalid argument (maybe the source filesystem doesn't support idmap mounts on this kernel?): unknown
This gives a hint on where to look at.
This come-up when looking at this bug report: …
> libct: Improve error msg when idmap is not supported

- Makefile
I have reviewed and found such errors for about 2 times.
So I think move the target `clean` next to `all` will reduce such type error in the future?
> remove remap-rootfs bin when running make clean

- docs/spec-conformance.md
1. The issue "Support rsvd hugetlb cgroup (#3859)" has been implemented in (#4073), and has been backported to 1.1 in (#4077 ).
2. We have implemented idmapped-mounts with no limitations in #3985 .
So we should update the doc.
> update spec-conformance.md(rsvd hugetlb cgroup and idmapped-mounts)

- script/check-config.sh
* don't check MEMCG_SWAP on newer kernels
* disable colors on non-terminal; honor NO_COLOR
* add check for CHECKPOINT_RESTORE
* fix kernel version checks, annotate with kernel commits
* add check for BLK_CGROUP_IOCOST
Partially taken from #4142.
> script/check-config.sh: fixes and additions

- libcontainer/dmz/_dmz.c
- tests/integration/run.bats
This error code is using functions that are present in nolibc too.
When using nolibc, the error is printed like:
exec /runc.armel: errno=8
When using libc, as its perror() implementation translates the errno to
a message, it is printed like:
exec /runc.armel: exec format error
Note that when using libc, the error is printed in the same way as
before.
---
We can try to do things to expand errno to a string with nolibc (like using the system's errno definitions and reimplement `strerror()` with those, ignoring locales; or try to send the errno back to go and using go unix package to print it), but it's not clear runc-dmz is a good idea in the first place, so let's go the easy path for now.
We can later revisit this if we want runc-dmz and we want to really reduce the size with nolibc. …
> Fix runc-dmz error printing

- libcontainer/init_linux.go
- libcontainer/sync_unix.go
- tests/integration/exec.bats
- tests/integration/run.bats
We have moved the error msg display position in #3385, I think it's reasonable to display the container init msg in one place, but in this PR, we changed an error ignore behavior in https://github.com/opencontainers/runc/blob/main/libcontainer/init_linux.go#L112-L113 .
Yes, we should display the error before `procReady` has sent, but we should ignore after that. So I think we can add a field to indicate whether we have sent `procReady` or not in child process. It's not needed for the parent process, but we can reuse it to remove a local var `seenProcReady`.
Fix #4171
> never send procError to parent process after sent procReady

- libcontainer/init_linux.go
- libcontainer/mount_linux.go
- libcontainer/setns_init_linux.go
- libcontainer/standard_init_linux.go
- libcontainer/utils/utils_unix.go
While it doesn't make much of a practical difference, it seems far more reasonable to use os.NewFile to wrap all of our passed file descriptors to make sure they're tracked by the Go runtime and that we don't double-close them.
> init: use *os.File for passed file descriptors

- libcontainer/setns_init_linux.go
- tests/integration/exec.bats
Fix #4183 
To simplify the implemention, we can keep it the same as in `standard_init_linux.go`.
----
Recent CVE-2024-21626 fix (commit f2f16213) broke a recently added test (commit 0bc4732c, #4173) because if exec fails, runc is unable to communicate the error back to the parent.
Let's not close syncPipe.
This fixes the following test failure:
```console
...
✗ RUNC_DMZ=legacy runc exec [execve error]
(in test file tests/integration/exec.bats, line 340)
`[ ${#lines[@]} -eq 1 ]' failed
runc spec (status=0):
runc run -d --console-socket /tmp/bats-run-77CvQx/runc.JurXM2/tty/sock test_busybox (status=0):
runc exec -t test_busybox /run.sh (status=255):
writing sync procError: write sync: bad file descriptor
exec /run.sh: no such file or directory
```
> Close sync pipe explicitly in exec

- .cirrus.yml
As go has released v1.22.0, so there is no 1.20.x in `https://go.dev/dl/?mode=json` anymore.
Let's update go version to `1.21.x`  in cirrus ci.
This will fix the error:
```
eval $(curl -fsSL "${PREFIX}?mode=json" | jq -r  --arg Ver "$GO_VERSION" '.[] | select(.version | startswith("go\($Ver)")) | .files[] | select(.os == "linux" and .arch == "amd64" and .kind == "archive") | "filename=\"" + .filename + "\""')
curl -fsSL "$PREFIX$filename" | tar Cxz /usr/local
gzip: stdin: not in gzip format
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
curl: (23) Failed writing body (679 != 1401)
```
> [ci] update go version to 1.21 in cirrus ci

- tests/integration/helpers.bash
This expression is specific to GNU awk (gawk), so if someone has other version of awk installed, this won't work and it's not easy to see why.
Explicitly requiring gawk here is better.
Revert "tests/int/helpers: gawk -> awk"
This reverts commit 4e65118d02b19963d49a6e0b12326123dd21c956.
Reported-by: lifubang <lifubang@acmcoder.com>
> tests/int: use gawk where needed

- .github/workflows/validate.yml
This permission is now needed so that the linter can annotate code in a PR (see [1]).
[1] https://github.com/golangci/golangci-lint-action/pull/931/commits/bc1904f0c946172fc1821908fc41649db49f0334
> ci/golangci-lint: add checks permission

- Makefile
* Simple error correction of a spelling mistake which was introduced at commit b8f75f3
> Fixed spelling mistake in the Makefile at .PHONY vendor

- Makefile
- README.md
- contrib/cmd/memfd-bind/README.md
- libcontainer/dmz/dmz_linux.go
- tests/integration/exec.bats
- tests/integration/run.bats
- tests/integration/selinux.bats
There are several issues that we caught at the last minute. Several maintainers said it seems safer to disable it by default, so let's do that.
runc-dmz is marked as experimental and besides the build tag you need to opt-in with `RUNC_DMZ=true` to use it.
Future PRs can go further and maybe even remove the buildtag, simplifying the CI (and the time it takes to run).
---
cc @cyphar @kolyshkin @lifubang
> Disable runc-dmz by default

- tests/integration/delete.bats
- tests/integration/helpers.bash
- tests/integration/kill.bats
It takes some time for the kernel to kill the process (and remove its
PID from cgroup.procs). To ensure we don't have flakes from reading
cgroup.procs right after the kill, check and wait for processes to
actually be gone.
Fixes: #4163
> tests/int: fix flaky kill tests

- .github/dependabot.yml
- go.mod
- go.sum
- vendor/modules.txt
The referenced issue was fixed in `github.com/urfave/cli` v1.22.6. We can now remove the dependabot ignore for this package.
> Remove dependabot ignore

- docs/spec-conformance.md
- features.go
See https://github.com/opencontainers/runtime-spec/blob/v1.2.0/features.md#unsafe-annotations-in-configjson
> features: implement returning potentiallyUnsafeConfigAnnotations list

- libcontainer/seccomp/patchbpf/enosys_linux.go
- libcontainer/seccomp/patchbpf/enosys_linux_test.go
It turns out that on ppc64le (at least), Docker doesn't include any
architectures in the list of allowed architectures. libseccomp
interprets this as "just include the default architecture" but patchbpf
would return a no-op ENOSYS stub, which would lead to the exact issues
that commit https://github.com/opencontainers/runc/commit/7a8d7162f9d72f20d83eaa36aeb5426deecd58f2 ("seccomp: prepend -ENOSYS stub to all
filters") fixed for other architectures.
So, just always include the running architecture in the list. There's
no real downside.
Ref: https://bugzilla.suse.com/show_bug.cgi?id=1192051#c6
Reported-by: Fabian Vogt <fvogt@suse.com>
> seccomp: patchbpf: always include native architecture in stub

- docs/spec-conformance.md
- libcontainer/configs/config.go
- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
- libcontainer/process.go
- libcontainer/process_linux.go
- libcontainer/specconv/spec_linux.go
- libcontainer/standard_init_linux.go
- tests/integration/ioprio.bats
- utils_linux.go
https://github.com/opencontainers/runtime-spec/pull/1191
> Add I/O priority

- .github/workflows/test.yml
- CHANGELOG.md
- libcontainer/nsenter/nsenter_go122.go
We will almost certainly need to eventually rework nsenter to:
1. Figure out a way to make pthread_self() not break after nsenter runs
(probably not possible, because the core issue is likely that we are
ignoring the rules of signal-safety(7)); or
2. Do an other re-exec of /proc/self/exe to execute the Go half of
"runc init" -- after we've done the nsenter setup. This would reset
all of the process state and ensure we have a clean glibc state for
Go, but it would make runc slower...
For now, just block Go 1.22 builds to avoid having broken runcs floating
around until we resolve the issue. It seems possible for musl to also
have an issue, but it appears to work and so for now just block glibc
builds.
Note that this will only block builds for anything that uses nsenter --
so users of our …
> [hotfix] nsenter: refuse to build with Go 1.22

- .github/workflows/test.yml
1. Sort the list of matrix excludes in the order of matrix,
add comments explaining why we disable some jobs.
2. Exclude some jobs:
- runc_nodmz && go 1.20.x
- runc_nodmz && -race
> ci/test: exclude some runc_nodmz jobs

- tests/integration/mounts_sshfs.bats
This is another way to fix the tests in debian testing. It's an alternative for #4242.
I think #4242 is a more reliable fix (besides it's number full of wisdom and the meaning of life :-D), but this also does the trick in case you prefer a smaller fix.
Fixes #4093
> Fix tests in debian testing (mount_sshfs.bats) - minimal fix

- tests/integration/update.bats
- update.go
Fix #4210 
We should set the default of `CpuBurst` to nil instead of 0 when we are updating a container's resource limit.
> set the default value of CpuBurst to nil instead of 0

- libcontainer/rootfs_linux.go
- libcontainer/rootfs_linux_test.go
The motivation behind this change is to provide a flexible mechanism for containers within a Kubernetes cluster to opt out of `FIPS` mode when necessary. This change enables apps to simulate `FIPS` mode being enabled or disabled for testing. Users can control whether apps believe `FIPS` mode is on or off by manipulating `/proc/sys/crypto/fips_enabled`.
> libcontainer: force apps to think fips is enabled/disabled for testing

- docs/isolated-cpu-affinity-transition.md
- features.go
- libcontainer/cgroups/cgroups.go
- libcontainer/cgroups/fs/fs.go
- libcontainer/cgroups/fs2/fs2.go
- libcontainer/cgroups/systemd/v1.go
- libcontainer/cgroups/systemd/v2.go
- libcontainer/container_linux_test.go
- libcontainer/process_linux.go
- libcontainer/process_linux_test.go
- libcontainer/system/kernelparam/lookup.go
- libcontainer/system/kernelparam/lookup_test.go
- tests/integration/exec.bats
- tests/integration/helpers.bash
This handles a corner case when joining a container having all the processes running exclusively on isolated CPU cores to force the kernel to schedule runc process on the first CPU core within the cgroups cpuset.
The introduction of the kernel commit
46a87b3851f0d6eb05e6d83d5c5a30df0eca8f76 has affected this deterministic scheduling behavior by distributing tasks across CPU cores within the cgroups cpuset. Some intensive real-time application are relying on this deterministic behavior and use the first CPU core to run a slow thread while other CPU cores are fully used by real-time threads with SCHED_FIFO policy. Such applications prevents runc process from joining a container when the runc process is randomly scheduled on a CPU core owned by a real-time thread.
* Fixes #3922
> Set temporary single CPU affinity before cgroup cpuset transition.

- .github/workflows/test.yml
- .github/workflows/validate.yml
- README.md
- tests/integration/cgroups.bats
- tests/integration/helpers.bash
- tests/integration/testdata/seccomp_syscall_test1.c
- tests/integration/testdata/seccomp_syscall_test1.json
See <https://actuated.dev/blog/arm-ci-cncf-ampere>. 
Thanks to Alex Ellis, Ampere Computing, and Equinix.
- - -
Host information:
* CPU: aarch64 (ARMv8)
* Kernel: 5.10.201
* Lacks ~`CONFIG_CHECKPOINT_RESTORE`~, `CONFIG_BLK_CGROUP_IOCOST`, etc.
* Cgroup: v2
* OS: Ubuntu 22.04
* Lacks `newuidmap`, `newgidmap`, etc. (still apt-gettable)
* `sshd` is not running
> CI: add actuated-arm64

- .github/workflows/test.yml
- tests/integration/checkpoint.bats
- tests/integration/helpers.bash
This re-enables [previously disabled](https://github.com/opencontainers/runc/pull/4142#issuecomment-1945408382) CRIU tests for actuated-arm64 as they appear to be working just fine now.
The only test we need to skip is criu pre-dump; apparently, [ARM kernel lacks dirty memory tracking feature](https://github.com/checkpoint-restore/criu/issues/1729).
See individual commits for more details.
> ci/actuated: re-enable CRIU tests

- CHANGELOG.md
- libcontainer/README.md
- libcontainer/cgroups/cgroups.go
- libcontainer/cgroups/systemd/common.go
- libcontainer/factory_linux.go
- main.go
This is the last step of refactoring done in #3452, which is needed to use runc/libct v1.2 in kubernetes and other libcontainer users (to avoid massive cilium/ebpf dependency).
----
Commit b6967fa84c26 moved the functionality of managing cgroup devices into a separate package, and decoupled libcontainer/cgroups from it.
Yet, some software (e.g. cadvisor) may need to use libcontainer package, which imports libcontainer/cgroups/devices, thus making it impossible to use libcontainer without bringing in cgroup/devices dependency.
In fact, we only need to manage devices in runc binary, so move the import to main.go.
The need to import libct/cg/dev in order to manage devices is already documented in libcontainer/cgroups. Let's improve that:
- update that documentation;
- add a similar note to …
> libct: decouple libct/cg/devices

- Vagrantfile.fedora
This is a backport of #4256 to release-1.1 branch. Just in case :)
> [1.1] Vagrantfile.fedora: bump Fedora to 39

- .github/workflows/validate.yml
- libcontainer/init_linux.go
Replaces #4253.
* bump golangci/golangci-lint-action to v5
* bump golangci-lint to v1.57
> ci/gha: bump golangci-lint[-action]

- libcontainer/rootfs_linux.go
- libcontainer/rootfs_linux_test.go
This is a backport of https://github.com/opencontainers/runc/pull/4246 to release-1.1. Original description follows.
The motivation behind this change is to provide a flexible mechanism for containers within a Kubernetes cluster to opt out of `FIPS` mode when necessary. This change enables apps to simulate `FIPS` mode being enabled or disabled for testing. Users can control whether apps believe `FIPS` mode is on or off by manipulating `/proc/sys/crypto/fips_enabled`.
> [1.1] libcontainer: force apps to think fips is enabled/disabled for testing

- tests/integration/tty.bats
Earlier, commit fce8dd4d (PR #2692) already increased this timeout from 1 to 5 seconds. Yet, I just saw this timeout being hit in actuated-arm CI ([here](https://github.com/opencontainers/runc/actions/runs/8840455799/job/24275831162?pr=4259#step:16:266), from #4259).
Increase the timeout again, this time from 5 to 50 (100 * 0.5) seconds.
Also, use `wait_pids_gone`, and improve some comments.
> tests/int/tty: increase the timeout

- libcontainer/cgroups/fs/cpu.go
If CPU burst knob is non-existent, the current implementation (added in commit e1584831, PR #3749) still tries to set it again after setting the new CPU quota, which is useless (and we have to ignore ENOENT again).
Fix this.
> libct/cg/fs: don't write cpu_burst twice on ENOENT

- tests/integration/spec.bats
When we run integration test in go 1.22, it got an error:
```
✗ spec validator
(in test file tests/integration/spec.bats, line 37)
`GO111MODULE=auto go get github.com/xeipuuv/gojsonschema' failed
runc spec (status=0):
Cloning into 'runtime-spec'...
HEAD is now at 36852b0 version: release v1.2.0
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
Although we have not supported go 1.22 yet, but I think we should update the spec.bat first.
> [ci] use go mod instead of go get in spec.bats

- Makefile
this allows using a custom version string while building runc without modifying the VERSION file
> allow overriding VERSION value in Makefile

- tests/integration/checkpoint.bats
Since PR #3816 (commit c77aaa3f) the tail of criu log is printed by runc, so there's no need to do the same thing in tests.
Related to #3711.
> tests/int/checkpoint: rm double logging

- Makefile
This is a backport of #4269.
----
this allows using a custom version string while building runc without modifying the VERSION file
(cherry picked from commit 9d9273c926450a2f6f658768e3238b7082ec878d)
> [1.1] allow overriding VERSION value in Makefile

- .github/workflows/validate.yml
Note that github-actions output format is deprecated and no longer supported, and it is also no longer needed since setup-go problem matcher already handles default golangci-lint output format ("colored-line-number").
> ci/gha: bump golangci-lint-action from 5 to 6

- libcontainer/standard_init_linux.go
- libcontainer/system/linux.go
It is not used since commit dac41717.
> Remove unused system.Execv

- libcontainer/init_linux.go
- libcontainer/integration/exec_test.go
- libcontainer/process_linux.go
- libcontainer/setns_init_linux.go
- libcontainer/system/linux.go
- tests/integration/rlimits.bats
Fix: #4195 
Close: #4237 
As @ls-ggg has given the detailed steps to reproduce the issue #4195 , and has given the core reason is that the go runtime will cache the value of rlimit nofile. [1] 
When we are running `runc exec` with nofile limit, runc set it in the parent process, it may cause a race with go runtime init. The race condition is in the time when runc parent process set the container child process's nofile limit just after go runtime init has fetched the nofile limit. [2]
So, we should set nofile limit after `syscall.rlimit.init()` completed.
As @kolyshkin have found an edge case for set nofile rlimit by runc, which is also caused by nofile rlimit cache in go stdlib. Although we have a way to resolve the above get/set race, but if the hard value of nofile rlimit configured in …
> Fix set nofile rlimit error

- .cirrus.yml
I tried to fix it (in https://github.com/opencontainers/runc/pull/4068), but it looks like older CentOS 7 kernel is the ultimate reason why it doesn't work.
So, remove FIXME and add some explanation.
> .cirrus.yml: rm FIXME from rootless fs on CentOS 7

- list.go
This is a backport of #3349 to release-1.1. Original description follows.
----
It is possible that parallel execution of runc list with runc delete will result in runc list fatal failure. Fix this.
Bonus: some refactoring.
Please review with `--ignore-all-space` ("Hide whitespace" checked on GH).
> [1.1] runc list: fix race with runc delete

- libcontainer/criu_linux.go
- libcontainer/integration/checkpoint_test.go
While investigating #4274 I found a few issues and rough edges with our c/r tests.
This, together with https://github.com/checkpoint-restore/criu/pull/2403 (which is already [applied to CRIU package](https://github.com/opencontainers/runc/pull/4276#issuecomment-2104283949) we use) fixes CI failures we see now.
Fixes: #4274.
> fix checkpoint/restore tests on actuated-arm64

- libcontainer/cgroups/fs/cpu.go
- tests/integration/update.bats
The problem/fix is similar to one in #3084/#3090.
A test case (by @ls-ggg) is copied from #4235.
Fixes: #4094.
Closes: #4235.
> libct/cg/fs: fix setting rt_period vs rt_runtime

- libcontainer/cgroups/fs/cpu.go
- tests/integration/update.bats
Backport of #4258 to release-1.1 branch.
The problem/fix is similar to one in #3084/#3090.
A test case (by @ls-ggg) is copied from #4235.
Fixes: #4094.
----
The issue is the same as in commit 1b2adcf but for RT scheduler; the fix is also the same.
Test case by @ls-ggg.
(cherry picked from commit b60079e2e59670b8babd653002d8f469064fb244)
> [1.1] libct/cg/fs: fix setting rt_period vs rt_runtime

- libcontainer/cgroups/devices/v1_test.go
This test panics if userns is detected (such as when run in a rootless docker container) because SetV1 does nothing in this case.
We could fix the panic, but it doesn't make sense to run the test at all.
> libct/cg/dev: fix TestSetV1Allow panic

- libcontainer/init_linux.go
- libcontainer/system/linux.go
- libcontainer/system/rlimit_linux.go
- libcontainer/system/rlimit_linux_go122.go
Go 1.23 tightens access to internal symbols, and even puts runc into
"hall of shame" for using an internal symbol (recently added by commit
da68c8e3). So, while not impossible, it becomes harder to access those
internal symbols, and it is a bad idea in general.
Since Go 1.23 includes https://go.dev/cl/588076,  we can clean the
internal rlimit cache by setting the RLIMIT_NOFILE for ourselves,
essentially disabling the rlimit cache.
Once Go 1.22 is no longer supported, we will remove the go:linkname hack.
> Rlimit cache rework for Go 1.23+

- .github/workflows/validate.yml
CI should not fail and require attention every time a new codespell version is released.
> ci: pin codespell

- tests/integration/scheduler.bats
This test case fails when there's a single CPU. Fix this by adding "require smp".
While at it, document the test case and add a FIXME to maybe remove this test later.
> tests/int/scheduler: require smp

- .github/workflows/validate.yml
- features.go
- utils_linux.go
This is a backport of #4291 and #4301 to release-1.1 branch.
----
./features.go:30: tru ==> through, true
...
./utils_linux.go:147: infront ==> in front
(cherry picked from commit 177c7d4f590dd6efc6fdff139aba728c694e90ad)
----
CI should not fail and require attention every time a new codespell version is released.
(cherry picked from commit b24fc9d2c44bc6e53b9a6ea580e96348181e2f27)
> [1.1] Fix codespell warnings

- .cirrus.yml
CS8 is EOL. As a temp workaround, fix repo URLs to point to vault.
> ci: workaround for centos stream 8 being EOLed

- .cirrus.yml
This is the backport of #4304 to relase-1.1 branch.
----
CS8 is EOL. As a temp workaround, fix repo URLs to point to vault.
(cherry picked from commit 48c4e733f4eaa4ca90c589c1e029e9785ce7a806)
> [1.1] ci: workaround for centos stream 8 being EOLed

- .cirrus.yml
It is past EOL and has been removed from GCE public images.
Fixes: #4302 4302
> ci/cirrus: rm centos stream 8

- .cirrus.yml
Backport of #4307 to release-1.1 branch.
----
It is past EOL and has been removed from GCE public images.
(cherry picked from commit 40bb9c468ea85a577ef501ca0ec15c078dec9488)
> [1.1] ci/cirrus: rm centos stream 8

- .github/workflows/test.yml
- .github/workflows/validate.yml
Let's replace ubuntu-22.04 with ubuntu-24.04 where we can, and keep
ubuntu-20.04 to test cgroup v1 stuff.
Leave ubuntu-22.04 for these jobs only:
- ci/cross-i386 (issue with systemctl restart hang after apt install)
- ~~validate/codespell (pip install won't work)~~ **UPDATE: fixed**
These issues can be addressed separately later.
The only kludge we have to add is enable userns for runc binary being
tested (as userns is disabled by apparmor system-wide by default now,
see [1]).
[1] https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890#unprivileged-user-namespace-restrictions-15
> ci/gha: switch to ubuntu 24.04

- Makefile
Fixes #3906 
Makes `-trimpath` optional by calling it as 
```sh
make runc TRIMPATH=
```
The default mode is unchanged.
Comments in the Makefile make it clear that this may still be required for reproducible builds.
cc @cyphar
> make trimpath optional

- libcontainer/init_linux.go
- libcontainer/system/rlimit_linux.go
- libcontainer/system/rlimit_linux_go122.go
- libcontainer/system/rlimit_stub.go
This is a backport of #4290 to release-1.1 branch.
----
Go 1.23 tightens access to internal symbols, and even puts runc into "hall of shame" for using an internal symbol (recently added by commit da68c8e3). So, while not impossible, it becomes harder to access those internal symbols, and it is a bad idea in general.
Since Go 1.23 includes https://go.dev/cl/588076, we can clean the internal rlimit cache by setting the RLIMIT_NOFILE for ourselves, essentially disabling the rlimit cache.
Once Go 1.22 is no longer supported, we will remove the go:linkname hack.
(cherry picked from commit 584afc675650e87ecc443896f56aed27a0064dc0)
> [1.1] libct/system: ClearRlimitNofileCache for go 1.23

- libcontainer/cgroups/fs2/memory.go
- tests/integration/cgroups.bats
- tests/integration/helpers.bash
- tests/integration/update.bats
- Fixes a few minor issues with integration tests.
- cgroup v2: do not set swap to 0 or unlimited when it's not available.
Fixes #4166
> tests/int: swap-related fixes

- script/keyring_validate.sh
- script/release_sign.sh
I used script/keyring_validate.sh, which gave me this error:
> [*] User cyphar in runc.keyring is not a maintainer!
Apparently, when gnupg 2.4.1+ sees a fresh install (i.e. no ~/.gnupg directory), it configures itself to use keyboxd instead of keyring files, and when just silently ignores options like --keyring and --no-default-keyring, working with keyboxd all the time.
The only way I found to make it not use keyboxd is to set --homedir. Let's do that when we explicitly want a separate keyring.
Similar change is made to script/release_key.sh.
Also, change "--import --import-options=show-only" to "--show-keys" which is a shortcut. When using this, there is no need to protect the default keyring since this command does not read or modify it.
> script/*: fix gpg usage wrt keyboxd

- libcontainer/nsenter/nsexec.c
When I was using `runc --debug` to run a container with user ns, I saw two debug msgs `request stage-0 to map user namespace`, it would make users confused.
At the first I thought runc requested stage-0 two times to map user ns? But after looked into the code, there are two same debug msgs in nsexec:
https://github.com/opencontainers/runc/blob/6b9b2c3d/libcontainer/nsenter/nsexec.c#L899
> fix a debug msg for user ns in nsexec

- libcontainer/cgroups/file.go
- libcontainer/cgroups/file_test.go
- libcontainer/cgroups/fs2/fs2.go
- tests/integration/cgroups.bats
It has been pointed out (in #4182) that some controllers can not accept multiple lines of output at once. In particular, io.max can only set one device at a time.
Practically, the only multi-line resource values we can get come from unified.* -- let's write those line by line.
Add a test case.
Reported-by: Tao Shen <shentaoskyking@gmail.com>
Closes: #4182
> libct/cg: write unified resources line by line

- Vagrantfile.fedora
Get the image directly from Fedora (see https://fedoraproject.org/cloud/download) as F40 is still not available from vagrant (https://app.vagrantup.com/fedora/).
Also, remove the cgroup v2 comment as it is now obsoleted (we also test cgroup v2 on Ubuntu 22.04 and CentOS Stream 9).
Pending #4292 merge.
> Vagrantfile.fedora: bump to F40

- .github/workflows/test.yml
- .github/workflows/validate.yml
- Dockerfile
- README.md
- libcontainer/user/user.go
- tests/integration/spec.bats
This is a partial backport of #4292 and a few other PRs.
High level overview:
- bump some GHA CI deps
- allow runc to be compiled with Go 1.22
- add Go 1.22 to CI matrix
- build release artefacts using Debian 12 and Go 1.22
> [1.1] Support Go 1.22, bump some CI deps

- libcontainer/container_linux.go
- libcontainer/integration/execin_test.go
By definition, every container has only 1 init (i.e. PID 1) process.
Apparently, libcontainer API supported running more than 1 "init", and
two tests mistakenly used it. Of course, the second "init" was not
PID 1, but it was started like init and, I guess, some of the Container fields
were set to wrong values.
Let's not allow that, erroring out if we already have init running.
Fix two cases in libct/int which ran two inits inside a container.
Also, fix a locking issue and remove some code that's not needed.
> libct.Start: fix locking, do not allow a second container init

- libcontainer/nsenter/nsexec.c
This is a backport of #4311 to release-1.1 branch.
----
When I was using `runc --debug` to run a container with user ns, I saw two debug msgs `request stage-0 to map user namespace`, it would make users confused.
At the first I thought runc requested stage-0 two times to map user ns? But after looked into the code, there are two same debug msgs in nsexec:
https://github.com/opencontainers/runc/blob/6b9b2c3d/libcontainer/nsenter/nsexec.c#L899 
(cherry picked from commit 24c2d28d1ff89b98f14922ec801b5fadad09471d)
> [1.1] fix a debug msg for user ns in nsexec

- script/keyring_validate.sh
- script/release_sign.sh
This is a backport of #4189 to release-1.1 branch.
----
I used script/keyring_validate.sh, which gave me this error:
> [*] User cyphar in runc.keyring is not a maintainer!
Apparently, when gnupg 2.4.1+ sees a fresh install (i.e. no ~/.gnupg directory), it configures itself to use keyboxd instead of keyring files, and when just silently ignores options like --keyring and --no-default-keyring, working with keyboxd all the time.
The only way I found to make it not use keyboxd is to set --homedir. Let's do that when we explicitly want a separate keyring.
Similar change is made to script/release_key.sh.
Also, change "--import --import-options=show-only" to "--show-keys" which is a shortcut. When using this, there is no need to protect the default keyring since this command does not read or …
> [1.1] script/*: fix gpg usage wrt keyboxd

- exec.go
- script/keyring_validate.sh
> Some nits I found from older PRs

- CHANGELOG.md
Please see https://github.com/opencontainers/runc/pull/4321#discussion_r1642069541
I think most of us think that the timeline order and the version order in `CHANGELOG.md` are ok, but if we are more like the version order, I can change it.
We should change it before we do the release `v1.2.0-rc.2`.
> Put the changelog of v1.1.13 after v1.2.0-rc.1

- EMERITUS.md
- MAINTAINERS
- MAINTAINERS_GUIDE.md
I talked to Michael, he says he is stepping down as a maintainer, being
busy with other stuff.
Thank you for all the hard work that you did!
----
Since Michael Crosby is stepping down, and we don't want to nominate
someone else to be a chief maintainer, let's remove the role.
> MAINTAINERS: move crosbymichael to EMERITUS; remove chief maintainer role

- libcontainer/container_linux.go
There is a small possibility error after the exec fifo file has created, so we should try to delete it if we get an error from `createExecFifo`.
This is a possible bug discovered when doing code review, I think we have not meet it in daily usage.
> Try to delete exec fifo file when failure in creation

- contrib/cmd/seccompagent/seccompagent.go
- contrib/cmd/seccompagent/unsupported.go
- libcontainer/apparmor/apparmor_unsupported.go
- libcontainer/capabilities/capabilities.go
- libcontainer/capabilities/capabilities_unsupported.go
- libcontainer/configs/cgroup_unsupported.go
- libcontainer/configs/configs_fuzzer.go
- libcontainer/configs/mount_unsupported.go
- libcontainer/configs/namespaces_syscall.go
- libcontainer/configs/namespaces_syscall_unsupported.go
- libcontainer/configs/namespaces_unsupported.go
- libcontainer/devices/device_unix.go
- libcontainer/devices/device_unix_test.go
- libcontainer/dmz/dmz_linux.go
- libcontainer/dmz/dmz_unsupported.go
- libcontainer/integration/seccomp_test.go
- libcontainer/nsenter/nsenter.go
- libcontainer/nsenter/nsenter_gccgo.go
- libcontainer/seccomp/patchbpf/enosys_linux.go
- libcontainer/seccomp/patchbpf/enosys_linux_test.go
- libcontainer/seccomp/patchbpf/enosys_unsupported.go
- libcontainer/seccomp/seccomp_linux.go
- libcontainer/seccomp/seccomp_unsupported.go
- libcontainer/system/linux.go
- libcontainer/userns/userns_fuzzer.go
- libcontainer/userns/userns_unsupported.go
- libcontainer/utils/utils_unix.go
Removed pre-go1.17 build-tags with go fix;
go fix -mod=readonly ./...
> remove pre-go1.17 build-tags

- libcontainer/userns/userns.go
- libcontainer/userns/userns_linux.go
- libcontainer/userns/userns_linux_fuzzer.go
- libcontainer/userns/userns_unsupported.go
This was a poor decision on my side; 4316df8b53cce2933d7f0f3cf4bf87da67459835 (https://github.com/opencontainers/runc/pull/2850)
moved this utility to a separate package, and split the exported function
from the implementation (and stubs). Out of convenience, I used an alias
for the latter part, but there's two downsides to that;
- `RunningInUserNS` being an exported var means that (technically) it can
be replaced by other code; perhaps that's a "feature", but not one we
intended it to be used for.
- `RunningInUserNS` being implemented through a var / alias means it's
also documented as such on [pkg.go.dev], which is confusing.
This patch changes it to a regular function, acting as a wrapper for
the underlying implementations. While at it, also slightly touching
up the GoDoc to describe …
> libct/userns: assorted (godoc) improvements

- CHANGELOG.md
Remove changes that are already reflected in v1.1.13 changelog:
- rlimit_nofile fix;
- rt_period vs rt_runtime fix;
- gpg vs keyboxd fix;
- nsexec debug log fix;
- fips faking;
- vagrant Fedora 39 bump;
- golangci-lint bump;
- x/net bump;
- centos stream 8 removal;
- codespell ci fixes;
- VERSION in Makefile (thx @rata)
Compact some of the entries that are related (e.g. about actuated-ci).
> CHANGELOG.md: dedup v1.2.0-rc.2 notes

- .cirrus.yml
- remove CentOS 7 as it is EOL, together with centos-7 specific tricks.
- add back a RHEL 8 clone (CentOS Stream 8 was removed by commit 40bb9c468ea85a) -- Almalinux 8.
- switch from CentOS Stream 9 to Almalinux 9, mostly for simplicity.
Closes: #4333 
Fixes: #4302
> ci/cirrus: rm CentOS 7; add Almalinux 8/9

- .cirrus.yml
(Backport of #4335.)
Remove CentOS 7 as it is EOL.
Add back RHEL 8 clone (CentOS Stream 8 was removed by commit 40bb9c468ea85a).
Switch from CentOS Stream 9 to Almalinux 9.
> [1.1] ci/cirrus: switch from CentOS to Almalinux

- libcontainer/container_linux.go
- libcontainer/rootfs_linux.go
- libcontainer/rootfs_linux_test.go
(Backport of a patch from #3985.)
<hr>
(This is a cherry-pick of cdff09ab875159d004035990c0d45e8bdf20ed35 but modified so that changes like 8e8b136c4923a and a60933bb24565 don't also need to be backported. Ideally we would backport the entire "remove all mount logic from nsexec" series, but that would be a bit too much.)
Our previous test for whether we can mount on top of /proc incorrectly assumed that it would only be called with bind-mount sources. This meant that having a non bind-mount entry for a pseudo-filesystem (like overlayfs) with a dummy source set to /proc on the host would let you bypass the check, which could easily lead to security issues.
In addition, the check should be applied more uniformly to all mount types, so fix that as well. And add some tests for some of the …
> [1.1] rootfs: fix 'can we mount on top of /proc' check

- .github/workflows/validate.yml
Add a CI job to ensure go fix produces no result. Quoting `go doc cmd/fix`:
> Fix finds Go programs that use old APIs and rewrites them to use newer
> ones. After you update to a new Go release, fix helps make the
> necessary changes to your programs.
As expected, the job fails before #4329 is merged.
> ci/gha: add go-fix job

- libcontainer/init_linux.go
- libcontainer/seccomp/patchbpf/enosys_linux.go
- libcontainer/seccomp/seccomp_linux.go
- libcontainer/seccomp/seccomp_unsupported.go
- tests/integration/seccomp-notify.bats
Fix #4328 
This reverts commit 20b95f23ca33cb1751ee0b5318e1d5f3676032c6.
> Conflicts:
>       libcontainer/init_linux.go
For:
- #4328
> Revert "libcontainer: seccomp: pass around *os.File for notifyfd"

- README.md
I had to build under alpine (musl), so I documented it. Hopefully this is helpful for others.
> document how to build under alpine

- libcontainer/criu_linux.go
- libcontainer/rootfs_linux.go
- libcontainer/utils/utils_unix.go
The logic for how we create mountpoints is spread over each mountpoint preparation function, when in reality the behaviour is pretty uniform with only a handful of exceptions. So just move it all to one function that is easier to understand.
> rootfs: consolidate mountpoint creation logic

- libcontainer/integration/seccomp_test.go
In all the three cases, we check that the program returned non-zero exit code. This can be done in a much simpler manner.
> libct/int/seccomp_test: simplify exit code checks

- tests/integration/helpers.bash
A kernel bug which resulted in cpu.max.burst value read which is 1000
times smaller than it should be has recently been fixed (see [1]).
Adapt the test so it works with either broken or fixed kernel.
[1]: https://lore.kernel.org/all/20240424132438.514720-1-serein.chengyu@huawei.com/
Fixes: #4373
🔔 **For CI, see #4375.**
> Fix cpu burst test failure on newer kernels

- .cirrus.yml
It seems that there are only two latest stable versions go in the content downloaded from `https://go.dev/dl/?mode=json`, so if we can't update the go's version in time, it will cause CI failure.
Please see: https://github.com/opencontainers/runc/pull/4374#issuecomment-2287882511
The relate error logs:
```
PREFIX="https://go.dev/dl/"
eval $(curl -fsSL "${PREFIX}?mode=json" | jq -r  --arg Ver "$GO_VERSION" '.[] | select(.version | startswith("go\($Ver)")) | .files[] | select(.os == "linux" and .arch == "amd64" and .kind == "archive") | "filename=\"" + .filename + "\""')
curl -fsSL "$PREFIX$filename" | tar Cxz /usr/local
gzip: stdin: not in gzip format
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
curl: (23) Failed writing body (360 != 1408)
```
> [CI] ensure we can download the specific version's go

- .cirrus.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
- go.mod
- libcontainer/cgroups/fs/blkio_test.go
- libcontainer/configs/config_test.go
As of #4290, we are already prepared, so the only things left to do are:
- drop Go 1.21;
- add Go 1.23;
- for a few jobs that were using Go 1.21, switch to 1.22;
Also, bump go to 1.22 in go.mod.
🔔 For CI, see #4375.
> Add Go 1.23, drop 1.21

- Makefile
- README.md
This reverts commit 9d9273c926450a2f6f658768e3238b7082ec878d. (PR #4270 and #4269) and adds a VERSION_EXTRA make variable (that is not read from env variables) to append a custom suffix for the version.
The reverted commit broke the build for several other projects (see comments here: https://github.com/opencontainers/runc/pull/4270, after the merge) and we don't really need this to be able to set the version without changing the file.
With this commit reverted, we can still run:
make VERSION="1.2.3"
and it just works. It doesn't take it from an env variable, but that is what broke all the other projects (VERSION is just too generic as an env var, especially for a project like runc that is embedded in many others).
Also, to simplify just adding a custom suffix to the version, a …
> Revert "allow overriding VERSION value in Makefile" and add EXTRA_VERSION

- .github/workflows/test.yml
- .github/workflows/validate.yml
The sole reason is to simplify branch protection rules, requiring just these to be passed.
~~Currently a draft, pending #4374 #4360 merge.~~
> ci/gha: add all-done jobs

- Makefile
- README.md
As discussed, backport of #4370 for 1.1.
@cpuguy83 it would be great if you can test this in your setup when you are back.
> [1.1] Revert "allow overriding VERSION value in Makefile" and add EXTRA_VERSION

- Makefile
We recently switched VERSION to be read from env vars (#4270). This
broke several projects, as they were building runc and using a `VERSION`
env var for, e.g. the containerd version.
When fixing that in #4370, we discussed to consider doing the same for
these variables too
(https://github.com/opencontainers/runc/pull/4370#pullrequestreview-2240030944).
Let's stop reading them from env vars, as it is very easy to do it by
mistake (e.g. compile runc and define a COMMIT env var, not to override
the commit shown in `runc --version`) and users that want can still
override them if they want to. For example, with:
make EXTRA_BUILDTAGS=runc_nodmz
> Makefile: Don't read COMMIT, BUILDTAGS, EXTRA_BUILDTAGS from env vars

- libcontainer/seccomp/patchbpf/enosys_linux.go
- libcontainer/seccomp/patchbpf/enosys_linux_test.go
*Backport of #4219 and #3635.*
<hr>
It turns out that on ppc64le (at least), Docker doesn't include any
architectures in the list of allowed architectures. libseccomp
interprets this as "just include the default architecture" but patchbpf
would return a no-op ENOSYS stub, which would lead to the exact issues
that commit https://github.com/opencontainers/runc/commit/7a8d7162f9d72f20d83eaa36aeb5426deecd58f2 ("seccomp: prepend -ENOSYS stub to all
filters") fixed for other architectures.
So, just always include the running architecture in the list. There's
no real downside.
Ref: https://bugzilla.suse.com/show_bug.cgi?id=1192051#c6
Reported-by: Fabian Vogt [fvogt@suse.com](mailto:fvogt@suse.com)
Signed-off-by: Aleksa Sarai [cyphar@cyphar.com](mailto:cyphar@cyphar.com)
> [1.1] seccomp: patchbpf: always include native architecture in stub

- libcontainer/container_linux.go
- libcontainer/init_linux.go
- libcontainer/state_linux.go
- tests/integration/kill.bats
`signalAllProcesses()` depends on the cgroup and is expected to fail when runc is running in rootless without an access to the cgroup.
When `RootlessCgroups` is set to `true`, runc just ignores the error from `signalAllProcesses` and may leak some processes running. (See the comments in this PR)
In the future, runc should walk the process tree to avoid such a leak.
Note that `RootlessCgroups` is a misnomer; it is set to `false` despite the name when cgroup v2 delegation is configured.
This is expected to be renamed in a separate commit.
Fix #4394
> libct: Signal: honor RootlessCgroups

- libcontainer/seccomp/patchbpf/enosys_linux.go
- libcontainer/utils/utils.go
It is available since Go 1.21 and is defined during compile time (i.e. based on GOARCH during build).
> libct/seccomp/patchbpf: use binary.NativeEndian

- go.mod
Go since 1.21 enforces the "go" version in go.mod as a minimum version[1]. As documented in the 1.2.0-rc.1 release notes, 1.22.4 is needed.
Let's enforce it.
[1]: https://go.dev/doc/toolchain
---
@kolyshkin @lifubang PTAL
> go.mod: Force 1.22.4 as min go version

- .github/workflows/test.yml
mig4/setup-bats is now unmaintained(last commit in Sep 2021). bats-core/bats-action can be used as a replacement maintained by the bats-core team.
this also removes deprecated notices while runnig the ci workflow
> ci: update to setup bats action from bats-core

- libcontainer/cgroups/cgroups.go
- libcontainer/cgroups/fs/fs.go
- libcontainer/cgroups/fs2/fs2.go
- libcontainer/configs/validate/rootless.go
- libcontainer/process_linux.go
- libcontainer/specconv/spec_linux.go
- tests/integration/create.bats
- tests/integration/helpers.bash
Shared pid namespace means `runc kill` (or `runc delete -f`) have to
kill all container processes, not just init. To do so, it needs a cgroup
to read the PIDs from.
If there is no cgroup, processes will be leaked, and so such
configuration is bad and should not be allowed. To keep backward
compatibility, though, let's merely warn about this for now.
Alas, the only way to know if cgroup access is available is by returning
an error from `Manager.Apply`. Amend fs cgroup managers to do so (systemd
doesn't need it, since v1 can't work with rootless, and cgroup v2 does
not have a special rootless case).
Related to #4394, #4395.
> runc create/run: warn on rootless + shared pidns + no cgroup

- libcontainer/container_linux.go
- libcontainer/error.go
- libcontainer/init_linux.go
For some rootless container, runc has no access to cgroup, But the container is still running. So we should return the `ErrNotRunning` and `ErrCgroupNotExist` error seperatlly.
Follow up of #4395, please see https://github.com/opencontainers/runc/pull/4395#discussion_r1757069353
> Add ErrCgroupNotExist

- .github/workflows/test.yml
- bats-core/bats-action installs a few support libraries by default which are not used by runc. Disable the installation, which will remove `/usr/bin/tar: Permission denied errors`. 
Ref: https://github.com/opencontainers/runc/actions/runs/11019452323/job/30602046848#step:13:59
Sample run: https://github.com/akhilerm/runc/actions/runs/11026954586/job/30624383166#step:13:1
- update bats-action to v2.1.1 that has support for cache key with multiple architectures
Fixes #4411
> ci: update bats-action to v2.1.1

- libcontainer/cgroups/fs/cpuacct.go
- libcontainer/cgroups/fs/cpuacct_test.go
- libcontainer/cgroups/fs/util_test.go
Initially, this was a commit to switch from `strings.Fields` to
`strings.SplitN` in getCpuUsageBreakdown, since `strings.Fields`
was probably slower than `strings.SplitN` in some old Go versions.
Afterwards, `strings.Cut` was also considered for potential
speed improvements.
After writing a benchmark test, we learned that:
- `strings.Fields` performance is now adequate;
- `strings.SplitN` is slower than `strings.Fields`;
- `strings.Cut` had <5% performance gain from `strings.Fields`;
So, remove the TODO and keep the benchmark test.
The following are benchmark differences using `strings.Fields`,
`strings.SplitN`, and `strings.Cut`.
Below, you can find the benchmark differences.
```bash
$ go test -run 1234 -bench . -benchmem -count 8 . > strings.Fields
$ vim cpuacct.go 
$ go test -run 1234 …
```
> libcontainer/cgroups/fs: remove todo since strings.Fields performs well 

- tests/integration/cgroups.bats
This is a backport of https://github.com/opencontainers/runc/pull/4020 for 1.1.
When trying to create a release for 1.1, CI starting failing. This PR in main fixed it, so I'm backporting it.
> [1.1]: Increase memory.max in cgroups.bats

- CHANGELOG.md
- libcontainer/rootfs_linux.go
_This is a backport of #4417 to release-1.1._
----
When preparing to mount container root, we need to make its parent mount private (i.e. disable propagation), otherwise the new in-container mounts are leaked to the host.
To find a parent mount, we use to read mountinfo and find the longest entry which can be a parent of the container root directory.
Unfortunately, due to kernel bug in all Linux kernels older than v5.8 (see [1], [2]), sometimes mountinfo can't be read in its entirety. In this case, getParentMount may occasionally return a wrong parent mount.
As a result, we do not change the mount propagation to private, and container mounts are leaked.
Alas, we can not fix the kernel, and reading mountinfo a few times to ensure its consistency (like it's done in, say, Kubernetes) does …
> [1.1] runc run: fix mount leak

- libcontainer/rootfs_linux.go
When preparing to mount container root, we need to make its parent mount private (i.e. disable mount propagation), otherwise the new in-container mounts are leaked to the host.
To find a parent mount, we use to read mountinfo and find the longest entry which can be a parent of the container root directory.
Unfortunately, due to kernel bug in all Linux kernels older than v5.8 (see [1], [2]), sometimes mountinfo can't be read in its entirety. In this case, getParentMount may occasionally return a wrong parent mount.
As a result, we do not change the mount propagation to private, and container mounts are leaked.
Alas, we can not fix the kernel, and reading mountinfo a few times to ensure its consistency (like it's done in, say, Kubernetes) does not look like a good solution for performance …
> runc run: fix mount leak

- README.md
In the readme there are two statements
1. the minimum version of go for runc is v1.21
2. if you use go v1.22 make sure it's newer than 1.22.4 due to a bug
when i use go v1.21 in Dockerfile for testing I got error
```
+ exec make localunittest TESTFLAGS=
rm -f libcontainer/dmz/binary/runc-dmz
go generate -tags "seccomp urfave_cli_no_docs" ./libcontainer/dmz
go: go.mod requires go >= 1.22 (running go 1.21.13; GOTOOLCHAIN=local)
make: *** [Makefile:116: runc-dmz] Error 1
make: *** [Makefile:161: unittest] Error 2
```
but with go v1.22 and v1.23 it was ok. so i change minimum version to 1.22.4 and delete the warning
> change go minimum version in README

- exec.go
- libcontainer/cgroups/fs/memory.go
- libcontainer/cgroups/systemd/cpuset.go
- libcontainer/init_linux.go
- libcontainer/utils/utils.go
there are some cases in the code that  this pattern used "strings.SplitN(expression, pattern, 2)"
as we see in #4403 strings.Cut has better performance than strings.SplitN.
i changed some of these cases (for rest of them i wasn't sure that it break the functionality or not)
> replace strings.SplitN with strings.Cut

- contrib/cmd/memfd-bind/README.md
- contrib/cmd/memfd-bind/memfd-bind@.service
The example of starting memfd-bind via systemd in README did not work
for me (Fedora 40, systemd 255):
```console    
Invalid unit name "memfd-bind@/usr/bin/runc" escaped as "memfd-bind@-usr-bin-runc" (maybe you should use systemd-escape?).
○ memfd-bind@-usr-bin-runc.service
Loaded: bad-setting (Reason: Unit memfd-bind@-usr-bin-runc.service has a bad unit file setting.)
Active: inactive (dead)
Docs: https://github.com/opencontainers/runc
```
So, let's use systemd-escape -p ("path") in the README example,
and use %f in the systemd unit file to prepend the slash to the
filename.
> memfd-bind: fixup systemd unit file and README

- libcontainer/dmz/cloned_binary_linux.go
Though creates a classic temp file for runc binary is the last fallback method of `CloneBinary`, we should also fix the error of it.
> dmz: cloned binary: set +x permissions when creating regular tmpfile

- libcontainer/nsenter/nsenter_test.go
- libcontainer/nsenter/nsexec.c
- libcontainer/process_linux.go
This initWaiter logic was introduced by commit 4ecff8d9 (PR #2855), but since the logic of /proc/self/exe was moved out of runc init in commit 0e9a335 (PR #3987), this seems unnecessary to have initWaiter.
Remove it.
This essentially reverts commit 4ecff8d9.
> libct: rm initWaiter

- tests/integration/update.bats
This test case is frequently hanging recently. Might be caused by a recent kernel update from 5.14.0-427.33.1.el9_4.x86_64 to 5.14.0-427.37.1.el9_4.x86_64.
Could not reproduce locally.
Let's skip it for now.
Fixes: #4454
> tests/int: skip "update memory vs CheckBeforeUpdate" on EL9

- libcontainer/capabilities/capabilities.go
We are not really interested in the capabilities of the current process, so there is no need to load those.
This results in some performance improvement since now the capability package don't have to parse `/proc/self/status`.
> libct/cap: no need to load capabilities

- libcontainer/dmz/cloned_binary_linux.go
- libcontainer/dmz/overlayfs_linux.go
- libcontainer/utils/utils_unix.go
- tests/integration/helpers.bash
- tests/integration/run.bats
Commit https://github.com/opencontainers/runc/commit/b999376fb237195265081a8b8ba3fd3bd6ef8c2c ("nsenter: cloned_binary: remove bindfd logic
entirely") removed the read-only bind-mount logic from our cloned binary
code because it wasn't really safe because a container with
CAP_SYS_ADMIN could remove the MS_RDONLY bit and get write access to
/proc/self/exe (even with user namespaces this could've been an issue
because it's not clear if the flags are locked).
However, copying a binary does seem to have a minor performance impact.
The only way to have no performance impact would be for the kernel to
block these write attempts, but barring that we could try to reduce the
overhead by coming up with a mount that cannot have it's read-only bits
cleared.
The "simplest" solution is to create a …
> dmz: use overlayfs to write-protect /proc/self/exe if possible

- libcontainer/container_linux.go
Fixes: #4294
There is a race situation when we are opening a file, if there is a
small fd was closed at that time, maybe it will be reused by safeExe.
Because of Go stdlib fds shuffling bug, if the fd of safeExe is too
small, go stdlib will dup3 it to another fd, or dup3 a other fd to this
fd, then it will cause the fd type cmd.Path refers to a random path,
and it can lead to an error "permission denied" when starting the process.
Please see #4294 and <https://github.com/golang/go/issues/61751>.
So we should not use the original fd of safeExe, but use the fd after
shuffled by Go stdlib. Because Go stdlib will guarantee this fd refers to
the correct file.
Signed-off-by: lfbzhm <lifubang@acmcoder.com>
> fix an error caused by fd reuse race when starting runc init

- libcontainer/nsenter/nsexec.c
- tests/integration/userns.bats
Containerd pre-creates userns and netns before calling runc, which
results in the current code not working when SELinux is enabled,
resulting in the following error:
> runc create failed: unable to start container process: error during
container init: error mounting "mqueue" to rootfs at "/dev/mqueue":
setxattr /path/to/rootfs/dev/mqueue: operation not permitted
The solution is to become root in the user namespace right after
we join it.
Fixes #4466.
Co-authored-by: Wei Fu <fuweid89@gmail.com>
Co-authored-by: Kir Kolyshkin <kolyshkin@gmail.com>
Co-authored-by: Aleksa Sarai <cyphar@cyphar.com>
> libct/nsenter: become root after joining userns

- libcontainer/integration/bench_test.go
- libcontainer/integration/template_test.go
- libcontainer/integration/utils_test.go
_Related to: #3181_ 
This is a benchmark which checks how fast we can execute /bin/true
inside a container.
Results from my machine are below. As you can see, in default setup
about 70% of exec time is spent for CVE-2019-5736 (copying runc binary),
and using either `RUNC_DMZ=true` or `memfd-bind` helps a lot.
This can also be used for profiling (using -test.cpuprofile option).
```console
[kir@kir-tp1 integration]$ sudo ./integration.test -test.run xxx -test.v -test.benchtime 5s -test.count 5 -test.bench . .
goos: linux
goarch: amd64
pkg: github.com/opencontainers/runc/libcontainer/integration
cpu: 12th Gen Intel(R) Core(TM) i7-12800H
BenchmarkExecTrue
BenchmarkExecTrue-20                 327          24475677 ns/op
BenchmarkExecTrue-20                 244          25242718 ns/op …
```
> libct/int: add exec benchmark

- libcontainer/nsenter/nsexec.c
- tests/integration/userns.bats
Backport of #4473 to release1.2. Original description follows.
PS I checked the added test case in #4476.
----
Containerd pre-creates userns and netns before calling runc, which
results in the current code not working when SELinux is enabled,
resulting in the following error:
runc create failed: unable to start container process: error during
container init: error mounting "mqueue" to rootfs at "/dev/mqueue":
setxattr /path/to/rootfs/dev/mqueue: operation not permitted
The solution is to become root in the user namespace right after
we join it.
Fixes #4466.
Co-authored-by: Wei Fu fuweid89@gmail.com
Co-authored-by: Kir Kolyshkin kolyshkin@gmail.com
Co-authored-by: Aleksa Sarai cyphar@cyphar.com
Signed-off-by: lifubang lifubang@acmcoder.com
> [1.2] libct/nsenter: become root after joining userns 

- contrib/cmd/memfd-bind/README.md
- docs/cgroup-v2.md
- docs/terminals.md
- tests/integration/README.md
Remove prompt symbols (`$`, `%`) for ease of copy-pasting
> docs: remove prompt symbols from shell snippets

- CHANGELOG.md
Those are taken from commit bc20cb44 in release-1.1 branch.
I did not try to dedup the entries.
> CHANGELOG: add (forward-port) v1.1.15 changes

- libcontainer/criu_linux.go
_This is a carry of #4431._
Fixes: #4381.
When the criu version does not meet the requirements, execution will be terminated directly to prevent unpredictable behavior.
> Terminate execution for criu that does not meet version requirements

- CHANGELOG.md
_Backport of #4489 to release-1.1 branch._
Those are taken from commit bc20cb44.
> [1.2] CHANGELOG: add (forward-port) v1.1.15 changes

- libcontainer/cgroups/utils.go
- libcontainer/cgroups/utils_test.go
This allows to do
runc update $ID --memory=-1 --memory-swap=$VAL
for cgroup v2, i.e. set memory to unlimited and swap to a specific value.
This was not possible because ConvertMemorySwapToCgroupV2Value rejected memory=-1 ("unlimited"). In a hindsight, it was a mistake, because if memory limit is unlimited, we should treat memory+swap limit as just swap limit.
While at it, improve some comments in the code, and revise the unit test.
Fixes: c86be8a2 ("cgroupv2: fix setting MemorySwap") aka #2288
> runc update: fix updating swap for cgroup v2

- libcontainer/cgroups/utils.go
- libcontainer/cgroups/utils_test.go
Cherry-pick (clean):
- https://github.com/opencontainers/runc/pull/4357
> [1.2] runc update: fix updating swap for cgroup v2

- libcontainer/process.go
- libcontainer/setns_init_linux.go
- libcontainer/standard_init_linux.go
- script/check-config.sh
_This is a backport of #4490 to release-1.2 branch._
---
Tiny nits needed after merging #4482 and #4448. Easy to review.
> [1.2] Post overlay addition and dmz removal nits

- contrib/cmd/memfd-bind/README.md
- docs/cgroup-v2.md
- docs/terminals.md
- tests/integration/README.md
Backports https://github.com/opencontainers/runc/pull/4484 to 1.2 branch
Remove prompt symbols (`$`, `%`) for ease of copy-pasting
(cherry picked from commit c8f5d033c26265ae08bc472e1c5f6c7f326fb668)
> [1.2] docs: remove prompt symbols from shell snippets

- Vagrantfile.fedora
> CI: bump Fedora 40 -> 41

- .cirrus.yml
https://github.com/hashicorp/vagrant/pull/13532
> ci: temporary set vagrant to 2.4.1-1

- README.md
- contrib/cmd/memfd-bind/README.md
- libcontainer/dmz/overlayfs_linux.go
In addition to some documentation fixes, fix the `xino` dmesg log issue.
<hr>
If /run/runc and /usr/bin are on different filesystems, overlayfs may
enable the xino feature which results in the following log message:
kernel: overlayfs: "xino" feature enabled using 3 upper inode bits.
Each time we have to protect /proc/self/exe. So disable xino to remove
the log message (we don't care about the inode numbers of the files
anyway).
Fixes #4508
Closes #4506
> dmz: overlay: minor fixups

- EMERITUS.md
- MAINTAINERS
Daniel @dqminh and Qiang @hqhq are stepping down as runc maintainers,
not being able to contribute as much as they used to.
Thank you for all the hard work!
<hr>
Merging this PR requires a 2/3 vote (6) of everyone in the MAINTAINERS file:
> MAINTAINERS: move dqminh and hqhq to EMERITUS

- Vagrantfile.fedora
> [1.2] CI: bump Fedora 40 -> 41

- .cirrus.yml
This reverts commit 5000f1697c7562e8fbc725da99e457949d4db1c6.
Because vagrant v2.4.3 has out, and this version includes the bug patch mentioned in #4514.
Please see: https://github.com/hashicorp/vagrant/blob/v2.4.3/CHANGELOG.md
> Revert "Temporary set vagrant to 2.4.1-1"

- libcontainer/cgroups/utils_test.go
This is a unit test for the similar issue of #4518.
> libct/cg: add test for remove a non-existent dir in a ro mount point

- libcontainer/cgroups/utils.go
- libcontainer/cgroups/utils_test.go
Backport: 
- #4523
- https://github.com/opencontainers/runc/pull/4526
----
This is an alternative to #4520.
----
An issue with runc 1.2.0 was reported to buildkit and then here (#4518),
in which `runc delete` returns with an error, with the log saying:
> unable to destroy container: unable to remove container's cgroup: open /sys/fs/cgroup/snschvixiy3s74w74fjantrdg: no such file or directory
Apparently, what happens is runc is running with no cgroup access
(because /sys/fs/cgroup is mounted read-only). In this case error to
create a cgroup path (in runc create/run) is ignored, but cgroup removal
(in runc delete) is not.
This is caused by commit d3d7f7d, which changes the cgroup removal
logic in `RemovePath`, and contains a bug. In the current code, if the
initial rmdir has failed (in this …
> [1.2] runc delete: fix for rootless cgroup + ro cgroupfs

- README.md
- contrib/cmd/memfd-bind/README.md
- libcontainer/dmz/overlayfs_linux.go
Backport: #4509 and #4525
----
In addition to some documentation fixes, fix the `xino` dmesg log issue.
<hr>
If /run/runc and /usr/bin are on different filesystems, overlayfs may
enable the xino feature which results in the following log message:
kernel: overlayfs: "xino" feature enabled using 3 upper inode bits.
Each time we have to protect /proc/self/exe. So disable xino to remove
the log message (we don't care about the inode numbers of the files
anyway).
Fixes #4508
Closes #4506
----
Arguably these docs should live elsewhere (especially if we plan to
remove memfd-bind in the future), but for now this is the only place
that fully explains this issue.
Suggested-by: Rodrigo Campos <rodrigoca@microsoft.com>
Signed-off-by: Aleksa Sarai …
> [1.2] dmz: overlay: minor fixups

- Makefile
- libcontainer/nsenter/nsexec.c
- tests/integration/userns.bats
If we are running with privileges and are asked to join an externally
created user namespaces as well as some other namespace that was *not*
created underneath said user namespace, the approach we added in commit
https://github.com/opencontainers/runc/commit/2cd9c31b995cff313c828dafbfeea082c7318c3f ("nsenter: guarantee correct user namespace ordering")
doesn't work.
While in theory you would want all externally created namespaces to be
sane, it seems that some tools really do create unrelated namespaces and
ask us to join them. Luckily we can just loosely copy what nsenter(1)
appears to do -- we first try to join any namespaces we can (with host
root privileges), then we join any user namespaces, and then we join any
remaining namespaces (now with the user namespace's privileges).
Note …
> nsenter: implement a two-stage join for setns

- libcontainer/cgroups/devices/ebpf_linux.go
In v0.13.0, cilium/ebpf stopped supporting setting BPF_F_REPLACE as an
explicit flag and instead requires us to use link.Anchor to specify
where the program should be attached.
Commit https://github.com/opencontainers/runc/commit/216175a9ca84cac30a570049a98e948f60c5f1a4 ("Upgrade Cilium's eBPF library version to 0.16")
did update this correctly for the actual attaching logic, but when
checking for kernel support we still passed BPF_F_REPLACE. This would
result in a generic error being returned, which our feature-support
checking logic would treat as being an error the indicates that
BPF_F_REPLACE *is* supported, resulting in a regression on pre-5.6
kernels.
It turns out that our debug logging saying that this unexpected error
was happening was being output as a result of this change, but …
> cgroups: ebpf: use link.Anchor to check for BPF_F_REPLACE support

- libcontainer/cgroups/devices/ebpf_linux.go
Backport of #4548. ~~(Draft until merged.)~~
<hr>
In v0.13.0, cilium/ebpf stopped supporting setting BPF_F_REPLACE as an
explicit flag and instead requires us to use link.Anchor to specify
where the program should be attached.
Commit https://github.com/opencontainers/runc/commit/216175a9ca84cac30a570049a98e948f60c5f1a4 ("Upgrade Cilium's eBPF library version to 0.16")
did update this correctly for the actual attaching logic, but when
checking for kernel support we still passed BPF_F_REPLACE. This would
result in a generic error being returned, which our feature-support
checking logic would treat as being an error the indicates that
BPF_F_REPLACE *is* supported, resulting in a regression on pre-5.6
kernels.
It turns out that our debug logging saying that this unexpected error
was happening …
> [1.2] cgroups: ebpf: use link.Anchor to check for BPF_F_REPLACE support

- .github/workflows/validate.yml
- README.md
- checkpoint.go
- libcontainer/criu_disabled_linux.go
- libcontainer/criu_linux.go
- libcontainer/criu_opts_linux.go
This allows to make a 17% smaller runc binary by not compiling in
checkpoint/restore support.   
It turns out that google.golang.org/protobuf package, used by go-criu,
is quite big, and go linker can't drop unused stuff if reflection is
used anywhere in the code.
Currently there's no alternative to using protobuf in go-criu, and since
not all users use c/r, let's provide them an option for a smaller
binary.
For the reference, here's top10 biggest vendored packages, as reported
by gsa[1]:
$ gsa runc | grep vendor | head
│ 8.59%   │ google.golang.org/protobuf                  │ 1.3 MB │ vendor    │
│ 5.76%   │ github.com/opencontainers/runc              │ 865 kB │ vendor    │
│ 4.05%   │ github.com/cilium/ebpf                      │ 608 kB │ vendor    │
│ 2.86%   │ github.com/godbus/dbus/v5 …
> Add `runc_nocriu` build tag to opt out of c/r

- libcontainer/cgroups/devices/devicefilter_test.go
- libcontainer/specconv/spec_linux.go
Since v1.2.0 was released, a number of users complained that the removal of tun/tap device access from the default device ruleset is causing a regression in their workloads.
Additionally, it seems that some upper-level orchestration tools (Docker Swarm, Kubernetes) makes it either impossible or impractical to supply additional device rules.
While it's probably not right to have /dev/net/tun in a default device list, it was there from the very beginning, and users rely on it.
This reverts commit 2ce40b6ad72b4bd4391380cafc5ef1bad1fa0b31 / PR #3468.
> Re-add tun/tap to default device rules

- libcontainer/cgroups/devices/devicefilter_test.go
- libcontainer/specconv/spec_linux.go
Backport of #4555.
Since v1.2.0 was released, a number of users complained that the removal
of tun/tap device access from the default device ruleset is causing a
regression in their workloads.
Additionally, it seems that some upper-level orchestration tools
(Docker Swarm, Kubernetes) makes it either impossible or cumbersome
to supply additional device rules.
While it's probably not quite right to have /dev/net/tun in a default
device list, it was there from the very beginning, and users rely on it.
Let's keep it there for the sake of backward compatibility.
This reverts commit 2ce40b6.
(Cherry-pick of commit 394f4c3.)
> [1.2] Re-add tun/tap to default device rules

- .github/workflows/validate.yml
1. golangci-lint v1.60 --> v1.62
2. ubuntu-latest -> ubuntu-24.04
> GHA CI bumps

- tests/fuzzing/oss_fuzz_build.sh
The fuzzer has been removed, so this line should be removed too.
> remove broken fuzzer from oss-fuzz build script

- libcontainer/container_linux.go
- libcontainer/process_linux.go
Because the `initProcess` and `setnsProcess` have many same fields, and they are all in a big file `process_linux.go`, so let's do some refactor to this file:
1. Introduce a common parent struct `containerProcess`, let both `initProcess` and `setnsProcess` are inherited from it;
2. ~~Move `initProcess` and `setnsProcess` definition and implementation out of `process_linux.go`, let them in their own seperate files: `init_process_linux.go` and `setns_process_linux.go`, it will make more clear when reading and changing the code.~~
EDIT: the second refactor could be refactored after the release-1.1 is EOL.
This refactor doesn't change any logic, and it's the first step of #4309 . After this refactor, both `initProcess` and `setnsProcess` can be treated as `containerProcess`, we can only need …
> refactor init and setns process

- libcontainer/configs/config.go
- libcontainer/container_linux.go
- libcontainer/criu_linux.go
- libcontainer/process_linux.go
- libcontainer/rootfs_linux.go
- libcontainer/standard_init_linux.go
1. libct: add/use configs.HasHook
This allows to omit a call to c.currentOCIState (which can be somewhat
costly when there are many annotations) when the hooks of a given kind
won't be run.
2. libct: don't pass SpecState to init unless needed
SpecState field of initConfig is only needed to run hooks that are
executed inside a container -- namely CreateContainer and
StartContainer.
If these hooks are not configured, there is no need to fill, marshal and
unmarshal SpecState.
> libct: add/use configs.HasHook

- libcontainer/configs/config.go
- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
- libcontainer/init_linux.go
- libcontainer/process_linux.go
- libcontainer/setns_init_linux.go
- libcontainer/standard_init_linux.go
- utils_linux.go
These commits amend commit bfbd0305 (#3783) and 770728e1 (#4025). Should not result in any visible change, except:
- invalid `IOPriority.Class` value will result in an error much earlier;
- `runc exec` changes IO priority later, just before exec;
- `configs.IOPrioClassMapping` map is removed from the public API.
Should be relatively easy to review.
> Fixups to scheduler/priority settings

- libcontainer/system/linux.go
This helper was added for runc-dmz in commit dac417174 (PR #3987), but runc-dmz was later removed in commit 871057d (PR #4482), which forgot to remove the helper.
> libct/system: rm Fexecve

- CHANGELOG.md
- libcontainer/configs/config.go
- libcontainer/configs/config_test.go
- libcontainer/env.go
- libcontainer/env_test.go
- libcontainer/factory_linux_test.go
- libcontainer/init_linux.go
- libcontainer/integration/bench_test.go
- libcontainer/integration/exec_test.go
- libcontainer/integration/execin_test.go
- libcontainer/setns_init_linux.go
- libcontainer/specconv/spec_linux.go
- libcontainer/standard_init_linux.go
- tests/integration/hooks.bats
This is a rework/carry of #1983.
----
The current implementation sets all the environment variables passed in
Process.Env in the current process, one by one, then uses os.Environ to
read those back.
As pointed out in [1], this is slow, as runc calls os.Setenv for every
variable, and there may be a few thousands of those. Looking into how
os.Setenv is implemented, it is indeed slow, especially when cgo is
enabled.
Looking into why it was implemented the way it is, I found commit
9744d72c and traced it to [2], which discusses the actual reasons.
It boils down to these two:
- HOME is not passed into container as it is set in setupUser by
os.Setenv and has no effect on config.Env;
- there is a need to deduplication of environment variables.
Yet it was decided in [2] to not go ahead with this …
> libct: speedup process.Env handling

- RELEASES.md
Historically, our release cadence and support policy has been quite
ad-hoc, which has caused some strife and is not really becoming of a
project as widely used as ours. So, in an attempt to make our releases
more regular and to provide more guidance on our backport policy, add a
document outlining our policy.
> RELEASES: add formal release policy for runc

- libcontainer/container_linux.go
The previous logic caused runc to hang if CloseExecFrom returned an error, as the defer waiting on logsDone never finished as the parent process was never started (and it controls the closing of logsDone via it's logsPipe).
This moves the defer to after we have started the parent, with means all the logic related to managing the logsPipe should also be running.
> libcontainer: Prevent startup hang when CloseExecFrom errors

- .github/workflows/test.yml
As of [1], criu requires uuid library.
[1]: https://github.com/checkpoint-restore/criu/pull/2550/commits/9a2b7d6b3baa2b3183489ed9cebece039f9f488f
> CI: fix criu-dev compile

- .github/workflows/test.yml
As of [1], criu requires uuid library.
[1]: https://github.com/checkpoint-restore/criu/pull/2550/commits/9a2b7d6b3baa2b3183489ed9cebece039f9f488f
Cherry picked from commit bccaab89aea826e2d4c495d45b4665b53ccca0f2 / PR #4609. ~~Draft until that one is merged.~~
> [1.2] CI: fix criu-dev compile

- libcontainer/cgroups/devices/systemd.go
- tests/integration/dev.bats
_(this is a carry of #4569 which adds a better comment and a test case)_
Every unit created by runc need daemon reload since systemd v230. This breaks support for NVIDIA GPUs, see
https://github.com/opencontainers/runc/issues/3708#issuecomment-2216967210
A workaround is to set DeviceAllow before DevicePolicy.
Also:
- add a test case (which fails before the fix) by @kolyshkin
- better explain why we need empty DeviceAllow (by @cyphar)
Fixes #4568.
Reported-by: Jian Wen <wenjianhn@gmail.com>
Co-authored-by: Jian Wen <wenjianhn@gmail.com>
Co-authored-by: Aleksa Sarai <cyphar@cyphar.com>
1.2 backport: #4615
> libct/cg/sd: set the DeviceAllow property before DevicePolicy

- libcontainer/internal/userns/userns_maps_linux.c
This fixes k3s cross-compilation on Windows, broken by commit 1912d5988bbb37918 ("*: actually support joining a userns with a new container").
[@kolyshkin: commit message]
Fixes: 1912d5988bbb37918
----
As far as I can see, this is first mentioned in https://github.com/k3s-io/k3s/pull/9332 a year ago but was never reported to runc 😞 
Indeed, Go recognizes `//go:build` in C files, and also matches GOOS and GOARCH in file names even for `.c` files.
Also, I don't know how to reproduce it here (`GOOS=windows CGO_ENABLED=1 go build ./libcontainer/...` gives too many errors).
> libc/int/userns: add build tag to C file

- libcontainer/cgroups/devices/systemd.go
- tests/integration/dev.bats
_A backport of #4612 to release-1.2. Draft until that one is merged. Original description follows._
----
Every unit created by runc need daemon reload since systemd v230. This breaks support for NVIDIA GPUs, see
https://github.com/opencontainers/runc/issues/3708#issuecomment-2216967210
A workaround is to set DeviceAllow before DevicePolicy.
Also:
- add a test case (which fails before the fix) by @kolyshkin
- better explain why we need empty DeviceAllow (by @cyphar)
Fixes 4568.
Reported-by: Jian Wen <wenjianhn@gmail.com>
----
(cherry picked from commit d84388ae10370654f9320addf4c9e364862165d8)
> [1.2] libct/cg/sd: set the DeviceAllow property before DevicePolicy

- libcontainer/internal/userns/userns_maps_linux.c
Backport of #4616 to release-1.2.
----
This fixes k3s cross-compilation on Windows, broken by commit 1912d5988bbb37918 ("*: actually support joining a userns with a new container").
[@kolyshkin: commit message]
Fixes: 1912d5988bbb37918
(cherry picked from commit ccb589bd7de3be12ca81e3f903f9e7bea1107eb2)
> [1.2] libc/int/userns: add build tag to C file

- libcontainer/capabilities/capabilities.go
Similar to when SetAmbient() can fail, runc should be graceful about ResetAmbient failing.
This functionality previously worked under gvisor, which doesn't implement ambient capabilities atm. The hard error on reset broke gvisor usage.
> capabilities: be more graceful in resetting ambient

- exec.go
- libcontainer/container_linux.go
- utils_linux.go
A few small and specific patches around how `runc exec` is being set up.
No changes to functionality, relatively easy to review.
Please see individual commit descriptions for details.
> Improvements to how `runc exec` is handled

- libcontainer/utils/utils_unix.go
This fixes 2 things:
1. The last argument needs to be at most a int32, so be sure to pass only that as the max (discovered under gvisor)
2. If close_range fails, don't error out, instead just close the fds the long way.
> utils: Handle close_range more gracefully

- script/release_sign.sh
On my machine, the --recv-keys steps to get upstream keys started
producing errors recently, and even setting a default keyserver in the
global gpg configuration doesn't seem to help:
+ gpg --homedir=/tmp/runc-sign-tmpkeyring.qm0IP6
--no-default-keyring --keyring=seccomp.keyring
--recv-keys 0x47A68FCE37C7D7024FD65E11356CE62C2B524099
gpg: keybox '/tmp/runc-sign-tmpkeyring.qm0IP6/seccomp.keyring' created
gpg: keyserver receive failed: No keyserver available
So just explicitly specify a reputable keyserver. Ideally we would use
an .onion-address keyserver to avoid potential targeted attacks but not
everybody runs a Tor proxy on their machine.
> release: explicitly set --keyserver in release signing scripts

- exec.go
- libcontainer/cgroups/devices/systemd.go
- libcontainer/cgroups/file.go
- libcontainer/cgroups/fs/cpuacct.go
- libcontainer/cgroups/fs/cpuacct_test.go
- libcontainer/cgroups/fs/cpuset.go
- libcontainer/cgroups/fs2/defaultpath.go
- libcontainer/cgroups/fs2/freezer.go
- libcontainer/cgroups/fs2/fs2.go
- libcontainer/cgroups/fs2/psi.go
- libcontainer/cgroups/fscommon/rdma.go
- libcontainer/cgroups/fscommon/utils.go
- libcontainer/cgroups/systemd/user.go
- libcontainer/cgroups/utils.go
- libcontainer/configs/validate/rootless.go
- libcontainer/specconv/spec_linux.go
- libcontainer/utils/utils.go
For the most part, this is a switch from `strings.Split[N]` to `strings.Cut`,
and from `strings.HavePrefix`/`strings.TrimPrefix` to `strings.CutPrefix`.
Using `strings.Cut` (added in Go 1.18, see [1]) results in faster and
cleaner code with less allocations (as we're not using a slice).
Using `strings.CutPrefix` (added in Go 1.20, see [2]) results in
slightly cleaner easier-to-read code.
There are a few other cleanups and nits here and there.
[1]: https://github.com/golang/go/issues/46336
[2]: https://github.com/golang/go/issues/42537
> Use strings.Cut and strings.CutPrefix where possible

- CHANGELOG.md
- libcontainer/capabilities/capabilities.go
- libcontainer/container_linux.go
- libcontainer/init_linux.go
- libcontainer/process.go
- libcontainer/rootfs_linux.go
- libcontainer/setns_init_linux.go
- libcontainer/standard_init_linux.go
- tests/integration/ioprio.bats
- tests/integration/scheduler.bats
runc exec (as well as libcontainer's `container.Run`/`container.Start`) has an interesting feature of deriving various process' properties from the runtime spec for container init (the `Process` entry in `config.json` aka spec).
This is mostly implemented via merging `Config` and `Process` properties into `initConfig`, which happens in [libcontainer/container_linux.go, func newInitConfig](https://github.com/opencontainers/runc/blob/610aa88ab201f289c05c2e262912d0630f46eb35/libcontainer/container_linux.go#L683-L721). Note how `initConfig` fields are taken from `c.config` first (they are there from spec's `Process`) and then are overwritten by properties of a particular process being run. These `initConfig` fields are then used to set up various process attributes.
Alas, this functionality …
> Fix process/config properties merging

- libcontainer/utils/utils.go
This simplifies the code flow and basically removes the last `filepath.Clean`, which is not necessary in either case:
- for absolute path, single `filepath.Clean` is sufficient (as it is guaranteed to remove all dot and dot-dot elements);
- for relative path, `filepath.Rel` already calls `Clean` at the end (which is even documented).
> libc/utils: simplify CleanPath

- go.mod
- go.sum
- vendor/golang.org/x/net/LICENSE
- vendor/modules.txt
There is a security patch for CVE-2024-45338 in this version.
Ref: https://github.com/advisories/GHSA-w32m-9786-jp63
The original post is here: https://github.com/opencontainers/runc/pull/4582#issuecomment-2581115722
> [1.2] build(deps): bump golang.org/x/net from 0.24.0 to 0.33.0

- .github/workflows/test.yml
There is an [announce] that Ubuntu 20.04 will be removed in April, and in March there will be a few "brown-out" dates/times when it won't work.
This leaves us with no other options than to remove ubuntu-20.04 from the testing matrix.
As a result, cgroup v1 testing will only be done on AlmaLinux 8 running on CirrusCI. It is probably going to be sufficient for the time being (until we deprecate cgroup v1).
If not, our options are
- run Ubuntu 20.04 (or other cgroup v1 distro) in a VM on GHA;
- switch to cirrus-ci.
[announce]: https://github.com/actions/runner-images/issues/11101
> CI: gha: rm ubuntu-20.04

- libcontainer/cgroups/devices/devicefilter_test.go
- libcontainer/cgroups/file.go
- libcontainer/cgroups/fs/paths.go
- libcontainer/cgroups/fs/paths_test.go
- libcontainer/cgroups/fs2/defaultpath.go
- libcontainer/cgroups/fs2/defaultpath_test.go
- libcontainer/cgroups/internal/path/path.go
This removes all the remaining libcontainer dependencies from libcontainer/cgroups, preparing it to be moved to a separate repository.
For #4618.
> libct/cg: eliminate remaining libct deps

- libcontainer/notify_v2_linux.go
- libcontainer/sync_unix.go
- libcontainer/utils/cmsg.go
It appears this similar pattern is done elsewhere in libcontainer. Unsure if it needs to be do everywhere unix. is used directly or not.
This was observed during a buildkit run, with this output:
```
runc run failed: unable to start container process: error during container init: reading from parent failed: fetch packet length from socket: interrupted system call
```
> Retry direct unix package calls if observing EINTR

- libcontainer/cgroups/fs/cpuset.go
Android mounts cgroup v1 with noprefix. Related to https://github.com/opencontainers/runc/issues/4443
```
none on /dev/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
none on /dev/cpuctl type cgroup (rw,nosuid,nodev,noexec,relatime,cpu)
none on /dev/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent)
none on /dev/memcg type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
none on /dev/stune type cgroup (rw,nosuid,nodev,noexec,relatime,schedtune)
none on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime)
```
```
ls -l /dev/cpuset
total 0
drwxr-xr-x. 2 system system 0 May 29  1970 background
drwxr-xr-x. 2 system system 0 May 29  1970 camera-daemon
-rw-r--r--. 1 root   root   0 Nov  5 19:48 cgroup.clone_children …
```
> support cgroup v1 mounted with noprefix

- tests/integration/hooks.bats
Looking into old opened runc issues, I noticed #1663 is there without any resolution, and wrote this simple test checking if we mangle hook's argv[0] in any way.
Apparently we're good, but the test actually makes sense to have.
> tests/int: add hooks argv[0] test

- contrib/cmd/memfd-bind/memfd-bind.go
- libcontainer/container_linux.go
- libcontainer/exeseal/cloned_binary_linux.go
- libcontainer/exeseal/overlayfs_linux.go
- libcontainer/process.go
- tests/integration/run.bats
The "dmz" name was originally used because the libcontainer/dmz package
housed the runc-dmz binary, but since we removed it in commit
871057d863e8("drop runc-dmz solution according to overlay solution")
the name is an anachronism and we should just give it a more
self-explanatory name.
So, call it libcontainer/exeseal because the purpose of the package is
to provide tools to seal /proc/self/exe against attackers.
Closes #4516
> libcontainer: rename dmz -> exeseal

- libcontainer/exeseal/cloned_binary_linux.go
Prior to kernel Linux 5.5 F_SEAL_FUTURE_WRITE has bug which maps memory as shared
between processes even if it is set as private.
https://github.com/torvalds/linux/commit/05d351102dbe4e103d6bdac18b1122cd3cd04925
Accoring to https://man.archlinux.org/man/fcntl64.2.en F_SEAL_WRITE is enough.
```
Furthermore, trying to create new shared, writable memory-mappings via mmap(2)
will also fail with EPERM.
Using the F_ADD_SEALS operation to set the F_SEAL_WRITE seal fails with EBUSY
if any writable, shared mapping exists. Such mappings must be unmapped before
you can add this seal.
```
F_SEAL_FUTURE_WRITE make sens only if R/W shared mapping in one process should be
R/O in another process. This is not case for runc.
Fixes #4640
> exeseal: do not use F_SEAL_FUTURE_WRITE

- libcontainer/container_linux.go
- tests/integration/timens.bats
Fix #4635 
When we exec a process in a container has private timens, we need to
join the init process's timens path, so, we should not send the timens
config to nsexec, otherwise, runc will try to update the process's time
ns configuration when joining the timens path.
We should configure the process's timens offset only when we need to
create new time namespace, we shouldn't do it if we are joining an
existing time namespace.
> libct: don't send config to nsexec when joining an existing timens

- libcontainer/system/linux.go
_This is a backport of #4576 to release-1.2. The sense of this backport is to make sure no one starts using this function._
This helper was added for runc-dmz in commit dac417174, but runc-dmz was later removed in commit 871057d, which forgot to remove the helper.
(cherry picked from commit 83350c24a979d9982f9c35a9311ef41180d7c4bd)
> [1.2] libct/system: rm Fexecve

- libcontainer/dmz/cloned_binary_linux.go
_This is a backport of #4641 to release 1.2. Original description follows._
----
Prior to kernel Linux 5.5, F_SEAL_FUTURE_WRITE has a bug which maps memory as shared between processes even if it is set as private. See kernel commit 05d351102dbe ("mm, memfd: fix COW issue on MAP_PRIVATE and F_SEAL_FUTURE_WRITE mappings") for more details.
According to the fcntl(2) man pages, F_SEAL_WRITE is enough:
> Furthermore, trying to create new shared, writable memory-mappings via
> mmap(2) will also fail with EPERM.
>
> Using the F_ADD_SEALS operation to set the F_SEAL_WRITE seal fails
> with EBUSY if any writable, shared mapping exists. Such mappings must
> be unmapped before you can add this seal.
F_SEAL_FUTURE_WRITE only makes sense if a read-write shared mapping in one process should be …
> [1.2] exeseal: do not use F_SEAL_FUTURE_WRITE

- libcontainer/notify_v2_linux.go
- libcontainer/sync_unix.go
- libcontainer/utils/cmsg.go
_This is a backport of #4637 to release-1.2._
----
Retry Recvfrom, Sendmsg, Readmsg, and Read as they can return EINTR.
(cherry picked from commit 28475f12e3eeebdf5923bcf7e41bd25a80ea3af7)
> [1.2] Retry direct unix package calls if observing EINTR

- libcontainer/container_linux.go
- tests/integration/timens.bats
_This is a backport of #4636 to release-1.2. Original description follows._
----
Fix #4635
When we exec a process in a container has private timens, we need to
join the init process's timens path, so, we should not send the timens
config to nsexec, otherwise, runc will try to update the process's time
ns configuration when joining the timens path.
We should configure the process's timens offset only when we need to
create new time namespace, we shouldn't do it if we are joining an
existing time namespace.
> [1.2] libct: don't send config to nsexec when joining an existing timens

- signals.go
- utils_linux.go
There is a big loop(at least 65 times) in `signal.Notify`, it costs as much time as `runc init`, so we can call it in parallel ro reduce the container start time. In a general test, it can be reduced about **38.70%** ↓.
In my test with this bash script:
```bash
#!/bin/bash
i=1
n=$2
runc=$1
while [ $i -le $2 ]; do
$runc run test
((i++))
done
```
```
lifubang@acmcoder:/opt/debian$ ./runc-1.2.5 -v
runc version 1.2.5
commit: v1.2.5-0-g59923ef1
spec: 1.2.0
go: go1.23.6
libseccomp: 2.5.5
lifubang@acmcoder:/opt/debian$ time sudo ./test.sh ./runc-1.2.5 100
real	0m5.152s
user	0m0.006s
sys	0m0.016s
```
```
time sudo ./test.sh /home/lifubang/go/src/github.com/opencontainers/runc/runc 100
real	0m3.158s
user	0m0.010s
sys	0m0.014s
```
(5152 - 3158)/5152 = 0.38
> performance improvement: setup signal notify in a new go routine

- docs/spec-conformance.md
Backport #4660 
----
Update runtime-spec version from `v1.2.0` to `v1.2.1`.
(cherry picked from commit 79e9cf53e0e4ad723005e1b8c4cfd6a0a829e168)
> [1.3] doc: update spec-conformance.md

- libcontainer/process_linux.go
- signals.go
This carries the first commit from #4517, and adds another patch on top of it.
The sole reason is to use pidfd_send_signal under the hood, if that's available.
> Use pidfd_send_signal under the hood

- .cirrus.yml
In a nutshell:
- use git-core instead of git;
- do not install weak deps;
- do not install docs.
This results in less packages to install:
- 25 instead of 72 for almalinux-8
- 24 instead of 90 for almalinux-9
> .cirrus.yml: install less dependencies

- .cirrus.yml
_Backport of #4671 to release-1.2._
----
In a nutshell:
- use git-core instead of git;
- do not install weak deps;
- do not install docs.
This results in less packages to install:
- 25 instead of 72 for almalinux-8
- 24 instead of 90 for almalinux-9
(cherry picked from commit 1d9bea537812e3a1ac18b072bd3ef5faab5f17fb)
> [1.2] .cirrus.yml: install less dependencies

- .cirrus.yml
_Backport of #4671 to release-1.3 branch._
----
In a nutshell:
- use git-core instead of git;
- do not install weak deps;
- do not install docs.
This results in less packages to install:
- 25 instead of 72 for almalinux-8
- 24 instead of 90 for almalinux-9
(cherry picked from commit 1d9bea537812e3a1ac18b072bd3ef5faab5f17fb)
> [1.3] .cirrus.yml: install less dependencies

- libcontainer/setns_init_linux.go
- libcontainer/standard_init_linux.go
This addresses a TODO item added by commit 40f146841 / PR #1893,
as we do have runc init logging working fine for quite some time.
While at it, fix a typo in a comment (standart -> standard).
> libct: log a warning on join session keyring failure

- libcontainer/configs/config.go
- libcontainer/configs/mount_linux.go
- libcontainer/configs/namespaces_linux.go
- libcontainer/configs/network.go
- libcontainer/container_linux.go
This makes the state.json file 1303 bytes or almost 25% smaller (when using the default spec, YMMV) by omitting default values.
Before: 5496 bytes
After: 4193 bytes
(With opencontainers/cgroups#9 applied on top, the new size is 3424, which is almost 40% savings, compared to the original).
> Make state.json 25% smaller

- CHANGELOG.md
> [1.2] CHANGELOG: v1.2.6 formatting fixes

- libcontainer/capabilities/capabilities.go
- libcontainer/seccomp/config.go
> Use Go 1.23 maps.Keys, slices.Sort more

- libcontainer/setns_init_linux.go
- libcontainer/standard_init_linux.go
when compare to crun runc will open "/proc/filesystems"  even process_label is null
when I try to make runc exec  faster
https://github.com/opencontainers/runc/issues/3181
> skip read /proc/filesystems if process_label is null

- .github/ISSUE_TEMPLATE/bug_report.yaml
We received several times issues that the repro steps are human readable text with ambiguous instructions. That usually ends up in maintainers asking questions so people provide clear steps.
Let's just make the issue template more clear in that regard.
> .github: Improve issue template description

- .golangci.yml
- libcontainer/factory_linux_test.go
- libcontainer/integration/checkpoint_test.go
- libcontainer/integration/exec_test.go
- libcontainer/integration/execin_test.go
- libcontainer/integration/seccomp_test.go
- libcontainer/rootfs_linux.go
- libcontainer/utils/cmsg.go
> Remove some nolint annotations, add nolintlint linter

- .github/workflows/validate.yml
- libcontainer/exeseal/cloned_binary_linux.go
- libcontainer/internal/userns/usernsfd_linux.go
- libcontainer/utils/utils_unix.go
- tests/integration/userns.bats
All but one were found by codespell.
> ci: bump codespell to v2.4.1, fix some typos

- Makefile
- tests/cmd/key_label/key_label.go
- tests/integration/selinux.bats
This tests the functionality added by commit cd96170c1
("Need to setup labeling of kernel keyrings.", PR #2012), for both
runc run and runc exec, with and without user namespace.
Related to https://github.com/opencontainers/selinux/issues/222
> tests/int/selinux: test keyring security label

- internal/linux/eintr.go
- internal/linux/linux.go
- libcontainer/console_linux.go
- libcontainer/init_linux.go
- libcontainer/rootfs_linux.go
- libcontainer/setns_init_linux.go
- libcontainer/specconv/spec_linux.go
- libcontainer/standard_init_linux.go
- libcontainer/sync_unix.go
- libcontainer/system/linux.go
- libcontainer/utils/cmsg.go
- libcontainer/utils/utils_unix.go
- notify_socket.go
- tests/cmd/seccompagent/seccompagent.go
Inspired by #4680. The idea here is hide the retry-on-EINTR functionality inside a package, as well as provide error wrappers.
A few more wrappers is to be added.
PS I'm not sure about the package name, perhaps `sys` or `uunix` is a better name. I want something short and simple.
> Introduce/use internal/linux pkg to handle EINTR and error wrapping

- .github/workflows/validate.yml
- .golangci-extra.yml
- .golangci.yml
- checkpoint.go
- libcontainer/capabilities/capabilities.go
- libcontainer/criu_linux.go
- libcontainer/intelrdt/cmt.go
- libcontainer/intelrdt/intelrdt.go
- libcontainer/intelrdt/mbm.go
- libcontainer/rootfs_linux.go
- notify_socket.go
- types/events.go
Switch to golangci v2.0.
The new configuration file was initially generated by golangci-lint
migrate, when tweaked to minimize and simplify.
golangci-lint v2 switches to a new version of staticcheck which shows
much more warnings. Some of them were fixed by a few previous commits,
and the rest of them are disabled.
In particular, ST1005 had to be disabled (an attempt to fix it was made
in https://github.com/opencontainers/runc/pull/3857 but it wasn't merged).
> ci: switch to golangci-lint v2

- libcontainer/init_linux.go
- tests/integration/exec.bats
- tests/integration/run.bats
Because we have to set a default HOME env for the current container user, so we should set it after we are in the jail of the container, or else we'll use host's `/etc/passwd` to get a wrong HOME value.
Fixes #4688.
> libct: we should set envs after we are in the jail of the container

- libcontainer/criu_linux.go
- tests/integration/checkpoint.bats
CRIU always restores processes into a time namespace to prevent backward jumps of monotonic and boottime clocks. This change updates the container config to ensure that `runc exec` launches new processes within the container's time namespace.
Fixes https://github.com/checkpoint-restore/criu/issues/2610
> criu: Add time namespace to container config after checkpoint/restore

- libcontainer/criu_linux.go
- tests/integration/checkpoint.bats
Backport of #4696 to release-1.3.
----
Since v3.14, CRIU always restores processes into a time namespace to prevent backward jumps of monotonic and boottime clocks. This change updates the container configuration to ensure that `runc exec` launches new processes within the container's time namespace.
Fixes #2610
(cherry picked from commit b68cbdff345fc196e8619164ebf40f1ebaeb6561)
> [1.3] criu: Add time namespace to container config after checkpoint/restore

- libcontainer/env.go
- libcontainer/env_test.go
- tests/integration/env.bats
I'm testing runc 1.3 in docker CI and I found these issues.
I've also added some e2e tests and verified that runc 1.2 behaves the same way.
Below the commit msg of the fix, but see each commit msg for more details
---
Before commit 06f1e0765 ("libct: speedup process.Env handling") we were
overriding HOME if it was set to "" too[1]. But now we only override it
if it wasn't set at all.
This patch restores the old behavior of overriding it if it was set to
an empty value.
Docker relies on this behaviour since ages[2].
[1]: https://github.com/opencontainers/runc/blob/1c508045727231e7342e258ab30add1478c1f981/libcontainer/init_linux.go#L544-L549
[2]: https://github.com/moby/moby/blob/843e51459f14ebc964d349eba1013dc8a3e9d52e/integration-cli/docker_cli_run_test.go#L822-L843
> Override HOME if its set to the empty string

- libcontainer/env.go
- libcontainer/env_test.go
- tests/integration/env.bats
Backport of #4704, fixing moby CI for the upcoming runc release.
> [1.3]  Override HOME if its set to the empty string #4704 

- libcontainer/criu_linux.go
- tests/integration/checkpoint.bats
This is a backport of PR #4696 to release-1.2 branch.
----
Since v3.14, CRIU always restores processes into a time namespace to prevent backward jumps of monotonic and boottime clocks. This change updates the container configuration to ensure that `runc exec` launches new processes within the container's time namespace.
Fixes #2610
(cherry picked from commit b68cbdff345fc196e8619164ebf40f1ebaeb6561)
> [1.2] criu: Add time namespace to container config after checkpoint/restore

- go.mod
This was added by dependabot in commit 0b536265. Seems there is a bug about it: https://github.com/dependabot/dependabot-core/issues/11933.
Having "toolchain" means instead of using installed go version to build/test, the version specified in toolchain is [downloaded and] used, which might not be what we actually want.
For more details on toolchain directive, see
https://go.dev/doc/toolchain.
> go.mod: rm toolchain

- pause.go
- ps.go
- utils_linux.go
This issue was originally reported in podman PR 25792 (https://github.com/containers/podman/pull/25792).
When calling runc pause/unpause for an ordinary user, podman do not provide --systemd-cgroups option, and shouldUseRootlessCgroupManager returns true. This results in a warning:
$ podman pause sleeper
WARN[0000] runc pause may fail if you don't have the full access to cgroups
sleeper
Actually, it does not make sense to call shouldUseRootlessCgroupManager at this point, because we already know if we're rootless or not, from the container state.json (same for systemd).
Also, busctl binary is not available either in this context, so shouldUseRootlessCgroupManager would not work properly.
Finally, it doesn't really matter if we use systemd or not, because we use fs/fs2 manager to …
> runc pause/unpause/ps: get rid of excessive warning

- pause.go
- ps.go
- utils_linux.go
This is a backport of #4709 to release-1.2.
----
This issue was originally reported in podman PR 25792 (https://github.com/containers/podman/pull/25792).
When calling runc pause/unpause for an ordinary user, podman do not provide --systemd-cgroups option, and shouldUseRootlessCgroupManager returns true. This results in a warning:
$ podman pause sleeper
WARN[0000] runc pause may fail if you don't have the full access to cgroups
sleeper
Actually, it does not make sense to call shouldUseRootlessCgroupManager at this point, because we already know if we're rootless or not, from the container state.json (same for systemd).
Also, busctl binary is not available either in this context, so shouldUseRootlessCgroupManager would not work properly.
Finally, it doesn't really matter if we use systemd …
> [1.2] runc pause/unpause/ps: get rid of excessive warning

- pause.go
- ps.go
- utils_linux.go
This is a backport of #4709 to release-1.3.
----
This issue was originally reported in podman PR 25792 (https://github.com/containers/podman/pull/25792).
When calling runc pause/unpause for an ordinary user, podman do not provide --systemd-cgroups option, and shouldUseRootlessCgroupManager returns true. This results in a warning:
$ podman pause sleeper
WARN[0000] runc pause may fail if you don't have the full access to cgroups
sleeper
Actually, it does not make sense to call shouldUseRootlessCgroupManager at this point, because we already know if we're rootless or not, from the container state.json (same for systemd).
Also, busctl binary is not available either in this context, so shouldUseRootlessCgroupManager would not work properly.
Finally, it doesn't really matter if we use systemd …
> [1.3] runc pause/unpause/ps: get rid of excessive warning

- .github/workflows/validate.yml
This is a followup to #4717, adding a CI check that `toolchain` is not present in go.mod.
> ci: add check for toolchain in go.mod

- tests/cmd/remap-rootfs/remap-rootfs.go
Similar to #1824, we need to convert the device number to uint64 for mips.
Signed-off-by: Henry Chen <henry.chen@oss.cipunited.com>
> tests/cmd/remap-rootfs: fix mips builds

- libcontainer/apparmor/apparmor.go
- libcontainer/apparmor/apparmor_linux.go
Unfortunately, Go documentation formatter does a sloppy job formatting documentation for variables -- it is rendered as comments (see [1]).
Switch to using wrapper functions, solely for the sake of better documentation formatting.
[1]: https://pkg.go.dev/github.com/opencontainers/runc@v1.3.0-rc.2/libcontainer/apparmor
> libct/apparmor: don't use vars for public functions

- main.go
This option is unusable since commit 6e1d476a / PR #3353, it's now time to actually remove it.
NO NEED TO BACKPORT TO release-1.3, we want to have it for v1.4 only.
> Completely remove --criu option

- .github/workflows/validate.yml
The colon after "Error:" caused actionlint to report error on map in context where map is not allowed.
> Fix "invalid workflow file" github actions error

- .cirrus.yml
- .github/workflows/test.yml
- script/setup_host_fedora.sh
- script/setup_rootless.sh
- tests/rootless.sh
1. We are seeing a ton on flakes on almalinux-8 CI job, all caused by criu inability to freeze a cgroup. This was worked around in criu (https://github.com/checkpoint-restore/criu/pull/2545), but obviously we can't rely on a distro vendor to update the package.
Let's use a copr (thanks to @adrianreber!)
Fixes: https://github.com/opencontainers/runc/issues/4273
2. ssh-keygen stopped working in AlmaLinux 8, fix this as well (see commit for details).
Fixes: #4731
> ci fixes (ssh-keygen and criu version bump for almalinux 8)

- libcontainer/mount_linux.go
- libcontainer/mount_linux_test.go
- libcontainer/rootfs_linux.go
While debugging an issue involving failing mounts, I discovered that
just returning the plain mount error message when we are in the fallback
code for handling locked mounts leads to unnecessary confusion.
It also doesn't help that podman currently forcefully sets "rw" on
mounts, which means that rootless containers are likely to hit the
locked mounts issue fairly often.
So we should improve our error messages to explain why the mount is
failing in the locked flags case.
Also, when reading mount errors, it is quite hard to make sense of mount
flags in their hex form. As this is the error path, the minor performance
impact of constructing a string is probably not worth hyper-optimising.
(Though maybe @kolyshkin has an opinion on this.)
> rootfs: improve mount-related errors

- script/setup_host_fedora.sh
Package criu-4.1-1 has a known bug [1] which is fixed in criu-4.1-2 [2],
which is currently only available in updates-testing. Add a kludge to
install newer criu if necessary to fix CI.
This will not be needed in ~2 weeks once the new package is promoted to
updates. 
~~OK, we need to wait until criu-4.1-2 is available from all fedora mirrors. Draft until then.~~
[1]: https://github.com/checkpoint-restore/criu/issues/2650
[2]: https://bodhi.fedoraproject.org/updates/FEDORA-2025-d374d8ce17
> ci: update to criu-4.1-2 on Fedora

- .cirrus.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
- Makefile
- script/setup_host_fedora.sh
- script/setup_rootless.sh
- tests/integration/hooks.bats
- tests/integration/run.bats
- tests/integration/seccomp-notify.bats
- tests/integration/tty.bats
- tests/rootless.sh
This is a backport of
- #4670 (except the last commit)
- #4728
- #4736 
to release-1.2 branch. Original description follows.
----
(from #4670)
High level overview:
- bump shfmt and shellcheck;
- get rid of some "shellcheck disable" annotations;
~~- bump bats to v0.11.0 so we use the same version everywhere.~~ (not applied)
----
(from #4728) 
We are seeing a ton on flakes on almalinux-8 CI job, all caused by criu inability to freeze a cgroup. This was worked around in criu (Freeze fixes and v1 kludges checkpoint-restore/criu#2545), but obviously we can't rely on a distro vendor to update the package.
Let's use a copr (thanks to @adrianreber!)
Fixes: #4273
ssh-keygen stopped working in AlmaLinux 8, fix this as well (see commit for details).
Fixes: #4731
----
(from #4736)
Package criu-4.1-1 …
> [1.2] ci fixes (ssh-keygen and criu version bumps for almalinux 8 and fedora)

- libcontainer/mount_linux.go
- libcontainer/mount_linux_test.go
- libcontainer/rootfs_linux.go
This is a backport of #4734 to 1.2.x.
<hr>
While debugging an issue involving failing mounts, I discovered that
just returning the plain mount error message when we are in the fallback
code for handling locked mounts leads to unnecessary confusion.
It also doesn't help that podman currently forcefully sets "rw" on
mounts, which means that rootless containers are likely to hit the
locked mounts issue fairly often.
So we should improve our error messages to explain why the mount is
failing in the locked flags case.
Also, when reading mount errors, it is quite hard to make sense of mount
flags in their hex form. As this is the error path, the minor performance
impact of constructing a string is probably not worth hyper-optimising.
(Though maybe @kolyshkin has an opinion on this.) …
> [1.2] rootfs: improve mount-related errors

- libcontainer/mount_linux.go
- libcontainer/mount_linux_test.go
- libcontainer/rootfs_linux.go
This is a backport of #4734 to release-1.3. Original description follows.
----
While debugging an issue involving failing mounts, I discovered that
just returning the plain mount error message when we are in the fallback
code for handling locked mounts leads to unnecessary confusion.
It also doesn't help that podman currently forcefully sets "rw" on
mounts, which means that rootless containers are likely to hit the
locked mounts issue fairly often.
So we should improve our error messages to explain why the mount is
failing in the locked flags case.
Also, when reading mount errors, it is quite hard to make sense of mount
flags in their hex form. As this is the error path, the minor performance
impact of constructing a string is probably not worth hyper-optimising.
(Though maybe @kolyshkin …
> [1.3] rootfs: improve mount-related errors

- .github/workflows/validate.yml
- .golangci-extra.yml
- .golangci.yml
- checkpoint.go
- libcontainer/capabilities/capabilities.go
- libcontainer/criu_linux.go
- libcontainer/intelrdt/cmt.go
- libcontainer/intelrdt/intelrdt.go
- libcontainer/intelrdt/mbm.go
- libcontainer/rootfs_linux.go
- notify_socket.go
- types/events.go
Backport #4692 
----
Switch to golangci v2.0.
The new configuration file was initially generated by golangci-lint
migrate, when tweaked to minimize and simplify.
golangci-lint v2 switches to a new version of staticcheck which shows
much more warnings. Some of them were fixed by a few previous commits,
and the rest of them are disabled.
In particular, ST1005 had to be disabled (an attempt to fix it was made
in https://github.com/opencontainers/runc/pull/3857 but it wasn't merged).
> [1.3][ci]: switch to golangci-lint v2

- .github/workflows/validate.yml
(The current v2.1 release is v2.1.5 as of today).
> ci: bump golangci-lint to v2.1

- Makefile
- main.go
This is a backport of #4718 to release-1.3 branch. Original description follows.
----
This is a carry/rework of #3163.
Aside from embedding VERSION file into the binary, it simplifies the output of `runc help`.
Before:
```console
$ runc help
...
USAGE:
runc [global options] command [command options] [arguments...]
VERSION:
1.3.0-rc.1+dev
commit: v1.3.0-rc.1-93-g932e8342
spec: 1.2.1
go: go1.24.2
libseccomp: 2.5.5
COMMANDS:
checkpoint  checkpoint a running container
...
```
After:
```console
$ runc help
...
USAGE:
runc [global options] command [command options] [arguments...]
VERSION:
1.3.0-rc.1+dev
COMMANDS:
checkpoint  checkpoint a running container
...
```
The full version info is still shown by `runc --version` exactly as before:
```console
$ runc …
```
> [1.3] Embed version from VERSION file

- go.mod
We already have the indirect require for 1.17.3, that comes opencontainers/cgroups[1]. That module requires that version as min, so go can't use older versions. We can just remove the excludes.
There might be cases where people can use runc as a dependency and use replace to override it (not sure, but probably). We were clear on what our dependencies are, so we can sleep fine. In the unlikely case that some project uses runc as a dependency and:
* Uses a replace for cilium v0.17.x but not the latest patch release (0.17.3 is fixed)
* they run with 32bits
* and hit this (that didn't happen always on CI)
* Ignore the changelog for 0.17.3 that mentions the buffer overflow on 32 bits platforms[2].
In that case, if we have a bug report, we can point them to the right place. But 0.17.3 was …
> go.mod: Delete exclude directives

- go.mod
This is a backport of #4748 for the 1.3 branch.
> [1.3] go.mod: Delete exclude directives

- .github/workflows/test.yml
For some reason, launchpad.net is frequently giving us Gateway Timeout. Let's retry adding the ppa once to mitigate that.
(The alternative is not to install criu and thus run criu-related unit tests on i386 -- this might actually be better).
> ci/cross-i386: retry adding ppa

- .github/workflows/validate.yml
To not accidentally break `go install`, let's add CI to check it. If in the future we need those directives, we can remove the CI check.
This should only be merged after #4748, as we are currently using an exclude directive.
> ci: Check for exclude/replace directives

- .github/workflows/test.yml
- .github/workflows/validate.yml
This is a partial backport of #4760 to release-1.3 branch, fixing some issues and allowing the scheduled jobs to be run on release-1.3 branch.
> [1.3] ci fixes + support for scheduled ci jobs

- libcontainer/rootfs_linux.go
- tests/integration/mounts_propagation.bats
This PR adds support for applying mount propagation settings (MS_SHARED or MS_UNBINDABLE) to the container root based on the value of config.RootPropagation. 
We apply mount propagation after executing pivot_root and rootfsParentMountPrivate
Fixes https://github.com/opencontainers/runc/issues/1755
Related:
https://github.com/opencontainers/runc/pull/1815 
https://github.com/youki-dev/youki/issues/3141
Signed-off-by: Yusuke Sakurai <yusuke.sakurai@3-shake.com>
> fix rootfs propagation mode to shared / unbindable

- .github/workflows/scheduled.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
This is to ensure that our CI is not rotting away even if there are no new PRs or merges. This is especially useful for release branches which tend to cease working over time due to some external reasons.
**Update:** I was not sure it's possible, but it appears to work on my fork now, but here it needs #4763 to be merged first, ~~thus the draft status (until #4763 is merged).~~ **Update2**: dep PR is merged so this one is ready, too.
> ci: add scheduled run of GHA CI

- features.go
- go.mod
- go.sum
- libcontainer/configs/config.go
- libcontainer/configs/doc.go
- libcontainer/configs/netdevices.go
- libcontainer/configs/validate/validator.go
- libcontainer/configs/validate/validator_test.go
- libcontainer/network_linux.go
- libcontainer/process_linux.go
- libcontainer/specconv/spec_linux.go
- libcontainer/specconv/spec_linux_test.go
- tests/integration/checkpoint.bats
- tests/integration/netdev.bats
- tests/integration/userns.bats
- vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/features/features.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
- vendor/modules.txt
Implementation of https://github.com/opencontainers/runtime-spec/pull/1271
It implements the new proposal to the OCI spec to be able to specify Network Devices that get attached ~detached~ from the containers (updated to match the merged proposal https://github.com/opencontainers/runtime-spec/pull/1271)
> Linux Network Devices

- libcontainer/configs/cgroup_deprecated.go
- libcontainer/configs/config.go
This is a followup to #4638, fixing a few minor issues I found just now.
> cgroups separation followup

- libcontainer/configs/cgroup_deprecated.go
- libcontainer/configs/config.go
Backport of #4784 to release-1.3.
Needed in 1.3 because deprecation notice for stuff in libcontainer/configs was not effective, thus users won't know they have to switch.
Original description follows.
----
This is a followup to #4638, fixing a few minor issues I found just now.
> [1.3] cgroup separation followup

- tests/integration/cgroups.bats
- tests/integration/helpers.bash
- tests/integration/update.bats
- update.go
This support was missing from runc, and thus the example from the podman-update wasn't working.
To fix, introduce a function to either update or insert new weights and iops.
Add integration tests.
Fixes: https://issues.redhat.com/browse/RHEL-81042
See also: https://github.com/containers/podman/pull/26308
> runc update: support per-device weight and iops

- docs/systemd.md
Include some important previously missed detail about how linux.cgroupsPath works.
> docs/systemd.md: amend

- libcontainer/seccomp/patchbpf/enosys_linux.go
I want to support runc compilation on loogarch64, this is the first step.
> Add audit support for loong64

- tests/integration/cgroups.bats
Backport of #4806 to release-1.2 branch. Original description follows.
----
The dmem controller is added into kernel v6.13 and is now enabled in Fedora 42 kernels. Yet, systemd is not aware of dmem.
This fixes the test case failure on Fedora.
For the initial test case, see commit 27515719.
For earlier commits similar to this one, see
commits 601cf582, 05272718, e83ca519.
(cherry picked from commit b3432118edfd9b600a68ed1a01c0ae98fb195871)
> [1.2] tests/int/cgroups.bats: exclude dmem controller

- libcontainer/rootfs_linux.go
- tests/integration/mounts_propagation.bats
(cherry picked from commit 04be81b6a3db3e9967ea83b39d8742f130110914)
Backport of https://github.com/opencontainers/runc/pull/4724 to release-1.2 branch. Original description follows.
---
This PR adds support for applying mount propagation settings (MS_SHARED or MS_UNBINDABLE) to the container root based on the value of config.RootPropagation.
We apply mount propagation after executing pivot_root and rootfsParentMountPrivate
Fixes https://github.com/opencontainers/runc/issues/1755
Related:
https://github.com/opencontainers/runc/pull/1815
https://github.com/youki-dev/youki/issues/3141
Signed-off-by: Yusuke Sakurai [yusuke.sakurai@3-shake.com](mailto:yusuke.sakurai@3-shake.com)
>  [1.2] fix rootfs propagation mode to shared / unbindable

- tests/integration/events.bats
These tests should work as rootless as long as cgroup access works.
> tests/int/events.bats: don't require root

- libcontainer/rootfs_linux.go
This is a backport of #4817.
<hr>
This was added in 2ee9cbb ("It's /proc/stat, not /proc/stats") with
no actual justification, and doesn't really make much sense on further
inspection:
* /proc/net is a symlink to "self/net", which means that /proc/net/dev
is a per-process file, and so overmounting it would only affect pid1.
Any other program that cares about /proc/net/dev would see their own
process's configuration, and unprivileged processes wouldn't be able
to see /proc/1/... data anyway.
In addition, the fact that this is a symlink means that runc will
deny the overmount because /proc/1/net/dev is not in the proc
overmount allowlist. This means that this has not worked for many
years, and probably never worked in the first place.
* /proc/self/net is already namespaced with network …
> [1.2] rootfs: remove /proc/net/dev from allowed overmount list

- .github/workflows/test.yml
Employ shallow git clone and parallel build.
> ci: speed up criu-dev install

- tests/cmd/pidfd-kill/pidfd-kill.go
- tests/cmd/recvtty/recvtty.go
- utils_linux.go
These typecasts can't fail, so it doesn't make sense checking for errors.
This also simplifies the cleanup logic.
Closes: #4821
Closes: #4780
(Authors of both PRs, i.e. @grey3228 and @mi4r, are credited in the second commit)
> Simplify getting net.UnixConn

- update.go
Prevent --l3-cache-schema from clearing the intel_rdt.memBwSchema state and --mem-bw-schema clearing l3_cache_schema, respectively.
> runc update: don't lose intelRdt state

- update.go
Prevent --l3-cache-schema from clearing the intel_rdt.memBwSchema state and --mem-bw-schema clearing l3_cache_schema, respectively.
(cherry picked from commit 57b6a317bb0ed7c7d2937b477ba9fb8a2ba50bae)
Backports: https://github.com/opencontainers/runc/pull/4828
> [release-1.2] runc update: don't lose intelRdt state

- update.go
Prevent --l3-cache-schema from clearing the intel_rdt.memBwSchema state and --mem-bw-schema clearing l3_cache_schema, respectively.
(cherry picked from commit 57b6a317bb0ed7c7d2937b477ba9fb8a2ba50bae)
Backports: #4828
> [release-1.3] runc update: don't lose intelRdt state

- update.go
Error out --l3-cache-schema and --mem-bw-schema if the original spec didn't specify intelRdt which also means that no CLOS (resctrl group) was created for the container.
This prevents serious issues in this corner case.
First, a CLOS was created but the schemata of the CLOS was not correctly updated. Confusingly, calling runc update twice did the job: the first call created the resctrl group and the seccond call was able to update the schemata. This issue would be relatively easily fixable, though.
Second, more severe issue is that creating new CLOSes this way caused them to be orphaned, not being removed when the container exists. This is caused by runc not capturing the updated state (original spec was intelRdt=nil -> no CLOS but after update this is not the case).
The most severe …
> runc update: refuse to create new rdt group

- script/lib.sh
Since commit 871057d8 we no longer have cc_platform.mk.
> script/lib.sh: remove obsoleted comment

- libcontainer/criu_linux.go
This makes `prepareCriuRestoreMounts` more readable, smaller, and slightly faster.
Split to 4 commits for easier review.
Should not change behavior in any way.
Covered by existing tests in `tests/integration/checkpoint.bats`.
> Refactor/improve prepareCriuRestoreMounts

- libcontainer/intelrdt/intelrdt.go
- libcontainer/intelrdt/intelrdt_test.go
Also, use GetPath() in Apply to get the resctrl group path, similar to other methods of intelRdtManager.
> libcontainer/intelrdt: refactor path handling

- CHANGELOG.md
- libcontainer/process_linux.go
- tests/integration/cpu_affinity.bats
- tests/integration/helpers.bash
Backport of #4858.
<hr>
In certain deployments, it's possible for runc to be spawned by a
process with a restrictive cpumask (such as from a systemd unit with
CPUAffinity=... configured) which will be inherited by runc and thus the
container process by default.
The cpuset cgroup used to reconfigure the cpumask automatically for
joining processes, but kcommit da019032819a ("sched: Enforce user
requested affinity") changed this behaviour in Linux 6.2.
The solution is to try to emulate the expected behaviour by resetting
our cpumask to correspond with the configured cpuset (in the case of
"runc exec", if the user did not configure an alternative one). Normally
we would have to parse /proc/stat and /sys/fs/cgroup, but luckily
sched_setaffinity(2) will transparently convert an all-set cpumask …
> [1.3] libct: reset CPU affinity by default

- libcontainer/criu_linux.go
Backport of https://github.com/opencontainers/runc/pull/4765 to release-1.2. Original description follows.
----
This makes `prepareCriuRestoreMounts` more readable, smaller, and slightly faster.
Split to 4 commits for easier review.
Should not change behavior in any way.
Covered by existing tests in `tests/integration/checkpoint.bats`.
> [1.2] Refactor/improve prepareCriuRestoreMounts

- libcontainer/criu_linux.go
Backport of https://github.com/opencontainers/runc/pull/4765 to release-1.3. Original description follows.
----
This makes `prepareCriuRestoreMounts` more readable, smaller, and slightly faster.
Split to 4 commits for easier review.
Should not change behavior in any way.
Covered by existing tests in `tests/integration/checkpoint.bats`.
> [1.3] Refactor/improve prepareCriuRestoreMounts

- tests/integration/cgroups.bats
Backport of https://github.com/opencontainers/runc/pull/4893 to v1.3
---
When a non–page-aligned value is written to memory.max, the kernel aligns it down to the nearest page boundary. On systems with a page size greater than 4K (e.g., 64K), this caused failures because the configured memory.max value was not 64K aligned.
This patch fixes the issue by explicitly aligning the memory.max value to 64K. Since 64K is also a multiple of 4K, the value is correctly aligned on both 4K and 64K page size systems.
However, this approach will still fail on systems where the hardcoded memory.max value is not aligned to the system page size.
Fixes: https://github.com/opencontainers/runc/issues/4841
(cherry picked from commit 830c479ae2a027ce671816a8f353a1264973dd25)
> [1.3] tests/int/cgroups: Use 64K aligned limits for memory.max

- tests/integration/cgroups.bats
Backport of #4893 to v1.4
---
When a non–page-aligned value is written to memory.max, the kernel aligns it down to the nearest page boundary. On systems with a page size greater than 4K (e.g., 64K), this caused failures because the configured memory.max value was not 64K aligned.
This patch fixes the issue by explicitly aligning the memory.max value to 64K. Since 64K is also a multiple of 4K, the value is correctly aligned on both 4K and 64K page size systems.
However, this approach will still fail on systems where the hardcoded memory.max value is not aligned to the system page size.
Fixes: https://github.com/opencontainers/runc/issues/4841
(cherry picked from commit 830c479ae2a027ce671816a8f353a1264973dd25)
> [1.4] tests/int/cgroups: Use 64K aligned limits for memory.max

- libcontainer/setns_init_linux.go
- libcontainer/standard_init_linux.go
- tests/integration/personality.bats
Set the process personality early to ensure it takes effect before
seccomp is initialized. If seccomp filters are applied first and they
block personality-related system calls (e.g., `personality(2)`),
subsequent attempts to set the personality will fail.
Please see:
https://github.com/opencontainers/runc/pull/4726#discussion_r2317775814
> libct: setup personality before initializing seccomp

- libcontainer/process_linux.go
- tests/integration/exec.bats
~~_Requires (and currently includes) PR #4822; draft until that one is merged._~~
It makes sense to make runc exec benefit from `clone2(CLONE_INTO_CGROUP)`, when
available. Since it requires a recent kernel and might not work, implement a fallback.
Based on:
- https://go-review.googlesource.com/c/go/+/417695
- https://github.com/coreos/go-systemd/pull/458
- https://github.com/opencontainers/cgroups/pull/26
- https://github.com/opencontainers/runc/pull/4822
Closes: #4782.
> runc exec: use CLONE_INTO_CGROUP

- events.go
- features.go
- go.mod
- go.sum
- internal/linux/linux.go
- libcontainer/configs/config.go
- libcontainer/configs/intelrdt.go
- libcontainer/configs/memorypolicy.go
- libcontainer/configs/tocpuset_test.go
- libcontainer/configs/validate/validator.go
- libcontainer/init_linux.go
- libcontainer/intelrdt/intelrdt.go
- libcontainer/intelrdt/intelrdt_test.go
- libcontainer/intelrdt/stats.go
- libcontainer/intelrdt/util_test.go
- libcontainer/setns_init_linux.go
- libcontainer/specconv/spec_linux.go
- libcontainer/standard_init_linux.go
- tests/integration/memorypolicy.bats
- types/events.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/features/features.go
- vendor/modules.txt
Backport of #4830 and #4726.
<hr>
* Implement support for Linux memory policy in OCI spec PR:
https://github.com/opencontainers/runtime-spec/pull/1282
Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>
* Implement support for the linux.intelRdt.schemata field of the spec.
This allows management of the "schemata" file in the resctrl group in a
generic way. https://github.com/opencontainers/runtime-spec/pull/1230
Signed-off-by: Markus Lehtonen <markus.lehtonen@intel.com>
> [1.4] Add memory policy and schemata support

- features.go
- libcontainer/configs/intelrdt.go
- libcontainer/configs/validate/intelrdt_test.go
- libcontainer/container_linux.go
- libcontainer/intelrdt/intelrdt.go
- libcontainer/intelrdt/intelrdt_test.go
- libcontainer/specconv/spec_linux.go
The linux.intelRdt.enableMonitoring field enables the creation of a per-container monitoring group. The monitoring group is removed when the container is destroyed.
Refs: https://github.com/opencontainers/runtime-spec/pull/1287
> libcontainer/intelrdt: add support for EnableMonitoring field
